### PR TITLE
[BUGFIX beta] Remove HTMLBars from builds.

### PR DESCRIPTION
**Pull request by rwjblue**
Ensure that only development builds contain full `htmlbars-compiler` and `htmlbars-syntax` packages.
- Makes `htmlbars-compiler` package optional (but `compile` and `precompile` would through a helpful error if you try to invoke them).
- Loads `ember-template-compiler.js` into test suite (for inline compiling).

### CODE REVIEW

**Comment by stefanpenner** [comment]
nice, any hints to the byte size difference?

**Comment by rwjblue** [comment]
before - 134.48kb
after - 104.59kb

**Comment by stefanpenner** [comment]
well thats good, hopefully with 2.0 we can cut that down even more.

**Comment by rwjblue** [comment]
@stefanpenner - Also, remember that we now do not need `handlebars.runtime.js` (which is another 6.42 after min+gz).  

1.9.1 is 103.42 (min+gz) with both handlebars.runtime + ember.prod.js.
1.10 should be within 0.5kb of 1.9 (I'm not quite done with the required updates for beta yet so I can't be 100% sure).

**Comment by ef4** [comment]
Why do we want to keep the compiler in dev builds? Wouldn't that just cause people to be surprised that their inline `compile()` works in development and then fails in production?

If test environments need it, they could load it explicitly as a separate library the same way they'd load qunit.

**Comment by rwjblue** [comment]
@ef4 - Good point.  We have had this working in dev (and prod) builds since landing HTMLBars feature flag on Canary (before 1.10 was branched).  If we remove from dev builds, folks will need to add `ember-template-compiler.js` to their development setups (as you mentioned) just like they would have previously added `handlebars.js`.  

We definitely do not want it in production builds, but I'm fine with it either way on dev builds.  I would like to settle this before shipping 1.10.0-beta.5 though (so that if you can use beta.5 you will be able to use 1.10.0 final), so we have relatively short time to decide.

**Comment by ahacking** [comment]
I support making inclusion of template compilation explicit and intentional.

The principle of least astonishment would suggest that besides development and debug instrumention, dev and prod builds should be equivalent featurewise.

**Comment by stefanpenner** [comment]
> If test environments need it, they could load it explicitly as a separate library the same way they'd load qunit.

:+1:

**Comment by mixonic** [comment]
It is tempting and convenient to keep the compiler and ember in a single debug package, but also inconsistent with how the ember.prod file and others are expected to work.

We has this discussion long ago. However @ef4's comment is a good gut check and I agree that splitting the compiler out of dev builds is the correct move.

**Comment by stefanpenner** [comment]
> I support making inclusion of template compilation explicit and intentional.

so you mean people must opt in, or we should include it by default?

**Comment by stefanpenner** [comment]
> We has this discussion long ago. However @ef4's comment is a good gut check and I agree that splitting the compiler out of dev builds is the correct move.

my only concern is semver?

**Comment by mixonic** [comment]
@stefanpenner We've asked users to change the version of Handlebars their apps depend upon to upgrade. This seems similar to me.

We've also asked them to include new dependencies (shims) for old environments during 1.x. Changing the dependency/packaging seems ok for something this important? And I'd also suggest our template compiler dep is well named and we could swap HTMLBars for something else in the future and not need to ask for this change a second time.

**Comment by stefanpenner** [comment]
> @stefanpenner We've asked users to change the version of Handlebars their apps depend upon to upgrade. This seems similar to me.

sounds good

**Comment by ahacking** [comment]
@stefanpenner by explict and intentional I mean opt-in given the default prod build is to not include template compilation, which I 100% agree with.

**Comment by stefanpenner** [comment]
> @stefanpenner by explict and intentional I mean opt-in given the default prod build is to not include template compilation, which I 100% agree with.

sounds good :)  Ya i think the confusing of the client-side template compiler gets many people, when typically if they would have known off the start they would have been in the clear.

**Comment by stefanpenner** [comment]
:shipit:

**Comment by jayphelps** [comment]
@rwjblue hehehe you dun broke a bunch of jsbins just now ;)

**Comment by rwjblue** [comment]
Yeah, it is unfortunate for sure. I'll be updating my bins today (after I pull this in to beta branch).

**Comment by iamjstates** [comment]
This is sounds dumb, but what do I do in development?

**Comment by mixonic** [comment]
@iamjstates you must also include `http://builds.emberjs.com/canary/ember-template-compiler.js`. This is similar to requiring Handlebars.

**Comment by ef4** [comment]
If you're using ember-cli, you shouldn't need a template compiler in the browser at all. The ember-cli-htmlbars package should be taking care of it all for you at build time.

**Comment by iamjstates** [comment]
I'm assuming in the bower.json @mixonic? @ef4 I'm using ember-cli 0.1.7 / ember#canary and I'm seeing this message:

Uncaught Error: Cannot call `compile` without the template compiler loaded. Please load `ember-template-compiler.js` prior to calling `compile`.

**Comment by rwjblue** [comment]
@iamjstates - How are you calling `Ember.Handlebars.compile` or `Ember.HTMLBars.compile`?  If it is in your userland or test code, you will have to `app.import('bower_components/ember/ember-template-compiler.js')`.

**Pull request merged**
