### PR TITLE
Link to materialize failing test

### PR DESCRIPTION
**Pull request by bcardarella**
Related to #4260

### CODE REVIEW

**Comment by justinko** [comment]
ping & pong ya'll - this bug doesn't occur if the user's username is `undefined` :stuck_out_tongue_closed_eyes:

**Comment by stefanpenner** [comment]
@bcardarella is this still an issue?

**Comment by bcardarella** [comment]
¯\_(ツ)_/¯

this PR has a failing test so I guess it can be run against master to see if it is

**Comment by stefanpenner** [comment]
> this PR has a failing test so I guess it can be run against master to see if it is

Awesome, let me know the outcome of running it against master.

**Comment by bcardarella** [comment]
Honestly I don't have the time to do that

**Comment by stefanpenner** [comment]
So i take it, this doesn't affect you guys anymore?

**Comment by stefanpenner** [comment]
or is this just a case you discovered, and avoid now?

**Comment by bcardarella** [comment]
It was on a client project from over a year ago. Last I checked it was still a problem. The failing test I provided is written for Handlebars. I don't know how best to move that over to HTMLBars. I'm pretty slammed with client work (hence being up at 5am EST) and don't have the time to learn how to convert this test over.

**Comment by stefanpenner** [comment]
alright, ill add it to the queue.

**Comment by bcardarella** [comment]
@stefanpenner I've updated the PR, wasn't as involved as I thought. Its still failing for `master`

**Comment by stefanpenner** [comment]
<3

**Comment by stefanpenner** [comment]
@machty are you able to look into this?

**Comment by sly7-7** [comment]
I've created a jsbin reproducing the test, and it seems to work: http://output.jsbin.com/wujase Am I missing something here ?

**Comment by machty** [comment]
@bcardarella can you take a look at @sly7-7's jsbin and see if it's working?

**Comment by bcardarella** [comment]
I've confirmed this is working with the new jsbin that @sly7-7. Not sure why my test is failing as that is essentially the same code. As a matter of comparison, this was not working with Ember 1.5 see: http://emberjs.jsbin.com/lodunime/1/edit?html,css,js,output and hover over the link to see the materialized url as `undefined`.

I'll close in favor of "works for me" status.

**Comment by stefanpenner** [comment]
@bcardarella ya very strange, oh well. If someone else reports we know there must be a difference.

@sly7-7 thanks for digging into this.

**Comment by sly7-7** [comment]
My pleasure :smile:

**Pull request closed without merging**
