### PR TITLE
[BUGFIX beta] reuse `extractQueryParamsArgument`

### PR DESCRIPTION
**Pull request by bekzod**

### CODE REVIEW

**Comment by locks** [comment]
@bekzod query param specs are complaining about this change, they're all coming back `null`.

**Comment by bekzod** [comment]
this also aligns `router-service / transitionTo` behave like `router / transitionTo`
which was regressed a bit with https://github.com/emberjs/ember.js/commit/7c7f9bc287606f79348f3498029471685edfbc82 
where `router-service / transitionTo` would not correctly work when only `queryParam hash` passed as first argument

**Comment by bekzod** [comment]
also added test for regression

**Comment by rwjblue** [comment]
Thanks @bekzod!

**Pull request merged**
