### PR TITLE
[FEATURE ember-metal-injected-properties] Injected properties

### PR DESCRIPTION
**Pull request by slindberg**
# Injected Properties

This PR is intended to implement the necessary features for Ember 'services' (see #4861). It introduces 'injection helpers' which are computed properties that are container-aware, but whose use is type dependent (e.g., you cannot define an injected controller property on a view). As discussed on @tomdale's PR, there is ambiguity between an injection helper named `Ember.controller` and the actual `Ember.Controller` class, so to avoid this I've created a new top level namespace called `inject` (see below).

As an example, the following is enabled:

``` javascript
App.PostController = Ember.Controller.extend({
  posts: Ember.inject.controller()
});
```

Which is functionally equivalent to:

``` javascript
App.PostController = Ember.Controller.extend({
  needs: 'posts',
  posts: Ember.computed.alias('controllers.posts')
});
```

This PR also adds the `controller` and `service` injection helpers (as well as `Ember.Service`), but those commits can easily be extracted into another PR
## Validation

In order to enforce good practices, injection helpers can only be used with certain ember objects (or rather _can't_ be used with certain ember objects).
1. controllers can only be injected into other controllers
2. ~~services cannot be injected into views or components~~

This validation check can happen in one of two places:
1. at mixin time
2. at instantiation time

The first option seems better since it happens early and only once.

A second type of validation ensures that the object with injection properties has a reference to the container, and that the container has knowledge of the requested injections (through `app.register` or the resolver). This check can happen at one of two places:
1. at instantiation time
2. at access time

The first option seems better since it happens earlier (assuming that registration of container types happens during app bootstrap).
## Injection

When an injection helper property is declared on a class, all instances of that class need the property looked up and set. There are a few places this can happen:
1. at instantiation time via normal container injection
2. at instantiation time in `CoreObject`
3. lazy lookup on container in computed property getter

The first option would maintain consistency with current container injections and allow instances to access their properties without calling `.get()`, but require either accessing the injection at mixin time (where a container is not currently accessible), or by altering the container to be aware of the ember object model (which it is currently only vaguely aware of). The last approach has the advantage of not performing a lookup if never accessed, and being able to take advantage of CP cache, which seems to make it the best candidate.
### Feature name

This touches more than just `ember-metal`, but that package is the lowest common denominator. It would be trivial to split this up into multiple dependent features as an alternative.
### `inject` namespace

This is simply to avoid the potential ambiguity between `Ember.controller`/`Ember.Controller` `Ember.service`/`Ember.Service`. It also happens to read well, since what the developer wants to do is, for example, 'inject [a] controller'.
### `inject` namespace (not) as a function

Much like `Ember.run` and `Ember.computed`, the `Ember.inject` namespace could potentially be a convenience method for a container injection property, however that would enable the "injection of anything into anything" anti-pattern that should be avoided if possible. By only allowing injected properties through predefined methods, Ember is enforcing best practices.
### Referencing the container in ember-metal

The container is not mentioned anywhere in `ember-metal`, but since injected properties are type of descriptor, and all other descriptor properties are defined in `ember-metal`, it seemed like the best place. It could also easily go in the `ember-runtime` package.
### ~~Validation in `Ember.Object` `init` event~~ (no longer applies)

There are a few places instantiation-time validation can happen:
1. directly in `CoreObject`'s constructor
2. `Object`'s init` event/hook
3. `Object`'s `didDefineProperty` hook

Although nothing in Ember core (to my knowledge) currently uses the `init` event, it seemed like the best option since requiring _all_ existing subclasses that define `init` or `didDefineProperty` hooks call `_super` for validation to work, is IMHO dangerous and could be considered a breaking API change. Yes, controllers currently implement this check in the `init` hook, but extending it to all objects is much farther reaching.
### `willMergeMixin` on `Ember.Object`

This is obviously dubious for the potential performance hit. However, during my `ember-metal` spelunking, it seems like this private hook is specifically intended for doing any special mixin-time handling. So short of baking injected property validation into `ember-metal` itself, this is all I could come up with.
### Branding vs. `instanceof`

This is something that @stefanpenner mentioned in the original PR. I could not find much information on the performance implications of "branding" versus use of the `instanceof` operator, except by inference in this [jsperf](http://jsperf.com/instanceof-performance/2) (which only shows results in chrome). This did not seem to warrant breaking existing patterns, and can easily be changed later when other `instanceof` checks are converted.
### `Ember.assert` vs. `throw new EmberError(...)`

To be perfectly honest, I have no idea when something warrants a full production-time exception over a development assertion. Is there a guide for this anywhere? I ended up just making best-guesses.
### TODO

It should be possible to cache a list of injected properties on the constructor's meta object when mixin-time validation happens, thereby avoiding the repeated descriptor lookups at instantiation-time validation. I just don't know enough about how metadata is stored/accessed to be confident enough to do this, especially since there are additional considerations when classes get extended multiple times with new injected properties.

### CODE REVIEW

**Comment by sandstrom** [comment]
@slindberg This is an awesome feature! Thank you!

During a refactor I've moved many things from my home-made services structure into Ember Services. However, for some use-cases I'd like to use something different, and it would be neat to create custom injections.

So, my question, do you know why `createInjectionHelper` is not available as a public API? Was there any discussion around this?

I can see the downside of people using it incorrectly, but that can be handled using documentation. Ember does surface quite a bit of useful low-level functionality in other areas (e.g. around the run-loop). Would be neat if `createInjectionHelper` was public too!

**Comment by stefanpenner** [comment]
> So, my question, do you know why createInjectionHelper is not available as a public API? Was there any discussion around this?

The concern boiled down to allowing arbitrary instance <-> instance injections. This confuses the data-flow model.

We feel good about allowing service -> component direct communication (since the life-cycles enable it) but not very good about aribtraryThingWithItsOwnLifeCycle < otherArbitraryThingWithItsOwnLifeCycle.

I think the easiest way to illustrate the limitation, is to align it slightly with the bindings down actions up strategy.

**Comment by sandstrom** [comment]
Got it. I'll respect whatever you prefer — i.e. it's a bad idea to make a change to Ember if I'm the only one with a need for it :) But count this as one token in the make-it-public bucket.

I've got one use-case where this would be useful, and still wouldn't collide with the limitation above. And I think the limitation could also be handled by documenting clearly the intended usage.

I'll find a work-around for my case (but if many others start asking for this it may be worth revisiting this).

***

I'm making an upgrade to 1.13 and a more component-driven structure. Works splendid! You [the core team] has done an amazing job! :boat:

**Comment by stefanpenner** [comment]
Share  our usecase :) the limitation is really conservative today.

**Comment by tim-evans** [comment]
I would like to create an injection helper for a pattern called 'actions', which are functions that do some business logic:

For example, in `actions/attach-image-to-comment.js`
```javascript
export default function (comment, file) {
  let store = this.get(comment, 'store');
  return file.upload().then(function (data) {
    let attachment = store.createRecord('attachment', {
      comment: comment,
      url: data.headers.Location
    });
    return attachment.save();
  });
}
```

This nicely encapsulates somewhat complicated behavior into a function. In our route, I might just care about testing that this *just got called*. In that case, it would be nice to swap out the action for a mock that returned a promise that I had control over in the test. That way, I could say that:

1. Yes, the action was called
2. Subsequent behaviors are called

This also removes complications around testing these usually tricky bits of business logic that cause a lot of friction to test.

**Comment by tomdale** [comment]
@tim-evans I have had this issue as well. I've wanted to inject a function, but found myself having to create a service with a single method on it—and having to do a little song and dance just to expose one method felt very Java-like to me (in the bad way).

I for one would definitely be open to an RFC explaining the primitive and making it possible for folks to inject functions.

**Comment by rwjblue** [comment]
FWIW: it is possible today with something like:

export default {
  create: function() {
    return someSpecialFunctionYouImported;
  }
}

**Comment by rwjblue** [comment]
But I absolutely agree that we should make it more ergonomic (and think through the ramifications) via an RFC.

**Comment by tim-evans** [comment]
@tomdale @rwjblue Followed your advice and created an RFC

**Pull request merged**
