### PR TITLE
[DOC beta] remove classic syntax examples from macros

### PR DESCRIPTION
**Pull request by knownasilya**
Part of https://github.com/emberjs/ember.js/issues/19702 initiative

### CODE REVIEW

**Comment by knownasilya** [comment]
@jenweber is this part of the v4 cleanup?

**Comment by jenweber** [comment]
@knownasilya yes it is, thank you! Can you put `[DOC beta]` at the beginning of your commit message? That will help make sure this gets in.

**Comment by knownasilya** [comment]
All set

**Review by locks — APPROVED** [review]

**Comment by locks** [comment]
In this goes!

**Pull request merged**
