### PR TITLE
[DOC] Add example of new CP syntax in features.md

### PR DESCRIPTION
**Pull request by cibernox**
I've just wanted to enable the new CP syntax and when I looked the exact feature flag name, I realized that a small code example would make the feature much easier to understand.

### CODE REVIEW

**Comment by rwjblue** [comment]
Thanks!

**Comment by workmanw** [comment]
One question on this example, I noticed the `set` doesn't return a value. IIRC in the RFC it was talked about the `set` would return the newly set value. Is that still true, or did it change and I missed it?

**Comment by cibernox** [comment]
@workmanw `Ember.set(obj, 'visible', false)` will return the return value of your setter, whatever it is, but its your decission to use that feature or not. In this case it would return undefined.

I think that it is a good practice though.

**Comment by workmanw** [comment]
@cibernox Excellent Thanks! For some reason I was thinking if you didn't return a value it'd cache "undefined" as the CP value, but yea, that's not the case. Cheer.

**Comment by teddyzeenny** [comment]
As @workmanw suggested, I think you should return the new value from the setter otherwise the CP will cache to `undefined`.

**Comment by workmanw** [comment]
@teddyzeenny Actually I don't think it does that any more. I tested with canary and it seems not returning a value caches the set value, rather than undefined. I swear this changed somewhere along the way. Maybe I'm crazy.

**Comment by cibernox** [comment]
I was just checking it right now and @teddyzeenny is right. In that situation it cached undefined.

I am creating a PR for fix this example and add a test harness for that situation, which I didn't covered in the initial PR.

**Comment by cibernox** [comment]
Check https://github.com/emberjs/ember.js/pull/10246

**Comment by workmanw** [comment]
Okay yea, so I was right originally, then went crazy while making a JSBin. But here is a JSBin demonstrating it. http://emberjs.jsbin.com/sezagaqagi/2/edit

I plead temporary insanity. Sorry.

**Pull request merged**
