### PR TITLE
Unify most remaining @htmlbars tests

### PR DESCRIPTION
**Pull request by chancancode**
Got a lot of them working in this session, here are the remaining ones on the glimmer side:

skipped

### CODE REVIEW

**Comment by chancancode** [comment]
cc @krisselden

**Comment by rwjblue** [comment]
The test changes look good to me.  I'll let someone else speak to the implementation changes....

**Comment by krisselden** [comment]
Looks like there are linting failures

**Comment by rwjblue** [comment]
I believe there are some non-linting failures too:

> Test failed: [glimmer] Helpers test: element action:  it should unregister event handlers when an element action is removed

> Test failed: [htmlbars] Helpers test: element action:  it should unregister event handlers when an element action is removed

**Pull request merged**
