### PR TITLE
Move beforeRender/afterRender into the legacy bin

### PR DESCRIPTION
**Pull request by ebryn**
As requested by @krisselden 

@mmun @rwjblue

### CODE REVIEW

**Comment by ebryn** [comment]
@rwjblue This should also get plucked into beta after the other commits do

**Comment by fivetanley** [comment]
In some of our apps we have used `Ember.run.scheduleOnce('afterRender')` to schedule some actions after stuff like `{{#if}}` takes place. Will that still be kosher or is there something else we should start moving toward?

**Comment by lukemelia** [comment]
@fivetanley The changes in this PR are unrelated to the `afterRender` queue of the RunLoop

**Comment by fivetanley** [comment]
Gotcha. Thanks.

**Pull request merged**
