### PR TITLE
[BUGFIX release] Fix classify for spaced strings

### LINKED ISSUE #13042: Regression in `Ember.String.classify` in ~2.1
In Ember 1.13 and 2.0, `Ember.String.classify("be a teacher");` generates `"BeATeacher"`
In Ember 2.4, `Ember.String.classify("be a teacher");` generates `"BeA Teacher"`

I've tracked the bug down to this commit: https://github.com/emberjs/ember.js/commit/85d725c61f3b43a630d1f806c7d0824b3c299d0e

Here is a jsbing containing the both codes to see the issue. Switch between the old and new implementation by commenting/uncommentiong to see the error in action.

http://jsbin.com/xeloxuw/edit?js,console

### PR DESCRIPTION
**Pull request by skeate**
Resolves #13042

### CODE REVIEW

**Comment by rwjblue** [comment]
Will need to be `[BUGFIX release]` (due to LTS) once you have the failing tests fixed...

**Comment by skeate** [comment]
Tests are passing locally for me; not sure why they aren't in Travis. Please excuse the debugging.

**Comment by skeate** [comment]
Looks like it's a difference of phantomjs versions. 1.9.8 doesn't handle RegExp's `test` method properly.

Fortunately in this case, getting rid of the `g` flag works (fingers crossed), since it's looping anyway.

**Comment by rwjblue** [comment]
The fix looks good to me. 

I believe the performance impact (adding a loop of regexps) to be a somewhat negligible difference due to the caching we do with these methods, but I would love @stefanpenner or @krisselden to confirm/deny.

**Comment by skeate** [comment]
One potentially better solution, if the loop is too much of performance concern, might be to add a regexp to handle the specific case of a one-character piece (which is, I believe, the only time this bug manifests).

**Comment by stefanpenner** [comment]
does ember or ember-data use classify anywhere? I don't know if its even relied upon.

**Comment by rwjblue** [comment]
ember-data [does not](https://github.com/emberjs/data/search?utf8=%E2%9C%93&q=classify) use it.

uses that I am aware of:

* resolver (both globals and ember-cli) for determining `resolveFooBar` method name
* ember-inspector's container debug adapter (displaying descriptions of items)

**Comment by stefanpenner** [comment]
> resolver (both globals and ember-cli) for determining resolveFooBar method name

ah, hmm.

resolving type should usually be a cache hit, as the number of types are relatively low. 

The only way to be sure is to test it in a large app, and see how many hits/misses etc.

**Comment by rwjblue** [comment]
@stefanpenner - Ya, exactly. I think the resolver lookups would definitely be nearly all cache hits (there are only like 5 or 6 types in the system).

**Comment by mixonic** [comment]
Next step here would maybe be to recreate an app with a lot of lookup in https://github.com/eviltrout/ember-performance and confirm there isn't a regression. Or alternatively make a one-off regression check against a real app.

**Comment by rondale-sc** [comment]
@mixonic Created a benchmark with ember-performance https://github.com/eviltrout/ember-performance/pull/107

Each test run classifies 1k random strings.  Results:

| pr/13044 | master |
| --- | ---- | 
| 770.88/per second  | 572.39/per second |

**Comment by tomdale** [comment]
Seems like close enough performance, give one is horribly broken and the other one works.

**Comment by rwjblue** [comment]
@skeate - Would you mind rebasing one last time, then we can land this?

**Comment by skeate** [comment]
Also: Are those columns mislabeled, or am I misinterpreting, or is this PR somehow faster than what's in master?

**Comment by mixonic** [comment]
@skeate yeah it looks like the PR performs better. I expect b/c the `if` statement using `test` often is `false` and avoids a string allocation? Might be fun to play with further optimizations now that there is a performance PR :-)

**Comment by stefanpenner** [comment]
> Seems like close enough performance, give one is horribly broken and the other one works.

We should be careful, as we have caches involved here. Real apps may blow this limits and cause some grief, as the micro benchmark path and real path may be substantially different.

We will have to be careful and do some tests in real apps. These caches have statistic tracking built in so it should be possible.

@krisselden this might be a good thing to try in one of the LI apps.

**Comment by stefanpenner** [comment]
I also think, this shouldn't be a `[BUGFIX release]` at the very least `beta` maybe canary, its possible people are depending on this behavior and fixing the output etc.

**Comment by mixonic** [comment]
@stefanpenner per the original issue https://github.com/emberjs/ember.js/issues/13042 this is a regression in 2.4 not present in 1.13 or 2.0. Seems pretty major, it seems unlikely any app relies on a classified string have a space 😬 

Ideally still a `[BUGFIX release]` back to LTS I think. It is so late you can argue the point, but the buggy behavior seems broken enough to be more trolling than possibly relied upon.

**Comment by stefanpenner** [comment]
ah its a regression, i see.

**Comment by rondale-sc** [comment]
@skeate they were mislabeld.  Sorry.

**Comment by Serabe** [comment]
Did anyone had time to perf this? Anyway I can help?

**Comment by mixonic** [comment]
I believe this blocked on a performance regression check in a real app, per @stefanpenner's comment. Embarrassingly, this regression has been around a whole LTS cycle.

**Comment by locks** [comment]
Hi @skeate, I am sorry that we let this PR sit in limbo for so long.

We have discussed this in the last core meeting and we decided we weren't comfortable changing the behaviour of an API that has been around for so long–mea culpa.

Instead, we would like to actually deprecate this and some similar methods, and move then to an addon. This way you can use the addon if you want the current behaviour, you can use another library like lodash, or you can implement it yourself.

**Pull request closed without merging**
