### PR TITLE
[FEATURE] Create helper integration tests

### PR DESCRIPTION
**Pull request by Gaurav0**
This is for: ember-cli/ember-cli#4517 and is paired with https://github.com/ember-cli/ember-cli-legacy-blueprints/pull/22

Note: I have not yet made integration tests default. I think it might be a good idea to do that in a followup PR once we know all is well and working?

### CODE REVIEW

**Comment by rwjblue** [comment]
What output does this result in?

**Comment by Gaurav0** [comment]
@rwjblue Sample output from `ember g helper-test bar-baz --integration` resulting in `tests/integration/helpers/bar-baz-test.js`

```
import { moduleForComponent, test } from 'ember-qunit';
import hbs from 'htmlbars-inline-precompile';

moduleForComponent('bar-baz', 'helper:bar-baz', {
  integration: true
});

// Replace this with your real tests.
test('it renders', function(assert) {
  this.set('inputValue', '1234');

  this.render(hbs`{{bar-baz inputValue}}`);

  assert.equal(this.$().text().trim(), '1234');
});
```

**Comment by rwjblue** [comment]
Thanks @Gaurav0!

**Comment by Gaurav0** [comment]
Thank you for reviewing, @rwjblue.

**Pull request merged**
