### PR TITLE
[BUGFIX release] Update HTMLBars to 0.13.32.

### PR DESCRIPTION
**Pull request by rwjblue**
Fixes a number of edgecases with property vs attributes.

### CODE REVIEW

**Comment by stefanpenner** [comment]
i'll take a look at the failures

**Comment by stefanpenner** [comment]
The test failures look valid. I will backport them to HTMLBars and fix.

**Comment by stefanpenner** [comment]
Actually it appears this is fixing bugs (bad tests so far). I'll still add the tests to HTMLBars for posterity.

**Comment by stefanpenner** [comment]
lets see if CI is happier now.

**Comment by rwjblue** [comment]
Thanks for fixing the failures, @stefanpenner!

**Pull request merged**
