### PR TITLE
Failing test for rerendering after updating `layout`.

### PR DESCRIPTION
**Pull request by rwjblue**
This test replicates https://github.com/emberjs/ember.js/issues/11301, https://github.com/emberjs/ember.js/issues/11186, and #12216.

### CODE REVIEW

**Comment by elwayman02** [comment]
We have a component that renders a number of different layouts based on certain conditions and flows.  In Ember 1.12.1, we were accomplishing this by updating the `layoutName` and then calling `rerender`.  When I updated our app to 1.13, the old template was still rendered, even though the layoutName had been updated.

I've created JSbins illustrating the approximate issue we're seeing.  The only difference is that in these examples, both the `layout` and `layoutName` attributes seem to be updating properly, whereas in our app, I'm not seeing `layout` update correctly when `layoutName` is changed.  In either case, both the examples and our app fail to render properly in 1.13, so I'm hoping the solution will be the same for each.

Working 1.12 Example: http://emberjs.jsbin.com/payuqe/3/edit?html,js,output

Broken 1.13 Example: http://emberjs.jsbin.com/xufezo/2/edit?html,js,output

**Comment by ResentedHook** [comment]
so...hey...any plans on merging this?  @rwjblue tends to know what he's doing...

**Comment by mixonic** [comment]
@ResentedHook this is a failing test, not an implementation of the fix.

**Comment by joankaradimov** [comment]
Can we expect this issue to ever be fixed?

**Comment by rwjblue** [comment]
No, I do not believe we will fix it. It was definitely a regression in 1.13, and I am terribly sorry about that. However, it was never supported in 2.x, and having layout for a component be static after `init` is pretty important for optimizations in Glimmer 2.

**Comment by joankaradimov** [comment]
:+1:

**Pull request closed without merging**
