### PR TITLE
Bump RSVP dependency

### PR DESCRIPTION
**Pull request by dschmidt**
Hey,

would be nice to have latest rsvp which adds the `label` as second argument to the `on('error', ...)` hook.

https://github.com/tildeio/rsvp.js/pull/404

BR,
Domme

### CODE REVIEW

**Comment by rwjblue** [comment]
Seems good to me. 

@stefanpenner - Any objections?

**Comment by rwjblue** [comment]
(Build is broken on master due to a downstream dep change, not necessarily this PR)

**Comment by stefanpenner** [comment]
> @stefanpenner - Any objections?

nope LGTM

**Comment by dschmidt** [comment]
Rebased but sauce build still fails, everything else is green

**Comment by stefanpenner** [comment]
potentially just a random saucelabs error, kicking it.

**Comment by dschmidt** [comment]
Looks like, before Edge was failing, now it's IE9 and IE10.. can you kick it again?

**Comment by stefanpenner** [comment]
@dschmidt kicking

Someone should likely add some basic retry (up to two times or something) to the sauce lab tests..

**Comment by dschmidt** [comment]
Everything passed! :+1:

**Comment by stefanpenner** [comment]
thank you kindly sir!

**Pull request merged**
