### PR TITLE
[CLEANUP] Move components to glimmer

### LINKED ISSUE #14020: Components in `ember-glimmer/components` symlink to HTMLBars.
The original source should be in `ember-glimmer` and the `ember-htmlbars` versions can be a symlink that points to `ember-glimmer`.  Currently, this is the other way around...

### PR DESCRIPTION
**Pull request by Serabe**
The original code is moved from `ember-htmlbars` to `ember-glimmer` and
symlinked from `ember-htmlbars`

Fixes #14020

### CODE REVIEW

**Comment by mixonic** [comment]
Seems reasonable to me, I'd like someone on the day-to-day of Glimmer to approve

**Comment by mixonic** [comment]
Merge-master @chancancode sez:

> @mixonic: I didn’t have time to look closely but if it’s literally/correctly `foreach(file in /ember-htmlbars/lib/components/*.js) { rm /ember-glimmer/$same-file; mv file /ember-glimmer/$same-place; ln -s /ember-glimmer/$same-file /ember-htmlbars/$same-file }` then it is :+1:

I did some sanity checks reading through the diff and all files seem to be accounted for as expected. @Serabe let me know if Godfrey's suggestion differs from what you did here.

Optimistically merging 😬 

Thanks!

**Comment by rwjblue** [comment]
Thanks @serabe!

**Comment by Serabe** [comment]
@mixonic I did something similar but using zsh Ctrl+x Ctrl+e that let's me edit the current command in my editor of choice. A couple of vim commands later I had everything in place :)

**Pull request merged**
