### PR TITLE
[glimmer2] enable tests fixed by #13615

### PR DESCRIPTION
**Pull request by fivetanley**
refs #13644

### CODE REVIEW

**Comment by chadhietala** [comment]
These are going to fail until the [two-flush branch](https://github.com/emberjs/ember.js/tree/two-way-flush) is merged I believe.

**Comment by fivetanley** [comment]
@chadhietala They seem to pass individually. Can you help me understand what the two-flush branch does and why it might fix these issues?

**Comment by chancancode** [comment]
@chadhietala I thought they were related, but I debugged this with @fivetanley and I think we just made a mistake (forgetting to clear the DOM when destroying the `RenderResult`). I am pretty confused how it went unnoticed for so long. We much have some other paths that "incidentally" clears the DOM most of the time so the other tests are not affected by it?

**Comment by chancancode** [comment]
Merged in #13832

**Pull request closed without merging**
