### PR TITLE
Code refactoring for ember-utils package

### PR DESCRIPTION
**Pull request by artemgurzhii**

### CODE REVIEW

**Comment by bjornharrtell** [comment]
Are the extra () really needed for the function to arrow function replacements?

**Comment by artemgurzhii** [comment]
Not sure that I understand what do you mean by that. Are you talking about [this line](https://github.com/emberjs/ember.js/pull/14833/commits/9261ac3d7a80967a1e929bbd276b4371c8286cb7#diff-522ab32c86869b9716d46d27c7d7f3b0L4)?

**Review by stefanpenner — APPROVED** [review]
🎉  👍

**Comment by bjornharrtell** [comment]
This:
```js
export const HAS_NATIVE_WEAKMAP = ((() => {
  // detect if `WeakMap` is even present
  let hasWeakMap = typeof WeakMap === 'function';
  if (!hasWeakMap) { return false; }
}))();
```

Seems to me have superflous () i.e this is equivalent:

```js
export const HAS_NATIVE_WEAKMAP = (() => {
  // detect if `WeakMap` is even present
  let hasWeakMap = typeof WeakMap === 'function';
  if (!hasWeakMap) { return false; }
})();
```

But perhaps there is something I'm simply missing here.. :)

**Comment by artemgurzhii** [comment]
I think I made mistake here, as I understand it should be an IIFE function, and this parenthesis can be omitted.

**Pull request merged**
