### PR TITLE
Update text_field.js

### PR DESCRIPTION
**Pull request by locks**

### CODE REVIEW

**Comment by rwjblue** [comment]
Why?

**Comment by locks** [comment]
@rwjblue wanted Travis to tell me what would break because my machine can't handle the tests and opened the PR in the wrong repo :$

**Comment by locks** [comment]
Out of curiosity, do you know why the try catch is there? Seems like something we should cover with a test.

**Comment by rwjblue** [comment]
Some browsers throw when changing `.type` on an `<input>` element.

**Pull request closed without merging**
