### PR TITLE
[DOC beta] Ember Route API - Change to avoid globals

### PR DESCRIPTION
**Pull request by greyhwndz**
@rwjblue: Would be glad to receive feedback on this. Thanks!

### CODE REVIEW

**Comment by rwjblue** [comment]
This looks good, but we need to hold off on changing API doc style completely until we have decided how to represent this in the website.  There are still many globals users and I would like to ensure that they can also use the API docs.

I'll try to remember to bring this up at the next core team meeting so we can decide the best path forward.

**Comment by greyhwndz** [comment]
@rwjblue: sure :+1:

**Comment by greyhwndz** [comment]
@rwjblue: do you think it's okay if instead of just presenting the new syntax we also present using the Globals?

**Comment by greyhwndz** [comment]
@rwjblue, can I just close this now?

**Comment by Serabe** [comment]
@rwjblue, can you check if we can close this, please?

 Thank you!

**Comment by locks** [comment]
I am closing this as the code samples have been updated to the latest syntax.
@greyhwndz thank you for your work!

**Pull request closed without merging**
