### PR TITLE
[BUGFIX beta] Ensure new Registry created with app instance

### PR DESCRIPTION
**Pull request by mutewinter**
References emberjs/ember.js#10310

### CODE REVIEW

**Comment by mutewinter** [comment]
Here's the PR @rwjblue

**Comment by stefanpenner** [comment]
@mutewinter test?

**Comment by mutewinter** [comment]
> @mutewinter needs test

Not sure how to write a test for this.

**Comment by fivetanley** [comment]
@dgeb @stefanpenner guidance for a test would be great

**Comment by searls** [comment]
I think I'm still getting bitten by this; any update?

**Comment by rwjblue** [comment]
I'm happy to help with the test here, but I need someone to help me with understanding the failure scenario (and to confirm it is still an issue)...

**Comment by rwjblue** [comment]
The entire purpose of the registry is that it is shared by many instances, so I'm doubtful that this is the right fix.

Closing for now, and continuing the conversation in #10310.

**Pull request closed without merging**
