### PR TITLE
jspm support

### PR DESCRIPTION
**Pull request by MajorBreakfast**
This should fix https://github.com/components/ember/pull/66

### CODE REVIEW

**Comment by MajorBreakfast** [comment]
That was quick. Thanks!

**Comment by stefanpenner** [comment]
@MajorBreakfast kein problem

**Comment by MajorBreakfast** [comment]
Will this make it into ember 1.11.0?

**Comment by rwjblue** [comment]
I use the commit prefixes to determine what to cherry-pick into beta/release channels.  This wasn't flagged as `[BUGFIX beta]` so I didn't initially pull it into beta.

It has been cherry-picked now, and should be included in 1.11.0.

**Comment by MajorBreakfast** [comment]
@rwjblue Thanks!

**Comment by OrKoN** [comment]
Was it included? The jspm key is still missing here https://github.com/components/ember/blob/master/package.json

**Comment by MajorBreakfast** [comment]
It's in the
- release branch
- beta branch
- canary branch

@OrKoN For now:
`jspm install ember=github:components/ember@release`
`jspm install ember=github:components/ember@beta`
`jspm install ember=github:components/ember@canary`
Just tested all three. All work fine. Pretty slick :)

@rwjblue Would it be possible to tag the releases to commits on the beta and release branch?

**Comment by rwjblue** [comment]
Possibly. I'll fix master and re-tag first (just to get it working ASAP).

**Pull request merged**
