### PR TITLE
add async functions and generator functions to Ember.typeof

### PR DESCRIPTION
**Pull request by anonrose**
https://github.com/emberjs/ember.js/issues/15151

### CODE REVIEW

**Comment by mmun** [comment]
Should consider generator functions as well.

**Comment by anonrose** [comment]
@mmun thanks

**Comment by rwjblue** [comment]
I think his is probably fine to land, but I do wonder if we should work towards deprecating `Ember.typeOf` completely, and instead suggest folks to "use the platform". All of these small custom "Embery" bits generally chafe the wrong way now that the platform is actually progressing...

**Comment by anonrose** [comment]
@rwjblue I completely agree

**Comment by stefanpenner** [comment]
we should bring this up at the meeting for discussion.

**Comment by rwjblue** [comment]
We discussed this in the weekly Ember core team meeting, and came to the conclusion that this API is not something that we want to continue making changes to. It is likely that we will work towards creating a deprecation RFC.

**Comment by rwjblue** [comment]
Thank you very much for taking the time to work on this! Given the decision to not change this, I am going to close this PR...

**Pull request closed without merging**
