### PR TITLE
Fixup build

### PR DESCRIPTION
**Pull request by stefanpenner**

### CODE REVIEW

**Comment by rwjblue** [comment]
Can you remove 6fd6b222eb0dd0071f0a5d6441e9e3af3dea1fca from this PR?  The commit in question was already reverted in https://github.com/emberjs/ember.js/pull/12574.

**Comment by stefanpenner** [comment]
cc @krisselden

**Comment by krisselden** [comment]
Thank you!

**Comment by stefanpenner** [comment]
@rwjblue good catch, fixed

**Comment by rwjblue** [comment]
:+1: - LGTM

**Pull request merged**
