### PR TITLE
[BUGFIX] use strict mode for Object.create

### PR DESCRIPTION
**Pull request by givanse**
Cleaning up the changes from https://github.com/emberjs/ember.js/pull/9442

Bug 138038 - [iOS8][ARMv7(s)] Optimized Object.create in 'use strict' context sometimes breaks.
https://bugs.webkit.org/show_bug.cgi?id=138038
> 2015-07-06
> This was fixed in iOS 9 Dev Seed 2.

### CODE REVIEW

**Comment by stefanpenner** [comment]
wooo nice. We will need to merge this, IFF the % of affected users is very low. Although I hope we can land this now.

**Comment by givanse** [comment]
Market share as measured by the App Store on October 25, 2016.

iOS 10 - 60%
iOS 9  - 32%
earlier - 8%

[This other site](https://data.apteligent.com/ios/) says: iOS 8 (3.59%)

And [this one](https://david-smith.org/iosversionstats/) says: iOS 8 (3.3%)

**Comment by stefanpenner** [comment]
@givanse thanks for those stats.

**Comment by stefanpenner** [comment]
We still don't know how many of those users are on 32bit devices (the affected devices). It may be quite abit smaller then?

**Comment by rwjblue** [comment]
@stefanpenner - Ya, agreed. Should be at least somewhat smaller, and if this rides the typical canary cycle it will be another 8-10 weeks more before release. 

This seems good to me...

**Comment by rwjblue** [comment]
Added to meeting agenda for 2016-12-02 (no meeting on 2016-11-25 due to Thanksgiving in the US).

**Comment by givanse** [comment]
From [list of iOS devices](https://en.wikipedia.org/wiki/List_of_iOS_devices), the ones with ARMv7 are the iPhone 5 and iPhone 5C.

[Device usage](https://david-smith.org/iosversionstats/):
iPhone 5	4.9%
iPhone 5c 2.9%

[iPhone 8.X adoption)](https://david-smith.org/iosversionstats/):
iPhone 5	7.1%
iPhone 5c 3.1%

Affected users:
iPhone 5	(4.9%/100 * 7.1%/100) * 100 = 0.3479%
iPhone 5c (2.9%/100 * 3.1%/100) * 100 = 0.0899%

total = 0.4378%

Plus, Christmas is coming and people will be getting new shinny mobiles XD

**Comment by rwjblue** [comment]
Awesome, thanks for digging in on these stats (they make this much more actionable)!

**Comment by givanse** [comment]
I would have done it with the PR submission, TIL webkit bugs have tags & ARMv7 is a x32 architecture :)

**Comment by stefanpenner** [comment]
@givanse big +1 on doing the digging on this one. you rock

**Comment by aleige1993** [comment]
For beginners, passing by

**Comment by stefanpenner** [comment]
Pinged the core-team, hoping to get a resolution this week.

My opinion is that, based on @givanse numbers provided (and that the fix is already somewhat precarious) we should let this ride the canary train.

**Comment by givanse** [comment]
forgot about this and `push -f`` to master in my fork, sorry about that XD

**Pull request closed without merging**
