### PR TITLE
[CLEANUP beta] Remove `legacy-each-view`

### PR DESCRIPTION
**Pull request by duggiefresh**

### CODE REVIEW

**Comment by rwjblue** [comment]
This needs to stay throughout the life of the ember-legacy-views addon. We ultimately should remove all of those legacy views and move them to the addon, but that work is not quite done yet.

**Comment by duggiefresh** [comment]
Ah! Good to know. Will close :ice_cream: Thanks, Rob.

**Comment by stefanpenner** [comment]
maybe we should commit a comment, so future travelers also know?

cc @duggiefresh

**Comment by duggiefresh** [comment]
Sounds good. I'll update the original comment found within the `legacy-each-view` view. :+1:

**Pull request closed without merging**
