### PR TITLE
Fix {{each}} inverse transitioning to template bug.

### PR DESCRIPTION
**Pull request by rwjblue**
Fixes https://github.com/emberjs/ember.js/issues/11140.

### CODE REVIEW

**Comment by rwjblue** [comment]
Just confirmed, this is still broken after https://github.com/emberjs/ember.js/pull/11338 (which changed some `yieldItem` internals in HTMLBars).

**Comment by tomdale** [comment]
@wycats We should take a look at this one next week too. I suspect it shouldn't be too hard to track down.

**Comment by rwjblue** [comment]
Thank you @tomdale!!!!!!

**Comment by tomdale** [comment]
Note to past @tomdale: it was hard to track down. :P

**Pull request merged**
