### PR TITLE
Update in readme.md in the Building Ember Section.

### PR DESCRIPTION
**Pull request by sambit2**
Updating Building Ember.js in the readme.md
Earlier: 
'npm install'
Now after change:
'npm install -g ember-cli'
As given in official site emberjs.com it should be the command as I changed because if we type 'npm install' then no file or package is found. This command written after change is already present in the official site but not in the readme for which I faced problem in installations.
@rwjblue Correct me if I am wrong as I am new to the Ember community.

### CODE REVIEW

**Comment by stefanpenner** [comment]
should be required:

https://github.com/emberjs/ember.js/blob/master/package.json#L27

**Comment by sambit2** [comment]
@stefanpenner I did not understand properly what do you mean by those links. When I tried with 'npm install -g ember-cli' then it worked but didn't work with what was mentioned. So, I wanted to change that line in readme file. So, did you mean that these packages are required before installing ember?

**Comment by stefanpenner** [comment]
Because npm install should already include ember cli in the node_modules and running npm run * will add node_modules/.bin/ to the path, which means it uses its own (and correct version) of ember

**Comment by andrewflash** [comment]
I also have the same issue with @sambit2. I tried to install on Windows 10 (fresh install), downloaded and installed `node.js v5.7.0 stable`. Here is the screenshot. 


Using `npm install` gives some errors, but using `npm install -g ember-cli` runs ok. Any suggestion? Thank you.

**Comment by btecu** [comment]
What you both are missing is that `npm install` should be run inside the `emberjs` repository folder, not in random places `(C:\Users\Toshiba)`.

Those instructions are for building `emberjs`.

Also, it is probably safe to assume that if you're working on `emberjs` you already have `ember-cli` installed.

**Comment by andrewflash** [comment]
@btecu ah.. ok.. case closed.. thanks..

**Pull request closed without merging**
