### PR TITLE
Allow IE8 to pass hasDOM check.

### LINKED ISSUE #10155: environment.hasDOM check broken on IE8
The check we are doing [here](https://github.com/emberjs/ember.js/blob/4a1010a490c09dc4d662d22b229523c8f8734f82/packages/ember-metal/lib/environment.js#L18-21) for `hasDOM` does not pass on IE8.  Specifically `typeof document.createElement` is `object` under `IE8`.

screenshot

### PR DESCRIPTION
**Pull request by rwjblue**
Fixes https://github.com/emberjs/ember.js/issues/10155.

/cc @wycats

### CODE REVIEW

**Comment by fivetanley** [comment]
Lol I am curious as to what the type is reported as in IE8.

**Comment by fivetanley** [comment]
Ah, I see, closes https://github.com/emberjs/ember.js/issues/10155.

**Comment by stefanpenner** [comment]
silly IE :P

**Comment by tomdale** [comment]
This is fine with me and @wycats. Scumbag IE8.

**Pull request merged**
