### PR TITLE
conditionally add bindings related methods to meta

### PR DESCRIPTION
**Pull request by bekzod**
`ENV._ENABLE_BINDING_SUPPORT` is not enabled there is no need to have such methods in `meta` ?

### CODE REVIEW

**Review by rwjblue — COMMENTED** [review]
Seems good,  but we should ensure the tests in Ember-2-legacy addon still pass. I recall there being a race condition where the addons code executes _after_ Ember is evaluated which would make this change break the addons ability to add binding Support...

**Comment by krisselden** [comment]
@rwjblue addons should get a chance to add to the env, I think module unification if I recall is pulling config too early and caching it, we should ensure the env does get baked until all addons been initialized.

**Comment by rwjblue** [comment]
@krisselden - I completely agree with what you said, but it has no relationship to this PR (or my prior comment).

**Comment by bekzod** [comment]
@rwjblue this is updated with svelting flags

**Review by rwjblue — APPROVED** [review]
Awesome, thank you!

**Pull request merged**
