### PR TITLE
[CLEANUP BETA] Remove {{with foo as bar}} support

### LINKED ISSUE #11780: Remove `{{with foo as bar}}` support.
* Remove https://github.com/emberjs/ember.js/blob/master/packages/ember-template-compiler/lib/plugins/transform-with-as-to-hash.js
* Remove https://github.com/emberjs/ember.js/blob/master/packages/ember-template-compiler/lib/main.js#L24
* Fix any tests that are not intentionally testing the deprecated format
* Delete any tests that are intentionally testing the deprecated format

### PR DESCRIPTION
**Pull request by pdud**
This fixes #11780

Thanks again for the Good for New Contributors label – I'm learning lots!

### CODE REVIEW

**Comment by rwjblue** [comment]
Looks great!

Since this needs to land in the beta cycle, can you prefix your commit with '[CLEANUP BETA]'?

**Comment by rwjblue** [comment]
Looks like this needs a rebase now since https://github.com/emberjs/ember.js/pull/11790 landed.

**Comment by pdud** [comment]
Added the prefix, updated a couple additional test descriptions away from foo as bar, and rebased.

Thanks for the info on the commit prefixes!

**Comment by rwjblue** [comment]
Thank you!

**Pull request merged**
