### PR TITLE
[Feature] util blueprint for module unification

### PR DESCRIPTION
**Pull request by daibhin**
part of ember-cli/ember-cli#7530

### CODE REVIEW

**Comment by GavinJoyce** [comment]
@daibhin looking good, nice one!

Can you also add some tests to [util-test-test.js](https://github.com/emberjs/ember.js/blob/master/node-tests/blueprints/util-test-test.js)? The test files should be colocated with the util function file, much like `service-test` in https://github.com/emberjs/ember.js/pull/16397

**Comment by daibhin** [comment]
@GavinJoyce Updated the `util-test-test.js` file, let me know if there's anything else that needs to be done 😄

**Comment by GavinJoyce** [comment]
`yarn run lint` gives the follow error which is causing CI to fail:

screen shot 2018-04-18 at 08 57 27

**Comment by daibhin** [comment]
Sorry about that, fixed! I'm still trying to figure out which is more amazing `yarn run lint:fix` or `describe.only`

**Comment by GavinJoyce** [comment]
@daibhin as a final step,  perhaps you could add an in-repo-addon test [similar to this](https://github.com/emberjs/ember.js/pull/16553)? This will ensure that we're not breaking existing functionality

**Comment by mixonic** [comment]
Looks great! Thanks @daibhin :-D

**Pull request merged**
