### PR TITLE
Update to ember-cli@3.5.0.

### PR DESCRIPTION
**Pull request by rwjblue**
Brings loads of changes/fixes, but the reason I did it was to start using Broccoli 2...

### CODE REVIEW

**Review by locks — APPROVED** [review]

**Comment by rwjblue** [comment]
Yeah, its because the tests are setup to expect the wrong thing by default `ember new foo`. Its going to be a bit of a chore to fix 😩.

**Comment by rwjblue** [comment]
I pushed one commit with fixes for `acceptance-test` file to show what I mean.

**Comment by Turbo87** [comment]
oh... that makes sense... 😞

**Comment by ppcano** [comment]
@simonihmig Will #17207 and #17198 finally unblock the `ember-cli@3.5` upgrade or there are something else that needs to be done.

I am working on the MU blueprints and I would like to test with new versions of `ember-cli` and `ember-cli-blueprint-test-helpers`.

**Comment by simonihmig** [comment]
> Will #17207 and #17198 finally unblock the ember-cli@3.5 upgrade or there are something else that needs to be done.

@ppcano I guess there are a few more blueprints that need to be "fixed", which I haven't touched yet (e.g. mixins). I believe making each single test explicit about the test framework version used is the key here, as in this example: https://github.com/emberjs/ember.js/pull/17207/files#diff-b1525449225102a81123371a3a8c87f8R26

**Comment by ppcano** [comment]
#17212 supersedes this PR

**Comment by rwjblue** [comment]
Thank you @ppcano!

**Pull request closed without merging**
