### PR TITLE
[BUGFIX release] Fix #13670

### LINKED ISSUE #13670: this.render and this.disconnectOutlet stopped working in 2.6.0
Hi there!

First of all thank you for an amazing work with Ember and its ecosystem, you guys are awesome!

Today I've updated my application to `2.6.0` ( together with Ember-CLI, as well as, Ember Data). However, after some testing, I've noticed my dialogs (modals) stopped working on consecutive action.

**Example:**

- user clicks on button to show modal via `this.render`
- user selects yes or no and component sends action with user's decision
- modal is closed via `this.disconnectOutlet`
- user attempts to open modal again and... **nothing happens** 

Here is a Twiddle with replicated issue: https://ember-twiddle.com/ff0aa621c1fde10858b4cc4f1fb62072 As you can see you cannot render dialog component multiple times.

Any help would be much appreciated, thanks!

### PR DESCRIPTION
**Pull request by krisselden**

### CODE REVIEW

**Comment by stefanpenner** [comment]
👍

**Comment by krisselden** [comment]
I squashed and updated the commit message, this is ready to go when green.

**Comment by stefanpenner** [comment]
@homu r+

**Comment by chadhietala** [comment]
The @homu thing never works correctly in this repo.

**Comment by stefanpenner** [comment]
> The @homu thing never works correctly in this repo.

:(

**Comment by ppcano** [comment]
@rwjblue Is it planned to port this fix to the `release` branch and publish the `2.6.1` release?
Thanks

**Comment by rwjblue** [comment]
@ppcano - Yes.

**Pull request merged**
