### PR TITLE
[DOC Release] Mark Route.disconnectOutlet() as public

### PR DESCRIPTION
**Pull request by joeruello**

### CODE REVIEW

**Comment by rwjblue** [comment]
I believe this is correct, but would like someone else to confirm.

**Comment by rwjblue** [comment]
@ef4 - What do you think? Should this be public?

**Comment by ef4** [comment]
Yes, I think it has been historically treated as public. But I would also be in favor of marking it deprecated.

**Comment by rwjblue** [comment]
Closing this PR (I'd rather not make it `@public` just before deprecating).

**Pull request closed without merging**
