### PR TITLE
[DOC] Use `as |obj|` syntax for #each examples

### PR DESCRIPTION
**Pull request by knownasilya**
The parameters still needs some work though, as well as the helper itself since it says that it requires the `{{#each item in list}}` form.

### CODE REVIEW

**Comment by rwjblue** [comment]
Looks like we lost the previous docs for `{{with}}` and `{{each}}` with the glimmer work merging.  Would you mind bringing them back and updating (as you have here) to use block params?

**Comment by knownasilya** [comment]
@rwjblue sure.

**Comment by knownasilya** [comment]
@rwjblue seems like `{{with}}` docs are still there. But I brought back the each docs, although the options need to be updated and I'm not sure what they are well enough to document them.

**Comment by mixonic** [comment]
@knownasilya shoot, I think we merged an alternative in https://github.com/emberjs/ember.js/pull/11146

If you take a look and think something is still missing, please open a fresh PR. Thanks for your work on this!

**Comment by knownasilya** [comment]
Yeah no problem

**Pull request closed without merging**
