### PR TITLE
[BUGFIX beta] Do not rely prototype extensions (objectAt)

### PR DESCRIPTION
**Pull request by btecu**
Do not use prototype extension for `objectAt`.

Related to #9269 and based on the work of @stefanpenner in #10899.

If this is acceptable, will continue addressing one extension at a time for quicker merging.

### CODE REVIEW

**Comment by mmun** [comment]
@btecu Awesome! Been hoping someone would start moving these over.

**Comment by stefanpenner** [comment]
> If this is acceptable, will continue addressing one extension at a time for quicker merging.

:+1:

**Comment by stefanpenner** [comment]
oh, lets make sure `objectAt` has a unit test.

We should also consider a future where we expose these as public API, similar to `get`/`set`, but that can come via RFC/later pr

**Comment by btecu** [comment]
Thanks both! I've added a unit test.

**Pull request merged**
