### PR TITLE
[DRAFT] Redesign API for trusted (unsafe) strings

### PR DESCRIPTION
**Pull request by chriskrycho**
This is a draft PR to accompany a forthcoming proposal to improve this API along lines folks have talked about for years; I drafted the change to make it easier to discuss concretely with the accompanying RFC. This should not be taken as indicating we *are* doing this, only that I am *proposing* we do it and making it easy if we decide to do so!

---

- Introduce an opaque public type for the result of marking a string as trusted, `TrustedString`. Make all the mechanical details of the class private, accessible *only* within the internal module. Define the type as an opaque type that other users can neither instantiate nor subclass, which implements the `SafeString` contract from Glimmer, i.e. it provides only a `toHTML(): string` method.

- Deprecate `htmlSafe` and `isHTMLSafe` and introduce new names which indicate what they actually do/are: `unsafelyTrustString` and `isTrustedString`.

### CODE REVIEW

**Comment by wagenet** [comment]
See also https://github.com/emberjs/rfcs/pull/443

**Comment by kategengler** [comment]
Is this still relevant? It is a draft PR

**Comment by chriskrycho** [comment]
Still worth doing, and this approach is probably roughly right, but obviously I am not going to land it. I will close this, but/and feel free to point people here as useful prior art, and folks should feel *very* free to `git cherry-pick` this and run with it themselves if anyone wants to!

**Comment by chriskrycho** [comment]
…also it needs an RFC. Which is why we did not land it.

**Pull request closed without merging**
