### PR TITLE
Removes deprecated Private INVOKE API

### PR DESCRIPTION
**Pull request by nlfurniss**
Removes deprecated Private INVOKE API, `actions.custom-invoke-invokable`

### CODE REVIEW

**Comment by chancancode** [comment]
Thanks! The content of the PR doesn't seem to match the title, is that right? (Also, for future, do you mind rebasing instead of merging master into your branch to keep the history more linear?)

**Comment by nlfurniss** [comment]
> Thanks! The content of the PR doesn't seem to match the title, is that right? (Also, for future, do you mind rebasing instead of merging master into your branch to keep the history more linear?)

Yeah something is off, I’ll take a look tomorrow. Normally I would rebase, but GH GUI only allows you to fetch and merge in fork, not rebase 😕 (and I’m on my phone since my laptop is out of juice). 

You can rebase and merge from the GUI though right?

**Comment by nlfurniss** [comment]
@chancancode okay figured out the discrepancy and fixed the title and desc

**Comment by mixonic** [comment]
I merged this and a number of other PRs what contained a merge commit from master into the PR's branch, but for the future @nlfurniss FWIW I strongly agree with @chancancode that a clean history is strongly preferred. It really helps us deal with rollbacks or understanding a change to have a fairly linear history on `master` with semantic commits. Thanks for taking it into consideration in the future.

**Comment by nlfurniss** [comment]
> I merged this and a number of other PRs what contained a merge commit from master into the PR's branch, but for the future @nlfurniss FWIW I strongly agree with @chancancode that a clean history is strongly preferred. It really helps us deal with rollbacks or understanding a change to have a fairly linear history on `master` with semantic commits. Thanks for taking it into consideration in the future.

@mixonic for sure. It’s sadly not possible with the GH UI, and I was hoping the ember repo allowed “rebase and merge” from PRs to fix the issue. Going forward the ones I haven’t reopened I’ll rebase.

**Pull request merged**
