### PR TITLE
Fix View#nearest* tests

### PR DESCRIPTION
**Pull request by mitchlloyd**
Using the `willRender` hook over `render` for test setup fixed the tests in this module.

### CODE REVIEW

**Comment by rwjblue** [comment]
This looks good.

Can you double check that we have some tests specifically for calling `View.prototype.render`?  We have to ensure that we have some tests around to make us fix this (for SemVer compliance in 1.x)....

**Comment by mitchlloyd** [comment]
Ah, I thought `render` wasn't around anymore and private. Now I see that it is in TemplateRenderingSupport. I'll close this and see if I can get `render` to work.

**Comment by rwjblue** [comment]
Pulled into idempotent-rerender branch in f892dc8390f40ba84e825e946dea131afbaa01c1 preserving attribution.  Thanks for the hard work here @mitchlloyd!

**Comment by mitchlloyd** [comment]
Aw thanks. I took a look at implementing the view's `render(buffer)` method for backwards compatibility but it did not seem like an easy change good for a new contributor. Seems like it might require some core team discussion and/or thought leadership ;)  

When that is figured out, I bet we'll see a lot more passing tests since `render` appears to be used a lot in test setup.

**Comment by rwjblue** [comment]
@mitchlloyd - Yes, agreed. Implementing `render: function(buffer) { }` is absolutely non-trivial. I brought up this case specifically during our core team meeting on Friday, and we decided that refactoring tests to use current idiomatic Ember app code is preferable (which is why in the commit referenced these were changed to use a template with `{{view}}`) as long as at least one test that deals with the old deprecated behavior still exists (to force us to ensure it works for SemVer purposes).

**Pull request closed without merging**
