### PR TITLE
[DOC lts] Document Transition directly in source, remove yuidoc.json stuff

### PR DESCRIPTION
**Pull request by Gaurav0**
This is for #16153 

This takes an alternative approach to @efx 's [attempt](https://github.com/efx/ember.js/commit/7a884338ada1ba3d7e853f417a6d61cafdb06227) and simply copies the transition docs into ember-source, which haven't changed in a very long time. While a direct import might be preferred for synchronization purposes, this might be better so that transition docs don't simply get lost again.

If it is possible, I'd like to see this backported to all releases since 2.15.

### CODE REVIEW

**Comment by toddjordan** [comment]
why is it that we can't just keep transition doc inline with its source?  Did we try changing lib to dist in yuidoc.json, or is there something keeping that from working?

**Comment by Gaurav0** [comment]
I think we'd have to revert https://github.com/tildeio/router.js/blob/master/package.json#L26-L29 in order to do so. (The original source files are not included when you import router.js via npm.)

While we could do that, I'm afraid unless we have some automated testing for documentation around it, we will lose these docs in the future again, that's why I proposed simply copying them here: https://github.com/emberjs/ember.js/issues/12142#issuecomment-362302246

**Comment by toddjordan** [comment]
A good way to check is from your ember.js project navigate to the path for transition in node_modules and see if the js file with documentation is there under dist.

**Comment by Gaurav0** [comment]
@toddjordan @efx transition.js appears in that directory. In fact, running `yarn run docs` produces the Transition.html document on his branch, so I see no reason why he couldn't PR his branch as is.

**Review by rwjblue — APPROVED** [review]
I prefer this version, as future refactors in router.js microlib may add more files/directories that we might forget to add to exclude.  This seems better to me...

**Comment by Gaurav0** [comment]
@rwjblue Why was this only merged to master? I wrote [DOC lts]

**Pull request merged**
