### PR TITLE
Mark Enumerable#sortBy as public

### PR DESCRIPTION
**Pull request by Kerrick**

### CODE REVIEW

**Comment by stefanpenner** [comment]
failure appears unrelated, re-running

**Comment by stefanpenner** [comment]
opened relevant issue: https://github.com/babel/babel/issues/1963

**Comment by stefanpenner** [comment]
babel is fixed, restarting build

**Comment by pixelhandler** [comment]
:+1:

**Comment by stefanpenner** [comment]
kicking sauce labs test scenario

**Comment by rwjblue** [comment]
Can you prefix the commit and PR title with `[DOC release]`?

**Comment by stefanpenner** [comment]
@Kerrick friendly reminder ^^

**Comment by rwjblue** [comment]
@Kerrick - ping

**Pull request merged**
