### PR TITLE
[DOC] Added documentation for didTransition bubbling

### PR DESCRIPTION
**Pull request by arunrajkumar235**

### CODE REVIEW

**Review by RobbieTheWagner — APPROVED** [review]
This seems fine to me, but curious what others think. @locks @jenweber @mansona thoughts?

**Review by locks — CHANGES_REQUESTED** [review]
I think you made a mistake @arunrajkumar235. You put the documentation in the `loading` event, not `didTransition`.
Can you update it so we can move it forward?

**Comment by rwwagner90** [comment]
@locks I just moved it. Aside from location, did the content look okay?

**Comment by pzuraq** [comment]
This PR looks good, but should be resubmitted against `master`. In general, if a PR should be backported to beta/release/lts, you can add the branch to backport to the tag:

```
[DOC release]
```

Going to close this for now, please do resubmit it though!

**Comment by rwwagner90** [comment]
@arunrajkumar235 can you open a new PR against master please?

**Pull request closed without merging**
