### PR TITLE
Replace instances of ArrayProto.slice(arguments) with non-leaking versions

### PR DESCRIPTION
**Pull request by jamiebuilds**

### CODE REVIEW

**Comment by mixonic** [comment]
@thejameskyle the test failure here looks like a legit failure not just a Travis quirk. I like the direction.

**Comment by thejameskyle** [comment]
Weird, I wasn't seeing those errors locally.

**Comment by mixonic** [comment]
If you run `npm test` locally you may hit them. The one I reviewed was in the individual packages tests, where we enforce that a given package only have access to a limited list of other packages. Usually I'm bit on those when I `import` something that is from a package not listed as a dependency.

The fix is to determine if adding the dependency is appropriate, add it if it is, or find an alternative solution if it is not appropriate.

But I'm not sure that is the cause. Might also be an issue in PhantomJS. Anyway, `npm test`.

**Comment by stefanpenner** [comment]
woop

**Comment by thejameskyle** [comment]
I'm having trouble nailing this down, I'm pretty certain it's an issue with phantom.

**Comment by stefanpenner** [comment]
rebase is also needed

**Comment by thejameskyle** [comment]
Rebased, I'll take another look at why this is erroring in phantom tonight.

**Comment by rwjblue** [comment]
@thejameskyle - Looks like this needs another rebase.

**Comment by thejameskyle** [comment]
How would you guys feel about a Babel plugin that would transform `Array.prototype.slice` to loops like seen in here?

**Comment by rwjblue** [comment]
@thejameskyle - Sounds nice to me, but I think there are a few places where we stash `var aSlice = Array.prototype.slice; aSlice.apply(this, arguments);` also, so it would have to handle that scenario also...

**Comment by thejameskyle** [comment]
Why bother stashing it if it will get transformed?

**Comment by rwjblue** [comment]
@thejameskyle - I was saying we have scenarios where we do this, not that it was good :stuck_out_tongue_closed_eyes:

**Pull request closed without merging**
