### PR TITLE
Start breaking up Ember.View code into mixins based on purpose

### PR DESCRIPTION
**Pull request by ebryn**
@mmun @krisselden

### CODE REVIEW

**Comment by drogus** [comment]
I'm curious, what's the purpose of this refactoring? Do you think these could be used outside of View or is it more for separation of concerns?

**Comment by ebryn** [comment]
@drogus I'm working on "metal views", the view layer performance improvements. Generally, I think it's useful to break apart massive classes such as Ember.View into their logical pieces so you can easily see how things fit together.

**Comment by rwjblue** [comment]
I'd like to see these mixins in separate files instead of all in the same place, but clearly that can be a later refactoring.

**Comment by drogus** [comment]
> I'm working on "metal views", the view layer performance improvements

Sounds great!

**Pull request merged**
