### PR TITLE
check circular imports

### PR DESCRIPTION
**Pull request by patricklx**
to fix issues like #20709

### CODE REVIEW

**Comment by boris-petrov** [comment]
My personal experience with `npx cycle-import-check` is that it also gives a warning for cycles in `type` imports (which I don't believe is a problem). The `eslint-plugin-import` that I mentioned in Discord works correctly in that case.

**Comment by patricklx** [comment]
well, this isnt't working correctly anyway because it only considers relative imports. But we have a lot of import like `@ember/object`.
i didnt get eslint-plugin-import to work, always gets stack out of memory.
and not sure if it will have the same issue with those imports

**Comment by boris-petrov** [comment]
I also have the following settings for the ESLint plugin in `.eslintrc.js` (v8):

```js
  settings: {
    'import/core-modules': ['moment'],
    'import/parsers': {
      '@typescript-eslint/parser': ['.ts'],
    },
    'import/resolver': {
      typescript: {
        alwaysTryTypes: true,
      },
    },
  }
```

Not sure if that helps in any way.

**Comment by patricklx** [comment]
ok, i think i now found the correct setup

**Review by anandfresh — APPROVED** [review]

**Comment by ef4** [comment]
These ideas got incorporated into #20734

**Comment by patricklx** [comment]
> These ideas got incorporated into #20734

okay, but this could have the advantage that it shows the import cycles during linting and in the github action flow

**Pull request closed without merging**
