### PR TITLE
[CLEANUP beta] Remove Ember.Component.reopen

### PR DESCRIPTION
**Pull request by SergeAstapov**
Part of #19617

### CODE REVIEW

**Comment by SergeAstapov** [comment]
There is related #19664 for the same removal but in built-in components

**Comment by SergeAstapov** [comment]
@mixonic looks like it's done as part of #19806 - would you like to have a small targeted PR or it does not make sense?

**Comment by mixonic** [comment]
@SergeAstapov we would like it to be one big PR, I think. This is because the removed components and much of their capability (like `reopen`) should all be contained within https://github.com/emberjs/ember-legacy-built-in-components/pull/1. `Component.reopen` itself should be removed and I think will *not* be in https://github.com/emberjs/ember-legacy-built-in-components/pull/1, but regardless I think the codepaths are likely tangled enough we should do it in a single go.

I'll review this PR to make sure I'm pulling these same things out in https://github.com/emberjs/ember.js/pull/19806. 

Thank you for this work though, it will be a helpful reference and good gut check.

**Comment by SergeAstapov** [comment]
@mixonic thank you for explanation! Feel free to close this PR once it's not needed (I wasn't sure was doing all things right way anyways, at least CI was happy)

**Pull request closed without merging**
