### PR TITLE
[BUGFIX beta] Avoid reading from `this` in constructor.

### PR DESCRIPTION
**Pull request by rwjblue**

### CODE REVIEW

**Review by chancancode — APPROVED** [review]

**Comment by GavinJoyce** [comment]
TIL, thanks

**Comment by topaxi** [comment]
Curious, why? I want to TIL too :D

**Comment by GavinJoyce** [comment]
@topaxi I believe by accessing `this.defRef` mid constructor, the runtime is forced to create two different shapes for this object. If we don't read from `this`, it only creates one

**Comment by topaxi** [comment]
Oh, thanks! I always assumed this only happens when setting properties 😄

**Pull request merged**
