### PR TITLE
[BUGFIX beta] Mention "computed properties" in the assertion message

### PR DESCRIPTION
**Pull request by chancancode**
cc @krisselden

### CODE REVIEW

**Comment by rwjblue** [comment]
Has a failing test (that is checking the assertion message)...

**Comment by rwjblue** [comment]
ping @chancancode

**Comment by chancancode** [comment]
Fixed it!

**Comment by rwjblue** [comment]
@chancancode - Nope, apparently didn't work:
```
Test failed: computed: accessing computed property descriptor through the object triggers an assertion
    Failed assertion: Expected failing Ember.assert: '/You attempted to access `foo\.isDescriptor` \(on `obj`\)\./', but got 'You attempted to access `foo.isDescriptor` (of `obj`), but `foo` is a computed property.
```

**Comment by chancancode** [comment]
🤞

**Comment by rwjblue** [comment]
:clap:

**Pull request merged**
