### PR TITLE
[CLEANUP beta] Remove keys.js

### PR DESCRIPTION
**Pull request by alexspeller**
Remove file that shouldn't be there any more at @rwjblue's request

### CODE REVIEW

**Comment by rwjblue** [comment]
I think you will also need to remove https://github.com/emberjs/ember.js/blob/master/packages/ember-metal/tests/keys_test.js

**Comment by stefanpenner** [comment]
woah, totally thought this was gone...

r+

**Comment by alexspeller** [comment]
> I think you will also need to remove https://github.com/emberjs/ember.js/blob/master/packages/ember-metal/tests/keys_test.js

That's only testing Object.keys - is it not testing that adding and removing observers behaves correctly?

**Comment by stefanpenner** [comment]
I suspect that test is pointless, browsers already test this themselves :P

**Comment by rwjblue** [comment]
https://github.com/emberjs/ember.js/blob/master/packages/ember-metal/tests/keys_test.js#L83-L119 is basically confirming that `addObserver` / `removeObserver` does not add new properties to the object.

**Comment by alexspeller** [comment]
That's what I thought, so that means the test is still good right (although maybe better suited to be in a different file)?

**Comment by rwjblue** [comment]
Yeah, that section at the bottom can stay but all the other tests are ensuring that `Object.keys` works which seems *very* weird for us to test.

**Comment by alexspeller** [comment]
OK, would it make sense to move those to https://github.com/emberjs/ember.js/blob/master/packages/ember-metal/tests/observer_test.js ?

**Comment by rwjblue** [comment]
Yeah, that sounds good if you don't mind.

**Comment by alexspeller** [comment]
OK here we go, turns out it was still being used in a couple of places - hopefully this is all resolved now

**Comment by rwjblue** [comment]
Looks good to me.  Restarted sauce labs tests.

**Comment by rwjblue** [comment]
Thank you!

**Comment by alexspeller** [comment]
:)

**Pull request merged**
