### PR TITLE
Backport/bugfix query params helpers  pr #18458  issue #18076

### PR DESCRIPTION
**Pull request by NullVoxPopuli**
thanks @Alonski !

### CODE REVIEW

**Comment by Alonski** [comment]
Welcome @NullVoxPopuli ;)

**Review by rwjblue — APPROVED** [review]

**Comment by rwjblue** [comment]
Looks like we have one test failure:

> Test failed: {{link-to}} component with query-params (rendering): `(query-params)` must be used in conjunction with `{{link-to}}", source:  (49)

**Comment by NullVoxPopuli** [comment]
yeah, the bug isn't actually fixed yet, somehow :(

**Comment by rwjblue** [comment]
@NullVoxPopuli - Hmm, maybe I'm miss reading that message but it seems that the test is **specifically** stating that `(query-params` can't be used outside of a `link-to` (whcih is the thing we fixed!). My suggestion: find the test, confirm its testing the bad behavior, delete the test.

**Comment by NullVoxPopuli** [comment]
it's this test: https://github.com/emberjs/ember.js/pull/18546/files#diff-a912b76af52c89d34aee6b496aa64b4dR70 the assertion is being raised incorrectly

**Comment by Alonski** [comment]
@NullVoxPopuli I just opened #18555
This can be closed?

**Pull request closed without merging**
