### PR TITLE
[BUGFIX release] view keyword should not chain directly off parent's view keyword

### PR DESCRIPTION
**Pull request by fivetanley**
Opening this although @mmun wrote the final fix. I built this and verified it fixed the memory leaks in #10270.

### CODE REVIEW

**Comment by mmun** [comment]
:+1: I think this needs to go into release.

**Comment by stefanpenner** [comment]
@mmun bugfix release? (i think so aswell.

**Comment by rwjblue** [comment]
@fivetanley - Can you prefix the commit with `[BUGFIX release]`?

**Comment by fivetanley** [comment]
@rwjblue done. This will go out in the 1.10 release, or are y'all saying we should also do a 1.9.2 release?

**Comment by rwjblue** [comment]
@fivetanley - I'm not sure yet, but it will make it into the release branch (where folks can grab a build from S3 or bower at least).

**Comment by fivetanley** [comment]
Do I need to manually merge into release or does travis also do that?

**Comment by mixonic** [comment]
Great catch @fivetanley!

**Comment by rwjblue** [comment]
@fivetanley - I do it manually once merged.

**Comment by fivetanley** [comment]
Awesome, thanks!

**Comment by fivetanley** [comment]
Interesting, I didn't know you could delete branches on my fork. :P

**Comment by rwjblue** [comment]
@fivetanley - You must have given me commit on your branch. I am trained to essentially mash that delete branch button if I ever see it. Sorry :)

**Comment by fivetanley** [comment]
Haha, I did give you access. No worries, I don't need to keep it around. :)

**Comment by rwjblue** [comment]
cherry-picked into beta and release branches

**Pull request merged**
