### PR TITLE
[DOC release] notes Ember.computed.oneWay doesn't work for objects

### PR DESCRIPTION
**Pull request by KTKate**
Much confusion, discussion and twiddling could be avoided by making it clear that `Ember.computed.oneWay` only works for properties, not objects.

### CODE REVIEW

**Comment by rwjblue** [comment]
I don't understand what you mean. What if the property was an object? Can you give me an example of what does and does not work?

**Comment by JKGisMe** [comment]
Here is an example of both: http://ember-twiddle.com/0d54cd82f8619ccf0f0b

`modelCopy: Ember.computed.oneWay('model')` 
- Doesn't act as 'one way'.
- If `modelCopy.name` is altered then `model.name` will change as well.

`modelNameCopy: Ember.computed.oneWay('model.name')`
- Acts as one-directional & changes to the oneWay copy won't affect the original.
- Here, `modelNameCopy` can be altered without affecting the original

**Comment by mmun** [comment]
Your addition does not make sense -- `model` is also a "property".

> If `modelCopy.name` is altered then `model.name` will change as well.

This has nothing to do with the binding though. The binding code is not executed when `modelCopy.name` is altered. It's for the same reason that `Object.freeze(object)` does not deeply freeze the object.

You could phrase it as "Ember.computed.oneWay can not guarantee that any properties on the bound object are also treated as one-way"

**Comment by JKGisMe** [comment]
The problem with that phrasing is that if I hadnt already struggled through this with some people on slack,  I would have no idea what that meant. 

Are there any objects for which Ember.computed.oneWay stops changes from reaching the original? Could it just be as simple as 'acts as Ember.computed.alias when used on an object'? My understanding is only works on properties which are leaves, not properties which are nodes if you understand what I mean.

**Comment by rwjblue** [comment]
Thank you for taking the time to submit this. I agree that this is somewhat more complicated than it should be in JS-land generally, but I don't think this is the direction we want to go here so I'm closing this PR for now.  

Thank you for pitching in and helping out!

**Comment by JKGisMe** [comment]
¯\\\_(ツ)_/¯ Still think it's misleading. Implies there is only 1 directional flow... not a Ember version of freeze. Lots of new ember people are also new JS people. If they can't google something like "How does Object.oneWay work in JS" and Ember doesn't tell them when the docs say `will not mutate the upstream property` it really means `in some situations` there's no way for anyone to find out other than through silent fails.

**Pull request closed without merging**
