### PR TITLE
[BUGFIX beta] Fix issues with SSR rehydration of <title>.

### PR DESCRIPTION
**Pull request by rwjblue**

### CODE REVIEW

**Comment by rwjblue** [comment]
CI failure seems very unrelated 🤔

```
not ok 14 Edge 18.18362 - [3 ms] - Engine initializers:  initializers require proper 'name' and 'initialize' properties
    ---
        actual: >
            null
        stack: >
               at Anonymous function (http://127.0.0.1:7774/217628314952/dist/tests/qunit/qunit.js:3257:7)
               at processTaskQueue (http://127.0.0.1:7774/217628314952/dist/tests/qunit/qunit.js:2623:6)
               at Anonymous function (http://127.0.0.1:7774/217628314952/dist/tests/qunit/qunit.js:2627:8)
               at run (http://127.0.0.1:7774/217628314952/dist/tests/polyfill.js:674:14)
               at Anonymous function (http://127.0.0.1:7774/217628314952/dist/tests/polyfill.js:691:31)
               at flush (http://127.0.0.1:7774/217628314952/dist/tests/polyfill.js:471:10)
        message: >
            Died on test #1    at generateTest (http://127.0.0.1:7774/217628314952/dist/tests/ember-tests.js:107409:9)
               at Set.prototype.forEach (native code)
               at setupTestClass (http://127.0.0.1:7774/217628314952/dist/tests/ember-tests.js:107393:5)
               at Anonymous function (http://127.0.0.1:7774/217628314952/dist/tests/ember-tests.js:107340:7)
               at Anonymous function (http://127.0.0.1:7774/217628314952/dist/tests/ember-tests.js:106732:9)
               at processModule (http://127.0.0.1:7774/217628314952/dist/tests/qunit/qunit.js:1191:5)
               at module$1 (http://127.0.0.1:7774/217628314952/dist/tests/qunit/qunit.js:1216:4): [object Object]
        negative: >
            false
        browser log: |

```

**Comment by pzuraq** [comment]
FWIW this is the same test that was causing the `assert` issue we saw on the tracked props PR. For some reason, when running all of the tests, by the end of this test `Ember.assert` would be stubbed and wouldn't go back to normal. This was _only_ if you ran all of the tests.

**Review by locks — APPROVED** [review]

**Comment by rwjblue** [comment]
Rebased, hopefully I had just not included that Edge `Ember.assert` reset fix you did. 🤞

**Comment by rwjblue** [comment]
Eeck. I completely forgot about this 😩. Rebased and updated to `BUGFIX release`.

**Pull request merged**
