### PR TITLE
spring cleaning

### PR DESCRIPTION
**Pull request by stefanpenner**
I can gladly split this up by file, or by module or by folder or leave it as is. Open to recommendations.
- use let/const when appropriate (and according to style guide) no more var
- concise functions when appropriate
- use `=>` were appropriate

### CODE REVIEW

**Comment by Turbo87** [comment]
I see a lot of conflicts with #13549 ahead of me... 😄

**Comment by stefanpenner** [comment]
> I see a lot of conflicts with #13549 ahead of me... 😄

I can rebase that for you once this lands

**Comment by Turbo87** [comment]
don't worry, I can take it :wink:

**Comment by Turbo87** [comment]
I'd appreciate an r+ on https://github.com/emberjs/emberjs-build/pull/163 though

**Pull request merged**
