### PR TITLE
[BUGFIX #17529] Refactor get to return object or path

### PR DESCRIPTION
**Pull request by eplata31**
I tracked issue [#17529](https://github.com/emberjs/ember.js/issues/17529) and as suggested on the thread, it worked on the get property.
I wrote a new test based on the one from jasonmit and got it to pass, also all other test passed
Screenshot from 2019-04-25 11-44-41

Hope this will help, but any comment, suggestion or advice is welcome with open arms.
I am kind of new in the open source world so I hope I follow all of your contributing guides well but if I didn't it will be awesome if you could point out what I missed. Thanks :D

### CODE REVIEW

**Comment by pzuraq** [comment]
I'm not sure we should incur extra overhead for this, I think supporting periods in keynames was actually a bug and wasn't really intended behavior.

**Comment by jasonmit** [comment]
> I'm not sure we should incur extra overhead for this, I think supporting periods in keynames was actually a bug and wasn't really intended behavior.

In dev mode, might be useful then to throw with a helpful error.  People are running into this while upgrading and it's not immediately clear what broke outside of nothing rendering.

**Comment by eplata31** [comment]
I agree with @jasonmit and also it will be good to close the related issues to avoid confusion and extra work.

**Comment by devop911** [comment]
@pzuraq dot notation objects are fairly Common and i dont see a reason to let ember Break on a valid JSON

**Comment by locks** [comment]
Sorry for the long turnaround! I think the ship has sailed on this 😅 We are trying to move off of EmberObject overall, too.

**Pull request closed without merging**
