### PR TITLE
Add missing versions to changelog (1.13.13, .12, .10 and .9)

### LINKED ISSUE #12869: Some 1.13.x versions missing from changelog
Please include a changelog entry for each tiny version release. Can't tell what's changing.

### PR DESCRIPTION
**Pull request by johnnyshields**
Fixes #12869

### CODE REVIEW

**Comment by stefanpenner** [comment]
I don't know if this is accurate, as after the branch point the changelogs are no longer linear, and have diverged.

**Comment by johnnyshields** [comment]
The master changelog should contain all versions released on NPM/Github, regardless of whether or not the specific release commits are in the direct ancestry of the master branch itself.

**Comment by stefanpenner** [comment]
@johnnyshields I'm not sure that's true. I could concede that at divergent points we link to the appropriate change log or present divergent entries clear as such. But faking a linear change log seems like a hazard

**Comment by johnnyshields** [comment]
* If a user wants to get quick information about all versions, they should be able to look at the master change log.
* If a user wants to do an archaeological dig on the exact history of master branch, they can use the plethora of git history viewing tools that are available.
* It should be safe to assume that any legacy patched versions would have the same change applied to master (OR the change is not relevant to master.) In other words, 1.13.13 should not have a new feature that is not present on the latest 2.x version

**Comment by Turbo87** [comment]
I tend to agree with @johnnyshields. Having releases missing from the changelog is much more confusing than having entries in there that might not be directly related to the master branch. this is particularly true for the missing releases below the included `1.13.11` release.

**Pull request merged**
