### PR TITLE
[BUGFIX lts] Ensures chain tags do not call unknownProperty unless necessary

### LINKED ISSUE #1146: Nightly Run Failure: 960921280
Nightly run failed on: 22 Jun 2021
https://github.com/hjdivad/ember-m3/actions/runs/960921280

### PR DESCRIPTION
**Pull request by pzuraq**
Fixes https://github.com/hjdivad/ember-m3/issues/1146

### CODE REVIEW

**Comment by runspired** [comment]
I'm investigating if this also fixes the beta/canary failures in ember-data

**Comment by runspired** [comment]
Applied this change locally and unfortunately it does not fix the test failures in ember-data. I'm not convinced we have the same root-cause as ember-m3 vs just a similar cause, though I could believe it because the test failures are very similarly around over-notification.

In our case we have an observer (not array observer) watching either `prop.@each` or `prop.[]` where prop is an async hasMany relationship. In one of the tests it is easy to covert the relationship to sync and so I was able to observe a failure still occurring with just the MutableArray implementation involved. It is worth noting that ember-data's tests *have not* defaulted observers to async and also *have not* manually passed options to these observers to set them as async/sync, which should mean that they are running in sync mode.

I'll happily set aside time to debug a root cause with you,

**Comment by pzuraq** [comment]
This fix ended up not being the path we want to go down, we're going to do a different fix instead.

**Comment by rwjblue** [comment]
@pzuraq What is the alternate path? As far as I can tell, both ember-data and ember-m3 are still borked ATM...

**Comment by pzuraq** [comment]
@rwjblue the full fix landed in Glimmer VM and needs to be updated in Ember still: https://github.com/glimmerjs/glimmer-vm/pull/1323

The short term solution was to revert all of the lazy hash changes in general, since they were broken, and then update to the latest version of Glimmer VM. I thought we had reverted these on canary and beta, did that not happen?

**Pull request closed without merging**
