### PR TITLE
[BUGFIX release] adjust assertion to allow for either undefined or null

### PR DESCRIPTION
**Pull request by Dhaulagiri**
https://github.com/emberjs/ember.js/pull/16485, but targeted against master

### CODE REVIEW

**Comment by rwjblue** [comment]
Thank you!

**Comment by rwjblue** [comment]
I've pulled these changes into the beta and release branches, you should be able to use the latest release / beta builds once CI is completed and the changes should be included in the next release of each branch...

**Comment by Dhaulagiri** [comment]
> you should be able to use the latest release / beta builds

@rwjblue is there a good place to find these or can we point package.json at `'ember/ember.js#release'`?

**Comment by rwjblue** [comment]
Turns out that I didn't have a good way to explain this, so I just made it simpler (in https://github.com/ember-cli/ember-source-channel-url/pull/2).

This should be all you need to do to get the URL to put in your package.json:

```
npm install -g ember-source-channel-url
ember-source-channel-url release
```

That will print out the current URL for that channel, and you can put that directly in your `package.json` like:

```js
//...snip...
"ember-source": "<URL GOES HERE>",
//...snip...
```

**Comment by Dhaulagiri** [comment]
Nice! I’ll try to see if there is a way to better document this in the ember repo.

**Pull request merged**
