### PR TITLE
Require space after opening object curly brace and before closing.

### PR DESCRIPTION
**Pull request by jbrown**
Related to #9849, #10072

Do you want all or nested mode?

Valid for mode "all"
`var x = {a: {b: 1}};`

Valid for mode "nested"
`var x = { a: {b: 1} };`

Invalid
`var x = { a: { b: 1 } };`

### CODE REVIEW

**Comment by twokul** [comment]
I can't look it up right now, could you post code examples so everyone can see?

**Comment by jbrown** [comment]
It seems that spaces inside object brackets is currently the more common pattern in Ember.

`disallowSpacesInsideObjectBrackets ` - 2087 code style errors found.
`requireSpacesInsideObjectBrackets ` - 672 code style errors found.

**Comment by twokul** [comment]
@jbrown nested looks more appealing to me but I would prefer curly braces to be on new lines. @rwjblue thoughts?

**Comment by jbrown** [comment]
@twokul Personally, I find it awkward to have spaces only some of the time.

I like the invalid which is equivalent to `"requireSpacesInsideObjectBrackets": "all"`

**Comment by rwjblue** [comment]
Let's require spaces inside object brackets always. Much easier to remember than if nested is a different way. 

Also, it is closer to what we already are doing (I'm not looking to dramatically change our style, just make it obvious and enforceable).

**Comment by jbrown** [comment]
@rwjblue Just to confirm...

`var x = { a: { b: 1 } };`

**Comment by twokul** [comment]
I'm all for consistency

**Comment by rwjblue** [comment]
@jbrown: confirm

**Pull request merged**
