### PR TITLE
Fix Rubygems publishing script

### PR DESCRIPTION
**Pull request by locks**
cc @rwjblue

### CODE REVIEW

**Comment by rwjblue** [comment]
Will test locally, but seems good to me.

**Comment by chancancode** [comment]
:+1:

**Comment by chancancode** [comment]
Does it need to trim the trailing newline?

**Comment by locks** [comment]
@chancancode seems fine here. I think `cat` reads the trailing newline as the file terminator or somesuch?

```bash
bash-3.2$ echo ember-source-`cat VERSION`.gem
ember-source-2.12.0.alpha.1.gem
```

**Pull request merged**
