### PR TITLE
[BUGFIX beta] Adding tests for #18732

### PR DESCRIPTION
**Pull request by GCheung55**
[BUGFIX beta] Adding tests for #18732

### CODE REVIEW

**Comment by chancancode** [comment]
Changing the base branch to master temporarily to confirm the tests do fail

**Comment by chancancode** [comment]
Hm. I guess that doesn't work

**Comment by chancancode** [comment]
Ok I think I did it (sorry, had to force push to your branch). If it fails correctly, I _think_ we can just change the base branch back to @pzuraq's branch.

**Comment by GCheung55** [comment]
@chancancode It failed, however, I'm unsure whether it failed expectedly.

**Comment by rwjblue** [comment]
Failure looks like I’d expect, updating target branch back.

**Pull request merged**
