### PR TITLE
[FEATURE ember-router-willtransition]

### PR DESCRIPTION
**Pull request by asakusuma**
Invoke willTransition function and event on Router, just like Route.

Addresses https://github.com/emberjs/ember.js/issues/10235

### CODE REVIEW

**Comment by chadhietala** [comment]
:+1: Not sure if this should be feature flagged or not.  Seems good as is.

**Comment by rwjblue** [comment]
This adds new API so it will need a feature flag.

**Comment by asakusuma** [comment]
I'll add a feature flag.

@rwjblue while I'm at it, can I address this issue: https://github.com/emberjs/ember.js/issues/10180

I would just need to pass in the handlers that the underlying tildeio/router hook already passes in. Or should I put that in a separate PR?

**Comment by asakusuma** [comment]
@wagenet why was the "Needs Submitter Response" tag added here? Is there something else I need to provide?

**Comment by rwjblue** [comment]
He likely didn't see that you updated the PR as requested.

**Comment by asakusuma** [comment]
Can anyone shed light on why it's failing now? Was passing before I merged bower.json.

Here is the job that is failing: https://travis-ci.org/emberjs/ember.js/jobs/48380622
Here is the same job passing in master: https://travis-ci.org/emberjs/ember.js/jobs/48389900

I don't see any errors besides the `Error: Element .does-not-exist not found.`, which is also present in the passing build.

**Comment by asakusuma** [comment]
@machty mind taking a look?

**Comment by machty** [comment]
@asakusuma regardless of these issues you'll need to rebase your changes on top of master and squash your (presently) 3 commits into one; once you do that, you might find that the issues you're running into magically disappear, so give that a shot first.

**Pull request closed without merging**
