### PR TITLE
[BUGFIX beta] bump route-recognizer to v0.3.3

### PR DESCRIPTION
**Pull request by stefanpenner**
TL;DR this reduces the number of arrays route-recognizer allocates dramatically, but should not include any observable feature changes.

### CODE REVIEW

**Review by rwjblue — APPROVED** [review]

**Comment by rwjblue** [comment]
Looks like some possibly related failures:

```
Test failed: Query Params - main:  Defaulting to params hash as the model should not result in that params object being watched
    Failed assertion: Promise rejected during  Defaulting to params hash as the model should not result in that params object being watched: Attempting to define property on object that is not extensible.
	at defineProperty ([native code])
	at Fallback_setMeta (http://localhost:13141/ember.debug.js:24553:32)
	at meta (http://localhost:13141/ember.debug.js:24611:12)
	at model (http://localhost:13141/ember-tests.js:74091:40)
	at deserialize (http://localhost:13141/ember.debug.js:32033:24)
	at applyHook (http://localhost:13141/ember.debug.js:50083:34)
	at runSharedModelHook (http://localhost:13141/ember.debug.js:50668:29)
	at getModel (http://localhost:13141/ember.debug.js:50866:37)

```

**Comment by stefanpenner** [comment]
> Looks like some possibly related failures:

Ya that one kinda makes sense, we should likely improve are ability to work with frozen objects and stuff. Taking a look now.

**Comment by stefanpenner** [comment]
@rwjblue I believe the non-weakmap path for setting meta is not aware of frozen objects. I think that is a bug, so I'll go and explore fixing that now.

**Comment by stefanpenner** [comment]
@rwjblue I have updated the test to pass, and as a bonus, it now tests what its assertion message claims directly.

**Review by rwjblue — APPROVED** [review]

**Comment by stefanpenner** [comment]
for anyone interested the test was introduced: https://github.com/emberjs/ember.js/commit/6a7b7cd4d8bb103a332f2ff51678f3fef933e014

**Pull request merged**
