### PR TITLE
[DOC release] - Mark Enumerable.isAny as `public`

### PR DESCRIPTION
**Pull request by duggiefresh**
[ci skip]

### CODE REVIEW

**Comment by stefanpenner** [comment]
this also appears to remove a function, is that intended?

**Comment by duggiefresh** [comment]
@stefanpenner Uh oh! I believe master's git history has been overwritten. My previous accepted PR was merged into the `emberjs/ember.js` master branch, hence why it's showing up as a commit now.

[Please see my forked `ember.js` repo](https://github.com/duggiefresh/ember.js/commits/master).

**Comment by stefanpenner** [comment]
@duggiefresh you need to rebase origin/mater

**Comment by duggiefresh** [comment]
@stefanpenner Okee doke. :) I totally get that my PR should consist of only one commit, the one regarding the doc change.

However, I still cannot find previously merged PR's in `origin/master`. For example, I could not find these recently merged PRs within the `master`, `stable`, or `beta` branches.

PRs in question: https://github.com/emberjs/ember.js/pull/11676 and https://github.com/emberjs/ember.js/pull/11677

Thanks in advance!

**Comment by stefanpenner** [comment]
you are correct, what the heck.

**Comment by stefanpenner** [comment]
@cibernox something went funky (maybe i did something by accident today, although that seems pretty unlikely)

Do you have  local Ref of that PR handy?

**Comment by duggiefresh** [comment]
Thanks for your patience, Stefan! I thought I was going crazy last night.

**Comment by cibernox** [comment]
I don't have any trace of that PR in my local repo. Cherry pick the commits can be an option?

**Comment by stefanpenner** [comment]
restoring it all manually or via CP if possible now.

**Comment by duggiefresh** [comment]
@stefanpenner Thanks for tracking this down. I updated this PR to reflect what's currently on `master`.

**Comment by btecu** [comment]
This looks good. `isEvery` is already public so having `isAny` public makes sense.

**Pull request merged**
