### PR TITLE
[Project Svelte] Add deprecation flags

### PR DESCRIPTION
**Pull request by chadhietala**
Currently this is a WIP based on #15062. Need a Confirm/Deny on a couple versions and then we can start marking code paths that can be safely stripped.

### CODE REVIEW

**Comment by jonnii** [comment]
@chadhietala there has never been an expectation for svelte builds, is the goal to produce svelte builds for pre-2.12/13 versions? If not would it be ok to have the deprecations only stripped from 2.13 onwards?

**Comment by rwjblue** [comment]
@jonnii - I agree that it seems pretty unlikely that we would support consuming anything older than ember-source@2.14 and getting to "svelte out" deprecated features, but either way we have to instrument the code (for both new and old deprecations) and it seems better to put the "real" version numbers in there "since we are in there"...

**Comment by jonnii** [comment]
@rwjblue makes sense, i suppose it's good to know when a deprecation went into affect outside of the svelte builds. that information could be used in the docs and in places like ember-try. :+1:

**Review by locks — APPROVED** [review]

**Comment by rwjblue** [comment]
@chadhietala - This can land, right?

**Pull request merged**
