### PR TITLE
bump to latest qunit-phantomjs-runner

### PR DESCRIPTION
**Pull request by stefanpenner**
- 2.2.0 of the runner
- set timeout to 90s

### CODE REVIEW

**Comment by krisselden** [comment]
Still failed with 90s timeout: "The specified timeout of 90 seconds has expired. Aborting...
  bower_components/qunit-phantom-runner/runner.js:88"

**Comment by stefanpenner** [comment]
ya

**Comment by stefanpenner** [comment]
rebased, lets see...

**Comment by rwjblue** [comment]
I _think_ this was just addressed (reopen if I got it wrong...)

**Pull request closed without merging**
