### PR TITLE
[Bugfix beta] Fix route blueprint for --reset-namespace

### PR DESCRIPTION
**Pull request by thorsteinsson**
@courajs and I paired on this at the Ember conf contributor workshop.

Fixes https://github.com/ember-cli/ember-cli/issues/6026.

### CODE REVIEW

**Comment by courajs** [comment]
We should port this to ember-legacy-blueprints after merge

**Comment by mmun** [comment]
Looks great. Thanks for contributing to the workshop. Needs a more experienced set of 👀  before merging.

**Comment by courajs** [comment]
ping @rwjblue can we get a review?

**Review by Turbo87 — APPROVED** [review]
LGTM, thanks @thorsteinsson!

**Pull request merged**
