### PR TITLE
[BUGFIX beta] join runloop in `Helper#recompute`

### LINKED ISSUE #14774: Ember 2.10.0 helper recompute bug
Calling recompute on a helper does not recompute in 2.10.0

Twiddle: https://ember-twiddle.com/3afc1bda1c824f4ed141b666e5521320?openFiles=helpers.my-helper.js%2C

When you change the dependency to 2.9 this code works, for 2.10 it does not work. It might be related to Glimmer update?

### PR DESCRIPTION
**Pull request by buschtoens**
Fixes https://github.com/emberjs/ember.js/issues/14774.

### CODE REVIEW

**Review by rwjblue — COMMENTED** [review]
Looks great! Just wanted to confirm that this test failed prior to adding the `run.join`, right?

**Comment by buschtoens** [comment]
@rwjblue Correct, it did! ☺️

**Comment by rwjblue** [comment]
Thank you!

**Comment by Windvis** [comment]
According to the [LTS info page](https://emberjs.com/releases/lts) LTS releases receive bugfixes for 30 weeks. Doesn't that mean that this fix should have been backported to the 3.8 LTS since the PR was merged in june? 😄

**Comment by rwjblue** [comment]
Sure, if we had thought about it at the time, we definitely could have. At this point 3.8 is receiving security fixes only, so it will not get this fix.

**Pull request merged**
