### PR TITLE
[BUGFIX Release] Special case `{{#with}}` for `isTruthy`

### PR DESCRIPTION
**Pull request by chadhietala**
Should resepect `isTruthy` on objects.

### CODE REVIEW

**Comment by rwjblue** [comment]
The failed tests were fixed in https://github.com/tildeio/glimmer/pull/71, I merged and restarted the build.

**Comment by ilucin** [comment]
I've upgraded to 2.4.1 and noticed that this commit broke something in my use case. I'm not completely sure if I'm doing something wrong here (I'm relatively new to Ember), so just wanted to check out with you guys @chadhietala @rwjblue 

I'm doing this in my component:

`{{#with invoice.deal as |deal|}}
    {{partial 'path/to/partial'}}
{{/with}}
`

.. where invoice & deal are DS.Models and invoice belongsTo deal.

Now, because `get('invoice.deal.isTruthy') => true` (not sure why/where this property got set, I would guess it's because it is an async relation), `params[0]` of 'with' helper was transformed to `true`. 
Of course, my partial expects for `deal` in the scope to be DS.Model and everything breaks.

If I do `{{#with invoice.deal.content as |deal|}}` everything works - but I think this is not a right solution to the problem (we don't want to be aware in our templates if the relation is async or not).

Anyways, something is wrong somewhere but I don't have enough experience to assume where. What do you think?

**Comment by rwjblue** [comment]
Hmm, there was a subsequent PR that ensured the right value was used in the block param, that pull request should have been included in 2.4.0/2.4.1 (though it is possible that I missed it when preparing for the release).

Can you open a new issue with a JSBin and/or ember-twiddle.com demo? You can create an object with an isTruthy method returning true and show that the wrong value is used as the block param (instead of setting up the whole ember-data model scenario in the demo).

**Comment by ilucin** [comment]
@rwjblue Sure, no problem.

**Comment by jcbvm** [comment]
Same problem here, created a JSBin.
http://emberjs.jsbin.com/vetezutapa/2/edit?html,js,output

**Comment by rwjblue** [comment]
@jcbvm - Same answer :smiling_imp:

**Comment by jcbvm** [comment]
Oh lol

**Pull request merged**
