### PR TITLE
fix hanging tests caused by legacy rsvp code

### PR DESCRIPTION
**Pull request by patricklx**
this should be legacy code?

this causes tests to hang when a RSVP promise gets rejected. E.g visit helper route reject 
causes by https://github.com/qunitjs/qunit/issues/1705

fixes https://github.com/emberjs/ember-qunit/issues/476

### CODE REVIEW

**Comment by chriskrycho** [comment]
Thanks for this! @rwjblue can you take a gander, as the person with (I think) the most context here? Also, @patricklx if you update (via rebase or merge), the type checking issue should be resolved now.

**Comment by chriskrycho** [comment]
Now you have *actual* type and test failures. 😉

**Comment by locks** [comment]
I tried rebasing but I can't push to @patricklx's remote. Do you have some time @patricklx?

**Comment by patricklx** [comment]
Hi @locks , sure. I totally forgot about this. It looks like it's still not fixed on qunit side...
Since you already have the rebase i just give you access:)

**Review by NullVoxPopuli — APPROVED** [review]

**Review by wagenet — APPROVED** [review]
@NullVoxPopuli assures me this is fine. I'll throw him under the bus if there are issues 😉

**Comment by NullVoxPopuli** [comment]
I accept these conditions :P

**Pull request merged**
