### PR TITLE
Enable features green lighted at core team meeting on 2017-02-24.

### PR DESCRIPTION
**Pull request by rwjblue**

### CODE REVIEW

**Comment by rwjblue** [comment]
FYI -  @trentmwillis @bcardarella (as the feature authors)

**Comment by bcardarella** [comment]
nice :)

**Comment by trentmwillis** [comment]
I had forgot that I added this haha, glad to see it getting turned on!

**Comment by locks** [comment]
Can you both check if https://github.com/ember-learn/dashboard/blob/master/app/routes/application.js#L3 needs updating? Thanks!

**Pull request merged**
