### PR TITLE
Idea to support duplicates of primitives in {{each}}

### PR DESCRIPTION
**Pull request by raytiley**
Just a quick idea. I know this is really basic but it should work? CC/ @mmun

### CODE REVIEW

**Comment by mmun** [comment]
This strategy is OK for compatibility but it will make things like resorting a list become a full rerender.

**Comment by raytiley** [comment]
Yeah, but that's probably better then completely failing if there are duplicates.

**Comment by krisselden** [comment]
There is a better proposal to support this by allowing a keyed bin to be a list like collisions in a hashmap.

**Comment by krisselden** [comment]
@raytiley would you like to try that? Do you mind if I close this?

**Pull request closed without merging**
