### PR TITLE
[Glimmer 2] failing test for #14001

### PR DESCRIPTION
**Pull request by GavinJoyce**
Failing test for https://github.com/emberjs/ember.js/issues/14001

screen shot 2016-08-04 at 15 48 55

### CODE REVIEW

**Comment by rwjblue** [comment]
@GavinJoyce - I wonder if we can:

*  remove `value` from `attributeBinding` [here](https://github.com/emberjs/ember.js/blob/3d25f9805cf1eb37a3f5ae6e05e3e2646b4f6175/packages/ember-htmlbars/lib/components/text_area.js#L41)
* add a template for it ([in this folder](https://github.com/emberjs/ember.js/tree/3d25f9805cf1eb37a3f5ae6e05e3e2646b4f6175/packages/ember-glimmer/lib/templates)) that has a single `{{value}}` in it

**Comment by GavinJoyce** [comment]
trying...

**Comment by GavinJoyce** [comment]
@rwjblue spike here : https://github.com/emberjs/ember.js/compare/master...GavinJoyce:gj/spike-textarea-template

There are at least two failing tests:

screen shot 2016-08-04 at 16 09 40

**Comment by rwjblue** [comment]
Based on that failing test, I would say that [this method](https://github.com/emberjs/ember.js/blob/master/packages/ember-views/lib/mixins/text_support.js#L199) isn't firing when those events are triggered.

**Comment by GavinJoyce** [comment]
@rwjblue I've [pushed a "fix"](https://github.com/emberjs/ember.js/commit/0509c8903177ddfa25c0c8e0e61da171216c4089) for that failing test, the htmlbars one has three `childNodes` (two for wrapping the dynamic node I suspect) while the glimmer one has just one.

I'm not sure how this strategy would work with user input though, especially in htmlbars. I'd like to write some tests that actually send keys to the text area. Do you know of anything like this elsewhere in ember tests?

**Pull request merged**
