### PR TITLE
didRender can receive out-of-date attr value

### PR DESCRIPTION
**Pull request by ef4**
AFAIK it should be OK to change cause `attrs` to change during `didInitAttrs`, and this does indeed seem to correctly trigger a second render that outputs the updated value into the DOM. But the second `didRender` hook sees the out-of-date value.

Failing test included.

### CODE REVIEW

**Comment by ef4** [comment]
After discussing with @wycats, it sounds like this scenario should also be triggering the "modified twice in single render" warning. But it isn't.

**Comment by wycats** [comment]
@ef4 did you test it in an environment other than Ember Twiddle? I noticed that Ember Twiddle reports the "why aren't you running debug builds" warning, which seemed odd.

**Comment by rwjblue** [comment]
@wycats - https://github.com/ember-cli/ember-twiddle/pull/184 should fix that

**Comment by ef4** [comment]
@wycats yes, I tried it beyond Ember Twiddle. See the attached test.

**Comment by krisselden** [comment]
@ef4 this is more likely to do with `didInitAttrs` being in a constructor and doing stuff that relies on events to initialize things rather than explicit initialization. When `didInitAttrs` was moved into the constructor was to prevent event churn, now you are expecting it to cause invalidation.  I'm hoping hooks will be revisited when doing angle bracket components.

**Comment by rwjblue** [comment]
Hmm, I think this is actually resolved.  We might need to rebase this branch to see/confirm though...

**Comment by Serabe** [comment]
@ef4 can you rebase this, please? Thank you!

**Comment by ef4** [comment]
I took a look at rebasing this, but its testing semantics that don't even really exist anymore. Closing.

**Pull request closed without merging**
