### PR TITLE
[CLEANUP beta] Remove deprecated CP semantics

### PR DESCRIPTION
**Pull request by cibernox**
I can't tell how long I've been waiting for this moment.

### CODE REVIEW

**Comment by stefanpenner** [comment]
yay

**Comment by stefanpenner** [comment]
kicking sauce labbs

**Comment by cibernox** [comment]
As a side note, a backwards compatible change is that the setter function always receives the `oldValue` as 3rd argument. 
Formerly it used to check the arity of the setter function to invoke it with or without the 3rd argument. I cannot think on a single good reason to do that now.

**Comment by stefanpenner** [comment]
@krisselden / @mmun can you review? I flew a red-eye last night, my judgement is likely not the best right now :sleeping: :

**Comment by rwjblue** [comment]
Let's prefix with [CLEANUP beta] (seems better than nothing and will make changelog work easier).

**Pull request merged**
