### PR TITLE
allows enumerable to be sorted in descending order

### PR DESCRIPTION
**Pull request by kagemusha**
useful in multi-column scenario when some columns asc and some desc

### CODE REVIEW

**Comment by bradleypriest** [comment]
I think this is a dup of #4785, which sadly seems to have fallen to the wayside

**Comment by kagemusha** [comment]
i see. so anything that can be about this or just leave it?

**Comment by stefanpenner** [comment]
unsure if this is something that will be accepted or not, but either way there are JSC (formatting) related test failures that likely need to be looked into

**Comment by rwjblue** [comment]
Thank you very much for taking the time to submit the patch! I am going to close this PR though because I believe that we plan on deprecating Enumerable at some point in the relatively near future, and I'd prefer to avoid changing it a ton while its in this odd not deprecated but might be soon stage. 

For now, I'd suggest making an addon that provides this functionality for folks.

**Pull request closed without merging**
