### PR TITLE
[BUGFIX stable] Collection View with bound attributes throws an exception when content is changed

### PR DESCRIPTION
**Pull request by taras**
_ember

### CODE REVIEW

**Comment by stefanpenner** [comment]
i think this is related to: https://github.com/emberjs/ember.js/issues/10792

**Comment by mixonic** [comment]
I have a spike for this as well- getting the cleanup working is the non-trivial part.

**Comment by taras** [comment]
@mixonic what do you mean cleanup?

**Comment by mixonic** [comment]
wip is here: https://github.com/mixonic/ember.js/compare/master...class-name-bindings-3 esp the second commit.

**Comment by mixonic** [comment]
IE is pissed, but +1

**Comment by mixonic** [comment]
Would like to see it go into beta, and if it is happy there to maybe go out in a point release.

**Comment by taras** [comment]
@mixonic anyway to find out how to make IE less upset?

**Comment by mixonic** [comment]
@taras I'm not sure, the sauce setup is new. I suggest running the specs on a VM

**Comment by mixonic** [comment]
@mmun restarted the build, he is distrustful of the sauce overlords

**Comment by mmun** [comment]
It's looking better this time. /me crosses fingers.

**Comment by mmun** [comment]
IE10 and IE11 are not passing. I will try it out in a VM.

**Comment by taras** [comment]
@mmun thank you :)

**Comment by mmpestorich** [comment]
@taras Thanks for this. Fixes the issue I had in #10792.

**Comment by taras** [comment]
@mmun I was able to get the tests running in BrowserStack and I can reproduce the failures. I'll fix them now.

**Comment by taras** [comment]
@mixonic it seems that a checkbox test fails on IE10 & IE11, specifically

```
QUnit.test("checked property mirrors input value", function() {
  checkboxView = Checkbox.create({});
  run(function() { checkboxView.append(); });

  equal(get(checkboxView, 'checked'), false, "initially starts with a false value");
  equal(!!checkboxView.$().prop('checked'), false, "the initial checked property is false");

  set(checkboxView, 'checked', true);

  equal(checkboxView.$().prop('checked'), true, "changing the value property changes the DOM");

  run(function() { checkboxView.remove(); });
  // TEST FAIL HERE
  run(function() { checkboxView.append(); });

  equal(checkboxView.$().prop('checked'), true, "changing the value property changes the DOM");

  run(function() { checkboxView.remove(); });
  run(function() { set(checkboxView, 'checked', false); });
  run(function() { checkboxView.append(); });

  equal(checkboxView.$().prop('checked'), false, "changing the value property changes the DOM");
});
```

**Comment by taras** [comment]
@mixonic what is this test even testing? Any idea why this test keeps removing and reappending the view?

**Comment by krisselden** [comment]
`Renderer.prototype.remove` needs to use the hook for childViews and not reach directly to `_childViews`

**Comment by mixonic** [comment]
IE10 dislikes setting `null` to type.

**Comment by taras** [comment]
@mixonic yeah, I discovered this too. But the problem arose from the fact that we weren't tearing down attrNodes when removing views from DOM. This resulted in attrNodes with broken state. I add used the hook the childViews hook in the renderer to get attrNodes with childViews and now the tests should pass.

**Comment by mixonic** [comment]
@taras Please squash and prefix with `[BUGFIX stable]`. Thanks very much! :-D

**Comment by taras** [comment]
@mixonic done and reran the tests on IE10 & IE11 to make sure cause sause is failing.

**Pull request merged**
