### PR TITLE
[BUGFIX Release]fix mocha blueprint service test filename

### PR DESCRIPTION
**Pull request by sly7-7**
Maybe this pr is incomplete, or I could add test in someway (even if this looks to be tested here: https://github.com/emberjs/ember.js/blob/master/node-tests/blueprints/service-test.js#L180,

but when I'm doing 
`ember g service blah`, it gives the results
```
installing service
  create app/pods/blah/service.js
installing service-test
  create tests/unit/pods/blah/service-test-test.js
```

Maybe all the test's blueprints filename should be rename '__test__.js' ? In that case tell me, and I could complete this pr

### CODE REVIEW

**Comment by Turbo87** [comment]
@sly7-7 could you add a test similar to https://github.com/emberjs/ember.js/blob/master/node-tests/blueprints/service-test.js#L170-L184 to verify that everything works as planned?

**Comment by stefanpenner** [comment]
@sly7-7 can you address @Turbo87 feedback?

**Comment by sly7-7** [comment]
@stefanpenner @Turbo87 Will do that, sorry for the delay, I was on vacation.

**Comment by sly7-7** [comment]
@stefanpenner I'm having trouble launching those tests. They do not seem to be executed when running `ember test --server`

**Comment by sly7-7** [comment]
@stefanpenner @Turbo87 Should be good now. Out of curiosity, are those tests running on travis ?

**Comment by Turbo87** [comment]
> Out of curiosity, are those tests running on travis ?

yes, see https://github.com/emberjs/ember.js/blob/master/.travis.yml#L64

**Comment by rwjblue** [comment]
Thank you!

**Pull request merged**
