### PR TITLE
[WIP] Fix eslint issues

### PR DESCRIPTION
**Pull request by Exelord**
I turned on `no-unused-vars` flag and fixed project's issues.

### Remaining Issues: 614/856

### CODE REVIEW

**Comment by rwjblue** [comment]
Does `eslint --fix` take care of these?  It may be easier than doing them by hand...

**Comment by Exelord** [comment]
Unfortunately not :/ I have to do it by hand

**Comment by locks** [comment]
@Exelord heya :) What's the status on this effort?

**Comment by Exelord** [comment]
Hey @locks :) I'm still working on it on. I have some problems with tests using unscoped variables and this blocked me right now. I will look at it once again when I will back from holidays.

**Comment by mmun** [comment]
We now error on no-unused-vars (https://github.com/emberjs/ember.js/blob/67bf23f2b0a9ed42bd6ccfcdb82aa9e89798bb52/.eslintrc-browser.js#L42).

**Pull request closed without merging**
