### PR TITLE
Add d8-*.js to .npmignore.

### PR DESCRIPTION
**Pull request by rwjblue**

### CODE REVIEW

**Comment by Turbo87** [comment]
shouldn't you also remove those files so that the rule works properly?

**Comment by rwjblue** [comment]
I'm not sure I follow. .npmignore has nothing to do with files being present or not. Maybe you mistook this for the gitignore?

**Comment by Turbo87** [comment]
you're right... time for bed!

**Comment by rwjblue** [comment]
Hehe, fair enough ;P

**Pull request merged**
