### PR TITLE
[DOC release] ember-glimmer/component: Remove duplicate API docs

### PR DESCRIPTION
**Pull request by Turbo87**
/cc @locks @rwjblue

### CODE REVIEW

**Comment by rwjblue** [comment]
I don't understand. Where are they duplicated?

**Comment by Turbo87** [comment]
@rwjblue right in the same file. the same API doc comments exist twice.

**Comment by rwjblue** [comment]
Ahh, but if you look they are not actually the same 😉. One is describing the `@event` the other is describing the `@method`.  They are two different things...

**Comment by Turbo87** [comment]
see, I'm blind...

**Pull request closed without merging**
