### PR TITLE
updates QUnit symver in bower.json to match QUnit symver in package.json

### PR DESCRIPTION
**Pull request by AmazingJaze**
updates QUnit symver in bower.json to match QUnit symver in package.json

### CODE REVIEW

**Comment by AmazingJaze** [comment]
@rwjblue The reported test failure in [ember-htmlbars](https://saucelabs.com/jobs/04606d26a8fc4c08b23c708b18897dd8) seems unrelated to this change. 
Can someone rerun the [travis job](https://travis-ci.org/emberjs/ember.js/jobs/114487826)?

**Comment by rwjblue** [comment]
I have restarted it a few times, the failure is legit but it is due to MS_Edge adding the function name to [this function](https://github.com/emberjs/ember.js/blob/master/packages/ember-htmlbars/tests/helpers/view_test.js#L1334-L1345) so the error [added here](https://github.com/krisselden/morph-range/pull/6/files) now has the function name.  We need to make the assertion use a regexp to prevent a failure...

**Comment by rwjblue** [comment]
I submitted https://github.com/emberjs/ember.js/pull/13073 to fix the MS Edge failure.

**Comment by AmazingJaze** [comment]
W00t!

**Comment by jdalton** [comment]
@rwjblue
On a side note is there a reason for having qunit in bowser and as an npm dep?
Would just having it as an npm dev dep do?

**Comment by rwjblue** [comment]
Yep, would work fine, but would require some build tooling changes (the build currently expects to find the file in bower_components) for the browser land tests.

**Comment by jdalton** [comment]
@rwjblue Is this PR ready to merge? It would help us (Edge) get our automated testing back-to-runnable for your master branch.

**Comment by rwjblue** [comment]
Ya, I had kicked off the CI build to rerun, but forgot to check back in :cry: 

Thanks for the help, and patience here!

**Pull request merged**
