### PR TITLE
Deprecate Ember.Handlebars.SafeString in favor of Ember.String.htmlSafe

### PR DESCRIPTION
**Pull request by drewchandler**
Addresses #13191

### CODE REVIEW

**Comment by abepetrillo** [comment]
Hey there, I added documentation to the website, but the anchor is `#toc_use-ember-string-htmlsafe-over-ember-handlebars-safestring`

Not sure if you want to use that or your own. PR is here: https://github.com/emberjs/website/pull/2524

**Comment by rwjblue** [comment]
Sounds good, can you update that URL?

**Comment by drewchandler** [comment]
@rwjblue done!

**Comment by rwjblue** [comment]
Thank you!

**Comment by topaxi** [comment]
How will we be able to detect htmlSafe strings now?

If `Ember.Handlebars.SafeString` is gone, we won't be able to do `if (foo instanceof Ember.Handlebars.SafeString) { }`.

**Pull request merged**
