### PR TITLE
[WIP] [FEATURE ember-metal-es5-getters] Implement feature

### PR DESCRIPTION
**Pull request by chancancode**
Moved to #16025

### CODE REVIEW

**Comment by btecu** [comment]
`package-lock.json` should not be included.

**Comment by chancancode** [comment]
Seems like [this is a regression](https://github.com/emberjs/ember.js/files/1565411/results.pdf), I will investigate if the implementation can be improved.

**Comment by chancancode** [comment]
The "Slightly different approach" commit (I might have broken IE11, but ignore that for now) seem to close the gap better getters on/off, but master vs either is still a (small) regression. So (perhaps unsurprisingly) moving the descriptor to meta does seems to have a small cost. But given the benefits, it's probably still worth it?

I'll see if I can get some results from ember-observer as well.

**Comment by chancancode** [comment]
Since the alternative version was causing problems on IE 11, and it did not affect the feature-off case at all, I would like to leave that out for now and iterate on the feature-on performance separately (that is an important concern for enabling the feature, but not necessarily for merging the initial implementation).

**Review by rwjblue — APPROVED** [review]

**Pull request closed without merging**
