### PR TITLE
[BUGFIX release] Replace broken ".npmignore" file with "files" list

### LINKED ISSUE #14936: Does not properly generate `*-test` blueprints.
Repro (assuming ember-cli@2.11 or higher):

```
ember new foo
cd foo
ember g acceptance-test bar
```

No files are created.

---

Prior to ember-source@2.11.1 this works properly (which means that ember-cli-legacy-blueprints were working properly and ember-source is not).

### PR DESCRIPTION
**Pull request by Turbo87**
aka. #14910 part 2

Resolves #14936

/cc @rwjblue @locks

### CODE REVIEW

**Comment by rwjblue** [comment]
@Turbo87 - Can you `npm pack` before and after this change, and share the tarballs?

**Comment by rwjblue** [comment]
### Before

```
~/Downloads/before/package
├── CHANGELOG.md
├── LICENSE
├── README.md
├── blueprints
│   ├── -addon-import.js
│   ├── acceptance-test
│   │   └── index.js
│   ├── component
│   │   ├── files
│   │   │   └── __root__
│   │   │       ├── __path__
│   │   │       │   └── __name__.js
│   │   │       └── __templatepath__
│   │   │           └── __templatename__.hbs
│   │   └── index.js
│   ├── component-addon
│   │   ├── files
│   │   │   └── __root__
│   │   │       └── __path__
│   │   │           └── __name__.js
│   │   └── index.js
│   ├── component-test
│   │   └── index.js
│   ├── controller
│   │   ├── files
│   │   │   └── __root__
│   │   │       └── __path__
│   │   │           └── __name__.js
│   │   └── index.js
│   ├── controller-test
│   │   └── index.js
│   ├── helper
│   │   ├── files
│   │   │   └── __root__
│   │   │       └── helpers
│   │   │           └── __name__.js
│   │   └── index.js
│   ├── helper-addon
│   │   ├── files
│   │   │   └── __root__
│   │   │       └── __path__
│   │   │           └── __name__.js
│   │   └── index.js
│   ├── helper-test
│   │   └── index.js
│   ├── initializer
│   │   ├── files
│   │   │   └── __root__
│   │   │       └── initializers
│   │   │           └── __name__.js
│   │   └── index.js
│   ├── initializer-addon
│   │   ├── files
│   │   │   └── __root__
│   │   │       └── __path__
│   │   │           └── __name__.js
│   │   └── index.js
│   ├── initializer-test
│   │   └── index.js
│   ├── instance-initializer
│   │   ├── files
│   │   │   └── __root__
│   │   │       └── instance-initializers
│   │   │           └── __name__.js
│   │   └── index.js
│   ├── instance-initializer-addon
│   │   ├── files
│   │   │   └── __root__
│   │   │       └── __path__
│   │   │           └── __name__.js
│   │   └── index.js
│   ├── instance-initializer-test
│   │   └── index.js
│   ├── mixin
│   │   ├── files
│   │   │   └── __root__
│   │   │       └── mixins
│   │   │           └── __name__.js
│   │   └── index.js
│   ├── mixin-test
│   │   └── index.js
│   ├── route
│   │   ├── files
│   │   │   └── __root__
│   │   │       ├── __path__
│   │   │       │   └── __name__.js
│   │   │       └── __templatepath__
│   │   │           └── __templatename__.hbs
│   │   └── index.js
│   ├── route-addon
│   │   ├── files
│   │   │   └── __root__
│   │   │       ├── __path__
│   │   │       │   └── __name__.js
│   │   │       └── __templatepath__
│   │   │           └── __templatename__.js
│   │   └── index.js
│   ├── route-test
│   │   └── index.js
│   ├── service
│   │   ├── files
│   │   │   └── __root__
│   │   │       └── __path__
│   │   │           └── __name__.js
│   │   └── index.js
│   ├── service-test
│   │   └── index.js
│   ├── template
│   │   ├── files
│   │   │   └── __root__
│   │   │       └── __path__
│   │   │           └── __name__.hbs
│   │   └── index.js
│   ├── test-framework-detector.js
│   ├── test-helper
│   │   └── index.js
│   ├── util
│   │   ├── files
│   │   │   └── __root__
│   │   │       └── utils
│   │   │           └── __name__.js
│   │   └── index.js
│   └── util-test
│       └── index.js
├── dist
│   ├── component.json
│   ├── composer.json
│   ├── ember-runtime.js
│   ├── ember-runtime.map
│   ├── ember-template-compiler.js
│   ├── ember-template-compiler.map
│   ├── ember-testing.js
│   ├── ember-tests.js
│   ├── ember.debug.js
│   ├── ember.debug.map
│   ├── jquery
│   │   └── jquery.js
│   ├── package.json
│   └── qunit
│       ├── qunit.css
│       └── qunit.js
├── index.js
├── package.json
└── vendor
    └── ember
        └── shims.js

80 directories, 66 files
```

### After

```
~/Downloads/after/package
├── CHANGELOG.md
├── LICENSE
├── README.md
├── blueprints
│   ├── -addon-import.js
│   ├── acceptance-test
│   │   ├── index.js
│   │   ├── mocha-files
│   │   │   └── tests
│   │   │       └── acceptance
│   │   │           └── __name__-test.js
│   │   └── qunit-files
│   │       └── tests
│   │           └── acceptance
│   │               └── __name__-test.js
│   ├── component
│   │   ├── files
│   │   │   └── __root__
│   │   │       ├── __path__
│   │   │       │   └── __name__.js
│   │   │       └── __templatepath__
│   │   │           └── __templatename__.hbs
│   │   └── index.js
│   ├── component-addon
│   │   ├── files
│   │   │   └── __root__
│   │   │       └── __path__
│   │   │           └── __name__.js
│   │   └── index.js
│   ├── component-test
│   │   ├── index.js
│   │   ├── mocha-0.12-files
│   │   │   └── tests
│   │   │       └── __testType__
│   │   │           └── __path__
│   │   │               └── __test__.js
│   │   ├── mocha-files
│   │   │   └── tests
│   │   │       └── __testType__
│   │   │           └── __path__
│   │   │               └── __test__.js
│   │   └── qunit-files
│   │       └── tests
│   │           └── __testType__
│   │               └── __path__
│   │                   └── __test__.js
│   ├── controller
│   │   ├── files
│   │   │   └── __root__
│   │   │       └── __path__
│   │   │           └── __name__.js
│   │   └── index.js
│   ├── controller-test
│   │   ├── index.js
│   │   ├── mocha-0.12-files
│   │   │   └── tests
│   │   │       └── unit
│   │   │           └── __path__
│   │   │               └── __test__.js
│   │   ├── mocha-files
│   │   │   └── tests
│   │   │       └── unit
│   │   │           └── __path__
│   │   │               └── __test__.js
│   │   └── qunit-files
│   │       └── tests
│   │           └── unit
│   │               └── __path__
│   │                   └── __test__.js
│   ├── helper
│   │   ├── files
│   │   │   └── __root__
│   │   │       └── helpers
│   │   │           └── __name__.js
│   │   └── index.js
│   ├── helper-addon
│   │   ├── files
│   │   │   └── __root__
│   │   │       └── __path__
│   │   │           └── __name__.js
│   │   └── index.js
│   ├── helper-test
│   │   ├── index.js
│   │   ├── mocha-0.12-files
│   │   │   └── tests
│   │   │       └── __testType__
│   │   │           └── helpers
│   │   │               └── __name__-test.js
│   │   ├── mocha-files
│   │   │   └── tests
│   │   │       └── __testType__
│   │   │           └── helpers
│   │   │               └── __name__-test.js
│   │   └── qunit-files
│   │       └── tests
│   │           └── __testType__
│   │               └── helpers
│   │                   └── __name__-test.js
│   ├── initializer
│   │   ├── files
│   │   │   └── __root__
│   │   │       └── initializers
│   │   │           └── __name__.js
│   │   └── index.js
│   ├── initializer-addon
│   │   ├── files
│   │   │   └── __root__
│   │   │       └── __path__
│   │   │           └── __name__.js
│   │   └── index.js
│   ├── initializer-test
│   │   ├── index.js
│   │   ├── mocha-files
│   │   │   └── tests
│   │   │       └── unit
│   │   │           └── initializers
│   │   │               └── __name__-test.js
│   │   └── qunit-files
│   │       └── tests
│   │           └── unit
│   │               └── initializers
│   │                   └── __name__-test.js
│   ├── instance-initializer
│   │   ├── files
│   │   │   └── __root__
│   │   │       └── instance-initializers
│   │   │           └── __name__.js
│   │   └── index.js
│   ├── instance-initializer-addon
│   │   ├── files
│   │   │   └── __root__
│   │   │       └── __path__
│   │   │           └── __name__.js
│   │   └── index.js
│   ├── instance-initializer-test
│   │   ├── index.js
│   │   ├── mocha-files
│   │   │   └── tests
│   │   │       └── unit
│   │   │           └── instance-initializers
│   │   │               └── __name__-test.js
│   │   └── qunit-files
│   │       └── tests
│   │           └── unit
│   │               └── instance-initializers
│   │                   └── __name__-test.js
│   ├── mixin
│   │   ├── files
│   │   │   └── __root__
│   │   │       └── mixins
│   │   │           └── __name__.js
│   │   └── index.js
│   ├── mixin-test
│   │   ├── index.js
│   │   ├── mocha-files
│   │   │   └── tests
│   │   │       └── unit
│   │   │           └── mixins
│   │   │               └── __name__-test.js
│   │   └── qunit-files
│   │       └── tests
│   │           └── unit
│   │               └── mixins
│   │                   └── __name__-test.js
│   ├── route
│   │   ├── files
│   │   │   └── __root__
│   │   │       ├── __path__
│   │   │       │   └── __name__.js
│   │   │       └── __templatepath__
│   │   │           └── __templatename__.hbs
│   │   └── index.js
│   ├── route-addon
│   │   ├── files
│   │   │   └── __root__
│   │   │       ├── __path__
│   │   │       │   └── __name__.js
│   │   │       └── __templatepath__
│   │   │           └── __templatename__.js
│   │   └── index.js
│   ├── route-test
│   │   ├── index.js
│   │   ├── mocha-0.12-files
│   │   │   └── tests
│   │   │       └── unit
│   │   │           └── __path__
│   │   │               └── __test__.js
│   │   ├── mocha-files
│   │   │   └── tests
│   │   │       └── unit
│   │   │           └── __path__
│   │   │               └── __test__.js
│   │   └── qunit-files
│   │       └── tests
│   │           └── unit
│   │               └── __path__
│   │                   └── __test__.js
│   ├── service
│   │   ├── files
│   │   │   └── __root__
│   │   │       └── __path__
│   │   │           └── __name__.js
│   │   └── index.js
│   ├── service-test
│   │   ├── index.js
│   │   ├── mocha-0.12-files
│   │   │   └── tests
│   │   │       └── unit
│   │   │           └── __path__
│   │   │               └── __name__-test.js
│   │   ├── mocha-files
│   │   │   └── tests
│   │   │       └── unit
│   │   │           └── __path__
│   │   │               └── __name__-test.js
│   │   └── qunit-files
│   │       └── tests
│   │           └── unit
│   │               └── __path__
│   │                   └── __test__.js
│   ├── template
│   │   ├── files
│   │   │   └── __root__
│   │   │       └── __path__
│   │   │           └── __name__.hbs
│   │   └── index.js
│   ├── test-framework-detector.js
│   ├── test-helper
│   │   ├── files
│   │   │   └── tests
│   │   │       └── helpers
│   │   │           └── __name__.js
│   │   └── index.js
│   ├── util
│   │   ├── files
│   │   │   └── __root__
│   │   │       └── utils
│   │   │           └── __name__.js
│   │   └── index.js
│   └── util-test
│       ├── index.js
│       ├── mocha-files
│       │   └── tests
│       │       └── unit
│       │           └── utils
│       │               └── __name__-test.js
│       └── qunit-files
│           └── tests
│               └── unit
│                   └── utils
│                       └── __name__-test.js
├── dist
│   ├── bower.json
│   ├── component.json
│   ├── composer.json
│   ├── ember-runtime.js
│   ├── ember-runtime.map
│   ├── ember-template-compiler.js
│   ├── ember-template-compiler.map
│   ├── ember-testing.js
│   ├── ember-tests.js
│   ├── ember.debug.js
│   ├── ember.debug.map
│   ├── jquery
│   │   └── jquery.js
│   ├── package.json
│   ├── qunit
│   │   ├── qunit.css
│   │   └── qunit.js
│   └── tests
│       ├── index.html
│       └── node
│           ├── app-boot-test.js
│           ├── component-rendering-test.js
│           ├── helpers
│           │   ├── app-module.js
│           │   ├── assert-html-matches.js
│           │   ├── build-owner.js
│           │   └── component-module.js
│           ├── template-compiler-test.js
│           └── visit-test.js
├── index.js
├── package.json
└── vendor
    └── ember
        └── shims.js

184 directories, 102 files
```

**Comment by rwjblue** [comment]
LGTM

**Review by rwjblue — APPROVED** [review]

**Comment by Turbo87** [comment]
updated the PR to exclude the `dist/tests` folder from being published

**Comment by chadhietala** [comment]
LGTM

**Review by locks — APPROVED** [review]

**Pull request merged**
