### PR TITLE
use es6 class style for location classes

### PR DESCRIPTION
**Pull request by bekzod**

### CODE REVIEW

**Comment by bekzod** [comment]
alright 👍

**Comment by bekzod** [comment]
rebased any chance merging this

**Comment by rwjblue** [comment]
Seems good to move forward here, have some conflicts to fix first though.

**Comment by locks** [comment]
@bekzod the lint build is complaining, can you take a look?

**Comment by bekzod** [comment]
I think things got messed after rebase I think I better do another PR

**Pull request closed without merging**
