### PR TITLE
{{#each}} and {{#each-in}} helpers with sparse array tests

### PR DESCRIPTION
**Pull request by kamilogorek**
Related issue https://github.com/emberjs/ember.js/issues/14725

### CODE REVIEW

**Comment by rwjblue** [comment]
See associated comment on #14725, can you tweak this to show the current 2.10 behavior as the expected result? Also, it might be good to explicitly add a test showing the work around (using `{{#each-in`) supports those needing sparse array support.

**Comment by kamilogorek** [comment]
Definitely. Is current test in `each-in` enough for

>  explicitly add a test showing the work around (using {{#each-in)

or do you want me to move it to `each` test suit?

**Comment by rwjblue** [comment]
Oops, sorry, yes the existing test is good for each-in. Thank you!

**Comment by rwjblue** [comment]
Yes, we intentially fall back to forEach when Array.isArray is false, this is intentional (e.g. To support things like linked lists or other objects that are iterable (in the future we will likely support `Symbol.iterBle`)).

**Comment by kamilogorek** [comment]
@rwjblue could you point me to a solution for this difference? or should I just move the test underneath `// TODO: Refactor the following tests so we can run them against different kind of arrays` and specify what types of arrays we want to test?

**Comment by kamilogorek** [comment]
Updated both tests. We're back to green now.

**Review by rwjblue — APPROVED** [review]

**Comment by rwjblue** [comment]
Thank you!

**Pull request merged**
