### PR TITLE
[BUGFIX release] Fix cyclic references on Array.prototype

### PR DESCRIPTION
**Pull request by jacobq**
My first non-doc `ember.js` PR so please be kind :)

* Should detect the regression that causes #17190 
* Test currently fails (correctly) on master but passes on v3.5.1
* Not sure if the test is located in the right place or applied to the right object(s)
* Note: this only checks the first level (e.g. won't catch a nested reference)

### CODE REVIEW

**Comment by jacobq** [comment]
I am looking at this again as it seems to have failed to correctly identify the point in git commit history was introduced. (It appears to pass against 246435e7260f45d9e5cc35a4a8b4de4f011f3625 although [that seems to be where the regression happened](https://github.com/emberjs/ember.js/issues/17190#issuecomment-447501532))

**Comment by jacobq** [comment]
@rwjblue Thanks for taking this on. Could you help me understand something here? How come when I checkout 246435e7260f45d9e5cc35a4a8b4de4f011f3625 and build it, running the script below in node shows the problem, but running the [test that import `NativeArray`](https://github.com/jacobq/ember.js/blob/3029e9df6ef110cdf4f68a379600e4b5308db86f/packages/%40ember/-internals/runtime/tests/array/apply-test.js#L7:L29) passes?

```js
global.EmberENV = {
  EXTEND_PROTOTYPES: false,
};

const Ember = require('./dist/ember.debug.js');

const isOK = (a) => {
  for (let p in a) {
    if (a[p] === a) {
      return false;
    }
  }
  return true;
}

const check = (klass) => {
  const a = new klass();
  const result = isOK(a);
  console.log(`${klass} ${result ? 'is ok' : 'is NOT OK -- cycle detected!'}`);
}

class ExtendedArray extends Array {}
Ember.NativeArray.apply(ExtendedArray.prototype);

[Array, ExtendedArray].forEach(check);
// outputs:
// function Array() { [native code] } is ok
// class ExtendedArray extends Array {} is NOT OK -- cycle detected!
```

**Comment by jacobq** [comment]
Also, FWIW, there's an [`is-circual`](https://github.com/tjmehta/is-circular/blob/master/index.js) module that could be used instead of my home-made function.

**Comment by rwjblue** [comment]
Just pushed a commit fixing the issue (details in the comments and commit message).

**Pull request merged**
