### PR TITLE
[DOC Release] Mark Route.renderTemplate() as public

### PR DESCRIPTION
**Pull request by joeruello**

### CODE REVIEW

**Comment by pixelhandler** [comment]
@joeruello thanks I use renderTemplate sometimes and totally makes sense to have a public API. I've used that hook to mark/measure performance timings having that as public worked out great.

**Comment by rwjblue** [comment]
Please send a PR updating docs for the method to @public.

**Comment by joeruello** [comment]
@rwjblue Bit confused, am I missing an issue with this PR?

**Comment by rwjblue** [comment]
Welp. Sorry about that! I got confused, and thought this was an issue not a PR.

**Pull request merged**
