### PR TITLE
[BUGFIX release] Ensure that multiple app event dispatching works properly.

### LINKED ISSUE #11195: Multiple apps break view -> controller bindings as of 1.12
Hi folks, thanks for Ember!

I just upgraded my app to the latest stable release (1.12) and noticed a regression: If you have multiple Ember apps on a single page, some of the view -> controller bindings stop working on the first app. Below is a JSbin reproducing the bug, with steps to reproduce.
 
http://emberjs.jsbin.com/topehoyewu/1/

If you change the links in the HTML to link to ember v1.11.3, the bindings work, so the regression was introduced in 1.12, so my guess is that its related to some of the fastboot groundwork. I've tried it in 1.13.beta.1 and 2.0 canary, and the bug is there as well.

I'd love to help get this fixed, but I'll need some guidance on how to turn this into a failing test, since it involves multiple apps. Any advice?

### PR DESCRIPTION
**Pull request by rwjblue**
Fixes #11195.

### CODE REVIEW

**Comment by botandrose** [comment]
Thanks for taking the time to fix this, @rwjblue!

**Comment by gnarf** [comment]
:+1: -- I just ran into this bug with 1.12.1 - Any word on when a patch might release?

**Comment by rwjblue** [comment]
You can use the latest build in the release channel now, but a 1.12.2 will likely be released sometime before Friday.

**Comment by gnarf** [comment]
Thanks for the quick response - I can wait until a 1.12.2... I added a `Application.ViewRegistry` to my application for a temp fix: http://jsbin.com/nohamakoge/1/edit?js,output

**Comment by botandrose** [comment]
Hmm, looks like this didn't make it into 1.13.0, either. Will it be in 1.13.1?

**Pull request merged**
