### PR TITLE
[BUGFIX release] Fix nested render helpers

### LINKED ISSUE #10827: Regression: Nested {{render}} helpers result in Uncaught TypeError
Using nested {{render}} helpers results in `Uncaught TypeError: undefined is not a function.` It seems this began with the changes made in #10602 (d8a16a4) for 1.11.0. 

This JSBin reproduces a simple example: http://emberjs.jsbin.com/moxugi/1/edit?html,js,console,output

(*carried over from #10760*)

### PR DESCRIPTION
**Pull request by awaer**
Fixes #10827 

This simply applies the change described by @ef4 in this comment: https://github.com/emberjs/ember.js/issues/10827#issuecomment-90241369

### CODE REVIEW

**Comment by rwjblue** [comment]
Looks good to me.

@ef4 - Can you :+1: / :-1:?

**Comment by ef4** [comment]
Looks good to me.

**Comment by mmun** [comment]
@awaer Can you add a test similar to https://github.com/awaer/ember.js/blob/53832b348c76147b345f44ceea2e3c8e138a0a06/packages/ember/tests/routing/basic_test.js#L3744-L3769 that tests an outlet inside of nested {{render}} calls?

**Comment by awaer** [comment]
I'm unfamiliar with the Travis CI feedback -- is this referring to something I need to resolve on this PR?

**Comment by rwjblue** [comment]
Phantom crashed. I just restarted that Travis build.

**Comment by rwjblue** [comment]
This commit is targeting `stable` branch, but we need these changes to target `master`.  Once merged, I cherry-pick into `beta` and `stable` branches...

**Comment by rwjblue** [comment]
This is passing, so I'll just cherry-pick the other way (from stable to beta and master).

**Comment by awaer** [comment]
Sorry for the branch mixup. Thanks, @rwjblue

**Comment by rwjblue** [comment]
@awaer - No worries!

**Comment by bfcoder** [comment]
This is still an issue in 1.11.1 http://jsbin.com/yiwama/1/edit?html,js,console,output Any chance this can be released or are there still issues with it?

**Comment by alexdiliberto** [comment]
@bfcoder This is fixed with today's 1.11.3 release http://jsbin.com/doheto/1/edit

**Comment by bfcoder** [comment]
@alexdiliberto I'm not seeing any release past 1.11.1 https://rubygems.org/gems/ember-source Nor in ember-cli is it past 1.11.1

**Comment by awaer** [comment]
http://emberjs.com/builds/#/tagged

**Comment by bfcoder** [comment]
Ok, I'll just have to be patient for it to be released to the gem. :] Thanks!

**Comment by bfcoder** [comment]
@rwjblue Any chance that 1.11.3 could be released to the ember-source gem? Or are there still issues that would prevent the release? Thanks!

**Pull request merged**
