### PR TITLE
Update blueprints and tests to RFC #176

### PR DESCRIPTION
**Pull request by locks**
[RFC #176](https://github.com/emberjs/rfcs/blob/master/text/0176-javascript-module-api.md).
[Conversion tables for imports](https://github.com/ember-cli/ember-rfc176-data).

- [x] Normalize `""`/`''` in imports
- [x] Address minor documentation issues, like typos and formatting
- [x] Update documentation code blocks
- [ ] Update documentation cross-linking (e.g. `Ember.ApplicationInstance` to `ApplicationInstance`)
- [x] Update blueprints and tests
- [ ] Update meta-documentation (`@module`, `@submodule`, etc)

### CODE REVIEW

**Comment by rwjblue** [comment]
@locks - Where are we at with this one?  Seems like tests are passing now, but I'm not sure where it falls as far as completeness...

**Comment by locks** [comment]
@rwjblue bullet list is up to date, there is some cross-linking cleanup to do which isn't blocking IMO. We need to figure out holistically how we will reference to stuff like `Ember.run` because it'll now be `run`.

**Review by rwjblue — APPROVED** [review]

**Comment by rwjblue** [comment]
OK, this looks good, can you squash?

**Comment by locks** [comment]
@rwjblue squished.

**Pull request merged**
