### PR TITLE
Add failing test for partials which contain contextual components

### PR DESCRIPTION
**Pull request by GavinJoyce**
related to https://github.com/emberjs/ember.js/issues/15621

TODO:

 * [x] bump `@glimmer` dependencies to `^0.25.4` and verify new tests pass
 * [x] address unrelated regression outlined here : https://github.com/emberjs/ember.js/pull/15777#issuecomment-339940275

### CODE REVIEW

**Comment by GavinJoyce** [comment]
it looks like updating to glimmer-vm `0.25.4` results in three test failures:

screen shot 2017-10-27 at 11 42 38

**Comment by GavinJoyce** [comment]
Here's the glimmer-vm diff: https://github.com/glimmerjs/glimmer-vm/compare/v0.25.3...v0.25.4

**Comment by GavinJoyce** [comment]
@rwjblue here's what I believe to be the current state of play:

 * A regression was introduced in Ember 2.15 time frame ([test here](https://github.com/emberjs/ember.js/pull/15777/commits/7c7a08b8a792af5cd64c12cbb5ab8917c7ab9534)) and is fixed in glimmer-vm 0.25.4
 * glimmer-vm 0.25.4 introduces a regression which results in [this test failing](https://github.com/emberjs/ember.js/blob/5f4ac602813d8fbd78f26fc955acf693e0b3d62a/packages/ember-glimmer/tests/integration/components/curly-components-test.js#L331-L351), it passes with glimmer-vm 0.25.3.
 * Your additional tests in https://github.com/emberjs/ember.js/pull/15674 aren't fixed with glimmer-vm 0.25.4

**Comment by GavinJoyce** [comment]
Digging into the failing test a little:

in glimmer-vm 0.25.3, the `get` opcode results in an `InternalReferenceHelper` of `classHelper` (which is correct):

screen shot 2017-10-28 at 21 55 42

in glimmer-vm 0.25.4, the `maybeLocal` opcode results in a `RootPropertyReference` with a value of `true` (which is incorrect):

screen shot 2017-10-28 at 21 57 53

**Comment by GavinJoyce** [comment]
Aha, `wrapComponentClassAttribute` currently only supports `Ops.Get`, not `Ops.MaybeLocal`:

https://github.com/emberjs/ember.js/blob/ef1880778b7ee259770d19accd978bb35abb3706/packages/ember-glimmer/lib/utils/bindings.ts#L50-L54

screen shot 2017-10-28 at 22 43 13

**Comment by GavinJoyce** [comment]
@rwjblue 🍏 and ready for review

**Comment by rwjblue** [comment]
Thank you very much for working on this!!

**Comment by tomdale** [comment]
Impressive work, @GavinJoyce. I agree with the comment: ideally this fixing up should happen at the AST level, not the opcode level. I'm afraid that future plans for generating more optimized bytecode will probably continue to cause breakage here if it's relying on specific opcodes instead of higher-level semantics.

**Pull request merged**
