### PR TITLE
[CLEANUP beta] Turn `template-only-glimmer-components` deprecation into an error

### PR DESCRIPTION
**Pull request by bertdeblock**
Part of #19617.

### CODE REVIEW

**Review by rwjblue — APPROVED** [review]

**Comment by bertdeblock** [comment]
@rwjblue Is the failing `Browser Tests (Firefox)` check related to my changes? They seem to run fine locally.

**Comment by mixonic** [comment]
@bertdeblock I'm re-running now

**Comment by mixonic** [comment]
Thank you @bertdeblock !

**Pull request merged**
