### PR TITLE
[fixes #11673] Ember.typeOf now understands [object XXX] including Symbol

### LINKED ISSUE #11673: Symbol is not a supported type in Ember.typeOf(); returns "object"
ember.js/packages/ember-runtime/lib/utils.js

### PR DESCRIPTION
**Pull request by stefanpenner**

### CODE REVIEW

**Comment by rwjblue** [comment]
Looks good, should this be `[BUGFIX beta]`?

**Comment by stefanpenner** [comment]
just confirmed it works with a valid polyfil.

```
% node -v                                                                                                                                                                  v0.10.35
```
which has no symbols,


```
> require('core-js/shim');
> Symbol
[Function: Symbol]
> Object.prototype.toString.call(Symbol)
'[object Function]'
> Object.prototype.toString.call(Symbol('a'))
'[object Symbol]'
>
```

**Comment by stefanpenner** [comment]
@rwjblue I have updated this to work generically with with all primordials. I realized that subclasses of these primordials dont currently inherit the `@@toStringTag` I can understand both sides of the argument. I'll have to do a check to see what the expected behavior is.

**Comment by rwjblue** [comment]
@stefanpenner - A few tests for `Ember.String.fmt` failed when "extend prototypes" is checked, seems like legit failures.

**Comment by stefanpenner** [comment]
ya, i'll take a look

**Comment by stefanpenner** [comment]
@rwjblue so, I realized this change may be breaking... If people are expecting `Ember.typeOf(Map) === 'object'`

**Comment by stefanpenner** [comment]
So it appears IE8:

```js
Object.prototype.toString.call(arguments) === '[object Object]';
```

IE9+
```js
Object.prototype.toString.call(arguments) === '[object Arguments]';
```

**Comment by stefanpenner** [comment]
Ok I think this path is fraught with peril, as various browsers are at different levels of completeness in implementing `@@toStringTag`

IE11:

```js
Object.prototype.toString.call(new Map()) === '[object Object]'
```

Chrome: Version 45.0.2449.0 canary (64-bit)
```
Object.prototype.toString.call(new Map()) === '[object Map]'
```

\w core-js everything appears to be correct.

**Comment by stefanpenner** [comment]
I'm going to conver

**Pull request closed without merging**
