### PR TITLE
[CI] Remove testem.js error

### PR DESCRIPTION
**Pull request by KamiKillertO**
This PR is related to this issue #17016.
As suggested I just remove the import of testem.js in the file `tests/index.html`and everything seems to works in local, all tests are green. With this PR we will see if everything still work as expected on travis

### CODE REVIEW

**Comment by rwjblue** [comment]
FWIW - This likely makes `ember test` not work, can you double check?

**Comment by KamiKillertO** [comment]
Ok my bad I was running the tests using `yarn test`, but with `ember test` the tests fail because testem is missing. 🤔 I'll explore other solutions ^^

**Comment by rwjblue** [comment]
No worries! You can probably work around the error by adding an empty `testem.js` file to the build. That way, when using `ember test` The “real” `testem.js` would be found, but when running via `yarn test` (which is effectively just `ember serve` + some puppeteering) it would avoid the error because this new empty file would be found.

**Review by rwjblue — COMMENTED** [review]
Awesome! Thank you!

**Pull request merged**
