### PR TITLE
[bugfix BETA] Fixes 12995 #with array yields true

### LINKED ISSUE #12995: #with array yields boolean
In both Beta and Canary, if the value in the `with` helper is an array, it will yield `true` rather than the array itself. 

See [this twiddle](https://ember-twiddle.com/62a6d7176f003bec0fbd?openFiles=twiddle.json%2Capplication.template.hbs) for an example. (This behavior does not occur on 2.3 and down).

### PR DESCRIPTION
**Pull request by spencer516**
This fixes https://github.com/emberjs/ember.js/issues/12995

### CODE REVIEW

**Comment by fivetanley** [comment]
:+1: Can you prefix your commit with `[bugfix BETA]`, and also make sure it works on the beta branch?

**Comment by fivetanley** [comment]
I confirmed this worked on the beta branch by cherry-picking it on. So, once the commit message is amended and approved by a core team member, this should be good to go.

**Comment by spencer516** [comment]
@fivetanley — got that commit message updated

**Comment by mmun** [comment]
[BUGFIX beta] :P

**Comment by rwjblue** [comment]
Thank you!

**Pull request merged**
