### PR TITLE
[BUGFIX release-1-13] use `read` in action helper

### LINKED ISSUE #13062: `{{action preventDefault=preventProperty}}` doesn't work.
We're using Ember 1.13. The action takes a `preventDefault` property but it only works with literal value (`true` and `false`). But if I try to pass another property, it always prevents default.

Here is a [jsfiddle](http://jsfiddle.net/6Evrq/849/) that reproduces the issue.

### PR DESCRIPTION
**Pull request by fivetanley**
Before, the values passed to the `action` helper were not using `read`.
This means if you did not pass a literal, but passed a binding or
computed property, it would pass the `KeyStream` along instead of
reading the value from the stream.

fixes #13062

I also fixed the jshint errors and other tests that were failing.

### CODE REVIEW

**Comment by fivetanley** [comment]
Also of note here is that `withKeyCode` doesn't seem to actually be used anywhere in the code base, but I added tests for it anyway.

**Comment by fivetanley** [comment]
I ended up removing `withKeyCode` as it wasn't used even in the function it was passed into.

**Comment by rwjblue** [comment]
@fivetanley - It was added for a feature that was subsequently removed...

**Comment by mixonic** [comment]
@fivetanley are these values also bound?

**Comment by rwjblue** [comment]
@fivetanley - Can you address @mixonic's comment?  I'd like to either land or close this soonish....

**Comment by fivetanley** [comment]
@mixonic @rwjblue i changed the added test cases to update using computed properties instead, let me know if you need anything else.

**Comment by fivetanley** [comment]
My livereload wasn't working, it turns out those tests fail. I think a partial fix is better than no fix at all, I think the current code would require a lot more reworking to get the tests in https://github.com/emberjs/ember.js/pull/13066/commits/db9d7f17ae647ebf223dd238a4473c28f03e32de to pass...

**Comment by fivetanley** [comment]
(to be clear i reset back to the original PR code)

**Comment by rwjblue** [comment]
Restarted sauce labs build.

**Comment by mixonic** [comment]
@fivetanley I also kicked sauce. What I was asking is not that they be CPs though, but that they be bound. Can you set a new value to that property and the helper will update? For example:

```js
QUnit.test("allows alternative events to be handled when computed property passed as `on` property", function() {
  var reachedAction;

  view = EmberView.extend({
    controller: Ember.Controller.extend({
      onAction: 'mouseUp',
      actions: {
        edit: function() {
          reachedAction = true;
        }
      }
    }).create(),
    template: compile('<a href="#" {{action "edit" on=onAction}}>edit</a>')
  }).create();

  runAppend(view);

  run(() => {
    view.$('a').mouseup();
  });

  equal(reachedAction, true, "The alternative mouseUp event was properly registered");

  // reset for test
  reachedAction = false;

  view.controller.set('onAction', 'mouseDown');
  run(() => {
    view.$('a').mousedown();
  });

  equal(reachedAction, true, "The action trigged for updated on value");
});
```

In general we've avoided making the use of a property "work" unless binding was also supported. Because as soon as somebody uses a property, someone else expects it to be bound.

**Comment by rwjblue** [comment]
@fivetanley - Can you update as @mixonic suggested?

**Comment by fivetanley** [comment]
@mixonic in my tests cases no, it does not work. Please see https://github.com/fivetanley/ember.js/blob/db9d7f17ae647ebf223dd238a4473c28f03e32de/packages/ember-routing-htmlbars/tests/helpers/element_action_test.js#L113. Like I said, they won't update accordingly without more work that I don't have time to do. Seems like an ember-metal thing someone on core would be more familiar with.

**Comment by fivetanley** [comment]
Those tests passed in ember canary though, so I don't think it's a problem there.

**Comment by mixonic** [comment]
It is a bit of a pain in Glimmer 1 for sure. Basically the stream for the keyword needs to have dependencies added for each argument. Ala: https://github.com/emberjs/ember.js/blob/master/packages/ember-routing-htmlbars/lib/keywords/closure-action.js#L69-L70

**Comment by rwjblue** [comment]
I'm going to go ahead and close this for now. We can reopen if needed, but 1.13 is super old at this point and dwindling in percentage of user base...

**Pull request closed without merging**
