### PR TITLE
correct spelling for 'property'

### PR DESCRIPTION
**Pull request by vsopvsop**

### CODE REVIEW

**Comment by stefanpenner** [comment]
going forward, it would be really nice if these could be single commits

**Comment by vsopvsop** [comment]
I am sorry. I am doing driveby contribution.

**Comment by vsopvsop** [comment]
I am really sorry that I was not aware of the issues posed by CI build. Now that I know I will try to comply with your request. 

I am a newbie. Please forgive me for my ignorance.

**Comment by stefanpenner** [comment]
> I am a newbie. Please forgive me for my ignorance.

We absolutely welcome the drive-by contributions :) They provide good value. I am merely making a recommendation to help improve the experience for all involved.

No need to appologies. I wish GH web UI provided a nicer way to easily batch these sorts of changes.

**Comment by tomdale** [comment]
@vsopvsop The fixes are much appreciated, thank you so much for taking the time to submit them. <3 <3 <3

**Comment by tomdale** [comment]
@vsopvsop I think this one is supposed to be "properly", not "property"

**Pull request merged**
