### PR TITLE
From ES5 to ES6

### PR DESCRIPTION
**Pull request by artemgurzhii**
Code refactoring.

### CODE REVIEW

**Comment by btecu** [comment]
Really nice!

You should discard the changes to `yarn.lock`.
Also, to be consistent, I would not add wrapping parenthesis to arrow function with a single argument:
`(prop) => ...` but `prop => ...`.

**Comment by artemgurzhii** [comment]
Also, I'm getting an error when using `for of` loop and `String.includes`. Is there any way to fix this?

**Comment by locks** [comment]
@artemgurzhii related: https://github.com/emberjs/emberjs-build/pull/186

**Comment by locks** [comment]
@artemgurzhii the PR is getting big enough to be confusing to review. Could you send a PR per package instead? This would also speed up merging, since a problem in one file wouldn't block another file!

**Comment by artemgurzhii** [comment]
Ok, sure.

**Comment by locks** [comment]
Appreciated! Thanks for the work so far.

**Pull request closed without merging**
