### PR TITLE
[FEATURE ember-libraries-isregistered] Add isRegistered to Ember.libraries

### PR DESCRIPTION
**Pull request by quaertym**

### CODE REVIEW

**Comment by wagenet** [comment]
@quaertym Since this is an API surface change, it will need to be feature flagged before it can become a candidate for merging.

**Comment by rwjblue** [comment]
I'm not opposed, it does seem nice, but I am curious what the reason for the change is? Is it to prevent double registration?

**Comment by quaertym** [comment]
@wagenet Done feature flagging.

@rwjblue Yep, main purpose is to prevent double registration. API feels more complete when there is a method to check whether a library is registered in addition to `register` and `deRegister` methods. It can also be useful for ember-inspector or addons like ember-cli-app-version.

**Comment by quaertym** [comment]
Travis fails, no idea why. Everything works fine locally.

**Comment by mixonic** [comment]
@quaertym have you run `npm test` locally? The tests there run in a more comprehensive mode (as individual packages) that differs slightly from the basic browser run.

**Comment by quaertym** [comment]
@mixonic `npm test` ends with 0 fails locally. In travis only this ENV causes problems `TEST_SUITE=built-tests EMBER_ENV=production`. How to run with these?

**Comment by rwjblue** [comment]
`TEST_SUITE=built-tests EMBER_ENV=production npm test`

**Comment by quaertym** [comment]
@rwjblue That's what I do. What's `phantomjs` version on travis? Running with `v1.9.7` results in 0 fails locally however running with `v2.0.0` is problematic.

**Comment by quaertym** [comment]
Running `TEST_SUITE=all npm test` results in a single failure:
```
Test failed: global failure
    Failed assertion: Error: Could not find module ember-dev/test-helper/index
file:///~/Desktop/ember.js/dist/ember-template-compiler.js:48
```
any idea why?

**Comment by quaertym** [comment]
@wagenet @rwjblue This is finally green on travis.

**Pull request merged**
