### PR TITLE
this._super() -> this._super.apply(this, arguments)

### PR DESCRIPTION
**Pull request by stefanpenner**

### CODE REVIEW

**Comment by dgeb** [comment]
I could see this one coming for a few days. Glad you got them all in one shot, Stef. Now quick - merge this sucker!

**Comment by stefanpenner** [comment]
good guy vim

```viml
:args packages/**/*.js
:argdo s/this._super()/this._super.apply(this, arguments)/gc
```

**Comment by jayphelps** [comment]
Does this counterintuitively _help_ an optimizing JIT these days? It used to forced depot back in the day, but can't find a solid answer. Looks like it "depends". I only ask because some of these classes are arguably hot in certain apps and a majority of the time they were effectively unnecessary. /endbikeshed

**Comment by mixonic** [comment]
@stefanpenner I'm also confused as to why this is the best thing to do. I presume benchmarks showed no impact?

**Comment by stefanpenner** [comment]
correctness, and no noticeable performance difference. Places were their is, we already special case it.

I would like people to cargo cult this pattern in their apps, calling `this._super()` without args, breaks the programming model of super. We have baked ourselves into a corner, and its time to fix it.

`this._super(...arguments)` can be done in es6, and eventually we want to use the real super in es6.

**Pull request merged**
