### PR TITLE
[BUGFIX beta] Remove link-to keyword.

### PR DESCRIPTION
**Pull request by rwjblue**
- `RELATED_VIEW` was actually referencing `this.parentView` so there was
  no need to pass it through specially.
- Change `component:-link-to` registration to `component:link-to`
  (allows users to implement a custom `{{link-to}}` in their apps at
  `app/components/link-to.js` without any special work).
- Move `{{link-to}}` documentation to `ember-routing-htmlbars/components/link-to`.
- `ember-routing-views/views/link` -> `ember-routing-views/components/link-to`
- Move `HAS_BLOCK` symbol to `ComponentNodeManager`.
- Remove `ember-routing-htmlbars/keywords/link-to.js`.

/cc @nathanhammond @mmun

### CODE REVIEW

**Comment by rwjblue** [comment]
Implementing a custom `{{link-to}}` is as simple as:

```javascript
export default Ember.LinkComponent.extend({
  attributeBindings: ['data-foo']
});
```

Demo: http://rwjblue.jsbin.com/fohaje/edit?html,js,output

**Comment by mmun** [comment]
yay. Why not move the docs to packages/ember-routing-views/lib/views/link.js? And why isnt it link-to.js? :p

**Comment by rwjblue** [comment]
> Why not move the docs to packages/ember-routing-views/lib/views/link.js?

Done.

> And why isnt it link-to.js?

Done.

**Comment by mmun** [comment]
Nice. This was a long time coming.

**Comment by rwjblue** [comment]
Sauce is having an issue with tunnels at the moment:

```
Error: 23 Aug 01:38:48 - GET https://saucelabs.com/rest/v1/ember-ci/tunnels?full=1: Timeout was reached.
```

**Comment by nathanhammond** [comment]
I almost removed the keyword but wasn't sure we wanted to collide with user-space. Is this the only registration we make that a user can collide with?

**Pull request merged**
