### PR TITLE
[DOC release] Update `get` helper action code sample

### PR DESCRIPTION
**Pull request by samselikoff**
Got tripped up by this today, there was another outdated sample.

I think pushing people towards onevent= is better?

### CODE REVIEW

**Comment by locks** [comment]
@samselikoff these are two different things though, the event handler will receive the event as an argument, while the action won't. The correct fix is the ugly double action helper: `{{action (action (mut factName) "height")}}`.

**Review by locks — CHANGES_REQUESTED** [review]
Do `{{action (action (mut factName) "height")}` instead because of the differing semantics of DOM event handlers.

**Comment by samselikoff** [comment]
Updated, should we `<button {{action` or `<button onclick={{action`?

**Comment by locks** [comment]
@samselikoff sorry for the delay, IMO it should be `<button {{action` so that the event handler gets scheduled with the global dispatcher thingie.

**Comment by samselikoff** [comment]
Should be all set

**Review by locks — APPROVED** [review]

**Comment by locks** [comment]
Thank yoouu 👯‍♂️

**Comment by nightire** [comment]
@locks May I ask what's the difference between `<button {{action` and `<button onclick={{action` behind the scene? I can't find concrete explanation through the api documentation, be more specific, I'm really eager to understand "...gets scheduled with the global dispatcher thingie", what does it mean?

**Comment by kumkanillam** [comment]
In [this thread](https://github.com/emberjs/ember.js/issues/14334) @locks explained ,
<button {{action 'actionName'}}> defines an Ember action on the button. Ember is responsible for managing it.
<button onClick={{action 'actionName'}}> defines an event handler for the DOM onClick event. So it's basically the browser that manages it, and eventually, triggers the event handler.

**Comment by nightire** [comment]
@kumkanillam I see, thanks for your explanation!

**Pull request merged**
