### PR TITLE
[FEATURE default helper manager] Add the default helper manager

### PR DESCRIPTION
**Pull request by Windvis**
This updates the Glimmer VM to version 0.84.2 which includes the default helper manager and a feature flag to conditionally enable that feature in Ember.

This PR supersedes #19973.

### CODE REVIEW

**Comment by Windvis** [comment]
Draft since there are more changes needed in the VM when using functions that are stored on class properties or passed as arguments.

**Review by chancancode — APPROVED** [review]
@Windvis do you have anything else you think needs to be done or are you happy with everything? at a glance it seems good to me

**Comment by wycats** [comment]
@chancancode any reason not to merge this?

**Comment by Windvis** [comment]
@chancancode I think it's good to go. :+1: The RFC mentions some documentation updates but that's part of the guides so nothing needs to be added here I think.

**Comment by Windvis** [comment]
@chancancode I think it's good to go. :+1: The RFC mentions some documentation updates but that's part of the guides so nothing needs to be added here I think.

**Pull request merged**
