### PR TITLE
Adding in sanitation for URLs with more than one slash in it

### PR DESCRIPTION
**Pull request by jonathanKingston**
Fixes: #10937

### CODE REVIEW

**Comment by stefanpenner** [comment]
needs test

**Comment by jonathanKingston** [comment]
@stefanpenner  will do, was committing so it didn't get lost. Which yeah two core devs proved I should have done that when I wrote it :D.

**Comment by rwjblue** [comment]
@jonathanKingston - needs a test still

**Comment by rwjblue** [comment]
Needs to be squashed and a test added...

**Comment by rwjblue** [comment]
Still needs tests, rebase, and squashing.

**Comment by jonathanKingston** [comment]
@rwjblue I have actually simplified this as @tomdale asked to just prefix with the sites `window.location.origin`

However was not sure of:
- Would the test be better as a unit test or integration?
- Do I need to shim `window.location.origin` as browser support is IE 11+ (I couldn't see one as part of babel or Ember)

**Comment by rwjblue** [comment]
> Do I need to shim window.location.origin as browser support is IE 11+

Yes, we will need some sort of shim.

> Would the test be better as a unit test or integration?

I think integration test would be best, but true integration tests using location are pretty hard (because changing location messes up the running tests) so a unit test would probably be fine.

**Comment by rwjblue** [comment]
Closing as this seems to have gone stale, I'm happy to reopen if you would like to pick this back up again.

**Pull request closed without merging**
