### PR TITLE
Initial lodash integration

### PR DESCRIPTION
**Pull request by tonycoco**
This is a WIP branch to import [lodash](https://github.com/lodash/lodash-cli) and leverage it's utility functions and performance gains inside Ember.
- [x] Get the ES6 imports working from a build of lodash
- [x] Replace current Ember utility functions with lodash functions
- [ ] Fix size vs. length deprecation warnings
- [ ] Fix Query Params test for undefined

Pairing with @crismali on this one at @devmynd studios. Thanks to @jdalton for lodash and helping integrate it in.

### CODE REVIEW

**Comment by tonycoco** [comment]
Just rebased this branch with master... seems like the ES6 length vs size error is messing things up when using lodash's functions.

**Comment by tonycoco** [comment]
Just some notes about the build size too...

```
Build          Original  Lodashed  Percentage Change
ember.min.js   489937    511774    1.04457103668431
ember.prod.js  1819247   1936421   1.06440796659277
```

**Comment by tonycoco** [comment]
@stefanpenner and @rwjblue any idea on how to get the ES6 `size` instead of `length` error to go away for these? Seems like it is only happening on the tests.

**Comment by tonycoco** [comment]
Just some notes about the build size too...

```
Build          Original  w/Lodash
ember.min.js   408048    432653
ember.prod.js  1444140   1528949
```

**Comment by stefanpenner** [comment]
thank you for this contribution. Unfortunately, we will be going in a slightly different direction.

* ember-cli's packager effort will allow for optimized builds directly from lodash-es https://github.com/ember-cli/ember-cli/issues/4211
* we will need to maintain the existing array enumeration helpers during the 2x life-cycle, but plan to migrate away, deferring more and more to lodash via ember-clis optimal builds
* ember 2.0 now supports only es5 browser, many of the enumerable helpers are natively provided

**Comment by tonycoco** [comment]
No problem, @stefanpenner. Thanks for the reply! Looking forward to the new ES2015 featureset use inside Ember itself.

**Pull request closed without merging**
