### PR TITLE
adjust assertion to allow for either undefined or null values

### PR DESCRIPTION
**Pull request by Dhaulagiri**
Based on conversation with @rwjblue in https://github.com/emberjs/ember.js/issues/16148 he suggested adjusting this assertion to allow `value` to be null.  I confirmed locally that this fixes the instances of https://github.com/emberjs/ember.js/issues/16259 we are seeing which we are unable to correct with the upstream Ember Data fix just yet.

If this looks good I can adjust the commit message as needed, but ideally this would be a [BUGFIX Release].

### CODE REVIEW

**Comment by rwjblue** [comment]
Seems good to me, `[BUGFIX release]` seems like a good target...

**Comment by Dhaulagiri** [comment]
@rwjblue i also targeted the release branch because master wouldn't let my app boot for reasons I didn't look into, is that a valid target as well?

**Comment by rwjblue** [comment]
Sadly due to somewhat arcane release processes (that are completely my fault) we need to target this PR at master, then cherry-pick (or land separate PRs) into beta and release.

**Comment by rwjblue** [comment]
Sorry for the run around @Dhaulagiri, thank you!

**Pull request closed without merging**
