### PR TITLE
Added Slack badge

### PR DESCRIPTION
**Pull request by crunchtime-ali**

### CODE REVIEW

**Comment by dj-hedgehog** [comment]
The badge is breaking the layout. I'm looking into why this happens. It works with Slackin-badges from other Slackin-apps.

**Comment by stefanpenner** [comment]
this was reverted, because the rendering box is square: see https://github.com/emberjs/ember.js/pull/12551 for more details.

If that is fixed we would totally accept the PR

**Comment by dj-hedgehog** [comment]
I contacted the author of Slackin but he didn't get back to me.
I wasn't able to find out what is causing the dimensions to be wrong on Heroku yet but will make another PR as soon as I found it out.

**Comment by dj-hedgehog** [comment]
@stefanpenner I don't know who is in charge of your [Slackin app](https://ember-community-slackin.herokuapp.com) but could you tell him/her to deploy it again with the most recent version of Slackin? I deployed two Slackin applications to Heroku. The badge SVG has the right dimensions for all of them

image

**Comment by stefanpenner** [comment]
@rwjblue / @wifelette any idea how manages that app for us?

**Comment by rwjblue** [comment]
I am uncertain.  I'll ping cromwellryan in slack (the initial creator) and see if he knows.

**Comment by cromwellryan** [comment]
The repo is https://github.com/cromwellryan/ember-community-slackin. Looks like slackin moved to babel from 6to5.  We made a few modifications to this instance, so I'll take a look at the upgrade and post back here.

**Comment by cromwellryan** [comment]
You should be all set @dj-hedgehog 

Example: [Slack](https://ember-community-slackin.herokuapp.com)

**Comment by dj-hedgehog** [comment]
The SVG has the correct dimensions but it looks like Github uses the old cached image :O

**Comment by dj-hedgehog** [comment]
I wrote to Github to find out how long they keep SVG's cached.

**Pull request merged**
