### PR TITLE
[Bugfix release] Allow class-based helpers in strict-mode

### PR DESCRIPTION
**Pull request by NullVoxPopuli**
https://github.com/emberjs/ember.js/issues/19877

Related:  https://github.com/emberjs/ember.js/pull/19878/

### CODE REVIEW

**Review by mixonic — APPROVED** [review]
Looks great! I would love a gut check from @chancancode @wycats or someone else close to the template/vm. This seems correct to me.

**Review by chancancode — APPROVED** [review]
Seems fine to me

**Comment by NullVoxPopuli** [comment]
:partying_face: let's merge?

**Comment by kategengler** [comment]
Is #19878 identical? (it looks so from a very quick look) If so, I think I'd prefer to merge that one and follow our normal release process.

**Comment by NullVoxPopuli** [comment]
Yup. I thought targeting the release branch was the thing to do for bug fixes 🙃

**Comment by kategengler** [comment]
Merged in #19878

Will backport.

**Comment by vstefanovic97** [comment]
@kategengler Hi! Can this be backported to a patch version for `3.28.*` ? Thanks in advance!

**Comment by NullVoxPopuli** [comment]
I submitted the fix for use with `<template>` / strict-mode templates / first-class-component-templates, and because [the rfc](https://github.com/emberjs/rfcs/pull/779) was only recently merged, I'm :shrug: on if it should be back ported to previous LTS. Any project where I'm using `<template>` atm (via [this addon](https://github.com/ember-template-imports/ember-template-imports/)), is using ember-source@4.2+ so... :shrug:

**Comment by chancancode** [comment]
It’s probably a good idea if it’s easy to do (ie the changes apply cleanly). It would help with polyfills etc.

**Pull request closed without merging**
