### PR TITLE
[BUGFIX release] Deprecate Freezable and frozenCopy. Resolves #11452

### LINKED ISSUE #11452: need to deprecated Freezable

### PR DESCRIPTION
**Pull request by jamiebuilds**
Hold off on merging, putting this up so @stefanpenner can take a look.

Other stuff:
- [x] Can't get new freezable test file to run
- [ ] frozenCopy still needs a test for the deprecation (the existing tests aren't actually run)

### CODE REVIEW

**Comment by mixonic** [comment]
Please also update the breaking changes list in the 2.0 beta blog post :-)

**Comment by stefanpenner** [comment]
@thejameskyle looks like this needs a rebase

**Comment by thejameskyle** [comment]
Rebased

**Comment by mixonic** [comment]
Darn it just kicked travis into submission, then noticed this is not flagged correctly. Please `[BUGFIX release]` so we can land it into 1.13.x

**Comment by thejameskyle** [comment]
I don't understand

**Comment by stefanpenner** [comment]
@thejameskyle the commit message should be prefixed with '[BUGFIX release]` that way our magically build tool fairy (@rwjblue) knows where it must go.

**Comment by mixonic** [comment]
FYI The context for tagging commits is in: https://github.com/emberjs/ember.js/blob/master/CONTRIBUTING.md#pull-requests

**Comment by stefanpenner** [comment]
@thejameskyle i think `packages/ember-runtime/tests/suites/copyable/frozenCopy.js` needs to be renamed to be `frozenCopy-test.js`

**Comment by thejameskyle** [comment]
@stefanpenner that's a suite, it gets pulled in by other tests.

**Comment by stefanpenner** [comment]
> @stefanpenner that's a suite, it gets pulled in by other tests.

Ah good catch.  Whats blocking that last checkbox?

**Comment by thejameskyle** [comment]
> Ah good catch. Whats blocking that last checkbox?

Me trying to finish my conference talk for next week. :stuck_out_tongue:

**Comment by stefanpenner** [comment]
> Me trying to finish my conference talk for next week.

ah ok. Carryon

**Comment by stefanpenner** [comment]
packages/ember-runtime/tests/suites/copyable/frozenCopy.js -> packages/ember-runtime/tests/suites/copyable/frozenCopy-test.js

**Comment by stefanpenner** [comment]
@rwjblue friendly reminder

**Comment by thejameskyle** [comment]
Updated

**Pull request merged**
