### PR TITLE
[FEATURE ember-runtime-proxy-mixin] Remove feature (make private).

### PR DESCRIPTION
**Pull request by rwjblue**
- Remove feature flags.
- Make `Ember._ProxyMixin` private API for internal use.

### CODE REVIEW

**Comment by alexparker** [comment]
Bump on @jayphelps question to @rwjblue ?

Was looking to create a proxy component using this mixin.

**Comment by Panman8201** [comment]
Just ran into this myself too. Need to use `ProxyMixin` on a `Service` since I get depreciation notices using `ObjectProxy` as a Service. API docs lead to the existence of `ProxyMixin` yet even though it's "Private" and renamed to `_ProxyMixin`.

http://emberjs.com/api/classes/Ember.ProxyMixin.html

**Comment by sandstrom** [comment]
@rwjblue I have the same question, any chance you could flip this to public? It's a very useful mixin, we've used it for a bunch of stuff.

***

@Panman8201 here is a hacky workaround. Still, I also prefer if this mixin was public.

```
# `Ember.ProxyMixin` is private, so we cannot use it. Instead we're using the public `ObjectProxy`,
# and fake the service part of it (by setting `isServiceFactory: true`).
# https://github.com/emberjs/ember.js/blob/master/packages/ember-runtime/lib/mixins/-proxy.js

PseudoServiceWithPromiseProxyMixin = Ember.ObjectProxy.extend(Ember.PromiseProxyMixin)

PseudoServiceWithPromiseProxyMixin.reopenClass({
  isServiceFactory: true
})

CurrentCompanyService = PseudoServiceWithPromiseProxyMixin.extend({

  init: ->
    deferred = RSVP.defer()
    @set('promise', deferred.promise)
    @set('deferred', deferred)
    @_super()

})

`export default CurrentCompanyService`
```

**Comment by Panman8201** [comment]
@sandstrom I was wondering how I'd use the `isServiceFactory` flag properly to get that depreciation to go away. I was simply extending `ObjectProxy` and trying to set `{isServiceFactory:true}` in the extending hash. Ended up just using the private `Ember._ProxyMixin` anyway. Also note that `ObjectProxy` is also marked Private, just not renamed with the underscore in front.

**Comment by sandstrom** [comment]
@Panman8201 Yes, that's the instance vs. class property thing.

It sure looks like it's public, see https://github.com/emberjs/ember.js/blob/master/packages/ember-runtime/lib/system/object_proxy.js#L71

**Comment by Panman8201** [comment]
@sandstrom I guess I was looking at the API docs (right above the Extends...): http://emberjs.com/api/classes/Ember.ObjectProxy.html

However, it looks like it was changed to public since the API docs were generated. https://github.com/emberjs/ember.js/commit/84909b21960e8b19a5e3d2d7f74febe227bf83af 

Either way, I'd vote for `Ember.ProxyMixin` to become public again.

**Pull request merged**
