### PR TITLE
[BUGFIX beta] Use fat arrow for nested Ember.run to maintain context

### PR DESCRIPTION
**Pull request by bagby**
Introduced in #10637.

### CODE REVIEW

**Comment by rwjblue** [comment]
:+1:

**Comment by bagby** [comment]
What the deuce? The tests "pass" in Safari, but...

screen shot 2015-04-01 at 9 46 28 pm

**Comment by rwjblue** [comment]
@bagby - This fix is correct, I submitted https://github.com/emberjs/ember.js/pull/10809 to remove Safari from the Sauce Labs runs as it has proven to be unstable.  Also, we only just this weekend enabled these automated cross browser testing so there are still some kinks...

**Comment by rwjblue** [comment]
Thank you!

**Pull request merged**
