### PR TITLE
Use routing service instead of application controller in test helpers

### PR DESCRIPTION
**Pull request by trentmwillis**
As mentioned [in this comment](https://github.com/emberjs/ember.js/pull/12310#discussion_r39123677).

### CODE REVIEW

**Comment by trentmwillis** [comment]
Looks like some versions of IE failed the Sauce tests for unrelated reasons.

**Comment by rwjblue** [comment]
Restarted Sauce Labs tests.

**Comment by trentmwillis** [comment]
@rwjblue rebased and re-pushed, all is green now

**Comment by rwjblue** [comment]
Thank you very much!

**Pull request merged**
