### PR TITLE
Clean up and light refactoring of chains.js

### PR DESCRIPTION
**Pull request by mitchlloyd**
While trying to learn more about Ember's computed property system I got sucked into doing some cleanup and refactoring of the chains.js file in ember-metal.

I know this kind of PR could potentially be obnoxious because it has lots of changes to review and doesn't really fix anything. I tried to make the commit history clean and easy to follow hoping that might help someone accept this PR.

Although this PR doesn't fix any bugs, these changes might raise the spirits of future developers that happen across this file.

### CODE REVIEW

**Comment by rwjblue** [comment]
In general this looks good, but I think that we should squash the commits after further review (by the "metal-experts").

**Comment by stefanpenner** [comment]
I am impressed with the work here

But I have some concerns: this is a tricky bit of code, we explicitly didn't dry parts of this code, due to how some runtimes decide (or decide not to) inline function calls in specific scenarios. I am hesitant to accept this PR until we have time to seriously dig into it.

This is a failing of us, we dont have a fantastic perf suite yet.

**Comment by mitchlloyd** [comment]
@stefanpenner Thanks for looking at this. Is there someone I could get in touch with to talk about the performance testing has been done in the past? Perhaps @ebryn or @krisselden? I'm foreseeing more time in my near future to work on open source. 

Ultimately I would like to keep working through the `watching` aspects of Ember and see if there is some opportunity to unify parts of the internals with Streams. I know that this stuff is sensitive and probably hasn't seen much love due to that. I'd be willing to put in some more time to see if I can measure perf changes in some way.

**Comment by mitchlloyd** [comment]
I've discovered Evil Trout's performance suite. As a first pass I ran the suite against current Canary and my refactor in Chrome, Firefox, and Safari. Everything seemed good except that `EmberObject.create` performance bombed with SpiderMonkey due to this line without a check: 

https://github.com/emberjs/ember.js/pull/10647/files#diff-ca4a7728f6d3a705f5a202589e46d85cR354

I've got a fix for that and I'm planning to create a perf test that exercises more observers and computed properties with chained dependencies.

**Comment by mmun** [comment]
@mitchlloyd I would massively prefer to separate out all syntax changes from semantic changes. @krisselden is considering dropping `watching` entirely. @wycats has a spike on unifying streams with CPs.

We'd be thrilled to have more people participating in ember-metal :) Feel free to reach out to me on IRC or google chat im.mmun@gmail.com.

**Comment by mitchlloyd** [comment]
Closed in favor of some more bite-sized PRs with plenty of review help from @mmun.

**Comment by stefanpenner** [comment]
@mitchlloyd I know both @krisselden and myself have been noodling on some really nice changes to this part of our code-base.  We are both busy, and its tricky to get the time to work on this. But maybe it is something we can work together on. The trick is finding time to even do that.

I am doing a big push on ember-cli right now, once that settles I was hoping to circle back and work on this stuff.

Maybe sometime next week we should plan for a hangout with @krisselden and see if we can make progress together.

**Comment by mitchlloyd** [comment]
@stefanpenner I would love to be involved with this. I have the time and motivation to contribute but could definitely use some guidance on the best way to make a positive impact and help get the code from here to there. 

You can reach me at mitch dot lloyd at gmail dot com.

**Pull request closed without merging**
