### PR TITLE
Expose `{{concat}}` helper publicly.

### PR DESCRIPTION
**Pull request by rwjblue**

### CODE REVIEW

**Comment by mmun** [comment]
Seems bad to call it `concat` since that's not what it is... It should be join if anything. Arguably it would take an array instead of positional args. What's the point of this PR?

**Comment by rwjblue** [comment]
> Seems bad to call it concat since that's not what it is in JS

I can remove the separator (which would make it a proper concat instead of a join + separator).

> What's the point of making this public?

It is a very commonly needed helper, that many folks end up writing themselves. With angle-bracket component invocation this is much less needed, but until angle-bracket invocation is ready to go I would like to bake this in.

One [specific example](http://emberjs.jsbin.com/rwjblue/544/edit): 

```hbs
<label for="{{elementId}}-input">{{label}}</label>
{{input id=(concat elementId '-input') value=value}}
```

Another example https://github.com/emberjs/ember.js/issues/11263:

```hbs
{{! this is deprecated }}
{{foo-bar classBinding=":truthy isStuff"}}

{{! this is how we silence the deprecation internally }}
{{foo-bar class=(-concat "truthy" (if isStuff "is-stuff") separator=" ")}}
```

As far as I can tell, it is not possible for users to satisfy this deprecation notice (I actually think we should disable the deprecation until angle bracket invocation is a bit better) without either writing your own `concat` helper or using the private one.

**Comment by mmun** [comment]
I'd rather write `(add elementId '-input')` in the first case, which is what you'd write in JS anyways.

For the second case, assuming we don't deal with the deprecation another way, I'd rather have a special `classes` helper that deals with spaces nicely. An Interpolation helper would be fine too `(interpolate "truthy ${}" (if isStuff "is-stuff"))`.

**Comment by rwjblue** [comment]
Updated to remove separator.

**Comment by rwjblue** [comment]
rebased

**Comment by mmun** [comment]
:+1:

**Pull request merged**
