### PR TITLE
[wip] failing test for GH#13494

### PR DESCRIPTION
**Pull request by GavinJoyce**
https://github.com/emberjs/ember.js/issues/13494

@miguelcobain 

http://localhost:4200/tests/index.html?hidepassed&filter=GH%2313494

screen shot 2016-07-26 at 16 24 41

### CODE REVIEW

**Comment by GavinJoyce** [comment]
Interestingly, this passes:

```js
['@test GH#13494 tagless blockless component with property binding'](assert) {
    this.registerComponent('foo-bar', {
      ComponentClass: Component.extend({ tagName: '' }),
      template: 'hello {{name}}'
    });

    this.render('{{foo-bar name=name}}', { name: 'Sarah' });

    assert.equal(this.$().text(), 'hello Sarah');

    this.runTask(() => this.rerender());

    assert.equal(this.$().text(), 'hello Sarah');

    this.runTask(() => this.context.set('name', 'Ben'));

    assert.equal(this.$().text(), 'hello Ben');

    this.runTask(() => this.rerender());

    assert.equal(this.$().text(), 'hello Ben');

    this.runTask(() => this.context.set('name', 'Sarah'));

    assert.equal(this.$().text(), 'hello Sarah');
  }
```

**Comment by GavinJoyce** [comment]
as does this:

```js
['@test GH#13494 tagless blockless component with property binding'](assert) {
    this.registerComponent('foo-bar', {
      ComponentClass: Component.extend({ tagName: '' })
    });

    this.render('hello {{name}}{{foo-bar name=name}}', { name: 'Sarah' });

    assert.equal(this.$().text(), 'hello Sarah');

    this.runTask(() => this.rerender());

    assert.equal(this.$().text(), 'hello Sarah');

    this.runTask(() => this.context.set('name', 'Ben'));

    assert.equal(this.$().text(), 'hello Ben');

    this.runTask(() => this.rerender());

    assert.equal(this.$().text(), 'hello Ben');

    this.runTask(() => this.context.set('name', 'Sarah'));

    assert.equal(this.$().text(), 'hello Sarah');
  }
```

**Comment by miguelcobain** [comment]
Looks like it is somehow related with component nesting then.

**Comment by asakusuma** [comment]
Thanks guys, I'll get a fix in ASAP

**Comment by miguelcobain** [comment]
What will happen with ember versions released with this bug? (2.6+)
We will have a bugfix release for them, correct?

**Comment by rwjblue** [comment]
I would not expect a 2.6 with the fix (it is not an LTS and is no longer the stable version).  Assuming the fix is straightforward (aka non-risky) we should get it into 2.7.

**Comment by asakusuma** [comment]
@rwjblue it's so straightforward I'm a little embarassed

**Comment by miguelcobain** [comment]
A case where the fix is straightforward, but where it isn't straightforward to reproduce the bug.

**Pull request merged**
