### PR TITLE
use `defineProperty` for property based descriptor depreciation 

### PR DESCRIPTION
**Pull request by bekzod**

### CODE REVIEW

**Review by rwjblue — COMMENTED** [review]
Hmm, I think that @krisselden did this on purpose because we only need one of the paths in `Ember.defineProperty`...

**Comment by rwjblue** [comment]
@krisselden - Can you confirm?

**Comment by krisselden** [comment]
@rwjblue confirm.

This is so the deprecation is cleanly removed with the deprecated feature when using a svelte build.

**Comment by bekzod** [comment]
cool

**Pull request closed without merging**
