### PR TITLE
WIP - [Enhancement] Sauce labs testing for iOS 8.2, 7.0 and Android 5.1

### PR DESCRIPTION
**Pull request by mike-north**
This PR introduces new sauce labs testing environments. The goal is to have the following tested as part of CI:

| Launcher in place | Device | OS Version | Architecture | Notes |
| --- | --- | --- | --- | --- |
| ✔ | iPhone 6 | 8.2 | 64 bit |  |
|  | iPhone 4s | 7.0 | 32 bit | iPhone 5c may be a faster 32 bit device |
| ✔ | Android Simulator | 5.1 | 64 bit |  |

This should help us catch some mobile-specific bugs a little earlier

### CODE REVIEW

**Comment by truenorth** [comment]
Oh dear 
screen shot 2015-04-29 at 4 29 21 pm

**Comment by stefanpenner** [comment]
thats an amazing error

**Comment by rwjblue** [comment]
I'm not 100% sure that it is related, but the test that is shown behind that error happens to be calling Object.create which (if confirmed) could be another case of the Safari 32bit bug we've been fighting (seemingly forever).

**Comment by truenorth** [comment]
@rwjblue Not easy to tell from the screenshot, but this was the iPhone simulator, simulating an iPhone 6.

**Comment by rwjblue** [comment]
Ahh, gotcha. I must have gotten confused andI thought it was the 32bit 4s from the checklist in the PR description.

**Comment by stefanpenner** [comment]
@truenorth are you interested in pushing this forward still? Todays conversation implied no.

Let me know, if you aren't interested we should just close this.

**Comment by rwjblue** [comment]
Closing for now, will reopen if you want to jump back into it...

**Comment by mike-north** [comment]
I have a few things ahead of this on my todo list, but I'll jump back in and reopen this soon

**Pull request closed without merging**
