### PR TITLE
[FEATURE wai-aria-attribute-support] Modifies the aria_role_support Mixin to support any WAI-ARIA property that starts with 'aria-'

### PR DESCRIPTION
**Pull request by hleimig**
Implements the feature https://github.com/emberjs/ember.js/issues/13224

With this modification, any property defined in Views or Components that starts with 'aria-' will be rendered into the View/Component's DOM, improving accessibility in Ember.js apps.

### CODE REVIEW

**Comment by sundered** [comment]
I'm not sure if `Object.keys` is the best way to access the properties of a View/Component. I tried to use the `attrs` property, but it is `null` while the Mixin is being created.

**Comment by mixonic** [comment]
@sundered we would want to see benchmarks that ensure this does not regress performance. Iterating the keys of every component during creation is likely going to give us a hit. Creating an observer for each binding will likely hit performance.

Generally I believe we're designing glimmer component with the accessibility use-cases in mind and will have a nicer solution there.

However there needs to be more investigation before landing this.

**Comment by sundered** [comment]
Ok, I'll try to improve this and get some benchmarks.

**Comment by sundered** [comment]
So, I had an ideia. What if the user could set a property called `aria` with an object that contained the aria- values and we used the `computed` set method to bind the variables. Something like this

```javascript
ariaProperties: {
    label: "A brief description",
    aria-disabled: false
}
```
```handlebar
{{foo-bar aria=ariaProperties}}
```

**Comment by rwjblue** [comment]
I'm not sure how I feel about adding a new API here since we intend for angle bracket components to automatically place any passed in attributes on the top level element of the component.  When that lands, no custom/special support will be needed to allow specifying of these properties.  

Example without needing to define `app/components/foo-bar.js`:

```hbs
{{! app/templates/components/foo-bar.hbs }}
<div class="some-special-thing"></div>
```

```hbs
{{! Invocation syntax }}
<foo-bar aria-label="foo" data-bar="blammo">
</foo-bar>
```

```html
<!-- rendered HTML -->
<div class="some-special-thing" aria-label="foo" data-bar="blammo"></div>
```

---

Adding any additional logic to curly component instantiation at this point is fairly risky due to performance concerns....

**Comment by rwjblue** [comment]
Closing...

See detailed comment in https://github.com/emberjs/ember.js/issues/13224#issuecomment-213861097.

**Comment by rwjblue** [comment]
And thank you very much for tackling this! I know it seems like a somewhat arbitrary thing, but we definitely need to put these sorts of conversations about new public API's through the RFC process. We have learned quite a bit from our users since starting the process, and I suspect this will be another example of that.

**Pull request closed without merging**
