### PR TITLE
Spelling

### PR DESCRIPTION
**Pull request by jsoref**
Generated by https://github.com/jsoref/spelling `f`; to maintain your repo, please consider `fchurn`

### CODE REVIEW

**Comment by locks** [comment]
Can you please squash the commits?

**Comment by jsoref** [comment]
If you're ok with the series of changes, sure. Right now, Travis reports one failure (which I can't understand). I don't like squashing until things are acceptable, otherwise, it's very hard to fix things.

**Comment by locks** [comment]
> If you're ok with the series of changes, sure.

Yes, that's what I meant with the request.

> Right now, Travis reports one failure (which I can't understand).

Unfortunately Edge 15 on saucelabs has been failing for a while :\ We haven't gotten down to the core of the problem.

**Comment by jsoref** [comment]
Ok, probably this evening after work.

**Comment by locks** [comment]
Appreciated 😄  Thanks for the work so far!

**Comment by jsoref** [comment]
Rebased. Please note that there's a cost to periodic rebases...

**Comment by mmun** [comment]
Hi @jsoref. Sorry for letting this sit so long. We'll look into running your spellchecking tool ourselves :+1:

**Pull request closed without merging**
