### PR TITLE
[Chore]: Add integration test for accessing a property during init

### LINKED ISSUE #19003: belongsTo relationship causes "used previously in the same computation" error
First posted in https://github.com/emberjs/data/issues/7196 but was referred here

When an API payload is received with an association not already set on a Ember Data model, the following error is seen:

```
Error: Assertion Failed: You attempted to update `content` on `<(unknown):ember173>`, 
but it had already been used previously in the same computation.  Attempting to update 
a value after using it in a computation can cause logical errors, infinite 
revalidation bugs, and performance issues, and is not supported.

`content` was first used:

- While rendering:
  
  application
    foo
      this.dataLength

Stack trace for the update:
    at dirtyTagFor (validator.js:514)
    at markObjectAsDirty (index.js:637)
    at notifyPropertyChange (index.js:675)
    at set (index.js:1622)
    at Proxy.set (observable.js:176)
    at InternalModel._updatePromiseProxyFor (-private.js:4379)
    at InternalModel.getBelongsTo (-private.js:4272)
```

This happens when the model is being consumed in a component template (via a getter) that depends on `post.user`

### Reproduction

https://github.com/wongpeiyi/data-computation

### Description

- When creating and saving a Post, no User association is set yet
- The API (mirage) sets a User and responds with a payload
- Ember Data updates the Post model
- Because the model is being consumed by the component getter that depends on `filterBy('user.id')`, the error is thrown

The error is not thrown when:
- Not filtering (or not consuming the user association)
- Using `{{@data.length}}` in the template instead of the component getter
- Using a getter on the controller without a component

This seems like a use case that should "just work"

### Versions

```cli
yarn list v1.19.2
warning Filtering by arguments is deprecated. Please use the pattern option instead.
└─ ember-source@3.18.1
✨  Done in 0.72s.
yarn list v1.19.2
warning Filtering by arguments is deprecated. Please use the pattern option instead.
└─ ember-cli@3.18.0
✨  Done in 0.65s.
yarn list v1.19.2
├─ @ember-data/adapter@3.18.0
├─ @ember-data/canary-features@3.18.0
├─ @ember-data/debug@3.18.0
├─ @ember-data/model@3.18.0
├─ @ember-data/private-build-infra@3.18.0
├─ @ember-data/record-data@3.18.0
├─ @ember-data/rfc395-data@0.0.4
├─ @ember-data/serializer@3.18.0
├─ @ember-data/store@3.18.0
├─ babel-plugin-ember-data-packages-polyfill@0.1.2
└─ ember-data@3.18.0
✨  Done in 0.63s.
```

### PR DESCRIPTION
**Pull request by snewcomer**
Screen Shot 2020-06-20 at 7 37 39 AM

close https://github.com/emberjs/ember.js/issues/19003

Fixed by #19023

### CODE REVIEW

**Comment by snewcomer** [comment]
Failing test - https://travis-ci.org/github/emberjs/ember.js/jobs/700343930
Passing test - recent CI run.

@pzuraq If this integration test for #19023 is useful, this PR is ready for review!

**Comment by rwjblue** [comment]
Happy to land this, could you squash down the commits for us?

**Comment by snewcomer** [comment]
done!

**Review by rwjblue — APPROVED** [review]

**Comment by rwjblue** [comment]
Awesome, thank you!

**Pull request merged**
