### PR TITLE
[BUGFIX] Reverts the naming of setClassicDecorator externally

### PR DESCRIPTION
**Pull request by pzuraq**
The rename was intended to be internal only, the external API is
already in use so we should keep it as is. Name is unfortunate, but
it kind of is either way.

### CODE REVIEW

**Review by josemarluedke — APPROVED** [review]
🎉

**Review by buschtoens — APPROVED** [review]

**Comment by buschtoens** [comment]
[ember-concurrency](https://github.com/machty/ember-concurrency/blob/f1649147285cdcc382289dc0cffe945f242b731c/addon/index.js#L22) is currently broken in Ember Octane because of this.

Thanks for fixing it so quickly! :)

**Comment by buschtoens** [comment]
I currently do this to fix it:

```js
// @see https://github.com/emberjs/ember.js/pull/17833
if (!Ember._setComputedDecorator) {
  Ember._setComputedDecorator = Ember._setClassicDecorator;
}
```

```js
// ember-cli-build.js
app.import('vendor/fix-decorator.js');
```

**Comment by igorT** [comment]
This broke Ember Data as well

**Comment by rwjblue** [comment]
Just pushed an additional commit that deprecates instead.

**Pull request merged**
