### PR TITLE
[BUGFIX beta] Ensure compat helpers calling options.fn work.

### LINKED ISSUE #270: Helper syntax documentation/clarification
Prior to HTMLbars things like this would work for defining helpers (this particular example in ember-cli):

```js
import config from 'ui/config/environment';

export function hasFeature(feature) {
	return (window[config.APP.FEATURES_KEY] || {})[feature] === true;
}

export default function (feature, options) {
  return hasFeature(feature) ? options.fn(this) : null;
}
```

Is there documentation somewhere or any discussion as to how to translate this to the new syntax? I was unable to find a clear path.

Happy to contribute docs if there is an answer somewhere and they haven't been written up yet.

Thanks!

### PR DESCRIPTION
**Pull request by rwjblue**
Fixes https://github.com/tildeio/htmlbars/issues/270.

### CODE REVIEW

**Comment by rwjblue** [comment]
Updated per discussion with @mmun.

**Comment by thejchap** [comment]
@rwjblue Should `options.inverse()` be included in this as well?

**Comment by ritesh83** [comment]
We have a custom handlerbars helper.
It works fine with ember 1.8 but not with 1.10

In the initializer, we have:        
        
        app.inject('helper', 'aclService', 'service:acl');

and in our helper:
        
        export default function(value, options) {
            var userAcl = this.get('aclService');   
    
            if(userAcl.get('isAdmin')) {
                return value.fn(this);
            } else {
                return value.inverse(this);  
            }
        }

The 'aclService' is now undefined in ember 1.10 (injections not working on helpers) and also the options.inverse was a function before but now it is an object (not callable).

Any suggestions on how to make it work in ember 1.10?

**Comment by pixelhandler** [comment]
@rwjblue this seems related https://github.com/emberjs/ember.js/issues/10812 correct?

**Pull request merged**
