### PR TITLE
[DOC Release] Mark Route.replaceWith() as public

### PR DESCRIPTION
**Pull request by joeruello**

### CODE REVIEW

**Comment by rwjblue** [comment]
I think this is correct, but I'm not 100% sure on this one. I'd like someone else to confirm...

**Comment by pixelhandler** [comment]
@rwjblue looking at the documentation example in the source for `.replaceWith()` It makes sense to have this as public API, the alternative is `this.transitionTo` which I think does not "replace the current history entry instead of adding a new one" correct?

**Comment by joeruello** [comment]
@rwjblue any word of this? Came up with a new team member today, poor guy was trying to hack browser history directly.

**Comment by rwjblue** [comment]
> poor guy was trying to hack browser history directly

yeah, that will likely lead to bad times

---

@machty - You are likely the most familiar here, do you have any objection to making `Route#replaceWith` public?

**Comment by joeruello** [comment]
@machty @rwjblue While you've having a look, #11585 and #11586 are still pending another set of eyes as well.

**Pull request merged**
