### PR TITLE
[DOC Release] Mark Enumerable.everyBy() as public

### PR DESCRIPTION
**Pull request by HeroicEric**

### CODE REVIEW

**Comment by stefanpenner** [comment]
instead a massive amount of PR, can we instead open a single issue or RFC issue with a long checklist?

**Comment by rwjblue** [comment]
@stefanpenner - I did request individual PR's per method when folks have asked (just as background on why we have so many small ones). I'm not opposed to alternative methods, but it seems that we should decide fairly quickly per "thing" and a large checklist issue can only be updated by us or the original poster.

**Comment by stefanpenner** [comment]
@rwjblue multiple PR seems copious amounts of work for all involved, Why wasn't just a single issue + checklist recommended?

**Comment by rwjblue** [comment]
>  it seems that we should decide fairly quickly per "thing" and a large checklist issue can only be updated by us or the original poster

**Comment by stefanpenner** [comment]
Fairly quickly appears to not have happened? Of should we expect to see the rest resolved in a timely manner

**Comment by rwjblue** [comment]
The ones that are pending are the Ember.Enumerable ones.  Many other PR's were merged in a very short manner.  I am not sure of the path for Enumerable docs...

**Comment by stefanpenner** [comment]
Sounds good. I've added it to today's meeting agenda

**Pull request merged**
