### PR TITLE
[DOC beta] Issue #12428 Add API Docs for deprecation and warning handlers

### PR DESCRIPTION
**Pull request by toddjordan**
Added api documentation for Ember.Debug.  Using examples from the 2.1 beta blog post.

See issue https://github.com/emberjs/ember.js/issues/12428

### CODE REVIEW

**Comment by rwjblue** [comment]
Looks great!  Can you prefix the commit with [DOC beta] (the PR title is already prefixed properly)? Can you also attach a screenshot of these two sections displayed in the running website?

**Comment by toddjordan** [comment]
Sure. I'll work on it when I get back online this afternoon.

**Comment by rwjblue** [comment]
Sorry for the annoyance, I'm just going to merge and pull down locally for testing with other changes I'm working on...

**Comment by toddjordan** [comment]
Not an annoyance. Happy to help!

**Pull request merged**
