### PR TITLE
Add cross browser tests.

### PR DESCRIPTION
**Pull request by rwjblue**
Need to add the following back into the `launch_in_ci` as soon as they are passing:
- SL_Firefox_Current
- SL_IE_8
- SL_Safari_Last
- SL_Safari_Current (doesn't want to connect to `localhost` for some reason)

### CODE REVIEW

**Comment by rwjblue** [comment]
These pass just fine locally (when running `testem ci` or the `bin/run-sauce-tests.js` script).  On Travis they are not even kicking off a Sauce job, and there is no output at all from `testem ci`.

I've tried many combinations here, I think I need to call in the expert.

@johanneswuerbach  - Would you mind taking a look?

**Comment by johanneswuerbach** [comment]
Sure, I'll take a look later today.

**Comment by ef4** [comment]
:clap:

**Comment by johanneswuerbach** [comment]
@rwjblue Safari 8 should work, when you choose a different port. I used [7000](https://github.com/tildeio/htmlbars/blob/master/bin/run-tests.js#L95) on htmlbars, dunno what is broken with the default one.

**Comment by rwjblue** [comment]
Thank you! Updated in https://github.com/emberjs/ember.js/pull/10787

**Pull request merged**
