### PR TITLE
Don't spin up extra run-loops when bubbling events.  Fixes #11540

### LINKED ISSUE #11540: Firing run loop on mousemove unnecessary?
Looks like a new run loop is kicked off [every time the mouse moves](https://github.com/emberjs/ember.js/blob/master/packages/ember-views/lib/system/event_dispatcher.js#L56).

Is this really necessary? @stefanpenner suggested that we might instead have components opt-in to needing this, instead of assuming we need a run loop on mouse movement.

### PR DESCRIPTION
**Pull request by runspired**
Fixes #11540

### CODE REVIEW

**Comment by rwjblue** [comment]
Seems good to me, @stefanpenner r?

**Comment by stefanpenner** [comment]
I plan to review in the morning. Unless there is s big rush tonight. If so I can gladly look into shortly

**Comment by rwjblue** [comment]
No huge rush.  Can go into `[BUGFIX beta]` tomorrow (for 2.1).

**Comment by rwjblue** [comment]
I kicked sauce labs.

@stefanpenner - Whenever you have a chance, I'd love your :+1: / :-1: here...

**Comment by rwjblue** [comment]
@stefanpenner - r?

**Comment by rwjblue** [comment]
@stefanpenner - :+1:  / :-1:?

**Comment by stefanpenner** [comment]
This fixes up the immediate concern so :+1: 

This doesn't prevent bubbling from spawning many loops per user action.

For example:

given the following hierarchy `root < a < b  < c`

if a and b have `click` handlers, and `c` returns `true`, `a` will gets its own run-loop. This isn't desirable. 

@runspired I believe due to how we currently integrate with jQuery prevent ^ in the same micro-task is tricky/not possible. To sort this out, I suspect taking your approach re: home-grown event-dispatcher is key.

**Comment by asakusuma** [comment]
Thanks @runspired!

**Pull request merged**
