### PR TITLE
[BUGFIX release-2-0] Upgrade htmlbars to 0.14.14

### PR DESCRIPTION
**Pull request by Dhaulagiri**
Brings the input fix from https://github.com/emberjs/ember.js/pull/12877 to those still on 2.0

### CODE REVIEW

**Comment by rwjblue** [comment]
@Dhaulagiri - The failures seem to be JSHint related (most likely improvements in JSHint parsing engine now catches things that were previously skipped).  Can you add a second commit fixing them?

**Comment by Dhaulagiri** [comment]
@rwjblue I fixed the jshint errors but there are still quite a few other failures.  It's probably not worth spinning tires on this too much since we are just trying to back port this fix.

**Comment by rwjblue** [comment]
Hmm, I thought when I looked that there were only the JSHint errors.  I'll double check again after Travis is done with this run...

**Comment by Dhaulagiri** [comment]
This was not as easy as I hoped so I think our effort is better spent getting our app off 2.0

**Pull request closed without merging**
