### PR TITLE
[BUGFIX release] Deprecate Controller#needs

### LINKED ISSUE #11683: ensure needs is correctly deprecated
https://github.com/emberjs/ember.js/blob/49d58530527c9025b4bafe4f937b0c78cfe3818e/packages/ember-application/lib/ext/controller.js#L41

### PR DESCRIPTION
**Pull request by ghost**
Resolves #11683

I also changed the wording of the deprecation message for `controllerFor`.

### CODE REVIEW

**Comment by rwjblue** [comment]
Thanks!

**Comment by novtor** [comment]
When replacing needs by Ember.inject.controller as stated in documentation, the ReferenceError occurs:

Uncaught ReferenceError: XXXController #needs does not include `YYYController`. To access the YYYController controller from XXXController , XXXController  should have a `needs` property that is an array of the controllers it has access to.

**Comment by martndemus** [comment]
Try `this.get('yyy')` instead of `this.get('controllers.yyy')`

**Comment by novtor** [comment]
Thank you @martndemus, I was using Ember.computed.alias('controllers.ControllerXXX.somefield') and in templates {{controllers.ControllerXXX.somefield}}

**Comment by martndemus** [comment]
Your welcome :smiley:

**Pull request merged**
