### PR TITLE
[BUGFIX beta] deprecate this.resource() in Router.map()

### PR DESCRIPTION
**Pull request by jayphelps**
Use `this.route('name', { resetNamespace: true })` instead.

This has been talked about for months, but hadn't seen a PR so figured 2.0 beta it was time.

Back in March, `this.resource` was [removed](https://github.com/emberjs/guides/commit/fb7f74b507972c7e123ec516a9ccddcd8e8bf8ae) from the guides and released [as 1.11.0](http://guides.emberjs.com/v1.11.0/routing/defining-your-routes/#toc_nested-routes).
- [x] Deprecate `this.resource()`
- [x] Add API docs for `resetNamespace`
- [x] Add Guide docs for `resetNamespace` https://github.com/emberjs/guides/pull/373

### CODE REVIEW

**Comment by jayphelps** [comment]
I assume the prod build failed because of deprecation stripping in env=prod. Not sure how to counter this?

```
Test failed: Ember Router DSL: should fail when using a reserved route name
    Failed assertion: Expected 12 assertions, but 8 were run
```

**Comment by jayphelps** [comment]
All green.

**Comment by workmanw** [comment]
I'm just curious, what's the reason for this? If `this.resource` is the same as `this.route('name', { resetNamespace: true })`, why bother?

**Comment by jayphelps** [comment]
@workmanw core team has their own rationale I'm sure, but IMO it's always been a **huge** confusion point for new-comers. Like, almost unanimously everyone is confused when I see them learning ember. Since you can nest `this.route` now, having the explicit `resetNamespace: true` makes it very clear *what you intended* vs. "wtf why isn't ember finding my route/model/template/etc".

**Comment by workmanw** [comment]
Gotcha. I hadn't really heard anything about this change and I was curious if there was some other plan for `this.route` or `this.resource`. 

I often see changes like this and am always curious about the rationale. Not questioning it. Just trying to better understand the motivation for the change.

**Comment by jayphelps** [comment]
@workmanw this particular case was definitely more informally discussed on IRC/slack/discuss.emberjs.com/etc. It's possible the core team has collectively not agreed to move forward on this, I just happened to be refactoring code and had the cycles to PR.

**Comment by rwjblue** [comment]
I am in favor of this PR, but there are a few things that will still be needed:

* PR updating guides
* Adding API documentation for `resetNamespace`

I'll confirm with others, but I believe that this is exactly the direction we have been intending to go...

**Comment by jayphelps** [comment]
@rwjblue happy to do both once someone confirms this/they will be merged. Thanks!

**Comment by jmurphyau** [comment]
I'm wondering if somehow, while the Router.map is being discussed, I can sneak in and ask for an opinion on https://github.com/emberjs/ember.js/pull/11308 ... 

Might be something for another time - needing more discussion etc - but if not then might be a good time to get two changes in at once or combine it into one PR or something? 

Given that resource is to be removed it might mean the idea behind my PR should be implemented differently

**Comment by jayphelps** [comment]
@jmurphyau IMO definitely a different discussion, although I do like the idea of your PR at first glance!

**Comment by jmurphyau** [comment]
👍 sweet - sounds good.. Had no activity on it since I opened it and seen this PR as a chance to steal some attention ;)

BTW +1 to route/resource being a pain point.. It was for me.. A `resetNamespace` option is a much better implementation.

**Comment by jayphelps** [comment]
Can someone kick saucelabs for me? I believe this is green and all requests by @rwjblue for docs should be ready, but IE test timed out
image

**Comment by stefanpenner** [comment]
kicked

**Comment by rwjblue** [comment]
Thanks @jayphelps!

**Comment by tim-evans** [comment]
As a follow up, could we have an ember-watson task for this?

**Comment by rwjblue** [comment]
@tim-evans - Seems good to me, would you mind making an issue over in ember-watson repo explaining what needs to be done?

**Pull request merged**
