### PR TITLE
[CLEANUP beta] Remove deprecate anyBy, everyProperty and some of enumerable

### PR DESCRIPTION
**Pull request by ghost**
They have been deprecated and were just aliases of existing better named methods.

### CODE REVIEW

**Comment by rwjblue** [comment]
Deprecations added in stable branch (for release in 1.13.5) here: https://github.com/emberjs/ember.js/pull/11774/files

**Comment by rwjblue** [comment]
Can you confirm all the deprecations listed in that PR are handled here?

**Comment by martndemus** [comment]
The other deprecated enumerable methods listed in that PR were already removed in other PRs

See:
- #11648 `mapProperty`
- #11611 `filterProperrty`
- #11706 `rejectProperty`
- #11700 `findProperty`
- #11707 `everyBy`
- #11690 `someProperty`

**Comment by rwjblue** [comment]
Awesome, thanks for confirming!

**Pull request merged**
