### PR TITLE
correct `undefined` checks

### PR DESCRIPTION
**Pull request by bekzod**

### CODE REVIEW

**Comment by SpikedKira** [comment]
My tests show `typeof x === 'undefined'` are slightly faster than `x === undefined`.
Did you see some different performance numbers?

**Comment by bekzod** [comment]
I think it is not https://jsperf.com/typeof-vs-undefined-check/12 also babel transpiles `x === undefined` to `x === void 0` which is fastest case

**Comment by SpikedKira** [comment]
https://jsperf.com/spikedkira-undefined

**Comment by bekzod** [comment]
@SpikedKira it is still faster :P

**Comment by SpikedKira** [comment]
@bekzod interesting, and possible.  My phone shows faster for undefined but chrome and firefox both are faster at typeof.  I wonder if my phone doesn't have the new interpreter o.O

**Comment by stefanpenner** [comment]
@bekzod / @SpikedKira in general, (as long as there isn't a major issue) the more concise the expression the more comfortable we should be taking that direction.

For example `typeof key === 'undefined'` vs `key === undefined` feels like they should eventually converge to something similar. But `key === undefined` feels more explicit, so I suspect our preference should be `key === undefined` (as long as there isn't a HUGE difference).

**Pull request merged**
