### PR TITLE
Cleanup ChainNode

### PR DESCRIPTION
**Pull request by bekzod**
splitting `path` once and using `array` instead of `string` for `tail` , which should perform better and looks much cleaner

### CODE REVIEW

**Comment by krisselden** [comment]
Looks good, did you measure it?

**Comment by bekzod** [comment]
will post measures soon

**Comment by bekzod** [comment]
benchmark: https://cl.ly/1R033K462y0C/results.pdf looks like makes tiny bit of difference :P

**Comment by mmun** [comment]
@bekzod The PDF only includes the ember version, but not the application code that was tested. What  were you benchmarking exactly?

**Comment by mmun** [comment]
> looks like makes tiny bit of difference :P

You should be careful when you're interpreting the chart. The last page reads:
 
> If the true location shift were equal to 0, there is a %75.58 chance of observing these samples:

This means there is a 75% chance that your code had performance impact at all (neither slower or faster)

**Comment by bekzod** [comment]
> You should be careful when you're interpreting the chart. The last page reads:
> This means there is a 75% chance that your code had performance impact at all (neither slower or faster)
ooh ok, even if it makes no difference it at least does not regress :P and chops few lines of code

**Comment by mmun** [comment]
BTW, I like this cleanup. It inspires me to look around and see where we could be sharing `.split('.')`s and avoiding `.join('.')`s. For example,

https://github.com/emberjs/ember.js/blob/706166a3fa92707c40374a4614bb76aad0764810/packages/ember-metal/lib/property_set.js#L118

**Comment by bekzod** [comment]
nice, I had similiar approach here https://github.com/emberjs/ember.js/pull/15532 need to rebase and benchmark again :)

**Comment by mmun** [comment]
I chatted with bekzod in #ember-dev on Slack and confirmed he was doing all the benchmarking steps correctly. He also shared his benchmarks with me in a zip. Here they all are together:

https://cl.ly/0o001L310624/bench.zip

**Pull request merged**
