### PR TITLE
[BUGFIX release] Fix an issue with bindings inside of a yielded template when the yield helper is nested inside of another view

### PR DESCRIPTION
**Pull request by ebryn**
@mmun @rwjblue 

JSBin showing working 1.9 behavior: http://emberjs.jsbin.com/kejicegowi/1/edit
JSBin showing broken 1.10 behavior: http://emberjs.jsbin.com/pugeweloke/1/edit

### CODE REVIEW

**Comment by ebryn** [comment]
This will likely fix https://github.com/emberjs/ember.js/issues/10402

**Comment by ebryn** [comment]
And perhaps https://github.com/emberjs/ember.js/issues/10401 as well

**Comment by rwjblue** [comment]
Cherry-picked into beta and release channels.

**Comment by ebryn** [comment]
It does not appear this fixes #10401

**Comment by workmanw** [comment]
I know it's a long shot ... but is there any work around for this? It's sadly keeping me from upgrading to 1.10.

**Comment by mmun** [comment]
You can use the #stable branch

**Comment by workmanw** [comment]
OH I didn't even know you guys maintained that. Sounds like it's the last release + any regression fixes?

**Comment by rwjblue** [comment]
@workmanw - If you are using bower you can add the following for Ember to get the latest build of the release channel (which is the stable branch):

```
"ember": "components/ember#release",
```

**Comment by rwjblue** [comment]
You can also download it from:

http://emberjs.com/builds/#/release

**Comment by workmanw** [comment]
Man that's so awesome. Thanks a lot! :heart:

**Comment by mmun** [comment]
Yay <3 Please report any other upgrade problems!

**Comment by workmanw** [comment]
@mmun Will do! Virtually all of our issues with 1.10 and HTMLBars were around us forgetting to close tags in our templates.

**Pull request merged**
