### PR TITLE
[DOC] Add router.js to yuidoc.json

### PR DESCRIPTION
**Pull request by Gaurav0**
This is for issue https://github.com/emberjs/ember.js/issues/12142

### CODE REVIEW

**Comment by rwjblue** [comment]
Please update the locked SHA in `bower.json` to use `04b27c911995902b022966f4d29d8686ba7d847c` (which includes your changes from https://github.com/tildeio/router.js/pull/169).

**Comment by rwjblue** [comment]
For others, the compare view: https://github.com/tildeio/router.js/compare/ed45bc5c5e055af0ab875ef2c52feda792ee23e4...04b27c911995902b022966f4d29d8686ba7d847c

**Comment by Gaurav0** [comment]
@rwjblue Updated. Don't know what is wrong with sauce test.

**Comment by stefanpenner** [comment]
sgtm. Do the output docs feel/look reasonable ?

**Comment by rwjblue** [comment]
@stefanpenner - Yes, this is exactly my concern.

I think we need to actually boot up the website and see what it looks like with these changes (there are docs [here](https://github.com/emberjs/website#api-documentation) that describe how to preview local changes).  My hunch is that there are other objects (like Transition itself) that are incorrectly documented, but this is still likely a net positive assuming we can confirm that it all works well.

**Comment by Gaurav0** [comment]
Some screenshots to satisfy your preview concerns. I am in no way qualified to determine if they "feel/look reasonable".

screen shot 2015-08-27 at 4 01 49 am

screen shot 2015-08-27 at 4 02 23 am

**Comment by nahtnam** [comment]
:+1:

**Comment by Gaurav0** [comment]
@rwjblue I excluded all of router.js from the yuidoc.json except for transition.js as discussed in #documentation on slack. Does this work for you?

**Comment by acorncom** [comment]
@Gaurav0 there's a failing test here, not sure if it's related to what you're doing or not ...

**Comment by Gaurav0** [comment]
@acorncom I doubt it, since I just edited yuidoc.json But I can't rerun it.

**Comment by Gaurav0** [comment]
@rwjblue Please review.

**Comment by wycats** [comment]
I see no reason not to merge this.

**Comment by Gaurav0** [comment]
@wycats Thank you.

**Pull request merged**
