### PR TITLE
I must have broken stuff, anyways restoring...

### PR DESCRIPTION
**Pull request by stefanpenner**
I must have forced push something :( going for PR and travis and branch to see what i stomped on.

### CODE REVIEW

**Comment by stefanpenner** [comment]
i think thats it

cc @machty / @cibernox

**Comment by stefanpenner** [comment]
fixing test shortly

**Comment by stefanpenner** [comment]
errors all appear intermittent npm / npm-registry related, rerunning affected tests.

**Comment by machty** [comment]
I have concerns that this push won't actually return master to a fast-fowardable form for anyone with PRs/branches/etc prior to the force push that messed things up, but that said, I do not fully appreciate how difficult/possible it is to correct history in such a way.

**Comment by stefanpenner** [comment]
> I have concerns that this push won't actually return master to a fast-fowardable form for anyone with PRs/branches/etc prior to the force push that messed things up,

As discussed in chat, commits/prs/clones prior to the incident are unaffected. The only window is clones / rebases in the last 18 hours. 

@cibernox and interim commit isn't available, no-one appears to have it local, and the branch on GH appears to be gone. So I had to reconstruct it myself, without this commit its impractical

**Comment by machty** [comment]
OK, seems fine to push.

**Pull request merged**
