### PR TITLE
make `new EmberObject(…)` work

### PR DESCRIPTION
**Pull request by stefanpenner**
- [x] pending removing of stuff like `Ember.Set`
- [ ] get review @wycats r?

### CODE REVIEW

**Comment by pixelhandler** [comment]
@stefanpenner I'm really happy to see this spike thanks! would love to see constructors work more like vanilla javascript. I've found that at times I'd like to protect attributes during the instantiation and doing that with re-defining `create` is a challenge. Does making `new EmberObject` work include support for application developers defining more traditional constructor functions ?

**Comment by stefanpenner** [comment]
> work include support for application developers defining more traditional constructor functions ?

Yes, but its not going to be part of the public API until we can confirm parts of the es7 spec (property initializers etc) work correctly.

**Comment by rwjblue** [comment]
I'm :+1:, I'd like to land this soon for 2.0.0-beta.5.

@stefanpenner - Are we still waiting on review by @wycats?

**Comment by stefanpenner** [comment]
> @stefanpenner - Are we still waiting on review by @wycats?

i am +1, would love a @wycats / @tomdale  +1 though. Although I would be surprised if its a -1

**Comment by mixonic** [comment]
> The integration story to allow backwards compat is mostly straightforward, but this wont become part of the public API until we have decided how to message and document the transition.

I'm +1 but I would really enjoy getting the context you mention here. I remain uncertain what the goal you are aiming for is and how this helps.

**Comment by stefanpenner** [comment]
The goal is to improve alignment with the languages own object system.

**Comment by krisselden** [comment]
@mixonic Also, this allows you to look at and modify props before accessing them or assigning them to `this` which allows us to deal with a class of deoptimizations we cannot now deal with.

**Pull request merged**
