### PR TITLE
Add nested link-to test.

### PR DESCRIPTION
**Pull request by rwjblue**
This does not seem to trigger the issue in https://github.com/emberjs/ember.js/issues/10366 and https://github.com/emberjs/ember.js/issues/10662, though I cannot see a major difference between the test here and the failing JSBin: http://emberjs.jsbin.com/pejavu/4/edit?html,js,output.

I will continue to bang on it...

### CODE REVIEW

**Comment by rwjblue** [comment]
@mixonic - I feel that I am getting trolled (this should not be passing?!?!!?), but I cannot for the life of me see what is different...

**Comment by mixonic** [comment]
@rwjblue I have something similar I believe should cause it to trigger: https://github.com/emberjs/ember.js/compare/beta...mixonic:argh But no failure. And this is against beta.

**Comment by rwjblue** [comment]
Argh!! I'll continue digging in the morning. With hopefully a fresh mind.

**Comment by rwjblue** [comment]
Updated router.js to ensure that a no-op transition returns the currently active transition (was previously returning a new transition which messed up the transition state classes).

Example JSBin: http://emberjs.jsbin.com/yopexu/1/edit?html,js,output

**Pull request merged**
