### PR TITLE
Deprecate tryFinally and tryCatchFinally

### PR DESCRIPTION
**Pull request by wagenet**
Still needs deprecation link

### CODE REVIEW

**Comment by stefanpenner** [comment]
we also use this internally to mitigate that old safari bug.

**Comment by wagenet** [comment]
@stefanpenner I don't think we can remove internal usages until 2.0 since it would mean dropping browser support. The number of desktop user affected is very small since it is present in early Safari 6.0 but is fixed by 6.0.5. However, all iOS 6 users are susceptible. I've tested on both 6.0 and 6.1. According to http://david-smith.org/iosversionstats/, 5% of users still use iOS 6.x. While I think we can make a good case for dropping this is 2.0, I don't think we can drop from 1.x.

**Comment by stefanpenner** [comment]
> While I think we can make a good case for dropping this is 2.0, I don't think we can drop from 1.x.

sounds good.

**Comment by wagenet** [comment]
@rwjblue Did we want a deprecation link for this?

**Pull request merged**
