### PR TITLE
Add failing test for observer computed reads 2.16 regression

### PR DESCRIPTION
**Pull request by ilucin**
Adds failing test for #15836

### CODE REVIEW

**Comment by bekzod** [comment]
this could be closed since fix already merged

**Comment by rwjblue** [comment]
Thanks @bekzod! The failing test here was cherry-picked into https://github.com/emberjs/ember.js/pull/15849.

**Comment by rwjblue** [comment]
Bringing this back to ensure that we incorporate it into the root cause fix (see https://github.com/emberjs/ember.js/pull/15849#issuecomment-344371913)

**Comment by mmun** [comment]
This test was merged in https://github.com/emberjs/ember.js/pull/15849.
This (second) fix was merged in https://github.com/emberjs/ember.js/pull/15982.

**Pull request closed without merging**
