### PR TITLE
[BUGFIX beta] Clean up link-to classes

### PR DESCRIPTION
**Pull request by Dhaulagiri**
Follow-on from #12344:
- Removes unnecessary massaging of activeClass/disableClass/loadingClass attrs
- Add tests

### CODE REVIEW

**Comment by Dhaulagiri** [comment]
Seems like the sauce failure is happening on master currently, so I don't think that failure is related to this change

**Comment by rwjblue** [comment]
Restarted

**Comment by Dhaulagiri** [comment]
:+1: thanks @rwjblue

**Comment by rwjblue** [comment]
No, thank you!

**Pull request merged**
