### PR TITLE
Revert "Remove dead view code"

### PR DESCRIPTION
**Pull request by trek**
Reverts emberjs/ember.js#10412

### CODE REVIEW

**Comment by rwjblue** [comment]
I'm ok with it, but would like to understand the reason for reverting.

**Comment by ebryn** [comment]
yes, please do explain... it must be for `_classStringForProperty`?

**Comment by trek** [comment]
These bits were used by Ember Inspector and canary was spitting errors for people. @teddyzeenny has more info on #10412

**Comment by rwjblue** [comment]
Pulled into beta branch, should be included in 1.11.0-beta.2.

**Pull request merged**
