### PR TITLE
[BUGFIX release] Fix substate interactions with aborts

### PR DESCRIPTION
**Pull request by chadhietala**
(cherry picked from commit 2b58f7a0624f2ce9b52d01d797f8dc4782641e86)

### CODE REVIEW

**Comment by bastimeyer** [comment]
Are there any plans for a `3.7.1` release which will include these changes? :smiley:

**Comment by rwjblue** [comment]
In general, yes it should end up being included in 3.7.1.

**Comment by bastimeyer** [comment]
Yes, I know, hence my comment on the PR for merging into the release branch. I was just wondering if it could be possible to publish a patch release any time soon, because I'm waiting for the fixes. Thanks!

**Comment by rwjblue** [comment]
No need to wait! Update your `package.json` to use the URL printed out by `npx ember-source-channel-url release` and you'll be off to the races 😸

**Comment by bastimeyer** [comment]
Thanks! I didn't know about Ember storing builds on s3.

**Pull request merged**
