### PR TITLE
[BUGFIX release] Ensure Engine Routes are deactivated before destruction

### PR DESCRIPTION
**Pull request by trentmwillis**
Makes tests fail to reproduce #14234.

Causes some existing tests to fail, though I can add a totally separate tests for this if needed.

### CODE REVIEW

**Comment by rwjblue** [comment]
Awesome, thank you!

>  I can add a totally separate tests for this if needed

That would be great if you don't mind. Iff nothing more it helps us ensure that our tests document the regression, and help ensure we don't accidentally "remove that errant set in deactivate" in the future.

**Comment by trentmwillis** [comment]
@rwjblue updated. A bit more clear as to what is being tested now 😄

**Comment by rwjblue** [comment]
Awesome! We should probably add some general purpose lifecycle ordering tests too at some point, but this is perfect to help track down the regression (and prevent it happening again in the future).

**Comment by trentmwillis** [comment]
@rwjblue updated with a fix. Tests passing except Sauce, which seems to have failed to connect properly.

What should I tag this as? `BUGFIX release`?

**Comment by rwjblue** [comment]
@trentmwillis - Yep, `[BUGFIX release]` sounds correct to me.

**Comment by trentmwillis** [comment]
Tests are passing. Pushing the amended commit message.

**Comment by rwjblue** [comment]
This has been cherry picked into beta and release branches.  Please test those channels (once Travis has pushed the builds up) to confirm before final release...

**Pull request merged**
