### PR TITLE
Correct the URL for running all unit tests in the browser.

### PR DESCRIPTION
**Pull request by kwight**

### CODE REVIEW

**Comment by rwjblue** [comment]
There is a redirect setup for `/` that redirects to `/tests/index.html?hidepassed`, so the docs in the README should actually be correct.

@kwight - Can you confirm?

**Comment by stefanpenner** [comment]
> There is a redirect setup for /

this is also what i see.

**Comment by kwight** [comment]
Uh, weird; nope, for me, `http://localhost:4200/` redirects to `http://localhost:4200` (which is what I would expect). I get this behaviour in Chrome and Firefox, both in Canary and another project still on 1.12 (and 2.0). It seems to make way more sense to me this way, that you have to explicitly go to the `tests` URL to ever see tests. I feel like I'm missing something here :)

It would also be confusing for the fact that `ember serve` gives the message `Serving on http://localhost:4200/` – which you're saying should be the tests page?..

**Comment by stefanpenner** [comment]
quick recording of what i see:

redirect

**Comment by kwight** [comment]
And myself:

https://cloudup.com/cMH7W0oR5Mn

**Comment by stefanpenner** [comment]
@kwight ah, you have confused. An ember app, with embers own test suite.

**Comment by kwight** [comment]
OMG, _now_ I'm following you! Well, I _knew_ it had to be some fundamental misunderstanding on my part, the conversation was just too odd otherwise. Carry on then :)

**Comment by stefanpenner** [comment]
@kwight maybe something in this readme needs to call out that it is for the ember.js code-base itself, not ember apps.

**Comment by kwight** [comment]
I think this is more clear now.

**Comment by stefanpenner** [comment]
@kwight I agree. Thanks for the updated pr ;)

**Pull request merged**
