### PR TITLE
[BUGFIX release] Fix DeprecatedView (and friends) reopen function to delegate to original

### LINKED ISSUE #11849: Ember.View.reopen() from guide for binding data-* attributes doesn't work since I updated ember to 1.13.x
I just put that code form guide in application route before the upgrade, then start to use `data-*` attributes. Like:

```handlebars
{{input data-parsley-required="true" data-...}}
```

It works fine.

But it doesn't work after the upgrade.

Now, I must put those `data-*` attributes into `Ember.TextField.reopen()`'s `attributeBindings` one by one.
Did I missing something?

### PR DESCRIPTION
**Pull request by ghost**
Fixes #11849

### CODE REVIEW

**Comment by rwjblue** [comment]
Thanks for tackling this, I am unsure if we need to also add a deprecation upon `reopen`. 

**Con:** - That there really is no way of doing what #11849 wants to do (adding `attributeBindings` for all `data-*` properties) while avoiding a deprecation.

**Pro** - I do not think we really want folks to do this without the addon at all (because in 2.0.0 they are not going to be exported without the addon).

**Comment by rwjblue** [comment]
@martndemus - Would you mind adding a deprecation for these using the legacy views env flag to disable (and `until` set to 2.4.0)?

**Comment by martndemus** [comment]
@rwjblue like so?

**Comment by mixonic** [comment]
Thanks sir :-)

**Pull request merged**
