### PR TITLE
Prevent 'invalid marker' error

### PR DESCRIPTION
**Pull request by cbou**
The input tag needs to be closed.

It produce an error with specific dtd.

### CODE REVIEW

**Comment by cbou** [comment]
Any news about it?

**Comment by stefanpenner** [comment]
Under what conditions does the above fail.

**Comment by rwjblue** [comment]
`<input type="checkbox">` is valid HTML.  We need more information on what was causing the failure before merging.

I'm going to go ahead and close this for now as it seems to have gone stale. I'm happy to reopen if you would like to pick this back up again.

**Comment by cbou** [comment]
Sorry for the delay.

Here is an example:

``` html
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<script type="text/javascript" src="jquery.js"></script>
		<script type="text/javascript" src="ember.js"></script>
	</head>
	<body>
		<h1>Please look at the JavaScript console.</h1>
	</body>
</html>
```

**Comment by cbou** [comment]
How can I reopen this issue @rwjblue ?

**Pull request closed without merging**
