### PR TITLE
keyUp, keyDown events not working

### LINKED ISSUE #10305: input helper and action does not work as expected
Im basically trying to get this to work. This is doable as per the docs http://emberjs.com/guides/templates/input-helpers/#toc_actions

    {{input value=firstName action="didType" on="key-press"}}

The problem is, when the action triggers, the value passed will always be 1 character short of actual value of the input element.
For eg: if input value is 'add', the value passed into the action is 'ad'.

Here is a failing bin. http://jsbin.com/lotete/3/edit

I also noted that using other events like `key-up` and `key-down` dont trigger that action.

I found this issue while solving this question on SO http://stackoverflow.com/questions/28191776/first-character-empty-using-ember-action-on-key-press

### PR DESCRIPTION
**Pull request by Saranya-Raaj**
fixes #10305

### CODE REVIEW

**Comment by trek** [comment]
Were there no tests around this before? Can you add a test so it doesn't regress?

**Comment by rwjblue** [comment]
They were tested (and passing) [here](https://github.com/emberjs/ember.js/blob/master/packages/ember-views/tests/views/text_field_test.js#L499-L547).

**Comment by rwjblue** [comment]
Using `key-up` and `key-down` does seem to work properly here: http://emberjs.jsbin.com/rwjblue/278/edit.

The old (non `this.sendAction`) code that is changed here is documented in the comments of this file as "legacy" from before `TextField` was a component (pre-1.0.0).

**Comment by rwjblue** [comment]
Thank you for the PR, but I believe that this is working properly at the moment.  I tried to explain in more detail over in https://github.com/emberjs/ember.js/issues/10305#issuecomment-73167586.

**Pull request closed without merging**
