### PR TITLE
Allow saucelabs test suite to fail

### PR DESCRIPTION
**Pull request by locks**
I can't press that restart button 10 times per PR anymore.

### CODE REVIEW

**Comment by stefanpenner** [comment]
have you looked at fixing the sauce labs issues?

**Comment by locks** [comment]
@stefanpenner it has been rotting for a while already :x I have not looked into what the actual issue is, but it is consistently MS Edge bailing out of the build.

**Comment by krisselden** [comment]
I'm not ok with this.

**Comment by krisselden** [comment]
The sauce labs tests have quite often caught bugs that the other tests don't. I'd rather add retrying to the edge test

**Comment by stefanpenner** [comment]
> I'd rather add retrying to the edge test

👍

**Comment by simonihmig** [comment]
Fwiw, as Edge was failing here, I tried to make testing with Edge 15 work some time ago in an addon, and just didn't manage it at all. Just by downgrading to Edge 14, all those problems were gone suddenly... 🤔

**Comment by johanneswuerbach** [comment]
@makepanic potentially has discovered a potential cause for that, will try to get it into a testem rc soonish https://github.com/johanneswuerbach/ember-cli-sauce/issues/102

**Comment by locks** [comment]
Addressed by https://github.com/emberjs/ember.js/pull/16047.

**Pull request closed without merging**
