### PR TITLE
Dectect changed model after creaed

### PR DESCRIPTION
**Pull request by Nacrylyc**
- The state of object after create and not yet save is : **root.loaded.created.uncommitted**
- If I set some attribute is stay in : **root.loaded.created.uncommitted**
- And if I do rollbackAttributes, is become : **root.deleted.saved**

1) Is not intuitive and is strange then after a rollbackAttributes the record become deleted. 
2) I need a state between just created and just after first modification.

The nicely thing is we can pass the initial object, like now but on call the rollbackAttributes the record come back to initial object. 

record = createRecord('model', {'var':'initValue');

record.get('isNew'); // true
record.get('isDelete'); // false
record.get('hasModifiedAttributes'); **// false**
record.get('var'); // initValue

record.set('var', 'newValue');

record.get('isNew'); // true
record.get('hasModifiedAttributes'); **// true**
record.get('var'); // newValue

record.rollbackAttributes();

record.get('isNew'); // true
record.get('isDelete'); **// false**
record.get('hasModifiedAttributes'); **// false**
record.get('var'); // initValue

### CODE REVIEW

**Comment by stefanpenner** [comment]
I suspect this was a mistake?

**Comment by Nacrylyc** [comment]
What do you mean by mistake?

It is a requirement for Ember and ember-data?

**Comment by stefanpenner** [comment]
it seems you opened a PR with 30 commits from the release -> master branch.

**Comment by Nacrylyc** [comment]
Excuse me, but where I put the generale request without any link with 
current dev?

**Pull request closed without merging**
