### PR TITLE
fix license year

### PR DESCRIPTION
**Pull request by antonovkrez**

### CODE REVIEW

**Comment by bertdeblock** [comment]
I think this should either be `Copyright (c) 2011` or `Copyright (c) 2011-2022`.
I don't think `Copyright (c) 2022` is what we want.

**Comment by chriskrycho** [comment]
We chatted about this a bit and it looks like at least for the US, we only need the first year. That means we don't need to maintain/update it over time. Thank you, though!

**Comment by chriskrycho** [comment]
Whoops, didn't mean to close it, sorry—if you want to switch it over to first year, `2011`, *that* we could merge!

**Comment by antonovkrez** [comment]
> Whoops, didn't mean to close it, sorry—if you want to switch it over to first year, `2011`, _that_ we could merge!

Hello! Yeah, I agree :)

**Comment by mixonic** [comment]
Thank you @antonovkrez !

**Comment by TwoCraZySaid4Ten** [comment]
I don't know what they did to prove to you that they were me or what they said to you or what they've done to you God forbid it be anything bad but I'm Tank 
Big TC Childers AKA btcc and TCC was my son

**Review by TwoCraZySaid4Ten — APPROVED** [review]

**Pull request merged**
