### PR TITLE
Module Unification support for the template blueprint

### PR DESCRIPTION
**Pull request by Willibaur**
@GavinJoyce This is the PR about MU Blueprints for Templates we worked with @pablobm at Ember meetup

### CODE REVIEW

**Comment by GavinJoyce** [comment]
👍 this looks great, 💥 👏

**Comment by GavinJoyce** [comment]
part of https://github.com/ember-cli/ember-cli/issues/7530

**Review by rwjblue — APPROVED** [review]

**Comment by rwjblue** [comment]
Thank you!

**Pull request merged**
