### PR TITLE
Add AliasedProperty to eachComputedProperty

### LINKED ISSUE #10823: Aliases are not enumerated in `eachComputedProperty`
While the docs indicate that the return value of `computed.alias` and friends is a `ComputedProperty`, they are not enumerated with a call to `eachComputedProperty`. E.g.

```js
var AClass = Ember.Object.extend({
  foo: Ember.computed(function() {
    return "foo";
  }),  
  bar: Ember.computed.alias('foo')
});
```

will only yield one CP for `foo`, not `bar`

Demonstration here:

http://emberjs.jsbin.com/wadirumiti/1/edit?html,js,output

### PR DESCRIPTION
**Pull request by pdud**
This fixes #10823

Thank you for labeling it as Good for New Contributors! :)

### CODE REVIEW

**Comment by stefanpenner** [comment]
@krisselden I wonder if they should share some comment ancestor. Or ducktype

**Comment by mmun** [comment]
@stefanpenner They are `Descriptor`'s, is there any reason not to just use that?

**Comment by stefanpenner** [comment]
Many unknowns :(

**Comment by pdud** [comment]
I haven't used `eachComputedProperty` either.

I'm still learning & reading into this but I believe that an `InjectedProperty` is also a `Descriptor`.

I suppose that `InjectedProperty`s might also be desirable to include in this `eachComputedProperty`.

https://github.com/emberjs/ember.js/blob/master/packages/ember-metal/lib/injected_property.js#L28

There is also mentions of `Descriptor`s in mixin.

https://github.com/emberjs/ember.js/blob/master/packages/ember-metal/lib/mixin.js#L730
https://github.com/emberjs/ember.js/blob/master/packages/ember-metal/lib/mixin.js#L750

**Comment by mmun** [comment]
Might be useful to do a full github search of `eachComputedProperty` instead. I bet ember-data uses it.

**Comment by rwjblue** [comment]
I think this is pretty safe, and solves the largest case where this is incorrect currently, but I am totally fine with changing the check to `property && property.isDescriptor` if y'all prefer.

**Comment by stefanpenner** [comment]
> property && property.isDescriptor if y'all prefer.

:+1:

**Comment by pdud** [comment]
I'd be happy to make that change if preferred? :)

As for some other projects

[ember-data](https://github.com/emberjs/data/search?utf8=%E2%9C%93&q=eachComputedProperty)
[ember-orbit](https://github.com/orbitjs/ember-orbit/search?utf8=%E2%9C%93&q=eachComputedProperty)
[ember-admin](https://github.com/ember-admin/ember-cli-admin/search?utf8=%E2%9C%93&q=eachComputedProperty)

It appears all filter `eachComputedProperties` using the metadata of the property so I believe would be unaffected by this PR or changing it to `property && property.isDescriptor`.

**Comment by rwjblue** [comment]
Yes, please update to that and lets confirm that the eachComputedProperty tests all pass.

**Comment by pdud** [comment]
The tests worked locally and travis is happy as well.

**Comment by rwjblue** [comment]
Awesome! Thank you!

**Pull request merged**
