### PR TITLE
Deprecate and remove TrackedArray and SubArray.

### PR DESCRIPTION
**Pull request by rwjblue**

### CODE REVIEW

**Comment by stefanpenner** [comment]
oh crap, did i forget to remove this from the RC/AC refactor?

**Comment by rwjblue** [comment]
Yessir, but @krisselden noticed during his recent work and asked me to remove.

**Comment by stefanpenner** [comment]
nice!

**Comment by stefanpenner** [comment]
> Yessir, but @krisselden noticed during his recent work and asked me to remove.

yay more bytes removed

**Pull request merged**
