### PR TITLE
[BUGFIX release-1-13] Updated backburner.js. Backported from master.

### PR DESCRIPTION
**Pull request by workmanw**
Addresses emberjs/ember.js#12193 and possibly emberjs/ember.js#10479.

### CODE REVIEW

**Comment by workmanw** [comment]
:( It's not clear what failed. 

One error was: 
> TypeError: Cannot read property 'QUnit' of undefined
Seems like something else going on there.

Second error was timeouts:
screen shot 2015-10-06 at 5 16 30 pm

Maybe it just needs a kick :mans_shoe:

**Comment by rwjblue** [comment]
Nah, it's failing upstream. I just fixed node tests on master yesterday. I need to backport that fix to beta, release, and release-1-13.

**Comment by workmanw** [comment]
@rwjblue Okay cool. Will rebase this when the other fix(es) have been backported.

**Comment by workmanw** [comment]
@rwjblue Actually, I'd be happy to open PRs to backport those fixes across those branches if you think it's straightforward (I don't have any specific knowledge of the fixes).

**Comment by rwjblue** [comment]
https://github.com/emberjs/ember.js/pull/12440

**Comment by rwjblue** [comment]
Can you rebase?

**Comment by workmanw** [comment]
@rwjblue Rebased.

**Comment by rwjblue** [comment]
Thank you!

**Comment by workmanw** [comment]
You're welcome! 

I'd be happy to back port these node test fixes to beta and release. I'll do that right meow. :smile_cat: 

One question, I'll be looking to use https://github.com/components/ember/tree/release-1-13. Does that just push automagically?

**Pull request merged**
