### PR TITLE
Add test to verify `makeArray` bug

### PR DESCRIPTION
**Pull request by pswai**
This adds tests to https://github.com/emberjs/ember.js/issues/14741

### CODE REVIEW

**Comment by mixonic** [comment]
@pswai thanks for looking into this. I believe this utility is private, and I expect we're simply not concerned with the array proxy case as they are rarely (never?) used in Ember internals.

Can you confirm you're making a comment about the private `makeArray` API here? Or perhaps I'm missing where this is impacting public API.

**Comment by pswai** [comment]
@mixonic I was looking at this file ember.js/packages/ember-utils/lib/make-array.js. The block comment there gives example of `ArrayProxy` so I am not sure whether it is due to broken `makeArray` or the comment needs to be updated

**Comment by rwjblue** [comment]
Sorry for the confusion, yes we should definitely fix the docs here...

**Comment by rwjblue** [comment]
Closing this in favor of a future documentation specific PR...

**Pull request closed without merging**
