### PR TITLE
Remove arity check from initializer

### PR DESCRIPTION
**Pull request by locks**

### CODE REVIEW

**Review by rwjblue — COMMENTED** [review]
Assuming the legacy addon can monkey patch via `Ember.Engine.reopen({ runInitializers() { }})`, I think this can safely be moved into the legacy addon.

Can you create an issue over there, and cross link back here?

**Comment by rwjblue** [comment]
@locks - Ping!

**Comment by thoov** [comment]
LGTM 🚢

**Comment by locks** [comment]
Finally green :)

**Review by rwjblue — APPROVED** [review]

**Pull request merged**
