### PR TITLE
[CLEANUP beta] Remove unused imports and other minor cleanup

### PR DESCRIPTION
**Pull request by btecu**

### CODE REVIEW

**Comment by btecu** [comment]
Versions of `require`?

**Comment by stefanpenner** [comment]
ya, we don't need those. if parts of ember want to use require they should import it

`import require from 'require'` should work [relevant code](https://github.com/emberjs/ember.js/blob/master/packages/loader/lib/index.js#L80-L81)

**Comment by btecu** [comment]
I tried removing `requireModule` but it's used in many places (in `dist` files) and tests fail if I remove it.

**Comment by rwjblue** [comment]
Thank you for your time on this! I'm going to go ahead and close this for now as it seems to have gone stale. I'm happy to reopen if you would like to pick this back up again.

**Comment by btecu** [comment]
@rwjblue other than rebasing, is there any other change you'd like me to do?

**Comment by rwjblue** [comment]
No, I think a rebase is all that is required here....

**Comment by btecu** [comment]
Rebased.

**Comment by rwjblue** [comment]
Thanks @btecu!

**Pull request merged**
