### PR TITLE
Update to qunit@2.5.0

### PR DESCRIPTION
**Pull request by rwjblue**
Some high level features:

* Contains `assert.rejects`
* Reduces the delays around `assert.async` and returning promises from hook methods.
* Adds a native promise unhandled rejection handler
* Fixes an issue with `notrycatch` mode being ignored for promises returned (e.g. it would previously always `.catch` every returned promise).

### CODE REVIEW

**Comment by thoov** [comment]
We should also update package.json with this as I find it a more accurate description at a glance as too which version we are supporting other than having to dive into the lock file.

**Comment by rwjblue** [comment]
Good point, updated!

**Comment by thoov** [comment]
LGTM once build passes

**Comment by rwjblue** [comment]
Seems like a consistent IE11 failure:
```
not ok 8 IE 11.0 - Application test: engine rendering:  loading substate route works for a child route of an Engine
    ---
        actual: >
            false
        expected: >
            true
        stack: >
               at RunLoopAssertion.prototype.assert (http://127.0.0.1:7774/4983/dist/ember-tests.js:80279:9)
               at Anonymous function (http://127.0.0.1:7774/4983/dist/ember-tests.js:80338:9)
               at options.afterEach (http://127.0.0.1:7774/4983/dist/ember-tests.js:80319:9)
               at callHook (http://127.0.0.1:7774/4983/dist/qunit/qunit.js:1497:6)
               at runHook (http://127.0.0.1:7774/4983/dist/qunit/qunit.js:1520:7)
               at advance (http://127.0.0.1:7774/4983/dist/qunit/qunit.js:1116:6)
        message: >
            Ember run should not have scheduled timers at end of test
        Log: |
    ...
```

**Comment by thoov** [comment]
Is it possible to run the browserstack tests locally? Running `yarn test:browserstack` wants a access_key?

**Comment by thoov** [comment]
It also seems like browserstack is a little flacky since this is also breaking it https://github.com/emberjs/ember.js/pull/16107

**Comment by rwjblue** [comment]
Yes, there is one particular test that seems flakey on IE11 (something about `focus-in`), but this PR is failing a different test (titled pasted above) _seemingly_ consistently. After, booting up my IE11 VM I am able to repro...

**Comment by rwjblue** [comment]
CI passed with that test refactor but there was a GitHub outage at the time the commit status was being updated 😩 

```
#
# Browser: Safari 11.0
# tests 6277
# pass  6273
# skip  4
# fail  0
#
# Browser: Edge 16.16299
# tests 6278
# pass  6274
# skip  4
# fail  0
#
# Browser: IE 11.0
# tests 6271
# pass  6267
# skip  4
# fail  0
#
1..18826
# tests 18826
# pass  18814
# skip  12
# fail  0
# ok
```

**Pull request merged**
