### PR TITLE
[bugfix] Fix intrumentation exports and tests

### LINKED ISSUE #15748: Cannot import unsubscribe and reset from '@ember/instrumentation'
With the old Ember global:

```
import Ember from 'ember';
const { Instrumentation: { instrument, subscribe, unsubscribe, reset } } = Ember;
```

returns defined for all 4 functions.

In the new module API:

```
import { instrument, subscribe, unsubscribe, reset } from '@ember/instrumentation';
```

returns undefined for `unsubscribe` and `reset`.

These imports are listed as supported: https://github.com/ember-cli/ember-rfc176-data#emberinstrumentation

### PR DESCRIPTION
**Pull request by sarupbanskota**
Fixes #15748

### CODE REVIEW

**Comment by Turbo87** [comment]
@sarupbanskota can you explain why your change is fixing the exports?

**Comment by sarupbanskota** [comment]
@Turbo87 sorry it was my first PR and turns out I misunderstood something - essentially I'm now causing it to be exported as `Ember.Instrumentation.x` vs just `Ember.x`

Also have a relevant PR here: https://github.com/ember-cli/ember-rfc176-data/pull/40

**Comment by rwjblue** [comment]
Previously, it was exported as _both_ `Ember.instrument` **and** `Ember.Instrumentation.instrument`, after this change the `Ember.instrument` export is removed. 

This seems not quite correct...

**Comment by rwjblue** [comment]
Closed by ember-cli/ember-rfc176-data#40

**Comment by sarupbanskota** [comment]
@rwjblue hm, I've added back the `Ember.instrument` export and it's test but have retained the removal of `Ember.subscribe` - lemme know if that's expected now?

**Comment by rwjblue** [comment]
Sorry, what I am saying is that I do not think changes are needed here in Ember at all. The required changes to fix the error reported in https://github.com/emberjs/ember.js/issues/15748 were fixed by your PR in https://github.com/ember-cli/ember-rfc176-data/pull/40.

**Comment by sarupbanskota** [comment]
ah, alright - so we want to keep `Ember.subscribe` in. It just seemed strange to me that is exported that way`subscribe` while `unsubscribe` isn't 🤔 

lemme know if you'd like me to introduce `Ember.subscribe = metal.instrument` in the test file - if not this PR could be closed! Thanks

**Comment by rwjblue** [comment]
Awesome, thank you for working on this!  I'm going to go ahead and close, because you already fixed the underlying issue.

**Pull request closed without merging**
