### PR TITLE
Make use of JS type coercion for validation

### PR DESCRIPTION
**Pull request by sarathkumarbaskaran**

### CODE REVIEW

**Comment by Serabe** [comment]
AFAIK, avoiding coercion in the framework is an optimization, so I find this unlikely to be merged.

**Comment by sarathkumarbaskaran** [comment]
@Serabe 
I think, validating the same key against two values (here) is not the optimized way, if the validation is quite certain.
Instead of writing every time `a === b` and `a === c`, it'd be better to have `a == b`, if at all the required condition passes. Even, it doesn't change the behavior while minify/uglify.
Correct me, if I'm wrong.

**Comment by rwjblue** [comment]
Generally speaking, folks in JS land avoid using == because it’s somewhat trolling in some circumstances (I’m actually surprised our eslint rules are not making this fail). 

TBH, I’m unsure what is “best” here. Perhaps @krisselden can chime in RE how various engines handle it...

**Comment by mmun** [comment]
As a point of style, we tend to use triple equal to make the code easier to understand at the expense of  brevity.

**Pull request closed without merging**
