### PR TITLE
[DOC] address typos in packages directory

### PR DESCRIPTION
**Pull request by sbatson5**
Was looking over some easy contributions for new contributors and spotted a few typos and figured that would be a good starting point.  Mostly just a few mis-spellings.

### CODE REVIEW

**Comment by sbatson5** [comment]
Thanks!  Rebased

**Comment by rwjblue** [comment]
Hmm, not sure why CI didn't get kicked off here.

**Comment by rwjblue** [comment]
@homu r+

**Comment by rwjblue** [comment]
@homu retry

**Comment by sbatson5** [comment]
Am I able to restart the CI tests?

**Pull request closed without merging**
