### PR TITLE
[FEATURE ember-improved-instrumentation]

### PR DESCRIPTION
**Pull request by wycats**
[WIP]

Right now, this PR adds instrumentation for interaction events.

We plan to add more instrumentation over the next few weeks under the same feature flag.

Some anticipated TODOs:
- [ ] Write a "deep dive" guide about the existing instrumentation as well as the instrumentation in this feature flag. This will be the official enumeration of instrumentation points and what they are intended to be used for.
- [ ] Instrument
  - [X] component event handling
  - [x] closure `action`s
  - [ ] element `action`s
  - [X] top-level routing transitions
  - [ ] granular routing hooks
- [ ] Think about linking user interactions to other work (e.g. if click on a button -> rerender, then you might want to link the two things together). Generally, because the reaction to user interaction is so often async, it would be useful to provide at least an opt-in way to tie together user interactions with an async job.

### CODE REVIEW

**Comment by rwjblue** [comment]
Will need a rebase (the closure action memory leak fix was merged).

**Comment by asakusuma** [comment]
Pretty exciting to see the start of this feature.

Perhaps this is inferred in one of the exiting TODO points, but it would be great to have a nice public API for adding custom instrumentation for things like instrumenting anchor tags to external links going outside the ember app.

**Comment by amkirwin** [comment]
How about initializer instrumentation?

**Comment by amk221** [comment]
How about initializer instrumentation?
It's easy to forget that these can add-up and create a slow app boot time

**Comment by rwjblue** [comment]
There is a very long trail on this one:

* https://github.com/emberjs/ember.js/pull/12550
* https://github.com/emberjs/ember.js/pull/13017
* https://github.com/emberjs/ember.js/pull/13279

Closing this version for now...

**Pull request closed without merging**
