### PR TITLE
[DOCS] Cleanup runloop example code

### PR DESCRIPTION
**Pull request by knownasilya**

### CODE REVIEW

**Comment by trek** [comment]
not sure why this failed CI. rerunning

**Comment by knownasilya** [comment]
@trek what's the issue?

**Comment by trek** [comment]
Ah, we've added some code style validations to the project: https://travis-ci.org/emberjs/ember.js/jobs/46351915 

They're laid out in https://github.com/emberjs/ember.js/blob/master/.jscsrc and https://github.com/emberjs/ember.js/blob/master/.jshintrc

If you run tests locally https://github.com/emberjs/ember.js/#how-to-run-unit-tests you can get a full list locally.

**Comment by knownasilya** [comment]
@trek all set

**Comment by trek** [comment]
Can you squash down into one commit for merge? Thanks.

**Comment by knownasilya** [comment]
@trek squashed

**Comment by rwjblue** [comment]
Build failing due to bower.herokuapp.com failure.

**Comment by knownasilya** [comment]
@rwjblue @trek ping

**Comment by stefanpenner** [comment]
needs rebase

**Comment by knownasilya** [comment]
@stefanpenner all set

**Comment by trek** [comment]
All merged in. Thank you!

**Pull request merged**
