### PR TITLE
[CLEANUP Beta] (╯°□°）╯︵ ʇǝs

### PR DESCRIPTION
**Pull request by stefanpenner**

### CODE REVIEW

**Comment by rwjblue** [comment]
LGTM

**Comment by rwjblue** [comment]
Needs a rebase.

**Comment by knownasilya** [comment]
Does this mean changing all code (for 2.0) from `this.set('key', val)` and `Ember.set(this, 'key', val)` to `this.key = val`?

**Comment by jonnii** [comment]
@knownasilya no, it means you can't use `Ember.Set` (http://emberjs.com/api/classes/Ember.Set.html). Different kind of set.

**Comment by knownasilya** [comment]
Ops, missed that.. ignore me :stuck_out_tongue_winking_eye:

**Pull request merged**
