### PR TITLE
Disallow space after opening array square bracket and before closing.

### PR DESCRIPTION
**Pull request by jbrown**
Related to #9849, #10072

Do you want all or nested mode?

Valid for mode "all"
`var x = [[1]];`

Valid for mode "nested"
`var x = [ [1] ];`

Invalid
`var x = [ [ 1 ] ];`

### CODE REVIEW

**Comment by jbrown** [comment]
Do you want all or nested mode?

**Comment by twokul** [comment]
I can't look it up right now, could you post code examples so everyone can see?

**Comment by jbrown** [comment]
@twokul updated above.

**Comment by twokul** [comment]
"all" seems like a good option to me.

**Pull request merged**
