### PR TITLE
failing test for #18318

### PR DESCRIPTION
**Pull request by GavinJoyce**
a failing test for https://github.com/emberjs/ember.js/issues/18318

Screenshot 2019-08-27 at 14 32 39

### CODE REVIEW

**Comment by rwjblue** [comment]
@gavinjoyce - Should we close this now? Or do we expect these tests to pass?

**Comment by GavinJoyce** [comment]
I just rebased, the test should pass with https://github.com/emberjs/ember.js/pull/18329 and it would be good to confirm.

It looks like ^ comes with meaningful tests, so there's probably no value in adding this test to master. I'll close it once we're 🍏

**Comment by GavinJoyce** [comment]
It's 🍏, closing

**Comment by rwjblue** [comment]
Awesome, thank you @gavinjoyce

**Pull request closed without merging**
