### PR TITLE
[BUGFIX release-1-13] backports V8 memory leak bug through registry / resolver access.

### PR DESCRIPTION
**Pull request by calderas**
- [x] Backports #12666 to ember 1.13
- [x] Fixes jshint tests on ember-1-13 branch

Related to #12618

### CODE REVIEW

**Comment by rwjblue** [comment]
Hmm, I'm somewhat concerned about this change being backported. It is a fairly large set of changes, and due to that it poses a level of risk that I'm not sure we should take on...

**Comment by rwjblue** [comment]
We discussed this in detail during the most recent core team meeting ([see notes here](https://github.com/emberjs/core-notes/blob/master/ember.js/2016-04/april-08.md#evaluatediscuss-risk-of-backporting)), and we generally agree that their is a bit more risk in backporting than we are comfortable with.  It is likely that other changes are required (there were when the original PR landed) in various parts of the ecosystem (like ember-test-helpers, ember-qunit, etc) to support this change.

We would absolutely consider a fix that is less risky (ala making these functions too large to inline by adding a large string)...

**Comment by rwjblue** [comment]
See https://github.com/emberjs/ember.js/pull/12652/files for an example of a very low risk change that prevents the leak also.

**Comment by rwjblue** [comment]
Closing based on response to last few comments.

**Comment by micky2be** [comment]
I tried using this patch on Ember 1.13.13 and still get PhantomJS to crash.
I'm trying to update my app from 1.12.2 to 2.x and going through 1.13.x is kinda mandatory for us to make sure we are not breaking anything on the way (it's a big app).

**Pull request closed without merging**
