### PR TITLE
Make Ember.Checkbox extend from Ember.Component

### PR DESCRIPTION
**Pull request by cibernox**
Public API unchanged.

### CODE REVIEW

**Comment by mixonic** [comment]
@cibernox per this burndown: https://github.com/emberjs/ember.js/issues/11377 we would like to make sure this does *NOT* go into 1.13 beta, but instead lands only in 2.0.

@rwjblue can we merge this to master? Don't want to trip you up.

**Comment by cibernox** [comment]
This can wait 3 days until the 12th.

If you feel that is convenient for organization purposes of that burndown merge all those changes in a single PR you can cherry-pick this commit and close this.

**Comment by mixonic** [comment]
@bantic and I are working on that burndown- definitely merging changes as we go.

**Comment by rwjblue** [comment]
I think there is an issue that is open about this that we can close now.

**Comment by pangratz** [comment]
@rwjblue this one #5433?

**Comment by rwjblue** [comment]
Yes, thank you!

**Comment by jfelchner** [comment]
Thanks for all the hard work everyone. It's very much appreciated.

**Pull request merged**
