### PR TITLE
[DOC beta] Deprecation link for Ember.Component.reopen

### PR DESCRIPTION
**Pull request by Glarregle**
Should wait for https://github.com/ember-learn/deprecation-app/pull/948

### CODE REVIEW

**Review by jenweber — APPROVED** [review]
The deprecation guide has been merged, so this can move forward.

@Glarregle please mark your commit with `[DOC beta]` at the beginning of the commit message. This will help us make sure it gets in for the next release.

**Comment by Glarregle** [comment]
Thanks @jenweber! Ready!

**Comment by mixonic** [comment]
This needs to be rolled back. This deprecation was targeting 4.0, and we want to remove the functionality in 4.0. Followup from @chancancode is:

- PR to move the deprecation guide to 3.x (also the link-to.disabled-when ones)
- PR to change "until" back to 4.0 on master and beta, as well as updating the URL to 3.x
- PR to backport adding the URL (and since) to 3.28

**Comment by jenweber** [comment]
@mixonic PR to fix the versions https://github.com/emberjs/ember.js/pull/19823

Sorry for the confusion @Glarregle, we gave you the wrong instructions about version numbers. Thanks again for your help with fixing missing info.

**Pull request merged**
