### PR TITLE
[docs] add filterBy example

### PR DESCRIPTION
**Pull request by rimian**

### CODE REVIEW

**Comment by rimian** [comment]
I hope this commit wasn't too small. I can do more next time if you want :)

**Comment by mansona** [comment]
@locks ?

**Comment by mansona** [comment]
@rimian in case you're wondering why this was closed, @locks has rebased your work and landed it in https://github.com/emberjs/ember.js/pull/17917

Thanks for the contribution 🎉

**Comment by locks** [comment]
Thanks Chris! I took care to keep your commit so you still get listed as an author. 😁

**Comment by rimian** [comment]
Thanks Chris for letting me know!

**Pull request closed without merging**
