### PR TITLE
some destructuring examples to prove it works

### PR DESCRIPTION
**Pull request by stefanpenner**
- [x] add style guide entry.
- [ ] bike-shed styles

### CODE REVIEW

**Comment by chadhietala** [comment]
@stefanpenner Probably will need to update the styleguide to show proper usage.

**Comment by stefanpenner** [comment]
@chadhietala will do!

**Comment by jasonLaster** [comment]
And it's begun

**Comment by stefanpenner** [comment]
> And it's begun

:+1:

**Comment by trev** [comment]
So hot right now :+1:

**Pull request merged**
