### PR TITLE
Fix observers (#16292)

### PR DESCRIPTION
**Pull request by BryanCrotaz**
Seeing observers not firing in real world app (where they used to work). See issue #16292 

This PR fixes the issue - either it's a fix to an edge case, or it might point the way to what the app might have done to break the framework, in which case this advice might need to be added to the docs or guides.

### CODE REVIEW

**Comment by Serabe** [comment]
These changes break tests.

**Comment by BryanCrotaz** [comment]
@serabe I'm not clear what the `if` is doing here - what does it say about my app that removing the else makes my observers fire?

**Comment by rwjblue** [comment]
You are making then fire even when deferred, something in your app must be deferring observers and never release the deferral

**Comment by BryanCrotaz** [comment]
@rwjblue I wasn't aware of deferring - what does it mean in this context? And how do you defer an observer?

**Comment by BryanCrotaz** [comment]
This is the observer that isn't firing:

```
// controller.js
import Controller from '@ember/controller';
import { later } from '@ember/runloop';
import { observer } from '@ember/object';
import { validator, buildValidations } from 'ember-cp-validations';
import { task, timeout } from 'ember-concurrency';
import { waitForProperty } from 'sc-pp-frontend/utils/wait-for';
const Validations = buildValidations({
  'data': validator('presence', true)
});

export default Controller.extend(Validations, {
  data: null,
  observerChanged: false,

  init() {
    this._super(...arguments);
    this.get('data');
  },

  dataChange: observer('data', function() {
    this.set('observerChanged', true);
    later(() => {
      this.set('observerChanged', false);
    }, 500);
  }),

  toggleTask: task(function*() {
    while(true) {
      yield timeout(1500);
      this.set('data', 'abc');
      yield timeout(1500);
      this.set('data', null);
    }
  }).on('init')
});


// template.hbs
TEST OBSERVER
<div>

  data: {{data}}
  <br/>
  Observer observed change: {{observerChanged}}
  <br/>
  {{input value=data }}

</div>
```

**Comment by mmun** [comment]
@rwjblue's assessment is correct. The existing code is correct and something is wrong in your app / an addon. Can you push a demo app that contains the error?

**Comment by mmun** [comment]
Please continue in https://github.com/emberjs/ember.js/issues/16292 as this PR is invalid (although it is indeed helpful for debugging the root cause :)).

**Pull request closed without merging**
