### PR TITLE
remove dependency on jQuery for adding and removing classes

### PR DESCRIPTION
**Pull request by benlesh**
Relates to #9745 

Do to the master failing currently, I was unable to build and run tests against this change. I'll watch for master to go green, rebase, and try again. Just want to get this PR in there.

### CODE REVIEW

**Comment by mixonic** [comment]
@blesh this has pretty much all changed in Glimmer, which we expect to land inside a week. In glimmer classes should be set with `setAttribute` at all times.

What is the motivation here? I presume it is trying to avoid `className=` inside jquery.

**Comment by blesh** [comment]
@mixonic JQuery doesn't work with namespaces other than HTML. So SVGElements whose `className` attributes are really `SVGAnimatedString` and not just `String` can't be set with `elem.className = "foo bar"` as what JQuery does. Worse, there's not even an error, it just doesn't work.

Using `setAttribute("class")` works just fine in all browsers, and `classList` is even better if the browser happens to support it. I *think* all browsers that support SVG also support classList, but I could be wrong.

My motivation is to keep [ember-nf-graph](http://github.com/Netflix/ember-nf-graph) working properly with Ember. 

If this PR isn't necessary because of a dramatic shift, that's fine... but at the very least, if I could have something to test for in ember-nf-graph before I patch it myself (which I'm currently doing) that would be good.

**Comment by topaxi** [comment]
According to http://caniuse.com/#feat=classlist IE doesnt support classList on SVG elements..

**Comment by mixonic** [comment]
`classList` also doesn't preserve order well enough for our needs in Ember.

`setAttribute` is definitely the right path.

**Comment by mixonic** [comment]
@blesh If you want to start testing and playing with Glimmer, I think you will probably find it ready. Just use the `idempotent-rerender` branch of Ember.js. May 1st is our theoretical branch date for 1.13, so it should be landing in master soon.

**Comment by blesh** [comment]
I'll try to give it a whirl this week. This particular issue isn't as pressing for me as collection performance, though.

**Comment by stefanpenner** [comment]
@blesh are you still interested in pursuing this or...

**Comment by stefanpenner** [comment]
@mmun / @mixonic is this still a think we need to care about in our new HTMLbars land of things?

**Comment by blesh** [comment]
@stefanpenner I don't currently have the bandwidth or the familiarity with Glimmer. I'm okay with this closing so long as the core team feels it's handled in Glimmer

**Pull request closed without merging**
