### PR TITLE
extract nested if from each-with-index code

### PR DESCRIPTION
**Pull request by koriroys**

### CODE REVIEW

**Comment by stefanpenner** [comment]
re-triggering the saucelabs job

**Comment by koriroys** [comment]
@stefanpenner could this get some love?

**Comment by rwjblue** [comment]
The feature flagging for each-with-index can be removed completely at this point. 

Can you take care of that here also?

**Comment by koriroys** [comment]
@rwjblue I think I got it all

**Comment by rwjblue** [comment]
Would you mind squashing commits?

**Comment by koriroys** [comment]
@rwjblue done

**Comment by rwjblue** [comment]
Thank you!!

**Pull request merged**
