### PR TITLE
[BUGFIX beta] Allow symbol usage throughout internals.

### PR DESCRIPTION
**Pull request by rwjblue**
Previously, this would result in an exception (both `Ember.get` and `Ember.set` expected a string for the key name argument).

### CODE REVIEW

**Comment by mmun** [comment]
I'm wondering about notifyPropertyChange for this pr and the previous one. Should we guard it?

**Comment by rwjblue** [comment]
@mmun - Add a few more tests in the general infrastructure (`addObserver`, `computed`, etc) that use both numbers and symbols, mind taking another look?

**Review by mmun — APPROVED** [review]

**Comment by rwjblue** [comment]
Rebased...

**Comment by locks** [comment]
Mega conflict. Should I attempt to rebase or would a fresh start be better?

**Comment by locks** [comment]
Closing as I'm pretty sure this is no longer relevant!

**Pull request closed without merging**
