### PR TITLE
Create CODE_OF_CONDUCT.md

### PR DESCRIPTION
**Pull request by CollectiveInclusion**
Thank you so much for this tweet: https://twitter.com/trek/status/611619058098634752

It would be great to formalize your support with the inclusion of @CoralineAda's code of conduct.

Thanks for your consideration.

### CODE REVIEW

**Comment by simi** [comment]
Why this file needs to be a part of git repository? IMHO http://emberjs.com/guidelines/ is better.

**Comment by mixonic** [comment]
We have a code of conduct on the website :-) http://emberjs.com/guidelines/

**Comment by stefanpenner** [comment]
If we choose to include this file, it should merely link to  http://emberjs.com/guidelines/.

**Comment by trek** [comment]
I'd love to have a code of conduct in each repo, but we should have it match the one on the site (or potentially link to the one on the site). 

If you have suggestions for updates to that code of conduct, https://github.com/emberjs/website/ is probably the place for us to have that discussion.

**Comment by stefanpenner** [comment]
> (or potentially link to the one on the site).

I prefer link, this keeps stuff from getting out of sync.

**Comment by CollectiveInclusion** [comment]
My hope was that we could agree on a standard CoC that would be unchanging and sitting side-by-side with the code. The Guidelines in the website are buried at the bottom.

**Comment by trek** [comment]
@rwjblue brought up a good point for including the text of a CoC inside the repo itself: you know exactly what you're agreeing to when you commit, whereas the site might change without you noticing.

**Comment by stefanpenner** [comment]
> whereas the site might change without you noticing.

likely easier to track temporal changes, yes

**Comment by jayphelps** [comment]
Perhaps just move http://emberjs.com/guidelines/ content to https://github.com/emberjs/ember.js/blob/master/CODE_OF_CONDUCT.md and redirect website url to that file. IMO repo CODE_OF_CONDUCT.md would get significantly more exposure and visibility. I didn't even know the website variant existed.

**Comment by wifelette** [comment]
Already working on a fix for this, just takes some time to get everything everywhere it ought be :p More info to follow.

**Comment by trek** [comment]
Closing in favor of #11516

**Comment by rwjblue** [comment]
Added CODE_OF_CONDUCT.md in the following commits:

https://github.com/emberjs/log-manager/commit/f60be219d55679e0d5ed462bb2f601b6b9e4466b
https://github.com/emberjs/ember-rails/commit/300f50c50e3b7f54ecb56f4ecb8cf55e05e7e2f7
https://github.com/emberjs/ember.js/commit/0401f9baf9c56e948d107dc21f36ddab927bd94d
https://github.com/emberjs/group-helper/commit/a4cc85ac6f5dc61aa81d3387c13de6820788e371
https://github.com/emberjs/ember-states/commit/f4501e6350521f517ba8a4002a750903596db62c
https://github.com/emberjs/cfp-app/commit/1d6b645ac460fced0cabcf933b2078e63972c2b2
https://github.com/emberjs/starter-kit/commit/e0b824583777964639d7a66356b389027d6fe84e
https://github.com/emberjs/ember-data-fixture-adapter/commit/ab1e6d0bad4290da9efbe0caef960e923872601a
https://github.com/emberjs/list-view/commit/c0d66ecf6a6dca72a81cc17521e8aa6c0a7a98c0
https://github.com/emberjs/emberjs-build/commit/d754f63e9ab6ac8ced4c41e1239c3db8e5014fbd
https://github.com/emberjs/api/commit/0468f7f44532e0f568bb34e49655fd8e19ba25f1
https://github.com/emberjs/ember-dev/commit/59fc42eee0d894c35248e98f5cf986fb0d031116
https://github.com/emberjs/ember-legacy-views/commit/6324888c945bd3c1f17b26df726c89dec4522a7f
https://github.com/emberjs/ember-inspector/commit/b80b93c7cfd109388c492b9ed5c80afc7c4afb83
https://github.com/emberjs/guides/commit/d9ca74293ecb29c98ee620e4a121b776ac0a6bef
https://github.com/emberjs/rfcs/commit/17e745ed98904a604fb9a034f1b35883db5e28f0
https://github.com/emberjs/website/commit/53b5087ca7b09361b69b7e7d920f716c1d27d730
https://github.com/emberjs/data/commit/599cf92736431d5e6d41725268e4d5a9c85407c2

**Comment by stefanpenner** [comment]
and for the ember-cli org:

https://github.com/ember-cli/ember-cli/commit/120a12af3e4682cc470a6ee7a294904733eb3423
https://github.com/ember-cli/exists-sync/commit/930ca0afa108731026bcc19bd8398534f56be53e
https://github.com/ember-cli/ember-cli-todos/commit/c233aaad3ed5ea1e0e692327560a937b9b9d1451
https://github.com/ember-cli/ember-cli-deploy/commit/e7dd0d8c308c404929918ff8d05c5e3646a48d08
https://github.com/ember-cli/broccoli-es6modules/commit/91d8674fae04fc282aa0a9aa3411fe68f9019234
https://github.com/ember-cli/ember-cli-shims/commit/c75070e333cf7872294fea7b9f0abf50bb0a2694
https://github.com/ember-cli/ember-cli-htmlbars/commit/60b55ea414ef4827b77a3608ce0c733d7c2b7d25
https://github.com/ember-cli/ember-resolver/commit/0ea3c72a9f3cf4743b90270a48513f751dcb1534
https://github.com/ember-cli/rfcs/commit/68a35f2aacf138962973b71cfd145453b3cb4ace
https://github.com/ember-cli/babel-plugin-feature-flags/commit/9524d4f1effd7f53f92ddd92ecee62a0dd4dbe9d
https://github.com/ember-cli/babel-plugin-filter-imports/commit/b5b6cead09135f5a5351eff8f803c0c0caa6f8e9
https://github.com/ember-cli/ember-cli-uglify/commit/211e1bd34a4a094a73408d47aa55f2bcca6c6d88
https://github.com/ember-cli/node-modules-path/commit/9d9aa5d80f8cf2bc32565a2319e808007ac03643
https://github.com/ember-cli/clean-base-url/commit/f2e77e390b1e6e1a6d39af400bfdec6ae6bc8c4d
https://github.com/ember-cli/process-relative-require/commit/e99fdcb35f3cc7b26f825f360ea5ebd6378e85fe
https://github.com/ember-cli/silent-error/commit/ed5486bd9e6e0eb879fc7f22f9f878c1dbb91c10
https://github.com/ember-cli/loader.js/commit/02dcbfb8c139a4bf2e3a8f017db8dddb00004886
https://github.com/ember-cli/ember-cli-qunit/commit/46677960363a0fded56a5e819fe38e5fe75e7e7a
https://github.com/ember-cli/broccoli-caching-writer/commit/c628339c53db306b27672fdcc18d732151adc0c7
https://github.com/ember-cli/core-object/commit/0632566364eaa18fadaff8721cf8da0006b48f50
https://github.com/ember-cli/ember-cli-test-loader/commit/1965a22282673bcda3d88fa3749672ad988cb954
https://github.com/ember-cli/ember-router-generator/commit/ff83146dc1edbb5113522cad2f2389665efb0768
https://github.com/ember-cli/ember-load-initializers/commit/4a1ca6a78a8fbe326287556c5317463f9b418234
https://github.com/ember-cli/ember-export-application-global/commit/ab2e988f5fdf736e0bee63ac013c81f1deeff519
https://github.com/ember-cli/blueprint/commit/e9399df2de766e0c62adb85cb7f1d0151172b2a6
https://github.com/ember-cli/ember-cli-media/commit/885d0ade641dc68a4b779a8cc7b32a86642b6275

**Pull request closed without merging**
