### PR TITLE
chore: fail test for each-in not accessing props properly whose keys contain a period

### PR DESCRIPTION
**Pull request by jasonmit**
Related to #17529

### CODE REVIEW

**Comment by bekzod** [comment]
probably caused by #17166 I think offending line https://github.com/emberjs/ember.js/blob/master/packages/@ember/-internals/metal/lib/property_get.ts#L99-L101

**Comment by chancancode** [comment]
Seems like the problem is we used to check `obj[key]` before we even check if key is a path? To fix #17529, we can probably call getPath directly with a single-element array. But is this behavior change in #17166 really okay?

**Comment by rwjblue** [comment]
We should add some tests if that is actually a thing we intend to support, but to my knowledge we have never "really" supported `get(obj, 'foo.bar.baz')` finding `obj['foo.bar.baz']`, have we?

**Comment by jasonmit** [comment]
@rwjblue I haven't found anywhere documented detailing this getter path behavior either, so it may have been a bug this app was depending on for a few years.

If we're not supporting it, I'd still like to send over tests so the behavior stays consistent into the future.  In our case it was a bit trolly since the keys were not symbolic of a path they were ISO datetime strings.

**Comment by rwjblue** [comment]
Ya, I totally agree that we should nail down the specific desired behavior with tests. If for nothing more than to ensure we don’t regress and change behavior _again_.

**Comment by kategengler** [comment]
I'm going to go ahead and close this -- this was unspecified behavior and not an area we want to touch going forward.

**Pull request closed without merging**
