### PR TITLE
[BUGFIX release] Add mut to attributes in contextual components

### PR DESCRIPTION
**Pull request by Serabe**
As explained in issue #13061, given a component `change-button` with template:

``` hbs
<button {{action (action (mut val) 10)}}>Change to 10</button>
```

If it is invoked as in the following template:

``` hbs
{{change-button val=value}}
<span class="value">
  {{value}}
</span>
```

Clicking on the button will cause `.value` to contain `10`.

On the other hand, invoking it via a closure component:

``` hbs
{{component (component "change-button" val=value)}}
<span class="value">
  {{value}}
</span>
```

Clicking on the button will not change the text in `.value`.

This PR adds a transform that adds `mut` to params and hash values.

### CODE REVIEW

**Comment by rwjblue** [comment]
I restarted the sauce labs tests, but can you also update the prefix to `[BUGFIX release]` (I think we will want this to land into the LTS)?

**Comment by Serabe** [comment]
Done!

**Comment by rwjblue** [comment]
OK, this looks good to me.  I'm going to land into canary and beta for some testing, but will backport into the LTS before shipping (assuming all is good).

**Comment by rwjblue** [comment]
Thank you @Serabe!

**Comment by Serabe** [comment]
Thanks. If you see any report that might be related to this, just mention
me, please.

**Comment by rwjblue** [comment]
Included in v2.4.4.

**Pull request merged**
