### PR TITLE
[BUGFIX release] Fix #12475

### LINKED ISSUE #12475: Computed Properties broken with @each in 2.1.0
Every computed property based on something using `@each` has broken with the 2.1.0 upgrade. Here are two examples: 

```javascript
  titleUniqueInCollection: Ember.computed('collection.sections.@each.title', function() {
    const sections = this.get('collection.sections');
    const sectionsWithSameTitle = sections.filterBy('title', this.get('title'));
    return sectionsWithSameTitle.length === 1;
  }),
```

```javascript
  sortedCollectionItems: Ember.computed('collectionItems', 'collectionItems.@each.rankPosition', function() {
    return this.get('collectionItems').sortBy('rankPosition');
  }),
```

The functions are no longer running as expected when an attribute is changed. 
Edited to reflect @stefanpenner's comment.

### PR DESCRIPTION
**Pull request by mmun**
Fixes #12475 by reverting the ArrayProxy code to use before-observers. In order to re-remove these before observers we will need to remove the `@array:before` event (AKA the `willChange` part of `array.addArrayObserver({ willChange, didChange })`)

For more details see https://github.com/emberjs/ember.js/pull/12860#issuecomment-179127070.

### CODE REVIEW

**Comment by stefanpenner** [comment]
would like @krisselden :eyes:  on this

**Comment by mmun** [comment]
Me too :sob:

**Comment by rwjblue** [comment]
OK, :green_apple: build now...

**Comment by krisselden** [comment]
I'm definitely sad about the fix, I think we can do something else but we have to fix the regression in the mean time.

**Comment by stefanpenner** [comment]
@krisselden good to merge for now?

**Comment by mmun** [comment]
@krisselden approved on Slack.

**Comment by runspired** [comment]
many tears are shed.

**Comment by mmun** [comment]
On the plus side, this bug got me more familiar with ember-metal. I'm going to spike out lazy array observers and see how bad it breaks my apps :)

**Comment by lozjackson** [comment]
Thankyou very much @mmun for fixing this.. I've been stuck on 2.0.3 because of this bug. I'm now on 2.4.1 and much happier. :)

**Pull request merged**
