### PR TITLE
[BUGFIX beta] Undefined should not set an attribute.

### LINKED ISSUE #10595: Ember 1.11 beta:  input placeholder "undefined"
When binding an input placeholder property to an undefined value, it will render the placeholder with the string "undefined"

http://emberjs.jsbin.com/xegoyofehi/1/

Does work in 1.10. Was occurring in all 1.11 betas I have tested

### PR DESCRIPTION
**Pull request by rwjblue**
Fixes #10595.

### CODE REVIEW

**Comment by rwjblue** [comment]
@mixonic - r?

**Comment by mmun** [comment]
Can you add a few assertions that assert that going from not-nullish to bullish removes the attribute?

**Comment by rwjblue** [comment]
@mmun - Great point!

I'm also going to add some tests that confirm this does not apply to `<div data-foo={{someThingNotThere}}>` as I believe that we intend this to work just like standard HTML (and add the `data-foo` attribute) [JSBin here](http://jsbin.com/mexula/1/edit).

**Comment by rwjblue** [comment]
@mmun - I have changed around the implementation a bit, and added tests as you suggested.  As you guessed the attribute is not removed when moving from an existing value to a `null` value. 

Tracking this down, its basically because we are just calling `element[attrName] = null` (using [setPropertyStrict](https://github.com/tildeio/htmlbars/blob/master/packages/dom-helper/lib/main.js#L236)).

@mixonic / @mmun - Thoughts on fixing this?

**Comment by mixonic** [comment]
placeholder used to be set via an attribute. I'm unsure about a generic way to make property things (value, placeholder) act like attributes.

The logic from `AttributeBindingNode` here can likely be folded back into `AttrNode`. Ideally attribute bindings and htmlbars bound attributes should share behavior, since they definitely will share behavior in Glimmer.

**Comment by rwjblue** [comment]
I originally had it in normal AttrNode, but assumed you didn't want it to apply in non-attributeBinding scenarios. I will move the change in logic back into AttrNode...

The fix here to ensure that placeholder is not set if undefined should likely land before 1.11.0 is released. I still have the general concern (as does @mmun based his comment/question above), but that seems like a larger issue and not isolated to this PR.

I'll update to get this passing shortly.

**Comment by rwjblue** [comment]
Updated to simplify and just modify `AttrNode` so the logic is the same.  Still does not address @mmun's comment (I do not think it is possible with the current strategy of HTMLBars with regards to props & attrs).

@mmun / @mixonic - Should be ready for another round of review.

**Comment by mixonic** [comment]
Thanks sir.

**Pull request merged**
