### PR TITLE
[BUGFIX] Namespaced strings conversions

### LINKED ISSUE #11000: Ember.String wrong conversions for namespaced model name
`Ember.String` methods don't work properly with namespaced model names:
````javascript
  Ember.String.classify("evilMinions/yellowMinion");
//=> unexpected "EvilMinions/yellowMinion"
// expected "EvilMinions/YellowMinion"

  Ember.String.camelize("YellowMinions/MiniPig");
//=> unexpected "yellowMinions/MiniPig"
// expected "yellowMinions/miniPig"
````
Tests and patch here #10980

### PR DESCRIPTION
**Pull request by artych**
Fixes #11000

### CODE REVIEW

**Comment by fivetanley** [comment]
It's not immediately obvious when I read the code what `STRING_CAMELIZE_REGEXP_2` is for. The change itself LGTM but it'd be great for future visits to the code to have something more intention revealing. Reading RegExp's is hard and it's not clear why _2 and not _2 exist

**Comment by artych** [comment]
Thank you, @fivetanley. I will clean up code, but I'd like to understand you correctly. There were at least 3 options of coding in that file before this PR: 
Option 1 (2 regexp vars):
````javascript
var STRING_UNDERSCORE_REGEXP_1 = (/([a-z\d])([A-Z]+)/g);
var STRING_UNDERSCORE_REGEXP_2 = (/\-|\s+/g);
var UNDERSCORE_CACHE = new Cache(1000, function(str) {
  return str.replace(STRING_UNDERSCORE_REGEXP_1, '$1_$2').
    replace(STRING_UNDERSCORE_REGEXP_2, '_').toLowerCase();
});
```` 
Option 2 (1 regexp var, 1 inline regexp):
````javascript
var CAMELIZE_CACHE = new Cache(1000, function(key) {
  return key.replace(STRING_CAMELIZE_REGEXP, function(match, separator, chr) {
    return chr ? chr.toUpperCase() : '';
  }).replace(/^([A-Z])/, function(match, separator, chr) {
    return match.toLowerCase();
  });
});
````
Option 3 (without regexp):
````
var CLASSIFY_CACHE = new Cache(1000, function(str) {
  var parts = str.split(".");
  var out = [];

  for (var i=0, l=parts.length; i<l; i++) {
    var camelized = camelize(parts[i]);
    out.push(camelized.charAt(0).toUpperCase() + camelized.substr(1));
  }

  return out.join(".");
});
````
Quite a diverse mix, isn't it? Which option do you suggest me to follow to make this PR code immediately obvious?

**Comment by artych** [comment]
Since no response, I've clean the code in favor of option 1, moved regexps just before function they used in, added comments. IMHO it looks better now.

**Comment by fivetanley** [comment]
LGTM. Can you amend the commit message to be `[BUGFIX beta]` so it goes out this release?

@stefanpenner r?

**Comment by artych** [comment]
@fivetanley `[BUGFIX beta]` done.

**Comment by artych** [comment]
Looks like forgotten during major changes?

**Comment by rwjblue** [comment]
Yeah, sorry about that.

**Pull request merged**
