### PR TITLE
[BUGFIX release] Fix EmberError import in system/router

### LINKED ISSUE #15237: EmberError or Error
emberDebug does not contain `EmberError` key, but emberDebug.EmberDebug is called
you should change `emberDebug.Error` to `emberDebug.EmberError`

### PR DESCRIPTION
**Pull request by Serabe**
Fixes a simple mistake while extracting debug.

Fixes #15237

### CODE REVIEW

**Comment by Serabe** [comment]
That was the best way I had to check the import was right, not sure it is the best.

Thank you!

**Review by rwjblue — APPROVED** [review]

**Comment by rwjblue** [comment]
@Serabe - Does this issue also exist in Ember 2.13?

**Comment by Serabe** [comment]
Yes. Been there since v2.13.0-beta.1

Do you want me to change to [BUGFIX release]?

**Comment by rwjblue** [comment]
Yes, please

**Comment by Serabe** [comment]
Done!

**Pull request merged**
