### PR TITLE
[WIP] Ensure correct shaping for `isDestroy[ing|ed]` on CoreObject.

### PR DESCRIPTION
**Pull request by rwjblue**
Shaping the prototype is not enough, we should ensure the instance properties are set in the constructor.

### CODE REVIEW

**Comment by mixonic** [comment]
@rwjblue is this something we should be benchmarking to show improvement? Or are you otherwise just waiting on review from a perf team member (I expect @krisselden or @stefanpenner )?

**Comment by rwjblue** [comment]
Yeah, this is still a bit WIP (I'll update it as such).

**Comment by stefanpenner** [comment]
> @rwjblue is this something we should be benchmarking to show improvement?

This is most likely to small a change to notice much.

* today i do not believe those properties are nonEnumerable once set
* setting them via the nonEnumerable path is most likely going to be slower during construction. Is it possible for us to just set them as a property or ideally, move them to meta?

**Comment by krisselden** [comment]
@stefanpenner the states should be moved to meta, and we should have accessors on the prototype that defer to meta for backwards compatibility.

I agree that this PR is a step backwards and that it is dubious to test non enumerability since they are enumerable once set currently.

**Comment by stefanpenner** [comment]
> @stefanpenner the states should be moved to meta, and we should have accessors on the prototype that defer to meta for backwards compatibility.
> 
> I agree that this PR is a step backwards and that it is dubious to test non enumerability since they are enumerable once set currently.

yes

**Comment by rwjblue** [comment]
Completely replaced by https://github.com/emberjs/ember.js/pull/14359

**Pull request closed without merging**
