### PR TITLE
Update emberjs-build to ensure features are replaced in template compiler.

### LINKED ISSUE #10224: Canary regression: ReferenceError: DEFAULT_FEATURES is not defined
Discussed with @rwjblue
```
version: 0.1.7
DEFAULT_FEATURES is not defined
ReferenceError: DEFAULT_FEATURES is not defined
    at _Ember (/Users/jlegg/ember/boot/bower_components/ember/ember-template-compiler.js:203:24)
    at requireModule (/Users/jlegg/ember/boot/bower_components/ember/ember-template-compiler.js:54:65)
    at requireModule (/Users/jlegg/ember/boot/bower_components/ember/ember-template-compiler.js:50:24)
    at /Users/jlegg/ember/boot/bower_components/ember/ember-template-compiler.js:7049:1
    at Object.<anonymous> (/Users/jlegg/ember/boot/bower_components/ember/ember-template-compiler.js:7051:3)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```
--> DEFAULT_FEATURES is supposed to be replaced by the config from Ember's default feature list

### PR DESCRIPTION
**Pull request by rwjblue**
Fixes #10224.

### CODE REVIEW

**Comment by stefanpenner** [comment]
maybe test failures :P

**Comment by rwjblue** [comment]
v0.0.18 of emberjs-build also updates JSCS to latest version which catches more errors.  Appended a commit dealing with those.

**Comment by twokul** [comment]
Travis is emo

**Comment by rwjblue** [comment]
@twokul indeed it is, I have been working on it

**Pull request merged**
