### PR TITLE
[DOC RELEASE] Move htmlSafe and isHTMLSafe to Ember.Template in documentation

### PR DESCRIPTION
**Pull request by locks**
For https://github.com/emberjs/rfcs/pull/236.

### CODE REVIEW

**Comment by Serabe** [comment]
@locks can you add the `[DOC]` tag to the title?

Restarted sauce labs.

**Comment by acorncom** [comment]
@Serabe [DOC] tag to the commit (which looks to be done now) or the PR?

**Comment by Serabe** [comment]
@acorncom usually both.

**Comment by acorncom** [comment]
@Serabe thanks, PR title updated

**Comment by alvincrespo** [comment]
Curious. Why is the @for tag updated to Ember.Component instead of Ember.String. Not apparent to me.

**Comment by locks** [comment]
@alvincrespo part of https://github.com/emberjs/rfcs/pull/236. The RFC still needs some tweaks, which I'll submit post vacations :)

**Comment by alvincrespo** [comment]
Awesome, have a safe and fun vacation - get off the internet 😄

**Comment by rwjblue** [comment]
Will need a rebase to accommodate the changes to the new API docs that @toddjordan did a few weeks ago.

**Comment by toddjordan** [comment]
@locks this should rather be `@for @ember/template`, according to the rfc.  Also, are we updating https://github.com/ember-cli/ember-rfc176-data/blob/master/mappings.json as well?  Also what module/package is this landing in now?  We'll need to add an `@module`

**Comment by locks** [comment]
> this should rather be @for @ember/template, according to the rfc. 

Confirm!

> Also, are we updating https://github.com/ember-cli/ember-rfc176-data/blob/master/mappings.json as well?

@serabe is [taking care of it](https://github.com/ember-cli/ember-rfc176-data/pull/38) :)

**Comment by Serabe** [comment]
Rebased

**Comment by Serabe** [comment]
Restarted one job.

**Review by rwjblue — APPROVED** [review]

**Pull request merged**
