### PR TITLE
Make dependencies that end in `@each` expand to `[]`.

### PR DESCRIPTION
**Pull request by krisselden**
Maybe should also add an assertion about `/@each\..*\./`  to this, but likely should be a separate PR.

### CODE REVIEW

**Comment by rwjblue** [comment]
Looks good to me.  There is a separate issue tracking the `@each..` scenario (I agree that it should be a separate PR).

**Comment by rwjblue** [comment]
Actually https://github.com/emberjs/ember.js/pull/12847 adds the warning for nested `@each.foo.bar` style.

**Comment by mmun** [comment]
:+1:

**Comment by stefanpenner** [comment]
@rwjblue ya seems like we whichever we merge, the other will need to update.

**Comment by rwjblue** [comment]
Ya, I'll land this one first because I need to backport it a ways...

**Comment by rwjblue** [comment]
FYI - I'll be pulling this into 1.13, 2.1, 2.2, 2.3, 2.4-beta branches.

**Comment by rwjblue** [comment]
Cherry picked into beta and release branches.

**Comment by stefanpenner** [comment]
<3

**Pull request merged**
