### PR TITLE
[BUGFIX] Add test for Ember.VERSION SemVer validity

### PR DESCRIPTION
**Pull request by mike-north**
Bug Report: #11256 

Related: https://github.com/cibernox/git-repo-version/pull/7 https://github.com/emberjs/emberjs-build/pull/99

TODO: 
- [x] Test to validate a given version
- [x] Upgrade ember-build [to include the fix for future versions of Ember](//github.com/emberjs/emberjs-build/pull/99)
- [x] A couple of additional tests to prove that this regex works

### CODE REVIEW

**Comment by stefanpenner** [comment]
you should add some tests for known passing/failing versions

**Comment by rwjblue** [comment]
emberjs-build 0.1.2 released

**Comment by truenorth** [comment]
Awesome. I'll update the pr tonight

**Comment by rwjblue** [comment]
Ugh.  Tests fail because we have two plusses now for canary.  Lets make https://github.com/emberjs/ember.js/blob/master/package.json#L4 be `2.0.0-canary` (which means the full `Ember.VERSION` would be `2.0.0-canary+123123`. Seems much easier to understand than `2.0.0-beta.1+canary.123123` anyways.

**Comment by truenorth** [comment]
@rwjblue that seems to be the choice most in alignment with SemVer, essentially making "canary" another value for the "pre-release" (along with "beta")

**Comment by rwjblue** [comment]
Agreed.  Lets doo eeet...

**Comment by rwjblue** [comment]
Thank you!

**Pull request merged**
