### PR TITLE
[CLEANUP beta] Remove deprecated Ember.View support from Ember global

### LINKED ISSUE #11775: Remove Ember.View support when not using ember-legacy-views addon.
* Only export the following when `Ember.ENV._ENABLE_LEGACY_VIEW_SUPPORT` is set:
  * [x] `Ember.CoreView` [here](https://github.com/emberjs/ember.js/blob/master/packages/ember-views/lib/main.js#L65) removed in https://github.com/emberjs/ember.js/pull/11794
  * [x] `Ember.View` [here](https://github.com/emberjs/ember.js/blob/master/packages/ember-views/lib/main.js#L66-L69) removed in https://github.com/emberjs/ember.js/pull/11794
  * [x] `Ember.Select` [here](https://github.com/emberjs/ember.js/blob/master/packages/ember-views/lib/main.js#L74) removed in https://github.com/emberjs/ember.js/pull/11794
  * [x] `Ember._Metamorph` [here](https://github.com/emberjs/ember.js/blob/master/packages/ember-views/lib/main.js#L86) removed in https://github.com/emberjs/ember.js/pull/11794
  * [x] `Ember._MetamorphView` [here](https://github.com/emberjs/ember.js/blob/master/packages/ember-views/lib/main.js#L87) removed in https://github.com/emberjs/ember.js/pull/11794
  * [x] `Ember._LegacyEachView` [here](https://github.com/emberjs/ember.js/blob/master/packages/ember-views/lib/main.js#L88) removed in https://github.com/emberjs/ember.js/pull/11794
* Only add the following AST Transforms when `Ember.ENV._ENABLE_LEGACY_VIEW_SUPPORT` is set:
  * [x] `TransformEachIntoCollection` [here](https://github.com/emberjs/ember.js/blob/master/packages/ember-template-compiler/lib/main.js#L28)
  * [x] `DeprecateViewAndControllerPaths` [here](https://github.com/emberjs/ember.js/blob/master/packages/ember-template-compiler/lib/main.js#L37)
  * [x] `DeprecateViewHelper` [here](https://github.com/emberjs/ember.js/blob/master/packages/ember-template-compiler/lib/main.js#L38)
* Only add the following keywords/helpers when `` is set:
  * [x] `{{view}}` [here](https://github.com/emberjs/ember.js/blob/master/packages/ember-htmlbars/lib/env.js#L94)
  * [x] `legacyEachWithControllerHelper` [here](https://github.com/emberjs/ember.js/blob/master/packages/ember-htmlbars/lib/main.js#L80)
  * [x] `legacyEachWithKeywordHelper ` [here](https://github.com/emberjs/ember.js/blob/master/packages/ember-htmlbars/lib/main.js#L81)
* Fix all the tests. :trollface:

### PR DESCRIPTION
**Pull request by ghost**
Addresses global exports listed in #11775

### CODE REVIEW

**Comment by rwjblue** [comment]
This looks like it addressed the global exports for #11775, lets land this then continue to work down that list.

**Comment by rwjblue** [comment]
* [ ] Removing `Ember.View._Renderer` [here](https://github.com/emberjs/ember.js/blob/680f997ed0958c420abdcd0b1673111aee26afe7/packages/ember-views/lib/main.js#L69) is causing [tests/node/app-boot-test.js](https://github.com/emberjs/ember.js/blob/master/tests/node/app-boot-test.js) to fail (which means ember-cli-fastboot needs to be updated to grab [this](https://github.com/tildeio/ember-cli-fastboot/blob/a74437ef87aec2960251975efd77ec895e21912c/app/initializers/fastboot.js#L26) from another location).  We can export it as `Ember._Renderer` for now (unless @mixonic or @tomdale have another preference), then PR to ember-cli-fastboot to do something like `var Renderer = Ember._Renderer || Ember.View._Renderer;`.
* [ ] Update [tests/node/app-boot-test.js](https://github.com/emberjs/ember.js/blob/master/tests/node/app-boot-test.js) to extend from `Ember.Component` [here](https://github.com/emberjs/ember.js/blob/a49526b9d07377a191ff9a43c73e5df49f3cca3c/tests/node/app-boot-test.js#L154)
* [ ] `Ember.View` needs to be changed to use `Ember.Component` helper [here](https://github.com/emberjs/ember.js/blob/a49526b9d07377a191ff9a43c73e5df49f3cca3c/tests/node/app-boot-test.js#L193)

**Comment by martndemus** [comment]
Should this be included in this or a other pull request?

**Comment by rwjblue** [comment]
I think it will need to be this one, because the node test suite (which is required for Travis to be green) will not pass without the above changes.

Also, you can run these tests yourself via `bin/run-node-tests.js` (assuming you have an instance of `ember server` or `npm start` running).

**Comment by martndemus** [comment]
~~Thats much faster then `TEST_SUITE=node npm test`~~

I have added the changes to the node tests.

**Comment by rwjblue** [comment]
https://github.com/tildeio/ember-cli-fastboot/pull/51 updates ember-cli-fastboot to use `Ember._Renderer` if present, I'll merge that shortly after this is merged.

**Comment by martndemus** [comment]
I was just about to open a PR for that, but you beat me to it. :+1:

**Pull request merged**
