### PR TITLE
deprecate `disabledWhen` in `link-to`

### PR DESCRIPTION
**Pull request by bekzod**
just to align `link-to` with other components

### CODE REVIEW

**Comment by bekzod** [comment]
can add tests confirming that `disabled` works like `disabledWhen` if necessary (by just duplicate `disabledWhen` tests)

**Comment by locks** [comment]
I'm confused @bekzod, is this attached to an RFC?

**Comment by bekzod** [comment]
@locks should it have RFC :P ? I think most people would agree that `disabledWhen` is weird part of `link-to` which needs ironed out :)

**Comment by locks** [comment]
Yup, it is through deprecation RFCs (in this case) that we communicate changes to the public API to the community. If there is already consensus on deprecating it, it will make for a very quick RFC ;)
Also want to note that new deprecations in 2.x should to be until 3.5.0, to avoid a deprecation explosion before 3.0.0.

**Comment by bekzod** [comment]
@locks wohoo my first RFC :P

**Comment by bekzod** [comment]
@locks added small rfcs https://github.com/emberjs/rfcs/pull/267

**Comment by Serabe** [comment]
This PR is loosing test coverage. All the tests that were added an `expectDeprecation` need to be redone for `disabled`

**Comment by bekzod** [comment]
@Serabe done

**Comment by locks** [comment]
Closing it since the underlying code has changed significantly, and the router service has shipped meanwhile. Thanks for your continued contributions :)

**Pull request closed without merging**
