### PR TITLE
[CLEANUP] Remove tests that were ported

### PR DESCRIPTION
**Pull request by chadhietala**
I believe all of these were ported in #13491 #13451 #13213.
- I believe #13491 and #13522 must have gotten lost because I moved the file
- In #13451 the ported tests were never deleted
- #13213 The test that was left was testing `view` keyword stuff which we are actively trying to remove.

### CODE REVIEW

**Comment by rwjblue** [comment]
👍

**Comment by stefanpenner** [comment]
> ☔ The latest upstream changes (presumably e5e6d25) made this pull request unmergeable. Please resolve the merge conflicts.

@chadhietala ^

**Comment by krisselden** [comment]
not sure why that didn't kick off a Travis build

**Comment by krisselden** [comment]
@homu +r

**Pull request merged**
