### PR TITLE
[CLEANUP beta] Remove deprecated Controller#controllerFor

### PR DESCRIPTION
**Pull request by ghost**
Controller#controllerFor has been deprecated, this commit removes the functionality.

Needs rebase once #11770 is merged.

### CODE REVIEW

**Comment by stefanpenner** [comment]
Although deprecated, we should be enumerate what need to enumerate:

1. what needs to be supported by legacy addon
2. what needs to continue to be in core to support basic controllers (since we dont have routable components yet)
3. anything else i'm missing?

**Comment by rwjblue** [comment]
Ready for rebase.

**Comment by martndemus** [comment]
Rebase'd

**Comment by martndemus** [comment]
@stefanpenner `Use `Ember.inject.controller()` instead.` ?

**Comment by rwjblue** [comment]
This isn't removing the fundamental capability (since `inject.controller()` works just fine), it is only removing the syntax of using `needs` instead of `inject.controller()`. This seems unlike `{{view}}` and friends where there is no alternative path.

**Comment by stefanpenner** [comment]
This seems likely it may want to be part of the legacy controllers addon, what do others think? cc @cibernox

**Comment by cibernox** [comment]
It could go into the addon, but I don't see a strong necessity since there is an alternative syntax to get the same result. I see this more like a ember-watson task for help in the migration.

**Comment by cibernox** [comment]
@abuiles you think that it's viable to to create a task that transform `needs` into `Ember.inject.controller()` and the replaces occurences of `this.controllerFor('whatever')` by `this.get('whatever')`?

**Comment by martndemus** [comment]
@cibernox @abuiles You would also have to transform `this.get('controllers.whatever')`

**Comment by cibernox** [comment]
True. 
Even if it's not really viable to automate the transformation I don't think that we should keep that feature alive in the addon since the functionality is still here just under a different syntax.

**Comment by stefanpenner** [comment]
> I see this more like a ember-watson task for help in the migration.

true

**Comment by martndemus** [comment]
I removed this branch per accident.

**Pull request merged**
