### PR TITLE
[FEATURE "ember-routing-transitioning-classes”]

### PR DESCRIPTION
**Pull request by machty**
Disables eager URL updates during slow transitions in favor of new CSS classes
added to `link-to`s (in addition to `active` class):
- `transitioning-in`: link-to is not currently active, but will be
  when the current underway (slow) transition completes.
- `transitioning-out`: link-to is currently active, but will no longer
  be active when the current underway (slow) transition completes.

This reverts the feature we added some months ago to eagerly update the URL even when a transition takes a while to complete; we realized that certain bugs (e.g. #5210 and #4908) didn't really otherwise have a clean solution since the original feature was at odds with the URL behavior people have come to expect from browsers.

### CODE REVIEW

**Comment by ef4** [comment]
Anything I can do to help GO this feature?

**Comment by machty** [comment]
@ef4 ? did you post to wrong issue?

**Comment by ef4** [comment]
No. I'm seeing code that is still wrapped in this feature flag. Should it not be?

**Comment by ef4** [comment]
For context: I am cleaning up link-to to be a normal component, so I'm dealing with the transitioning classes.

**Comment by rwjblue** [comment]
It is enabled by default. Flags can be removed.

**Comment by ef4** [comment]
Cool, will do.

**Pull request merged**
