### PR TITLE
[DOC RELEASE] Ember 1.13 Component Lifecycle Events API Docs

### LINKED ISSUE #13244: didReceiveAttrs and friends from 1.13 not documented in API
I would be willing to write and PR this but I am not sure which file the documentation belongs. It may be Ember.ViewTargetActionSupport?

### PR DESCRIPTION
**Pull request by Gaurav0**
Fixes #13244

screen shot 2016-04-04 at 5 17 38 pm

### CODE REVIEW

**Comment by rwjblue** [comment]
This documents the evented versions of these, can we also document the methods themselves (which I think should be the primary way to use these hooks)?

**Comment by Gaurav0** [comment]
@rwjblue Sure. Done!

**Comment by rwjblue** [comment]
Looks like some JSCS errors with trailing white space are failing the build here. Can you take a look?

**Comment by Gaurav0** [comment]
@rwjblue Fixed.

**Comment by rwjblue** [comment]
@Gaurav0 - Would you mind squashing, and prefixing the remaining commit with `[DOC release]`?

This LGTM, @acorncom / @locks would one of y'all mind reviewing also?

**Comment by locks** [comment]
I'm a bit iffy of so many `view` references, but I've read it and it looks good.

**Comment by rwjblue** [comment]
@locks - The screenshot says "view", but the diff uses "component" (the screenshot wasn't updated after the last round of changes).

**Pull request merged**
