### PR TITLE
guard against nodes changing due to a prior iteration

### LINKED ISSUE #13470: ChainWatchers.notify errors on _notifyProperties by ED
``` no-highlight
TypeError: Cannot read property 'notify' of undefined
    at Object.ChainWatchers.notify (http://crcogct.localhost:3000/dashboard/assets/vendor.js:28475:17)
    at chainsDidChange (http://crcogct.localhost:3000/dashboard/assets/vendor.js:34505:9)
    at Object.propertyDidChange (http://crcogct.localhost:3000/dashboard/assets/vendor.js:34415:5)
    at contentPropertyDidChange (http://crcogct.localhost:3000/dashboard/assets/vendor.js:46339:32)
    at Object.apply (http://crcogct.localhost:3000/dashboard/assets/vendor.js:37154:18)
    at Object.sendEvent (http://crcogct.localhost:3000/dashboard/assets/vendor.js:30699:28)
    at ObserverSet.flush (http://crcogct.localhost:3000/dashboard/assets/vendor.js:34022:25)
    at Object.endPropertyChanges (http://crcogct.localhost:3000/dashboard/assets/vendor.js:34533:19)
    at _notifyProperties (http://crcogct.localhost:3000/dashboard/assets/vendor.js:127142:25)
    at InternalModel.adapterDidCommit (http://crcogct.localhost:3000/dashboard/assets/vendor.js:126466:19)
```

I'm using Ember 2.5.1 and Ember Data 2.5.2.

The error seems like it could be avoided on the Ember side. Not sure what would make the node undefined, but there should probably be a check, because otherwise it rejects the `model.save()` promise (although the save works, but any `then`s do not fire).

> Original issue https://github.com/lytics/ember-data-model-fragments/issues/198

### PR DESCRIPTION
**Pull request by christophersansone**
Fixes #13470 in the 1.x branch.  I'm not sure how to write a reasonable test since we have yet to isolate a minimum test case.  Any help or guidance would be appreciated!

### CODE REVIEW

**Comment by krisselden** [comment]
Thanks for digging into this, this stops it from throwing an exception but it doesn't actually ensure the state is ok, the issue is you are implying that the state is being mutated as a side effect of computing the chain value, we made need to copy state.  I really need a reproduction.  Even a stack trace from the value() can you console.trace() there?

**Comment by christophersansone** [comment]
Thanks @krisselden!  I dove pretty deep into the evaluation of `value()`, and right at this spot in the stack below, I watched `nodes.length` go from 3 to 2 to 1 as it iterated through the calls to `propertyDidChange`.

Let me explain what is happening in the app when this occurs.  The data is an n-level tree: an object of its type can contain an array of other objects of its type, like a tree view or DOM elements.  I'm using `ember-data-model-fragments` to build models for each object from the nested data structure.  At the root of the tree is an actual ED model that contains the fragments.  There are a couple different visual representations of each object (components) at the time of the error.  The issue occurs when I save the ED model.  The HTTP request is successful, but the error occurs when the nested data is torn down and rebuilt from the response, with all the components still attached.

The error does not occur all the time with any sort of data.  There is a correlation between the size / complexity of the data and the chances of it occurring.  Small models do not exhibit, larger models exhibit occasionally, and still larger ones can reproduce the error every time.

Stack trace below.  Thanks again!

```
Error
    at dependentKeysDidChange (vendor.js:31134:7)
    at propertyDidChange (vendor.js:31086:7)
    at chainsDidChange (vendor.js:31223:7)
    at Object.propertyDidChange (vendor.js:31089:5)
    at exports.default._emberMetalMixin.Mixin.create.propertyDidChange (vendor.js:47434:34)
    at exports.default._emberMetalMixin.Mixin.create.notifyPropertyChange (vendor.js:47448:12)
    at Ember.Object.extend._notifyProperties (vendor.js:76384:16)
    at InternalModel.ember$data$lib$system$model$internal$model$$InternalModel.setupData (vendor.js:82182:23)
    at model$fragments$lib$fragments$fragment$$setFragmentData (vendor.js:88965:74)
    at /assets/vendor.js:89061:15
    at Array.map (native)
    at model$fragments$lib$util$map$$map (vendor.js:88996:28)
    at model$fragments$lib$fragments$array$fragment$$normalizeFragmentArray (vendor.js:89040:14)
    at model$fragments$lib$fragments$array$stateful$$default.extend._normalizeData (vendor.js:89103:16)
    at ember$lib$main$$default.ArrayProxy.extend.setupData (vendor.js:88322:34)
    at setupFragmentArray (vendor.js:89602:21)
    at model$fragments$lib$util$ember$new$computed$$default.get (vendor.js:89570:26)
    at Descriptor.ComputedPropertyPrototype.get (vendor.js:25514:26)
    at get (vendor.js:31389:19)
    at _getPath (vendor.js:31473:14)
    at Object.get (vendor.js:31385:14)
    at Descriptor.AliasedProperty_get [as get] (vendor.js:24013:36)
    at Object.get (vendor.js:31389:19)
    at lazyGet (vendor.js:24897:36)
    at Object.ChainNode.value (vendor.js:24904:23)
    at Object.ChainNode.didChange (vendor.js:25094:32)
    at Object.ChainNode.didChange (vendor.js:25116:23)
THIS IS WHERE nodes.length CHANGES ---->    at chainsDidChange (vendor.js:31214:14)
    at propertyDidChange (vendor.js:31089:5)
    at iterDeps (vendor.js:31176:9)
    at dependentKeysDidChange (vendor.js:31132:7)
    at propertyDidChange (vendor.js:31086:7)
    at chainsDidChange (vendor.js:31223:7)
    at Object.propertyDidChange (vendor.js:31089:5)
    at exports.default._emberMetalMixin.Mixin.create.propertyDidChange (vendor.js:47434:34)
    at exports.default._emberMetalMixin.Mixin.create.notifyPropertyChange (vendor.js:47448:12)
    at Ember.Object.extend._notifyProperties (vendor.js:76384:16)
    at InternalModel.ember$data$lib$system$model$internal$model$$InternalModel.setupData (vendor.js:82182:23)
    at model$fragments$lib$fragments$fragment$$setFragmentData (vendor.js:88965:74)
    at /assets/vendor.js:89061:15
    at Array.map (native)
    at model$fragments$lib$util$map$$map (vendor.js:88996:28)
    at model$fragments$lib$fragments$array$fragment$$normalizeFragmentArray (vendor.js:89040:14)
    at model$fragments$lib$fragments$array$stateful$$default.extend._normalizeData (vendor.js:89103:16)
    at ember$lib$main$$default.ArrayProxy.extend.setupData (vendor.js:88322:34)
    at setupFragmentArray (vendor.js:89602:21)
    at model$fragments$lib$util$ember$new$computed$$default.get (vendor.js:89570:26)
    at Descriptor.ComputedPropertyPrototype.get (vendor.js:25514:26)
    at get (vendor.js:31389:19)
    at _getPath (vendor.js:31473:14)
    at Object.get (vendor.js:31385:14)
    at exports.default._emberMetalMixin.Mixin.create.get (vendor.js:47274:38)
    at .<anonymous> (app.js:51616:21)
    at Descriptor.ComputedPropertyPrototype.get (vendor.js:25514:26)
    at Object.get (vendor.js:31389:19)
    at exports.default._emberMetalMixin.Mixin.create.get (vendor.js:47274:38)
    at .<anonymous> (app.js:51628:21)
    at Descriptor.ComputedPropertyPrototype.get (vendor.js:25514:26)
    at Object.get (vendor.js:31389:19)
    at Object._emberMetalMerge.default.compute (vendor.js:32520:40)
    at Object.Stream.value (vendor.js:32704:27)
    at Object.read (vendor.js:33045:21)
    at Dependency._emberMetalMerge.default.getValue (vendor.js:32463:38)
    at Object._emberMetalMerge.default.compute (vendor.js:32518:35)
    at Object.Stream.value (vendor.js:32704:27)
    at Object.read (vendor.js:33045:21)
    at Object.compute (vendor.js:19109:31)
    at Object.Stream.value (vendor.js:32704:27)
    at Object.read (vendor.js:33045:21)
    at getValue (vendor.js:18971:41)
    at each (vendor.js:19747:35)
    at handleKeyword (vendor.js:62585:14)
    at handleRedirect (vendor.js:62571:9)
    at Object.block (vendor.js:62532:9)
    at Object._htmlbarsUtilObjectUtils.merge.block (vendor.js:61763:17)
    at /assets/vendor.js:61851:28
    at dirtyCheck (vendor.js:61906:7)
    at Object.exports.default._htmlbarsUtilObjectUtils.merge.block (vendor.js:61850:7)
    at RenderResult.populateNodes (vendor.js:63428:19)
    at RenderResult.revalidateWith (vendor.js:63402:10)
    at Object.validateChildMorphs (vendor.js:63764:24)
    at dirtyCheck (vendor.js:61911:31)
    at Object.exports.default._htmlbarsUtilObjectUtils.merge.content (vendor.js:61864:7)
    at RenderResult.populateNodes (vendor.js:63432:19)
    at RenderResult.revalidateWith (vendor.js:63402:10)
    at ComponentNodeManager.block (vendor.js:63959:31)
    at ComponentNodeManager.<anonymous> (vendor.js:21408:14)
    at Object.instrument (vendor.js:22153:23)
    at ComponentNodeManager.rerender (vendor.js:21386:55)
    at Object.componentHook [as component] (vendor.js:18675:21)
    at handleRedirect (vendor.js:62560:21)
    at Object.inline (vendor.js:62714:9)
    at Object._htmlbarsUtilObjectUtils.merge.inline (vendor.js:61774:17)
    at /assets/vendor.js:61858:28
    at dirtyCheck (vendor.js:61906:7)
    at Object.exports.default._htmlbarsUtilObjectUtils.merge.inline (vendor.js:61857:7)
    at RenderResult.populateNodes (vendor.js:63430:19)
    at RenderResult.revalidateWith (vendor.js:63402:10)
    at Object.validateChildMorphs (vendor.js:63764:24)
    at dirtyCheck (vendor.js:61911:31)
    at Object.exports.default._htmlbarsUtilObjectUtils.merge.content (vendor.js:61864:7)
    at RenderResult.populateNodes (vendor.js:63432:19)
    at RenderResult.revalidateWith (vendor.js:63402:10)
    at Object.validateChildMorphs (vendor.js:63764:24)
    at dirtyCheck (vendor.js:61911:31)
    at Object.exports.default._htmlbarsUtilObjectUtils.merge.inline (vendor.js:61857:7)
    at RenderResult.populateNodes (vendor.js:63430:19)
    at RenderResult.revalidateWith (vendor.js:63402:10)
    at validateChildMorphs (vendor.js:63764:24)
    at Object.validateChildMorphs (vendor.js:63760:9)
    at dirtyCheck (vendor.js:61911:31)
    at Object.exports.default._htmlbarsUtilObjectUtils.merge.block (vendor.js:61850:7)
    at RenderResult.populateNodes (vendor.js:63428:19)
    at RenderResult.revalidateWith (vendor.js:63402:10)
    at Object.validateChildMorphs (vendor.js:63764:24)
    at dirtyCheck (vendor.js:61911:31)
    at Object.exports.default._htmlbarsUtilObjectUtils.merge.block (vendor.js:61850:7)
    at RenderResult.populateNodes (vendor.js:63428:19)
    at RenderResult.revalidateWith (vendor.js:63402:10)
    at Object.validateChildMorphs (vendor.js:63764:24)
    at dirtyCheck (vendor.js:61911:31)
    at Object.exports.default._htmlbarsUtilObjectUtils.merge.inline (vendor.js:61857:7)
    at RenderResult.populateNodes (vendor.js:63430:19)
    at RenderResult.revalidateWith (vendor.js:63402:10)
    at Object.validateChildMorphs (vendor.js:63764:24)
    at dirtyCheck (vendor.js:61911:31)
    at Object.exports.default._htmlbarsUtilObjectUtils.merge.content (vendor.js:61864:7)
    at RenderResult.populateNodes (vendor.js:63432:19)
    at RenderResult.revalidateWith (vendor.js:63402:10)
    at Object.validateChildMorphs (vendor.js:63764:24)
    at dirtyCheck (vendor.js:61911:31)
    at Object.exports.default._htmlbarsUtilObjectUtils.merge.block (vendor.js:61850:7)
    at RenderResult.populateNodes (vendor.js:63428:19)
    at RenderResult.revalidateWith (vendor.js:63402:10)
    at Object.validateChildMorphs (vendor.js:63764:24)
    at dirtyCheck (vendor.js:61911:31)
    at Object.exports.default._htmlbarsUtilObjectUtils.merge.inline (vendor.js:61857:7)
    at RenderResult.populateNodes (vendor.js:63430:19)
    at RenderResult.revalidateWith (vendor.js:63402:10)
    at Object.validateChildMorphs (vendor.js:63764:24)
    at dirtyCheck (vendor.js:61911:31)
    at Object.exports.default._htmlbarsUtilObjectUtils.merge.content (vendor.js:61864:7)
    at RenderResult.populateNodes (vendor.js:63432:19)
    at RenderResult.revalidateWith (vendor.js:63402:10)
    at Object.validateChildMorphs (vendor.js:63764:24)
    at dirtyCheck (vendor.js:61911:31)
    at Object.exports.default._htmlbarsUtilObjectUtils.merge.block (vendor.js:61850:7)
    at RenderResult.populateNodes (vendor.js:63428:19)
    at RenderResult.revalidateWith (vendor.js:63402:10)
    at Object.validateChildMorphs (vendor.js:63764:24)
    at dirtyCheck (vendor.js:61911:31)
    at Object.exports.default._htmlbarsUtilObjectUtils.merge.content (vendor.js:61864:7)
    at RenderResult.populateNodes (vendor.js:63432:19)
    at RenderResult.revalidateWith (vendor.js:63402:10)
    at ComponentNodeManager.block (vendor.js:63959:31)
    at ComponentNodeManager.<anonymous> (vendor.js:21408:14)
    at Object.instrument (vendor.js:22153:23)
    at ComponentNodeManager.rerender (vendor.js:21386:55)
    at Object.componentHook [as component] (vendor.js:18675:21)
    at handleRedirect (vendor.js:62560:21)
    at Object.inline (vendor.js:62714:9)
    at Object._htmlbarsUtilObjectUtils.merge.inline (vendor.js:61774:17)
    at /assets/vendor.js:61858:28
    at dirtyCheck (vendor.js:61906:7)
    at Object.exports.default._htmlbarsUtilObjectUtils.merge.inline (vendor.js:61857:7)
    at RenderResult.populateNodes (vendor.js:63430:19)
    at RenderResult.revalidateWith (vendor.js:63402:10)
    at Object.validateChildMorphs (vendor.js:63764:24)
    at dirtyCheck (vendor.js:61911:31)
    at Object.exports.default._htmlbarsUtilObjectUtils.merge.content (vendor.js:61864:7)
    at RenderResult.populateNodes (vendor.js:63432:19)
    at RenderResult.revalidateWith (vendor.js:63402:10)
    at Object.validateChildMorphs (vendor.js:63764:24)
    at dirtyCheck (vendor.js:61911:31)
    at Object.exports.default._htmlbarsUtilObjectUtils.merge.content (vendor.js:61864:7)
    at RenderResult.populateNodes (vendor.js:63432:19)
    at RenderResult.revalidateWith (vendor.js:63402:10)
    at Object.validateChildMorphs (vendor.js:63764:24)
    at dirtyCheck (vendor.js:61911:31)
    at Object.exports.default._htmlbarsUtilObjectUtils.merge.block (vendor.js:61850:7)
    at RenderResult.populateNodes (vendor.js:63428:19)
    at RenderResult.revalidateWith (vendor.js:63402:10)
    at Object.validateChildMorphs (vendor.js:63764:24)
    at dirtyCheck (vendor.js:61911:31)
    at Object.exports.default._htmlbarsUtilObjectUtils.merge.content (vendor.js:61864:7)
    at RenderResult.populateNodes (vendor.js:63432:19)
    at RenderResult.revalidateWith (vendor.js:63402:10)
    at Object.validateChildMorphs (vendor.js:63764:24)
    at dirtyCheck (vendor.js:61911:31)
    at Object.exports.default._htmlbarsUtilObjectUtils.merge.content (vendor.js:61864:7)
    at RenderResult.populateNodes (vendor.js:63432:19)
    at RenderResult.revalidateWith (vendor.js:63402:10)
    at Object.validateChildMorphs (vendor.js:63764:24)
    at dirtyCheck (vendor.js:61911:31)
    at Object.exports.default._htmlbarsUtilObjectUtils.merge.content (vendor.js:61864:7)
    at RenderResult.populateNodes (vendor.js:63432:19)
    at RenderResult.revalidateWith (vendor.js:63402:10)
    at Object.validateChildMorphs (vendor.js:63764:24)
    at dirtyCheck (vendor.js:61911:31)
    at Object.exports.default._htmlbarsUtilObjectUtils.merge.content (vendor.js:61864:7)
    at RenderResult.populateNodes (vendor.js:63432:19)
    at RenderResult.revalidateWith (vendor.js:63402:10)
    at Object.validateChildMorphs (vendor.js:63764:24)
    at dirtyCheck (vendor.js:61911:31)
    at Object.exports.default._htmlbarsUtilObjectUtils.merge.content (vendor.js:61864:7)
    at RenderResult.populateNodes (vendor.js:63432:19)
    at RenderResult.revalidateWith (vendor.js:63402:10)
    at Object.validateChildMorphs (vendor.js:63764:24)
    at dirtyCheck (vendor.js:61911:31)
    at Object.exports.default._htmlbarsUtilObjectUtils.merge.content (vendor.js:61864:7)
    at RenderResult.populateNodes (vendor.js:63432:19)
    at RenderResult.revalidateWith (vendor.js:63402:10)
    at Object.validateChildMorphs (vendor.js:63764:24)
    at dirtyCheck (vendor.js:61911:31)
    at Object.exports.default._htmlbarsUtilObjectUtils.merge.content (vendor.js:61864:7)
    at RenderResult.populateNodes (vendor.js:63432:19)
    at RenderResult.revalidateWith (vendor.js:63402:10)
    at RenderResult.revalidate (vendor.js:63379:10)
    at Renderer_revalidateTopLevelView [as revalidateTopLevelView] (vendor.js:23556:35)
    at _emberViewsViewsCore_view.default.extend.revalidate (vendor.js:61360:21)
    at Queue.invoke (vendor.js:11582:16)
    at Object.Queue.flush (vendor.js:11646:11)
    at Object.DeferredActionQueues.flush (vendor.js:11447:17)
    at Object.Backburner.end (vendor.js:10736:25)
    at Object.Backburner.run (vendor.js:10858:18)
    at Object.run (vendor.js:31705:27)
    at hash.success (vendor.js:72919:21)
    at fire (vendor.js:3357:30)
    at Object.self.fireWith [as resolveWith] (vendor.js:3469:7)
    at done (vendor.js:9523:14)
    at XMLHttpRequest.callback (vendor.js:9927:8)
```

**Comment by christophersansone** [comment]
Working to reproduce it, but no luck so far.  Here's the [twiddle](https://canary.ember-twiddle.com/695a91d44f35a9a9554094fc9ea043c5?openFiles=controllers.application.js%2Ctemplates.components.div-view.hbs) I'm working on.  It's a tough one!

**Comment by christophersansone** [comment]
I worked on the twiddle but still cannot reproduce.  This is [my latest attempt](https://canary.ember-twiddle.com/695a91d44f35a9a9554094fc9ea043c5), which traverses the tree in both directions.  I'm not sure what else I can try.

**Comment by mmun** [comment]
I'm closing this PR (and the [related issue](https://github.com/emberjs/ember.js/issues/13470)) as it's not clear that it is an error with Ember. Please chime in if you'd like us to reopen this issue.

**Pull request closed without merging**
