### PR TITLE
Update view.js

### PR DESCRIPTION
**Pull request by stefanpenner**
ensure views and components all shape with an attrs slot

### CODE REVIEW

**Comment by chadhietala** [comment]
Probably should add a test to verify the objects are of the same shape so we don't regress in the future.

**Comment by stefanpenner** [comment]
> Probably should add a test to verify the objects are of the same shape so we don't regress in the future.

This is tricky, I am unsure if there is a good solution. In theory, in d8/node we may be able to tap into some shape allocation logging?

**Comment by chadhietala** [comment]
I'm just say we there needs to be something from having this accidentally removed. A person not aware of V8 hidden classes will be confused.  A simple `view.attr === undefined` test might be good enough for now, but yes a long term anti-regression system would be preferred.

**Comment by stefanpenner** [comment]
> I'm just say there needs to be a guard from having this accidentally removed. A person not aware of V8 hidden classes will be confused. A simple view.attrs === undefined test might be good enough for now, but yes a long term anti-regression system would be preferred.

we can likely add a test helper that does.

`ensurePropertiesOnSelf(entity, ['list', 'of', 'properties', 'that', 'must', 'be', 'on', 'this', 'and', 'not', 'prototype'])`

**Comment by stefanpenner** [comment]
hmm this is actually not a bad idea...

**Comment by stefanpenner** [comment]
after some further investigation, `component.create()` already assigns attrs, so the shape is correct. Just not obviously so.

**Pull request closed without merging**
