### PR TITLE
enhance custom location API documentation 

### PR DESCRIPTION
**Pull request by H1D**
didn't  find anything on how to register cutom location implementation for router.

Not sure should i use `ember-cli` code examples with `export default {` instead of `Em.Application.initializer({`

### CODE REVIEW

**Comment by rwjblue** [comment]
This seems similar to https://github.com/emberjs/ember.js/pull/12737 (i.e. how to have a custom location implementation).  Can you update to avoid the use of an initializer?

**Comment by H1D** [comment]
@rwjblue done

**Comment by rwjblue** [comment]
There is some extra trailing whitespace that is causing the build to fail here.

**Comment by H1D** [comment]
@rwjblue looks good now

**Comment by rwjblue** [comment]
Thank you @H1D!

**Pull request merged**
