### PR TITLE
Cherry-picked @rwjblue's commit to fix the node tests.

### PR DESCRIPTION
**Pull request by workmanw**
> Fix node tests.
> 
> QUnit 1.19 was released and changed the way the npm package exports its value (it no longer sets up `global.QUnit` and all the assertion methods automatically).
> 
> This updates to a better pattern of importing `QUnit` and using the `assert` argument for assertions.

So this technically doesn't "fix them". I think there is a genuine failure here, they're busted on master. But this does make it possible to run the tests without a QUnit issue.

### CODE REVIEW

**Comment by rwjblue** [comment]
Issues in release branch should be fixed now, can you rebase and drop out that extra commit?

**Comment by workmanw** [comment]
@rwjblue Happy to.

**Comment by workmanw** [comment]
Still one failing :( 

I was trying to just be helpful here, but if it's easier for you to take the wheel you can close this PR. Whatever's easiest.

**Comment by rwjblue** [comment]
That last failure is transient.  Haven't had a chance to track it down yet.

**Comment by workmanw** [comment]
@rwjblue Cool. Two down, one to go. I'll cherry-pick to beta.

**Comment by stefanpenner** [comment]
@workmanw thanks for all the help here :)

**Comment by workmanw** [comment]
@stefanpenner Happy to help :)

**Pull request merged**
