### PR TITLE
[CLEANUP beta] Remove legacy behaviour from yield

### PR DESCRIPTION
**Pull request by cibernox**
Is it neccessary to mantain any addon? No test failed after removing it.
Suspicious....

@mixonic Am I missing something here?

### CODE REVIEW

**Comment by rwjblue** [comment]
It is used in the legacy each case (when itemController, itemViewClass, itemView, etc are used). 

* https://github.com/emberjs/ember.js/blob/master/packages/ember-template-compiler/lib/plugins/transform-each-into-collection.js#L29
* https://github.com/emberjs/ember.js/blob/master/packages/ember-views/lib/views/legacy_each_view.js
* https://github.com/emberjs/ember.js/blob/master/packages/ember-htmlbars/lib/templates/legacy-each.hbs

**Comment by cibernox** [comment]
@rwjblue I saw that, but all those behaviours are being removed anyway, correct?

**Comment by rwjblue** [comment]
They are disabled by default, but enable via a flag that is set by the ember-legacy-views addon.  So we need to maintain support internally, until we no longer wish to support that addon (the current plan is for that to be in 2.4.0).

**Comment by cibernox** [comment]
So, I was missing something. Closing

**Pull request closed without merging**
