### PR TITLE
[BUGFIX] Patch CoreView legacy creation for non-browser enviroments

### LINKED ISSUE #10724: CoreView legacy creation needs hasDOM check
Non-browser environments (fastboot) fails when attempting to create a view without the container:
https://github.com/emberjs/ember.js/blob/master/packages/ember-views/lib/views/core_view.js#L55

### PR DESCRIPTION
**Pull request by gpoitch**
Fixes https://github.com/emberjs/ember.js/issues/10724

### CODE REVIEW

**Comment by rwjblue** [comment]
@wycats / @tomdale - r?

**Comment by gdub22** [comment]
Ping @tomdale. This throws a `document is not defined` error, breaking SSR builds.

**Comment by tomdale** [comment]
@gdub22 What's the use case for creating views in SSR without a container?

**Comment by gdub22** [comment]
@tomdale supporting legacy code that pre-dated the public container.  Since just refactored said code.

**Comment by stefanpenner** [comment]
I don't think we want to support this scenario. If the error isn't good, we should make it better and more clear.

**Pull request closed without merging**
