### PR TITLE
Start GlimmerVM 0.44.0 update

### PR DESCRIPTION
**Pull request by knownasilya**
WIP

### CODE REVIEW

**Comment by knownasilya** [comment]
hum, will probably need to update glimmer-vm, so not as disconnected as I thought.

**Comment by pzuraq** [comment]
This is something we're planning on working on in the next couple of months, I _think_ we decided it would probably make more sense to try to upgrade to the latest versions of Glimmer directly, but @chancancode and @wycats will have the most context here. Definitely glad you're getting this started though, thank you!

**Comment by pzuraq** [comment]
@knownasilya the last commit you pushed in particular is actually work that will have to be undone - on master, `createTag` is the default way of doing things now.

**Comment by knownasilya** [comment]
@pzuraq do you recommend changing direction to update to latest?

**Comment by pzuraq** [comment]
Yeah, definitely. We won't be able to land an upgrade unless we get to the latest version, since all of the performance fixes we landed in 0.38.5-alpha.3 aren't available again until 0.42.2

**Comment by knownasilya** [comment]
Yay, fixed a couple tests.

**Comment by knownasilya** [comment]
I have no idea what I'm doing 😂

**Comment by btecu** [comment]
@knownasilya looks like it needs a rebase?

**Comment by knownasilya** [comment]
@btecu that's done haha

**Comment by knownasilya** [comment]
ops, accidentally closed.

**Comment by knownasilya** [comment]
Anyone know how to run tests for a specific package?

**Comment by knownasilya** [comment]
Ok got that, but now getting `Uncaught Error: Could not find module @glimmer/compiler required by: @glimmer/opcode-compiler` which seems weird..

**Comment by pzuraq** [comment]
Checkout the broccoli build pipeline, it pulls in a number of Glimmer packages but not all of them. May need to be tweaked.

**Comment by knownasilya** [comment]
@pzuraq that helperd. Now stuck on `Uncaught Error: Could not find module simple-html-tokenizer required by: @glimmer/syntax` and I tried adding it to a few places but no luck.

**Comment by bekzod** [comment]
can be closed, 0.46.0 update in master 9bc32be7d05d43badf1c5221b8f66987d5678c91

**Comment by locks** [comment]
Thank you for your efforts @knownasilya!

**Pull request closed without merging**
