### PR TITLE
[WIP] Chore: add commitplease to check commit messages

### PR DESCRIPTION
**Pull request by alisianoi**
Hello, ember.js! I have noticed that you consistently use a [commit message style](https://github.com/emberjs/ember.js/blob/master/CONTRIBUTING.md#commit-tagging). However, once in a while there is a stray commit message that does not follow the style, like e176cff7ee9dc3cf5200d1ffe3cadfdf892208d9 or 751e7c2a032070a1903cd240f8a47c4d6adb7d96

Would you like to automatically check the style of your commit messages? Here is a quick example how you could set it up with [`commitplease`](https://github.com/jzaefferer/commitplease/issues/62), a module that I contribute to:

record_ember

So, whenever you type `git commit`, an automatic style check of the commit message is run. Under the hood it is just another `devDependency` for your project that installs with `npm install` and just works.

commitplease is used by Query Core, jQuery UI, jQuery Mobile, Globalize and QUnit. If you feel like using it too, let me know. We would add an ember commit message style to the list of supported styles then. Or maybe you even would like to switch to [jquery style](http://contribute.jquery.org/commits-and-pull-requests/#commit-guidelines) or [angular style](https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#commit)?

### CODE REVIEW

**Comment by tomdale** [comment]
Hi @all3fox, thank you for your PR. We are theoretically interested in this but we have a few questions.

1. How does this work with "drive-by" contributions via GitHub's editing feature? We want to make sure we don't dissuade people from making changes to things like documentation via the web interface.
2. Would you (or others on the commitplease team) be willing to implement the Ember commit style for us?

**Comment by all3fox** [comment]
Hi @tomdale, thanks for your interest

1. commitplease does not affect anything that does not trigger a local git hook (specifically, `.git/hooks/commit-msg` and `.git/hooks/prepare-commit-msg`). These are local scripts on your machine, so the web interface is not affected.

2. Sure, an [old review][1] shows that your commit message style is not "special" in any way. Unless it has changed dramatically in the last year or so.

/cc @jzaefferer

[1]: https://docs.google.com/document/d/18-7o8-RUUpK_xydsTUAx3QT0h9GOi-vPNvXraOMCDjQ/edit

**Comment by Serabe** [comment]
@tomdale ping

**Comment by mmun** [comment]
Thank you very kindly for reaching out! I don't think we're prepared to enforce a structure on our commit messages at this time, but we'll certainly keep commitplease in mind if we decide to do so in the future.

**Pull request closed without merging**
