### PR TITLE
Revert "Fixes: Safari's 'double finally on error bug'"

### PR DESCRIPTION
**Pull request by stefanpenner**
This reverts commit 917da11e1814d88106b5c62022486c716a94afaf.

iOS 6 makes up less the 4% of the iOS market, and this bug appears to be
fixed in iOS 6.1. As such the potentially affected devices is quite
small. Finally, the bug only comes into play in very specific failure
scenarios which are nearly all already handled in backburner.
- [ ] confirm with the rest of core that the affected scenarios are so minuscule we can age this out.

### CODE REVIEW

**Comment by mixonic** [comment]
+1, please also call out on the 2.0 breaking changes in the blog post

**Comment by stefanpenner** [comment]
> +1, please also call out on the 2.0 breaking changes in the blog post

do we have an issue tracking that?

**Comment by mixonic** [comment]
No, just the blog post for 2.0-beta

**Comment by stefanpenner** [comment]
> No, just the blog post for 2.0-beta

is there someone i can add to a checklist (i wont remember)

**Comment by mixonic** [comment]
Come on man. Here is an issue: https://github.com/emberjs/website/issues/2222

We **must** document these breaking changes. If you contribute a deprecation or breaking change, it **must** be documented.

**Comment by stefanpenner** [comment]
> Come on man. Here is an issue: emberjs/website#2222

Thanks, i was merely asking if there was an existing issue that tracked this.

**Pull request merged**
