### PR TITLE
only invoke didChange if a node is still present.

### LINKED ISSUE #11564: Chains: Uncaught TypeError: Cannot read property 'willChange' of undefined
After https://github.com/emberjs/ember.js/pull/11536 I'm seeing `TypeError: Cannot read property 'willChange' of undefined` error

image

I added the if and debugger statement to catch the error just before it happens. Is there a problem in the new logic? I'll try to debug this further.

@stefanpenner

### PR DESCRIPTION
**Pull request by stefanpenner**
noticed this in : https://github.com/emberjs/ember.js/pull/11513
introduced: https://github.com/emberjs/ember.js/pull/11536/files

[fixes #11564]
-  [x] add test
- [x] add similar guard for willChange

### CODE REVIEW

**Comment by rwjblue** [comment]
LGTM, I'd like to land the RC/AC PR soonish, timeline on adding test (then rebasing that PR)?

**Comment by stefanpenner** [comment]
I'll be adding an explicit  test after breakfast today.

Have you had a chance to test out AC/RC in your own apps?

**Comment by rwjblue** [comment]
@stefanpenner - Yes, I have tested in a couple apps (I'm not using all possible macros though) and things worked (all tests pass).  The only way to get more testing, is to land in canary and/or beta...

**Comment by stefanpenner** [comment]
> The only way to get more testing, is to land in canary and/or beta...

Ya, im totally fine with it getting pulled in. :)

**Comment by rwjblue** [comment]
closed by #11513

**Comment by rwjblue** [comment]
This change already exists in master, and I believe that a rebase will make this commit a noop.

**Comment by stefanpenner** [comment]
> This change already exists in master, and I believe that a rebase will make this commit a noop.

needs a test still

**Comment by rwjblue** [comment]
Yep, completely agreed.

**Comment by stefanpenner** [comment]
if its closed i'll forget to write the test

**Comment by stefanpenner** [comment]
@rwjblue friendly reminder to pull this into beta

**Pull request merged**
