### PR TITLE
[DOC RELEASE] Document queryParamsDidChange

### PR DESCRIPTION
**Pull request by Gaurav0**
This is for https://github.com/emberjs/ember.js/issues/10877

Screenshot preview:

screen shot 2016-04-22 at 1 20 49 pm

### CODE REVIEW

**Comment by rwjblue** [comment]
LGTM, thanks for adding

**Comment by Gaurav0** [comment]
What's with the jscs error? I supplied `@private`

**Comment by rwjblue** [comment]
I believe it is due to the `* ` in front, but haven't double checked yet

**Comment by Gaurav0** [comment]
@rwjblue Thanks for your help

**Comment by rwjblue** [comment]
Yeah, that rule should be tweaked to allow the `*` prefix style (I know a bunch of editors add that by default when doing block comments).

**Comment by rwjblue** [comment]
Thanks!

**Comment by JackieChiles** [comment]
This no longer appears in the docs for some reason, though it does appear in search and links here: https://emberjs.com/api/classes/Ember.Route.html#method_queryParamsDidChange

**Comment by devinrhode2** [comment]
So does an Ember.Service inherit from Ember.Route?

**Comment by Gaurav0** [comment]
@rwjblue Can someone reopen this issue? Or is a new issue required?

**Comment by rwjblue** [comment]
Well, this is a PR and it was merged. I don’t think GitHub allows me to reopen an already merged PR...

**Comment by Gaurav0** [comment]
I meant reopen https://github.com/emberjs/ember.js/issues/10877

**Pull request merged**
