### PR TITLE
Meta refactor part 3

### PR DESCRIPTION
**Pull request by ef4**
This un-reverts #12177 and adds two new commits that address its bugs.

The test from #12218 now passes. #12234 was a more vague report, but I strongly suspect this fixes that too.

### CODE REVIEW

**Comment by stefanpenner** [comment]
is this the one where Darth Vader dies, or was begins his reign?

**Comment by ef4** [comment]
How dare anyone revert my buggy code. :stuck_out_tongue: 

6a00d83451b52369e2019b03296647970d-550wi

**Comment by stefanpenner** [comment]
star-wars-quotes-10

**Comment by rwjblue** [comment]
Sorry for pulling the trigger on the revert too soon. Thank you for tracking down and fixing.

**Comment by stefanpenner** [comment]
Lgtm

**Pull request merged**
