### PR TITLE
Bump glimmer

### PR DESCRIPTION
**Pull request by chadhietala**

### CODE REVIEW

**Comment by rwjblue** [comment]
I was under the impression that there were some changes that had to be made here to bump?

**Comment by krisselden** [comment]
@rwjblue to support components with slash in the name.

**Comment by rwjblue** [comment]
Ya, I'm totally in favor of updating, but what I'm saying is that there are broken tests when we update. So I assumed that some changes upstream in glimmer need corresponding updates here.

**Comment by krisselden** [comment]
@rwjblue confirm there is a branch dealing with the reference/validator changes.

**Comment by krisselden** [comment]
this was superseded by #13278

**Pull request closed without merging**
