### PR TITLE
Added Ember.computed.flattenArray

### PR DESCRIPTION
**Pull request by Nopik**
Ember.computed.flattenArray proposal to allow computed flattenning of arrays. E.g.:

``` javascript
var item1 = Ember.Object.create({
  tags: [ 'important', 'bug', 'task' ],
});

var item2 = Ember.Object.create({
  tags: [ 'urgent', 'feature', 'task' ],
});

App.ItemList = Ember.ArrayProxy.extend({
  allTags: Ember.computed.flattenArray( 'content', 'tags' )
});

var myList = App.ItemList.create({ content: [ item1, item2 ] });
myList.get( 'allTags' );
// -> ["important", "bug", "task", "urgent", "feature", "task"]
```

### CODE REVIEW

**Comment by bgentry** [comment]
I definitely agree that this would be useful to include in Ember. This is especially non-trivial when you're trying to flatten multiple levels of `hasMany` associations in ember-data. For example, consider trying to fetch all of an Artist's Songs when only their Albums are directly associated.

Is there a 3rd party solution for that sort of thing?

**Comment by stefanpenner** [comment]
> Hi guys (@bradleypriest, @wycats, @stefanpenner), would you reconsider your previous decision and tell us what you think?

this still feels like a great community add-on.

**Comment by jrjohnson** [comment]
@Nopik - are you willing to create a pull request to add this to [ember-cpm](https://github.com/cibernox/ember-cpm) - or would you mind someone else doing that with your code?

**Comment by stefanpenner** [comment]
> @Nopik - are you willing to create a pull request to add this to ember-cpm - or would you mind someone else doing that with your code?

:+1:

**Comment by Nopik** [comment]
Go ahead and create the pull request. I wasn't working with ember-cpm at all, and stopped using Ember over a half year ago, so you probably will do that better.

**Pull request closed without merging**
