### PR TITLE
[BUGFIX release] Fix nested simple bindings inside of nested yields within views

### PR DESCRIPTION
**Pull request by ebryn**
@mmun @rwjblue

### CODE REVIEW

**Comment by stefanpenner** [comment]
@ebryn was this the source of that list-view issue?

**Comment by ebryn** [comment]
@stefanpenner yes, it manifested it within a list view, but wasn't related to it

**Comment by ebryn** [comment]
this is a followup to #10489

**Comment by ebryn** [comment]
Travis + PhantomJS are trolling me so hard here

**Comment by mixonic** [comment]
Passing. @mmun a :+1: would be great. Looks sane to me.

**Comment by quaertym** [comment]
@ebryn unrelated but how Travis + PhantomJS trolling is fixed?

**Comment by ebryn** [comment]
@mmun already :+1:ed this privately

**Comment by ebryn** [comment]
@quaertym just kept rerunning it

**Pull request merged**
