### PR TITLE
Complain if you use the wrong map macro

### PR DESCRIPTION
**Pull request by ghost**
Add a warning message when you use the wrong computed macro for map. At the moment the error message is not very helpful:

```
Uncaught TypeError: callback.call is not a function
```

Perhaps it would make sense to combine these into one macro that knows what to do depending on the type of the second argument?

### CODE REVIEW

**Comment by stefanpenner** [comment]
looks like a good PR, but this code is actually deprecated.

**Comment by bdvholmes** [comment]
Oh well at least I won't have to worry about this again :+1:

**Comment by stefanpenner** [comment]
> Oh well at least I won't have to worry about this again

well, you will. Sorry i hit enter before i was finished. Please review what i wrote

**Comment by bdvholmes** [comment]
Ok cool, was thinking about how to add a test but wasn't sure how. I'll see if I can find a similar example using assert.

**Comment by mixonic** [comment]
@bdvholmes there is an `expectAssertion` helper- [For example](https://github.com/emberjs/ember.js/blob/4d97d612ebe0841c0d40e57b276c9bc2bf896768/packages/ember-metal/tests/run_loop/schedule_test.js#L76-L78):

```js
expectAssertion(function() {
  doSomethingMightAssert();
}, /regex against the assertion message/);
```

**Comment by bdvholmes** [comment]
@mixonic thanks that's just what I was looking for. I just wrote one with throw, will use the helper instead.

**Comment by bdvholmes** [comment]
@stefanpenner tests are added. Also tweaked the way it gets called - is the deprecation the fact that we don't need computed arrays with Glimmer?

**Comment by rwjblue** [comment]
Looks good, thanks for taking the time to help folks out!  Can you squash your commits and prefix with `[BUGFIX beta]`?

**Comment by stefanpenner** [comment]
superseded by https://github.com/emberjs/ember.js/pull/11528

**Pull request closed without merging**
