### PR TITLE
Add queryParams to RouterService

### PR DESCRIPTION
**Pull request by Exelord**
Can we add router params and queryParams to the public interface of RouterService? It will help in many cases when you try to access queryParams in the components.

### CODE REVIEW

**Comment by rwjblue** [comment]
This router service is still behind a feature flag, and not available to folks.  It is also aiming to implement the specific API that was proposed and accepted in [emberjs/rfcs#95](https://github.com/emberjs/rfcs/blob/master/text/0095-router-service.md), which I don't _think_ have these properties.

Adding them would require another RFC I believe...

**Comment by Exelord** [comment]
I think this is a great feature. We should highly consider it even in the case of opening a new RFC.
but... it's your choice. I just wanted to solve a problem that I currently meet in many places on the web.

**Comment by sdhull** [comment]
@Exelord this would be extremely helpful to me like ... right now 😁

**Comment by lifeart** [comment]
up

**Comment by locks** [comment]
I'm closing this for now as the router service RFC does not include these APIs. The next step forward would be to propose a new RFC, and go from there :)
Thanks for the contribution!

**Pull request closed without merging**
