### PR TITLE
Make Ember.HTMLBars version of registerHelper private.

### PR DESCRIPTION
**Pull request by rwjblue**
As requested by @wycats / @tomdale.

### CODE REVIEW

**Comment by rwjblue** [comment]
@tim-evans - @wycats and @tomdale were uncomfortable with the API.  They will have to chime in as to why.

**Comment by tim-evans** [comment]
Thanks for the quick response. The line in question that squelches registering these terse helpers is https://github.com/emberjs/ember.js/blob/876eecf6ab29159b1ef5474f2c62da139bb636c0/packages/ember-htmlbars/lib/system/lookup-helper.js#L38

It also doesn't emit a warning (which I believe it should) telling people writing helpers / components that they need to include dashes in their templates.

**Comment by rwjblue** [comment]
@tim-evans - If it emitted a warning, you would get a warning for every non-dashed property lookup (since `{{t}}` is not obviously a helper or a property).

**Comment by tim-evans** [comment]
Better than nothing IMO

**Comment by rwjblue** [comment]
Agree to disagree :)

**Comment by tim-evans** [comment]
I'm a tad confused by your statement. I thought that this is one of those things that is actionable. Helpers / components registered without dashes are completely unsupported unless you bypass that directly with `registerHelper`.

If you try to register a `t` helper in ember-cli by creating a file named `helpers/t.js`, it will silently not exist.

**Comment by rwjblue** [comment]
Consider [this JSBin](http://emberjs.jsbin.com/rwjblue/296/edit?html,js). View source, and add a breakpoint on the line that contains `if (!container || ISNT_HELPER_CACHE.get(name)) {`. You will see that it is hit when rendering.  In this case, there are no helpers at all, and the intended behavior is to simply render the `t` value from the templates associated controller.  So if we add a warning in an `else` fo that `if` (which is what I believe you were suggesting in https://github.com/emberjs/ember.js/pull/10379#issuecomment-73394988) then every time you use a non-dashed word in a template you will receive that warning.

**Comment by tim-evans** [comment]
That makes sense. I think my problem is that when I started using ember, it was clear that components need dashes, but not so clear on helpers. And I was thinking about adding a warning in debug mode if:

```javascript
if (!container || ISNT_HELPER_CACHE.get(name)) {
    // if debug
    if (container) {
       if (container.lookup(`helper:${name}`)) {
          // Warn about helpers needing dashes
       } else if (container.lookup(`component:${name}`)) {
          // Warn about components needing dashes
       }
    }
    return;
}
```

A better solution would be to have this built into a read-time execution in debug mode only. That way, the warning is only displayed once

**Comment by tim-evans** [comment]
Just a side reference: 

https://github.com/stefanpenner/ember-inflector/issues/63

**Pull request merged**
