### PR TITLE
Continuation of instance initializer blue print for module unification

### PR DESCRIPTION
**Pull request by NullVoxPopuli**
Continuation of https://github.com/emberjs/ember.js/pull/16491
 - rebased

### CODE REVIEW

**Comment by NullVoxPopuli** [comment]
ah ok, so the tests still need some work. cool.

**Comment by simonihmig** [comment]
This will need another rebase, as I have been working on refactoring the tests to use fixtures everywhere, including #17205...  

@NullVoxPopuli are you able to continue with this? If not, I can pick this up.

**Comment by NullVoxPopuli** [comment]
I don't have the time at the moment. So, feel free :)

**Comment by ppcano** [comment]
@simonihmig 

I am working on `Acceptance test blueprint` as part of ember-cli/ember-cli#7530

Do you also plan to work on #16492 supercedes by #16944?

**Comment by ppcano** [comment]
@NullVoxPopuli Can be closed by #17235 (same for #16944)

**Comment by NullVoxPopuli** [comment]
sounds good!

**Pull request closed without merging**
