### PR TITLE
[BUGFIX beta] restore Ember.computed.collect

### PR DESCRIPTION
**Pull request by csantero**
Ember.computed.collect needs to come from ember-runtime now, instead of ember-metal.

### CODE REVIEW

**Comment by rwjblue** [comment]
Awesome, thank you!

**Comment by rwjblue** [comment]
I just caught that this was targeted at `beta` branch.  Generally speaking, all changes should target master and then get pulled into the appropriate branches as part of the release process.

**Comment by csantero** [comment]
Oh, sorry, my bad.

**Comment by rwjblue** [comment]
No worries, I was just letting you know for next time!  I already pulled the commit into master...

**Pull request merged**
