### PR TITLE
[WIP] Update route-recognizer.

### PR DESCRIPTION
**Pull request by nathanhammond**
_Do not merge._

This is the complete enumeration of tasks gating landing of what will be the next version of route-recognizer into Ember. I'm hoping to land this as part of 2.9.
- [x] Port build into ember-route-recognizer.
- [x] Port benchmarks into ember-route-recognizer.
- [x] Add warning for duplicate route addition.
- [x] ES3-ify `dist/*`.
- [ ] Performance
  - [ ] Ensure benchmarks are approximately the same speed or better.
  - [ ] Convert to TypeScript
  - [x] Do a better job at serialization (breadth-first compaction).
- [ ] Improve the automatic serialization build process.
  - [ ] Make it less brittle.
  - [ ] Make the addon version's build process strip out the compiled-in route-recognizer when used with older versions of Ember.
- [ ] Testing
  - [ ] End-to-end Ember tests.
  - [ ] More obnoxious permutations.
  - [ ] Add node-tests for the build process.
- [ ] Implement [RFC #154](https://github.com/emberjs/rfcs/pull/154)
  - [ ] Optional Segments
  - [ ] Dynamic Segment Constraints
- [ ] Add support for `this.delegate`. [Originally added here.](https://github.com/tildeio/route-recognizer/commit/a667625cb80984cc730a3986fa4dd265c85665ff)
- [ ] Optimize out unreachable routes alerts user.
- [ ] Repository shuffling?
  - [ ] Move the code in [ember-route-recognizer](https://github.com/nathanhammond/ember-route-recognizer/) into [route-recognizer](https://github.com/tildeio/route-recognizer/)?
  - [ ] Move into the [emberjs GitHub org](https://github.com/emberjs/).

### CODE REVIEW

**Comment by rwjblue** [comment]
@nathanhammond - This is still on your radar (just delayed), right?

**Comment by nathanhammond** [comment]
Not only on my radar, still making progress: https://github.com/nathanhammond/ember-route-recognizer/commits/master

On 11/5 I built a 100% working copy of Ember with my route-recognizer fork. Need to write high quality benchmarks that can be run in different modes before proceeding with the perf work.

**Comment by marcemira** [comment]
:wave: @nathanhammond - Just wanted to know if this still going to happen. Thanks :pray:

**Comment by mmun** [comment]
Closing as stale. (Route recognizer is already at version 0.3.3).

**Pull request closed without merging**
