### PR TITLE
initial d8-runner ready to go

### PR DESCRIPTION
**Pull request by stefanpenner**

### CODE REVIEW

**Comment by krisselden** [comment]
I don't understand why the node dom helper isn't being chosen.  You shouldn't need the dom patches, and they will not work if something actually uses `{{{html}}}`

**Comment by krisselden** [comment]
Otherwise, awesome work.

**Comment by stefanpenner** [comment]
> I don't understand why the node dom helper isn't being chosen. You shouldn't need the dom patches, and they will not work if something actually uses {{{html}}}

I was having a hard time debugging in D8. Maybe we can sit down later today or tomorrow and address what you mentioned

**Comment by rwjblue** [comment]
@stefanpenner  - Any reason not to land this and iterate further while on master?

**Comment by stefanpenner** [comment]
@rwjblue no reason, other then. we should then likely open an issue for

> We obviously want to make sure this uses the Node dom helper stuff, i don't think it is yet.

**Comment by stefanpenner** [comment]
https://github.com/emberjs/ember.js/issues/14551

**Pull request merged**
