### PR TITLE
Pass event as context to input helper key-press action

### PR DESCRIPTION
**Pull request by mmelvin0**
The key-up and key-down input helper actions already do this.

### CODE REVIEW

**Comment by mmelvin0** [comment]
I don't understand the nature of this test failure. Any guidance would be appreciated.

**Comment by rwjblue** [comment]
I don't really think that we should pass the event through to the resulting action as a rule.  Maybe it is ok in this case, but I'd like to chat about it with a few others before we decide.

**Comment by anru** [comment]
And that's not merged already ?!
Linked issues: #10959, 10569

**Comment by rwjblue** [comment]
Discussed with core team, and we do not want to expose the DOM event to these default actions.  If you need this behavior you can subclass...

**Comment by wuarmin** [comment]
but can you explain why key-down or key-up behaviour pass it, and key-down doesn't? I'm confused ;)

**Pull request closed without merging**
