### PR TITLE
[BUGFIX release] Remove Ember.merge deprecation.

### PR DESCRIPTION
**Pull request by rwjblue**
The deprecation was too noisy, and not enough libraries updated prior to release (to avoid deprecation). At this point the deprecation is just a nuisance to our users.

### CODE REVIEW

**Comment by chadhietala** [comment]
LGTM

**Comment by workmanw** [comment]
Just to clarify, the plan is still to eventually deprecate and remove `Ember.merge`? This is just a removal of the warning for now until the rest of us addon maintainers get caught up?

**Comment by stefanpenner** [comment]
@workmanw i believe the plan is to re-evaluate at a later date.

**Comment by rwjblue** [comment]
Confirm. We do not currently have plans to reintroduce, but I would be somewhat surprised if both methods make it into 3.0.0.  But obviously that is quite a ways away, and we don't really know what that will look like.

**Comment by workmanw** [comment]
@stefanpenner @rwjblue Thanks for the clarifications!

**Pull request merged**
