### PR TITLE
[DOC release] Update event name to camelCase in htmlbar action

### PR DESCRIPTION
**Pull request by zoltan-nz**
Releated conversation: https://github.com/emberjs/guides/issues/853#issuecomment-154834994

Only the `camelCase` version works. The Api doc was misleading.

### CODE REVIEW

**Comment by kiwiupover** [comment]
@rwjblue there seems to be a problem with the build, IE9 in particular on source labs. Can you point me in the right direction to fix it? 

Cheers Mate

**Comment by acorncom** [comment]
@szines If you rebase, do the builds work now?  I'm seeing other recent builds that are working at this point ...

**Comment by szines** [comment]
@acorncom I give it a try.

**Comment by szines** [comment]
After rebase, there are still two tests failing. Screenshot from SauceLabs:

image

```
Running: ./node_modules/.bin/testem ci -f testem.dist.json --port 7000
ok 1 SL_Chrome_Current - https://saucelabs.com/jobs/280a4d704577465c998f442c66d7bc36
ok 2 SL_IE_11 - https://saucelabs.com/jobs/8833092993cd4e2d9586b8c5acfcb733
not ok 3 SL_MS_Edge - https://saucelabs.com/jobs/0823295e4f114ad68c651ee5918abb04
ok 4 SL_Safari_Current - https://saucelabs.com/jobs/7d35939a5cab428f8bbf74f8906bfcda
ok 5 SL_Firefox_Current - https://saucelabs.com/jobs/de901ee80fd248d0a737cefe85b1fe09
ok 6 SL_IE_10 - https://saucelabs.com/jobs/a1f98adbf5b147afb739f6a784477fdf
not ok 7 SL_IE_9 - https://saucelabs.com/jobs/783127ba8abb44c6b27106a13e954deb
1..7
# tests 7
# pass  5
# fail  2
```

**Comment by rwjblue** [comment]
We have addressed many long standing issues with sauce labs, I suspect with a rebase this will pass...

**Pull request closed without merging**
