### PR TITLE
Bump htmlbars

### PR DESCRIPTION
**Pull request by chadhietala**
Interested in getting a release where https://github.com/tildeio/htmlbars/pull/400 is in a canary. Upstream PR https://github.com/tildeio/htmlbars/pull/419

### CODE REVIEW

**Comment by rwjblue** [comment]
Restarted the Travis build after releasing 0.14.6

**Comment by rwjblue** [comment]
@duggiefresh - Didn't you have an issue where you needed an HTMLBars version bump too?

**Comment by duggiefresh** [comment]
Yes, sir! https://github.com/emberjs/ember.js/issues/12316

Gracias! :tada:

**Comment by rwjblue** [comment]
Thanks @chadhietala !

**Pull request merged**
