### PR TITLE
Disallows blocks from beginning and ending with 2 newlines.

### PR DESCRIPTION
**Pull request by twokul**
i.e:

``` javascript
// bad
if (true) {

  doSomething();

}

// good
if (true) {
  doSomething();
}
```

### CODE REVIEW

**Comment by rwjblue** [comment]
Looking good.  Let us know when green....

**Comment by tomdale** [comment]
I personally like adding extra space around large blocks, as the whitespace can help break it into logical stanzas. What motivated this change?

**Comment by twokul** [comment]
@tomdale Inconsistency really. We use extra space less than no space around blocks (most of the extra spaces come from tests) hence the change.

**Comment by rwjblue** [comment]
@twokul - This PR looks good. 

@tomdale - Are you :-1: on this?  It is likely not a huge deal either way, just don't want to require this PR to be rebased a bunch (as it changes a number of files).

**Comment by stefanpenner** [comment]
this seems to have gone quite stale.

@tomdale are you :+1:  or :-1:  on this?

@twokul are you still interested in getting this back on track (pending @tomdale's response that is)

**Comment by tomdale** [comment]
Does it allow comments? E.g.

```js
if (true) {
  // Here is the code
  blah();
}
```

**Comment by twokul** [comment]
@tomdale I think it does. I can rebase and double check.

**Comment by tomdale** [comment]
@twokul I think I am okay with this, comments are the main thing I was worried about, and as long as you can still have newlines inside the block. I hate reading code with very dense blocks, where even comments are jammed up against the statements.

**Comment by twokul** [comment]
@tomdale :+1:

**Comment by stefanpenner** [comment]
@twokul are you able to rebase and stuff?

**Comment by twokul** [comment]
@stefanpenner will try in an hour or so

**Comment by stefanpenner** [comment]
> @stefanpenner will try in an hour or so

awesome thanks

**Comment by twokul** [comment]
@stefanpenner re-pushed

**Comment by tomdale** [comment]
@twokul it was a pleasure doing business with you

**Comment by twokul** [comment]
@tomdale likewise, Sir Dale

**Pull request merged**
