### PR TITLE
[bugfix beta] update backburner

### PR DESCRIPTION
**Pull request by fivetanley**
Removes old IE-specific detection for try/catch fix, see
https://github.com/ebryn/backburner.js/pull/162

### CODE REVIEW

**Comment by stefanpenner** [comment]
Lgtm

**Comment by stefanpenner** [comment]
Lgtm should likely be bug fix beta

**Comment by rwjblue** [comment]
Agreed, should go into beta branch.

**Comment by fivetanley** [comment]
cherry-picked as e7f2656962853fad5a066c338368a9077fad782f on beta.

**Pull request merged**
