### PR TITLE
assert for non-array values in `concatenatedProperties` and `mergedProperties`

### PR DESCRIPTION
**Pull request by bekzod**
possible fix for #16014

### CODE REVIEW

**Comment by rwjblue** [comment]
I mentioned in the other issue, I don't think this is the right path forward. I think we should assert when given anything that isn't an array...

**Comment by bekzod** [comment]
ok

**Comment by rwjblue** [comment]
Had a chance to pick this back up @bekzod?

**Comment by bekzod** [comment]
looking at it now :)

**Comment by bekzod** [comment]
@rwjblue just to note
```javascript
let mixinA = Mixin.create({
   concatenatedProperties: ['foo'],
   foo: ['bar']
})

let mixinB = Mixin.create({
   foo: 'boom'
})

mixin({}, mixinA, mixinB); // will not throw assertion 

let mixinC = Mixin.create({
   concatenatedProperties: 'boom'
})

mixin({}, mixinA, mixinC); // will throw assertion 

```

**Comment by bekzod** [comment]
@rwjblue maybe we could also merge #15704 😉

**Comment by bekzod** [comment]
closing, too much has changed and EmberObject probably will be gone soon

**Pull request closed without merging**
