### PR TITLE
[BUGFIX release] Ensure that inline {{link-to}} does not cause a crash.

### LINKED ISSUE #10360: Issue with link-to helper causing page freezes
Ember version: 1.9

So I recently encountered an issue where rendering a particular view was causing the browser to slow down and eventually freeze.

After a bit of digging the culprit turned out to be the following line:

`{{link-to modelAttr 'someRoute' }}`

In some cases we expected `modelAttr` to be null, which turned out to be the root cause of what triggered the browser freeze.

I couldn't find anything in the docs to explain how `link-to` would handle `null`. 

In the UI, it would just render an empty string which is what I expected, but find it strange that it would cause the browser to freeze.

To give some more context. On the left-hand side of the page we have a navigation panel which lists all models in a collection. And by clicking on each it links to the show action for that resource. The issue doesn't occur at first, but it seems to build up after clicking on links in the left-hand nav container.

Let me know if there is anymore info or code I can post here to help.

### PR DESCRIPTION
**Pull request by rwjblue**
Fixes #10360.

### CODE REVIEW

**Comment by mmun** [comment]
Much better!

**Comment by ef4** [comment]
How did this crash the browser? I'm asking because I still see a browser crash that may be similar, and I don't understand this diff.

**Comment by rwjblue** [comment]
@ef4 - The stream for the bound title (in inline form), was never unsubscribed and it triggered a re-render, which then kept growing the streams (which were never cleaned up) and eventually (after 10 or so times) would completely freeze and crash.

**Comment by rwjblue** [comment]
@ef4 - Demo with v1.10.0: http://emberjs.jsbin.com/berebe/4/edit?html,js

**Comment by ef4** [comment]
Ok, I suspect the crash I was getting is unrelated. I don't think it's ember's fault at all, I think that Chrome has a bug when dealing with CSS3 transforms scaled down near zero size.

**Pull request merged**
