### PR TITLE
Remove dead view code

### PR DESCRIPTION
**Pull request by ebryn**
@mmun @rwjblue @krisselden Seems to have been killed with the renderer work

### CODE REVIEW

**Comment by teddyzeenny** [comment]
`View.addMutationListener` is for the inspector.

**Comment by trek** [comment]
I've reverted. @teddyzeenny can you PR some comments and/or move this to a place that better indicates its use by the inspector?

**Comment by teddyzeenny** [comment]
Thanks @trek. I will add some comments. Reverting this removes the error, but I don't think it's enough since the actual triggering of the mutation event has been removed in a previous commit (so the view tree will not auto-update). I have some free time tomorrow, I can investigate.

**Comment by teddyzeenny** [comment]
I looked into this today, we can use the "Render Performance Tab" instrumentation to detect changes to the view tree. I will remove the dependency and we can delete this code after we release a new inspector version.

**Pull request merged**
