### PR TITLE
[BUGFIX beta] Fixes {{link-to}} classes when transition is aborted

### LINKED ISSUE #13164: `{{link-to}}` transitioning classes are incorrect after `transition.abort()`
twiddle: https://ember-twiddle.com/8aa9da800a7883b6c59a?openFiles=routes.page2.js%2C

The `ember-transitioning-in` and `.ember-transitioning-out` classes don't seem to be updated correctly when linking to a route that aborts the transition:

``` js
export default Ember.Route.extend({
  beforeModel: function(transition) {
    return delay(1000).then(function() {
      transition.abort();   
    });
  }
});
```

I'll try to create a failing test now

### PR DESCRIPTION
**Pull request by GavinJoyce**
fixes https://github.com/emberjs/ember.js/issues/13164

### CODE REVIEW

**Comment by rwjblue** [comment]
This seems good to me. 

@machty - Would love your eyes on this to make sure I'm not missing something...

**Comment by machty** [comment]
:+1: thanks for digging into this :)

**Comment by rwjblue** [comment]
@machty - Thanks for reviewing!

**Comment by medokin** [comment]
@GavinJoyce There is a new issue. Active class is missing when redirecting in before/afterModel. Will investigate and provide an example.

**Comment by GavinJoyce** [comment]
@medokin thanks, I'll look into this now

**Pull request merged**
