### PR TITLE
Reimplement inline link-to as an AST transform

### PR DESCRIPTION
**Pull request by mmun**
I also had to fix broken tests that didn't pass enough arguments to link-to because they were triggering an assertion that `params.length > 0`.

### CODE REVIEW

**Comment by mmun** [comment]
Hmm, this strategy doesn't work with custom link-tos.

**Comment by rwjblue** [comment]
I think that it is fine that the inline form is specifically for `{{link-to}}` and not for custom versions of `link-to`.

**Comment by rwjblue** [comment]
@mmun - This needs a rebase and some updates when you have a minute.

**Comment by nathanhammond** [comment]
This is only *marginally* different from the current state with extending the `link-to` component. If you need to modify `qualifiedRouteName` or `willRender` you lose the ability to have an extended inline link-to because you don't have a reference to the `HAS_BLOCK` symbol. Those two will, of course, be the primary places people want to make changes.

I'm in favor of implementing this as an AST transform even with the knowledge that it *does* make it a bit more magical. (I don't imagine that most people using Ember expect that the code they write is going to be modified like this before it runs which may confuse somebody's debugging session.)

@mmun you want to bring this home, or for me to adopt it?

**Comment by mmun** [comment]
@nathanhammond Sure, feel free to adopt! :)

**Comment by mmun** [comment]
I've given you access to my fork of ember.js if you'd prefer to rebase this branch.

**Comment by stefanpenner** [comment]
Just a side-thought, we may need to make the AST, or atleast the transforms/reducers be part of the public API at some point.

**Comment by nathanhammond** [comment]
Ready for review and possible landing. :)

**Comment by rwjblue** [comment]
Rebased again.  Gonna land when :green_apple:....

**Pull request merged**
