### PR TITLE
[BUGFIX] Fix blockless component meta resolution

### PR DESCRIPTION
**Pull request by asakusuma**
Addresses https://github.com/emberjs/ember.js/issues/13494
Closes #13632.

### CODE REVIEW

**Comment by asakusuma** [comment]
cc @rwjblue

**Comment by rwjblue** [comment]
Can you add another local lookup test that ensures a tagless and block less component can use local lookup (and is able to rerender)?

**Comment by asakusuma** [comment]
@rwjblue How do you write a blockless component that uses local lookup? My understanding is that the component has to define a template where a local lookup occurs, and if there's a template, there's a block.

**Comment by rwjblue** [comment]
Thanks for the added test, I was just concerned about this case (but its nice to have more tests).

This LGTM when green...

**Pull request merged**
