### PR TITLE
Refactor the build!

### PR DESCRIPTION
**Pull request by rwjblue**
* Enable easy dynamic package creation (no special sauce to add a new package, just do it...)
* Enable seamless `.ts` usage throughout all of `packages/**` (just rewrite a file from `*.js` to `*.ts` and make linting happy 😝 )
* Remove arbitrary filtering/building of packages and simplify what is included and excluded from various builds.

TODO:

- [x] Remove `lib/packages.js`
- [x] Make adding new `packages/*/tests` "just work" with `each-package-tests`
- [x] Fix `node` test runs
- [x] Add `ember-utils` package to `ember-template-compiler.js` asset

### CODE REVIEW

**Comment by rwjblue** [comment]
I have uploaded a tarball including `dist` [here](http://assets.rwjblue.com.s3.amazonaws.com/ember/tarballs/ember-source-3.3.0-streamlined-build-refactor-3255cc2.tgz) if anyone wants to review the build output...

**Review by chadhietala — APPROVED** [review]

**Comment by stefanpenner** [comment]
Can you share the before/after slow-tress output for `cold build` and `js rebuild` ?

**Comment by rwjblue** [comment]
<details>
<summary>The timings seem roughly unchanged (expand for specifics...)</summary>

### Before

#### Cold Initial Build

```
Build successful (77367ms) – Serving on http://localhost:7020/

Slowest Nodes (totalTime => 5% )              | Total (avg)
----------------------------------------------+---------------------
Babel (57)                                    | 67061ms (1176 ms)
TypeScriptPlugin (1)                          | 4371ms
```

#### Warm Initial Build

#### JS Rebuild

```
Build successful (2708ms) – Serving on http://localhost:7020/

Slowest Nodes (totalTime => 5% )              | Total (avg)
----------------------------------------------+---------------------
broccoli-typescript-compiler (1)              | 2376ms
```

### After

#### Cold Initial Build
```
Build successful (79002ms) – Serving on http://localhost:7020/

Slowest Nodes (totalTime => 5% )              | Total (avg)
----------------------------------------------+---------------------
Babel (7)                                     | 66325ms (9475 ms)
Rollup (21)                                   | 5227ms (248 ms)
TypeScriptPlugin (1)                          | 4704ms
```

#### Warm Initial Build

```
Build successful (12413ms) – Serving on http://localhost:7020/

Slowest Nodes (totalTime => 5% )              | Total (avg)
----------------------------------------------+---------------------
Rollup (21)                                   | 4389ms (209 ms)
TypeScriptPlugin (1)                          | 4055ms
Babel (7)                                     | 1697ms (242 ms)
Funnel (16)                                   | 898ms (56 ms)
Concat (5)                                    | 750ms (150 ms)
```

#### JS Rebuild

```
Build successful (2674ms) – Serving on http://localhost:7020/

Slowest Nodes (totalTime => 5% )              | Total (avg)
----------------------------------------------+---------------------
broccoli-typescript-compiler (1)              | 1578ms
Rollup: rollup ember-metal (1)                | 247ms
Rollup: rollup ember-glimmer (1)              | 240ms
Funnel (16)                                   | 229ms (14 ms)
```
</details>

**Comment by stefanpenner** [comment]
> Warm Initial Build

before: `2708ms`
after: `12413ms`


this seems like a regression?

**Comment by rwjblue** [comment]
The cold initial and rebuild times are roughly the same, and I didn't compare the warm initial build times after prepping the numbers. Will dig into it a bit and see what we can do to improve. 

Ultimately, IMHO the overall benefits of this PR (mentioned in the PR description) are significant and are valuable enough to justify the (hopefully temporary) warm initial build regression...

**Comment by rwjblue** [comment]
After starting to poke at that, I realized that the numbers you were comparing were the "Before: JS rebuild" time and "After: Warm Initial Build" time. This is because I had forgotten to paste in the "Before: Warm Initial Build" time 😭.

I've updated the comment above, but here is a screenshot of what it was before (where I accidentally trolled you 😢 ):

original screenshot

**Comment by stefanpenner** [comment]
> Ultimately, I still think there is a small regression for initial builds (~ 3% on initial cold, ~ 9% on initial warm) but a small improvement for rebuilds. Definitely still room for improvement!
> 
> 😄 1

ya that type of regression isn't fatal, carry on. Thanks for digging in.

**Pull request merged**
