### PR TITLE
inject the router service inside ember-router

### PR DESCRIPTION
**Pull request by sly7-7**
Related #19405 (maybe replace?)

I don't know if it's the right way, and feel maybe weird.
 
cc/ @Ravenstine  @rwjblue

### CODE REVIEW

**Comment by rwjblue** [comment]
Conceptually this seems good to me also, does it pass tests?

What do you think @ravenstine @snewcomer?

**Comment by sly7-7** [comment]
Unless I missed something, they pass locally. Thanks to @Ravenstine for writing it :) in it's PR.
I realize some work has been done between his PR and the master, I just had to wire the router service into the ember router

**Comment by snewcomer** [comment]
@sly7-7 This seems like a close direct copy with some modifications.  Why don't we continue with comments and iterate on @Ravenstine's PR?

**Comment by rwjblue** [comment]
Either is fine, @sly7-7 was using the `Co-authored-by` thing to attribute the work from @ravenstine, but I'm not sure why it doesn't show that in the commit above. 🤔

**Comment by rwjblue** [comment]
OK, so looks like this strategy definitely works.

@ravenstine - Think you can incorporate this into https://github.com/emberjs/ember.js/pull/19405?

**Comment by rwjblue** [comment]
Thanks for testing this out @sly7-7! I'm going to go ahead and close this one, in favor of landing these tweaks over in #19405.

**Comment by snewcomer** [comment]
That certainly is my fault for making that assumption and I sincerely apologize!  

So the only difference is Ben's throws an error if the router svc isn't available whereas yours fails gracefully.  We weren't sure which approach is preferred but throwing the error caught a few tests that needed to `setupRouter` explicitly.

https://github.com/emberjs/ember.js/pull/19405/files#r575540397

**Pull request closed without merging**
