### PR TITLE
[ISSUEFIX] Break loop after one refresh in queryParamsDidChange

### LINKED ISSUE #14597: Optimization for Ember.Route.actions.queryParamsDidChange
Hey, sorry if I'm seeing this wrong, but looking at this line:
https://github.com/emberjs/ember.js/blob/v2.9.1/packages/ember-routing/lib/system/route.js#L776
it seems that after finding one queryParam that needs to trigger a refresh the loop should break.
If 2 parameters changed there's no need to trigger 2 refreshes at the same time, right?
One refresh should be enough.

### PR DESCRIPTION
**Pull request by daibhin**
Fixes #14597

### CODE REVIEW

**Comment by rwjblue** [comment]
I'd suggest adding a test similar to [this one](https://github.com/emberjs/ember.js/blob/d37d38b8a21f859ecb8b62f74a9dea92b0289866/packages/ember/tests/routing/query_params_test.js#L527-L568), that overrides `refresh` and confirms it is only called once when two params change.

**Comment by rwjblue** [comment]
Test looks good!  Can you confirm that it fails without your changes?

**Comment by daibhin** [comment]
Did a manual confirmation and the test indeed fails without the `break;`. Is there anything I need to do to confirm this?

**Comment by rwjblue** [comment]
Nope, looks great to me! Thank you!!

**Comment by daibhin** [comment]
@wagenet this was to address https://github.com/emberjs/ember.js/issues/14597. Not fully sure of the context in https://github.com/emberjs/ember.js/issues/5566 but I think that's a different issue.

**Comment by wagenet** [comment]
Ah I see. Thanks :)

**Pull request merged**
