### PR TITLE
[BUGFIX beta] allow numeric `0` key to work with `get` helper

### LINKED ISSUE #15666: Numeric get not working for arrays
```javascript
{{get object 0}} // works ok
{{get array 0}} // does not work
// but
{{get array '0'}} // works ok
{{get array 1}} // works ok
```

https://ember-twiddle.com/3be646d4e82a480e0993ce7093c2ac52

### PR DESCRIPTION
**Pull request by bekzod**
fixes #15666

### CODE REVIEW

**Comment by rwjblue** [comment]
Can you prefix the commit (and PR title) to be `[BUGFIX beta]`?

**Review by rwjblue — APPROVED** [review]

**Comment by bekzod** [comment]
even commit message ? I will have to push again that will trigger another CI run :P ?

**Comment by bekzod** [comment]
sauce doesn't like `[BUGFIX beta]` tag

**Comment by rwjblue** [comment]
LOL, sauce doesn't like _anything_....

**Comment by locks** [comment]
💪 only takes like 20 retries

**Pull request merged**
