### PR TITLE
Host App to Engine Transition with Object type QP

### LINKED ISSUE #16655: Host App to Engine's Route Transition with QueryParam of type object is not working properly
In my host app repository, I have an in Repo lazy loading engine. 

When I proceed transition from my host app to engine's route with Query param of type object for the very first time, It shows the error like 

> SyntaxError: Unexpected token o in JSON at position 1

And if i do the same again, its working fine.

Actually, I found that router._queryParamsFor(handlerInfos) method in "router.js" returns the empty objects("map" and "qps") for the first time, host app tries to transtion to engine's route.

For the next time, it returns the value for the objects("map" and "qps"), this is happening becuase engine's instance is already created by the previous transition.

Also, if _queryParamsFor method returns empty object. Since, there is no type check for an object in _serializeQueryParam. It will return the string as "[object object]". .

```
_serializeQueryParam(value, type) {
   if (value === null || value === undefined) {
     return value;
   } else if (type === 'array') {
     return JSON.stringify(value);
   }

   return `${value}`;
 }
```

How can I proceed the transaction to an engine with object type QP?

### PR DESCRIPTION
**Pull request by kishoreyuvan**
fixes #16655

### CODE REVIEW

**Comment by kishoreyuvan** [comment]
@rwjblue kindly check this.

**Comment by kishoreyuvan** [comment]
@locks @rwjblue any update on this?

**Review by rwjblue — COMMENTED** [review]
The change seems reasonable to me, but I think we'd need a previously failing test case in order to land this PR.

**Comment by locks** [comment]
@kishoreyuvan are you able to add the test?

**Comment by kategengler** [comment]
Closed as abandoned

**Pull request closed without merging**
