### PR TITLE
[DEPRECATION beta] Deprecate context switching form of {{each}}.

### PR DESCRIPTION
**Pull request by rwjblue**
Deprecate the context switching form of `{{each}}`.

Will be updating the website and guides to remove old references.

From the 2.0 RFC:

---
## More Consistent Handlebars Scope

In today's Ember, the `each` and `with` helpers come in two flavors: a "context-switching" flavor and a "named-parameter" flavor.

``` handlebars
{{#each post in posts}}
  {{!-- the context in here is the same as the outside context,
        and `post` references the current iteration --}}
{{/each}}

{{#each posts}}
  {{!-- the context in here has shifted to the individual post.
        the outer context is no longer accessible --}}
{{/each}}
```

This has proven to be one of the more confusing parts of the Ember templating system. It is also not clear to beginners which to use, and when they choose the context-shifting form, they lose access to values in the outer context that may be important.

Because the helper itself offers no clue about the context-shifting behavior, it is easy (even for more experienced Ember developers) to get confused when skimming a template about which object a value refers to.

In Ember 1.10, we will deprecate the context-shifting forms of `#each` and `#with` in favor of the named-parameter forms.
### Transition Plan

To transition your code to the new syntax, you can change templates that look like this:

``` hbs
{{#each people}}
  <p>{{firstName}} {{lastName}}</p>
  <p>{{address}}</p>
{{/each}}
```

with:

``` hbs
{{#each people as |person|}}
  <p>{{person.firstName}} {{person.lastName}}</p>
  <p>{{person.address}}</p>
{{/each}}
```

**We plan to deprecate support for the context-shifting helpers in Ember 1.9 and remove support in Ember 2.0.** This change should be entirely mechanical.

### CODE REVIEW

**Comment by OrKoN** [comment]
@rwjblue Is the non-block version of the each helper deprecated too?

We use it like this:
```
    {{each items itemViewClass="test-item"}}
```

It looks like the context switching is convenient in this case. Otherwise, I would need to write a more lengthy template:

```

    {{#each items as |item|}}
      {{view 'test-item' contentBinding="item"}}
    {{/each}}

```

and the view needs to know the binding name:

```
App.TestItemView = Ember.View.extend({value
  tagName: 'li',
  template: Ember.Handlebars.compile("{{item.value}}")  
});

```

instead of 

```
App.TestItemView = Ember.View.extend({
  tagName: 'li',
  template: Ember.Handlebars.compile("{{item}}")  
});

```

jsbin: http://emberjs.jsbin.com/moxasifeha/1/edit?html,js,console,output

What would you recommend?

**Comment by drogus** [comment]
@OrKoN you don't have to write a lengthy version, it will still work as expected. You can also still use `{{value}}` by setting `contextBinding` to `content`. http://emberjs.jsbin.com/tololutuge/1/edit?html,js,console,output

**Comment by OrKoN** [comment]
@drogus thanks, that's a better version. Is the contextBinding documented somewhere? But still I'd have to align all each's with all views.. Is there a way to avoid this? Is there a default contextBinding?

**Comment by drogus** [comment]
> Is the contextBinding documented somewhere?

`context` is documented in `Ember.View`'s docs: http://emberjs.com/api/classes/Ember.View.html. `context`'s value is basically used when you want to access a property in a template.

> Is there a default contextBinding?

By default it will be a controller or parentView's context, depending on which one is set.

**Comment by OrKoN** [comment]
@drogus thanks. Do you maybe know if it's possible to write my own helper with HtmlBars which would implement the context switching for this special case of non-block each?

**Pull request merged**
