### PR TITLE
Revert dependabot version bumps that didn't go through CI

### PR DESCRIPTION
**Pull request by locks**
This reverts commit 6438e9c1ee465b3368789ecd07db7c52fcc6fce7.

### CODE REVIEW

**Review by kategengler — APPROVED** [review]

**Comment by kategengler** [comment]
Will dependabot reopen these updates after we do this?

**Comment by locks** [comment]
I _think_ so?

**Comment by rwjblue** [comment]
Yes, I was thinking that it would reopen them also. Basically, we don't know which bump caused the fundamental issue, so having dependabot reopen them makes work that out much easier (IMHO).

**Comment by locks** [comment]
I will trigger it from the dasboard if it doesn't soon!

**Pull request merged**
