### PR TITLE
[DOC Release] Mark multiple methods in Ember.Router as public

### PR DESCRIPTION
**Pull request by mikepmunroe**
Mark Ember.Router.url as public
Mark Ember.Router.startRouting as public
Mark Ember.Router.isActive as public
Mark Ember.Router.isActiveIntent as public
Mark Ember.Router.hasRoute as public
Mark Ember.Router.reset as public

### CODE REVIEW

**Comment by acorncom** [comment]
Doesn't seem identical, but may be related to #12211

**Comment by rwjblue** [comment]
@acorncom - Ya, definitely related but distinct.

@mikepmunroe - I'm unsure if all of these were intended to be public API's.  I would like @machty's thoughts here, as he has the most context into the intent....

**Comment by machty** [comment]
I don't think we should mark these public. If there are any of these we definitely need/want, it'd be better to make note of it as part of the [Routing Service PR](https://github.com/emberjs/rfcs/pull/95)

**Comment by mikepmunroe** [comment]
Closing this. We will add requests to the Routing Service PR, if needed.

**Pull request closed without merging**
