### PR TITLE
Add missing assertion for testing dynamical positionalParams

### PR DESCRIPTION
**Pull request by pangratz**
The setup for the assertion is there, but the actual assertion is missing ...

### CODE REVIEW

**Comment by rwjblue** [comment]
:+1:

**Comment by pangratz** [comment]
Hmm, Travis error message: `not ok 5 SL_IE_9 -`. The screencast of the [failed test run for IE9 in SauceLab](https://saucelabs.com/tests/dd9f86bd04b04ecb815ad125740dd08b) shows failed tests for `ember-testing` package ...

screen shot 2015-05-06 at 19 12 33

**Comment by rwjblue** [comment]
I do not thing this failure is related to your PR.  It is most likely just a slow VM that we got for this run.   Restarted sauce labs job.

**Comment by rwjblue** [comment]
Thansk!

**Pull request merged**
