### PR TITLE
Add documentation for tagName: '' option on view.

### PR DESCRIPTION
**Pull request by hrishikeshs**
I found that specifying tagName: '' on a view will not wrap the generated html in a 'div'. Since I've had to do this a couple of times and there was no documentation about this, thought I'd add it.

### CODE REVIEW

**Comment by ofersadgat** [comment]
@trek Is there an official solution for this?

**Comment by tomdale** [comment]
@ofersadgat You can set tagName to '' on any component.

**Comment by sourvb** [comment]
Any update on this? I am setting tagName="" in my component. But I cannot access the DOM by this.$(). The default tagName (div) is ruining my template style. Is there any solution for this?

**Comment by tomdale** [comment]
@sourvb There is not any work at the moment on supporting `this.$()` for tagless components. That said, if the reason you are using a tagless component is due to CSS issues, I suspect there are ways to style a div to not affect the style of child elements.

**Comment by sourvb** [comment]
#12500

**Comment by miguelcobain** [comment]
@tomdale there is work done on #12500. It would be great if the core team could either close it or accept it. No rush, tough. :)

**Comment by gnapse** [comment]
What if I want to use `this.$('.selector')` to address elements in my component's template, and not to address the root component element as in `this.$()`. I agree the latter makes no sense under `tagName: ''`, but the former example does.

**Comment by Dorian** [comment]
For anyone wondering about the usage, it looks like `{{rental-tile rental=rental tagName=''}}` for instance.

**Comment by vibestring** [comment]
example of use case on a component.
`import Component from '@ember/component';

export default Component.extend({
    tagName: ''
});`

**Pull request closed without merging**
