### PR TITLE
[BUGFIX beta] Avoid assertion when `id=` is provided to tagless components.

### PR DESCRIPTION
**Pull request by rwjblue**
Fixes https://github.com/emberjs/ember.js/issues/14105.

### CODE REVIEW

**Comment by mixonic** [comment]
👍 :shipit: 🙇

**Comment by krisselden** [comment]
Can we at least say people should do this?

**Comment by krisselden** [comment]
Should not I mean,  warn that it won't do anything

**Comment by rwjblue** [comment]
@krisselden - It does not do anything from Ember's perspective, but `id` is a perfectly valid hash argument (though ambiguous in many cases also) to use for many scenarios where it may be unrelated to `id` in the DOM.

I guess we could add a deprecation when using `id`, and folks would just need to come up with better hash argument names...

**Pull request merged**
