### PR TITLE
Multiple setter calls when binding to a component's computed property

### PR DESCRIPTION
**Pull request by ebryn**
JSBin reproduction: http://emberjs.jsbin.com/toqupogezi/edit?html,js,console,output

Failing test attached.

image

### CODE REVIEW

**Comment by wycats** [comment]
Thanks! We'll take a look at this soon.

**Comment by ebryn** [comment]
https://github.com/emberjs/ember.js/pull/11225 may also be relevant/related

**Comment by ebryn** [comment]
@rwjblue why was this closed?

**Comment by rwjblue** [comment]
@ebryn - My guess is that any PR's targetting `stable` branch, were auto-closed when I deleted `stable` branch (as discussed in our meeting I was renaming to `release`).  Sorry about the confusion (I had no idea that it would close this but I suppose it makes sense).

**Comment by rwjblue** [comment]
Can you submit a new PR targeting the new branch?

**Pull request closed without merging**
