### PR TITLE
[BUGFIX beta] update lastValue of AttrNode even when not rerendering

### LINKED ISSUE #10541: Input helper valueBinding not updated
This code stopped working recently:

http://jsbin.com/cosogimulu/1/edit?html,js,output

Regression caused by https://github.com/emberjs/ember.js/pull/10525?

### PR DESCRIPTION
**Pull request by raytiley**
Fixes #10541

### CODE REVIEW

**Comment by rwjblue** [comment]
:+1:

**Comment by ilkkao** [comment]
With this PR app my app works correctly again.

**Comment by rwjblue** [comment]
https://github.com/emberjs/ember.js/pull/10545 should fix the build

**Comment by rwjblue** [comment]
@raytiley - Can you rebase?

**Pull request merged**
