### PR TITLE
[BUGFIX release] Fix bug in utils.isArray wherein an object with a length property would be considered an array.

### PR DESCRIPTION
**Pull request by schreiaj**
Fixes issue #12094

### CODE REVIEW

**Comment by rwjblue** [comment]
Can you rebase and update to `[BUGFIX beta]`?  I'm happy to reevaluate this after shipping 2.5.0...

**Comment by rwjblue** [comment]
Still needs a rebase and commit prefix update...

**Comment by Serabe** [comment]
@schreiaj can you please try to rebase this? Thank you!

**Comment by Serabe** [comment]
Merged as #15146. Thank you!

**Pull request closed without merging**
