### PR TITLE
Allow usage of limited ES2015 sematics.

### PR DESCRIPTION
**Pull request by rwjblue**
emberjs-build now uses Babel and a whitelist of transforms during transpilation.

Current whitelisted transforms are:
- [es6.templateLiterals](http://babeljs.io/docs/learn-es6/#template-strings)
- [es6.parameters.rest](http://babeljs.io/docs/learn-es6/#default-rest-spread)
- [es6.arrowFunctions](http://babeljs.io/docs/learn-es6/#arrows)

Additional transforms can be added to the whitelist [here](https://github.com/emberjs/emberjs-build/blob/72244cbc501adf1266bad941c9d2227308b93629/lib/utils/transpile-es6.js#L18), but will only be accepted if they are guaranteed to be ES3 safe.

### CODE REVIEW

**Comment by igorT** [comment]
How come this PR does't edit the whitelist?

**Comment by rwjblue** [comment]
@igorT - Not sure I follow you, edit the list how?  As mentioned in the PR description the [whitelist is here](https://github.com/emberjs/emberjs-build/blob/72244cbc501adf1266bad941c9d2227308b93629/lib/utils/transpile-es6.js#L18)...

**Comment by igorT** [comment]
I got confused between emberjs and emberjs-build repos, and was wondering how this PR had no code that was enabling es2015 stuff. Nevermind me.

**Comment by cibernox** [comment]
Make the code use ES6 features is just allowed or also something we aim for to improve readability?

**Comment by stefanpenner** [comment]
> Make the code use ES6 features is just allowed or also something we aim for to improve readability?

improved readability/productivity

**Pull request merged**
