### PR TITLE
Remove shims for now

### PR DESCRIPTION
**Pull request by chancancode**
cc @rwjblue

### CODE REVIEW

**Review by rwjblue — COMMENTED** [review]
This is likely good, but I want to test locally before landing. Will try to do that first thing tomorrow.

**Comment by stefanpenner** [comment]
@nathanhammond I heard you may be working to unblock this, do you still have any free cycles?

**Comment by nathanhammond** [comment]
We know the path forward, it's blocked on time to implement. Short version:

- `ember-cli-shims` to combination Ember Addon/Bower package.
- Drop shims from `ember-source` build.
- Provide it via addon so we don't have to unwind the bower changes.

**Comment by rwjblue** [comment]
I am working on this one right now:

> ember-cli-shims to combination Ember Addon/Bower package.

**Pull request merged**
