### PR TITLE
Failing test for inline if

### PR DESCRIPTION
**Pull request by mitchlloyd**
Failing test for #11306.

### CODE REVIEW

**Comment by mitchlloyd** [comment]
From the debugging I did, it appears that this needs to be fixed in HTMLBars.

https://github.com/tildeio/htmlbars/blob/cb6363de7c65ce07abf30b18542cd3034b8ebb54/packages/htmlbars-runtime/lib/hooks.js#L658

Changing that to:

```
if (result && result.value !== undefined)
```

Fixes the failing test in Ember and doesn't break any others. I don't understand the logic of guarding for falsey values here, but there is an Ember test that fails without the guard.

Also I could use some guidance on the testing approach for HTMLBars. The testing in that repository looks pretty minimal.  Should I try to write a test there? Where would a test like this go?

**Comment by rwjblue** [comment]
yes, there is already a pr for this there

**Comment by rwjblue** [comment]
I believe that https://github.com/tildeio/htmlbars/pull/356 fixes this.

Can you update HTMLBars in `package.json` to 0.13.22?

**Comment by mitchlloyd** [comment]
Wow, I'm glad @rwjblue knows what going on across all the repos :smile:!

The bump fixed the test. 

cc/ @jmurphyau

**Comment by rwjblue** [comment]
Thank you @mitchlloyd for reporting and bumping the priority of the fix over in HTMLBars!

**Pull request merged**
