### PR TITLE
Add Weakmap – Weak from Map -> Obj, not Obj -> Map

### PR DESCRIPTION
**Pull request by stefanpenner**
RFC is likely not needed, as this is a polyfil using embers internal machinery for a spec'd ES6 feature. We don't really have flex room on this feature, constraints are fixed.
- [ ] docs
  - [x] basic API
  - [ ] flesh out + examples
- [ ] feature flags
- [x] RFC https://github.com/emberjs/rfcs/pull/91

### CODE REVIEW

**Comment by rwjblue** [comment]
Do we have a need for this in the codebase right now?

**Comment by stefanpenner** [comment]
@rwjblue i believe the final fix for https://github.com/emberjs/ember.js/pull/12221 will want this.

**Comment by stefanpenner** [comment]
after some thought, in theory we could let people choose the direction they want the weakness to be in...

**Comment by stefanpenner** [comment]
I'm going to likely merge this, and not make it public. Im going to need it for #12221

**Comment by rwjblue** [comment]
:+1:

**Comment by stefanpenner** [comment]
error if primitive key is used:
```
a = new WeakMap()
WeakMap {}
a.set('a', '1')
VM266:2 Uncaught TypeError: Invalid value used as weak map key(…)
```

**Comment by tomdale** [comment]
Excited to have this. A public way to decorate objects with metadata without exposing `__meta__` and friends === :heart::heart::heart:

**Comment by stefanpenner** [comment]
@tomdale got any comments for the RFC?

**Comment by mmun** [comment]
This implementation will leak memory. Specifically, the keys of the WeakMap will retain a reference to the WeakMap in their meta. E.g.

```js
function leak(k) {
  let wm = new WeakMap();
  wm.set(k, 1);
}

let foo = {};
leak(foo);
// `foo` will retain the WeakMap for as long as it lives
```

To work around this we could have the WeakMap also keep track of the object that it contains (like a regular map :P) and add a `WeakMap#destroy()` that the owner of the WeakMap _must_ call before the WeakMap is garbage collected. Basically the same strategy as Ember.Object#destroy + chains.

**Comment by mmun** [comment]
@stefanpenner The current implementation will retain values longer than expected:

```
function leak(key) {
  let wm = new WeakMap();
  wm.set(key, new VeryLargeObject());
}

let obj = {};
leak(obj);

// obj will retain the VeryLargeObject for the rest of its life.
```

I think we'll need to implement a `destroy` that the WeakMap owner must call before the WeakMap is discarded. Basically the same strategy we use for tearing down chain watchers on Ember objects.

**Comment by stefanpenner** [comment]
Ya that is expected. Userland can only make weak one sided (reasonably), this pattern is still valuable, as it essentially opens storage on meta as a stable public API.

I thought I documented it as such, but if you have suggestions on how to improve the docs to be clearer I'm all ears

**Comment by mmun** [comment]
The commits in this PR were rebased and merged in another PR (#12990). There is still work required to make WeakMap public. Let's have that conversation in a separate PR and close this one.

@stefanpenner Gotcha. I tweaked the docs to make it a little clearer.

**Pull request closed without merging**
