### PR TITLE
Added failing test to tackle down misbehaving nested named outlets

### PR DESCRIPTION
**Pull request by fpauser**

### CODE REVIEW

**Comment by fpauser** [comment]
Related to #10652

**Comment by ef4** [comment]
Thanks, picking apart this failing test helped me uncover a regression (#10683).

However, this test case overall is doing some ambiguous stuff that -- if it ever worked -- only worked out of sheer luck.

The biggest problem is that it tries to render the same template multiple times into different places at the same time. For example, when handling the url `/section/subsection/sub1/1/edit` the template `section/subsection/sub1` gets render by `SectionSubsectionRoute` and by `SectionSubsectionSub1Route` simultaneously.

**Comment by fpauser** [comment]
@ef4 So my example cannot be done with the current router/outlet logic, or do I miss something here?

**Comment by ef4** [comment]
Your example can certainly be made to work. But it will need to be changed to not try to render the same template into multiple places simultaneously.

Here's an edit to your original jsbin that's changed to avoid double rendering the same templates, and to force the children to share the same controller.  http://emberjs.jsbin.com/fuzavecidu/3/edit

(I'm not recommended the above as a good way to organize this app, I'm just showing the minimal changes that would make your example work.)

**Comment by fpauser** [comment]
Thanks for sharing the fix to my jsbin. Now I get what goes wrong - although I do not understand why it is mandatory to provide a controller doing a 'customized' `render`...

At least my bad example helped/inspired you somehow ;)

**Pull request closed without merging**
