### PR TITLE
Failing test around CP setter behavior

### PR DESCRIPTION
**Pull request by ebryn**
JSBin reproduction: http://emberjs.jsbin.com/toqupogezi/edit?html,js,console,output

Failing test attached.

image

(This is a reopening of #12045)

### CODE REVIEW

**Comment by rwjblue** [comment]
Thank you for reopening, sorry that it got closed accidentally.

**Comment by bekzod** [comment]
How can I update this PR ?, I pulled the PR and rebased it with master and corrected test code. Currently only second test is failing, couldn't fix the main cause of the problem (will try more) but noticed that CP setter is called twice each time when new value is set, and when `setAttr` used instead of `set` there is no such problem.

**Comment by bekzod** [comment]
removing `legacyPropertyDidChange` from `view state` fixes this issue I guess once deprecated `view` things are gone this will be fixed too

**Comment by locks** [comment]
@ebryn is this still relevant?

**Comment by locks** [comment]
Closing as PR targets non-existing files.

**Pull request closed without merging**
