### PR TITLE
[CLEANUP beta] Remove deprecated mouse events

### PR DESCRIPTION
**Pull request by btecu**
cc @mixonic

### CODE REVIEW

**Comment by mixonic** [comment]
@btecu I believe there are some test failures in here still.

**Comment by simonihmig** [comment]
@btecu there are still tests failing here, and my recently merged changes related to the event dispatcher have caused merged conflicts here unfortunately. Do you still have time to work on this? Otherwise I could pick up your work here, and try to finish it.

**Comment by btecu** [comment]
@simonihmig I rebased but yes, I'd appreciate the help with the failing test.

**Comment by nlfurniss** [comment]
> @simonihmig I've rebased but yes, I'd appreciate the help with the failing test.

I don't have access to push to your branch, but after applying this diff all tests pass:

```diff
diff --git a/packages/@ember/-internals/glimmer/tests/integration/components/fragment-components-test.js b/packages/@ember/-internals/glimmer/tests/integration/components/fragment-components-test.js
index ff692ad05..5d5fb77ae 100644
--- a/packages/@ember/-internals/glimmer/tests/integration/components/fragment-components-test.js
+++ b/packages/@ember/-internals/glimmer/tests/integration/components/fragment-components-test.js
@@ -67,7 +67,7 @@ moduleFor(
 
       expectAssertion(() => {
         this.render(`{{#foo-bar}}{{/foo-bar}}`);
-      }, /You can not define `click,mouseEnter` function\(s\) to handle DOM event in the .* tagless component since it doesn't have any DOM element./);
+      }, /You can not define `click` function\(s\) to handle DOM event in the .* tagless component since it doesn't have any DOM element./);
     }
 
     ['@test throws an error if a custom defined event function is defined in a tagless component']() {
```

**Comment by simonihmig** [comment]
All green now, awesome! :tada: 
/cc @mixonic

**Comment by btecu** [comment]
@nlfurniss thank you!

**Pull request merged**
