### PR TITLE
Possible workaround for #13071

### PR DESCRIPTION
**Pull request by krisselden**
I think this may possibly workaround #13071 and is better anyway since this is a very hot path.

### CODE REVIEW

**Comment by krisselden** [comment]
So, this didn't affect #13071 but I still think this improves debug-ability since it at least shows the name in the inlining log and is easier to step through and has a minimal cost

**Comment by rwjblue** [comment]
Seems good to me, can you prefix [BUGFIX beta]?

**Comment by stefanpenner** [comment]
lgtm

**Comment by stefanpenner** [comment]
@rwjblue I think it's a bugfix release no?

**Comment by rwjblue** [comment]
I'm fine with that (this is totally safe), but since it is confirmed to not fix the issue I didn't think it needed a 2.4.3 release.  We can pull it into release branch though, so when we do get a solution we can include this with the fix..

**Comment by stefanpenner** [comment]
ah sorry, didn't read @krisselden follow up comment correctly

**Comment by dgeb** [comment]
There's an equivalent [registryAlias](https://github.com/emberjs/ember.js/blob/master/packages/ember-runtime/lib/mixins/registry_proxy.js#L256-L260) method. I'm curious if together the changes could fix #13071 (and I'm willing to follow through with a patch here to try).

**Comment by stefanpenner** [comment]
lets just merge this into canary

**Pull request merged**
