### PR TITLE
[BUGFIX] Set computed property constructor

### PR DESCRIPTION
**Pull request by ming-codes**
Need this for class/extend keywords to work correctly.

### CODE REVIEW

**Review by rwjblue — COMMENTED** [review]
Seems good to me. 

@krisselden - r?

**Comment by stefanpenner** [comment]
I noticed this myself recently, good catch!

**Comment by stefanpenner** [comment]
@homu r+

**Comment by stefanpenner** [comment]
@homu retry

**Comment by stefanpenner** [comment]
@homu retry

**Comment by rwjblue** [comment]
LOL, homu is having a hard time

**Comment by stefanpenner** [comment]
😴

**Comment by stefanpenner** [comment]
@homu your drunk go home.

**Comment by ming-codes** [comment]
LOL

**Pull request merged**
