### PR TITLE
[GLIMMER2] Optimize {{property}} PropertyReference

### PR DESCRIPTION
**Pull request by chancancode**
A quick survey in our app indicates ~77% of `PropertyReference` have a const parent. This is unsurprising, because most path lookup curlies are single-level (no dots in the path) lookup on the component directly.

This means we can do less work and book-keeping in those cases (checking if the parent is a proxy on every `compute`, etc).

### CODE REVIEW

**Comment by chancancode** [comment]
In my <not completely scientific> experiments, this accounts for over 10% improvements in initial render time.

**Comment by krisselden** [comment]
@mmun I thought we had tests that allowed {{str.length}}

**Comment by chancancode** [comment]
@krisselden that crossed my mind too, but I am just mirroring the current behavior

**Comment by chancancode** [comment]
@krisselden while you are here, can you review https://github.com/emberjs/ember.js/pull/14041/commits/4ce09546103ae4dc1fee97320b90add4f6ff7c37 ?

**Comment by chancancode** [comment]
There seems to be additional wins associated with the latest commits, but my setup is too noisy to test that at the moment

**Comment by krisselden** [comment]
@chancancode this is supported with the glimmer flag off https://ember-twiddle.com/cb89209f43d67d81fb74eaa59d442200?openFiles=templates.application.hbs%2C

**Pull request merged**
