### PR TITLE
[Glimmer2] Components should have access to the view registry

### PR DESCRIPTION
**Pull request by chadhietala**
Not sure if this is something we want to continue with or not
/cc @wycats @chancancode

### CODE REVIEW

**Comment by krisselden** [comment]
This is fine for now but this test is testing something internal more HOW instead of WHAT, I would like to move the view registry to the renderer or event dispatcher (which in reality should be per document rather than per app).

**Comment by chadhietala** [comment]
@krisselden Gotcha. I think I was more or less asking if this is the right place. In the current implementation this gets set in a hook that I don't think exists in glimmer https://github.com/emberjs/ember.js/blob/master/packages/ember-views/lib/mixins/view_child_views_support.js#L83-L126

**Comment by krisselden** [comment]
I'm surprised that is even used by anything, that has more to do with the old view layer than anything else

**Comment by landongn** [comment]
(▀̿Ĺ̯▀̿ ̿) :shipit:

**Comment by mixonic** [comment]
@chadhietala should it also be set onto the instance in `init` for shaping perhaps?

**Comment by krisselden** [comment]
@mixonic seems like this could just be injected onto the event dispatcher, I don't understand why every component needs this field?

**Comment by rwjblue** [comment]
Today, the views register themselves upon init. This could easily be done by the renderer or other higher level environment thing though.

Ultimately, I don't think we *have* to inject this into each component. The key bit is that the registry must exist and been kept up to date.

**Comment by krisselden** [comment]
superseded by #13852 which handles event dispatching without needing the behavior this test was testing.

**Pull request closed without merging**
