### PR TITLE
[Glimmer] Add empty tagName to avoid unnecessary div-tag

### LINKED ISSUE #11056: [Glimmer] `each` helper with `itemController` generates extra div tag
I know that `itemController` is deprecated. But current canary can break style for existing apps.

* canary: http://emberjs.jsbin.com/keyuxirejo/1/edit
* v1.11.3: http://emberjs.jsbin.com/picuxepepu/1/edit

We can workaround this by passing `tagName=''`. And I think that LegacyEachView's tagName can be empty-string by default, is it correct?

### PR DESCRIPTION
**Pull request by hibariya**
Fixes #11056

### CODE REVIEW

**Comment by mixonic** [comment]
@hibariya does this address a regression?we should match the behavior of 1.12 as closely as possible.

**Comment by mixonic** [comment]
Ah I see the ticket you like linked to now.

**Comment by rwjblue** [comment]
@mixonic - It does match a regression (see #11056).

**Comment by rwjblue** [comment]
:+1: - Looks good to me.

**Comment by rwjblue** [comment]
@hibariya - Thanks for reporting and fixing!

**Comment by hibariya** [comment]
:smiley:

**Pull request merged**
