### PR TITLE
[DOC release] Making guidFor public

### PR DESCRIPTION
**Pull request by thoov**
@rwjblue @stefanpenner

### CODE REVIEW

**Comment by rwjblue** [comment]
Can you prefix the commit and PR title with `[DOC release]`?

**Comment by rwjblue** [comment]
Definitely :+1: other than that small tweak.

**Comment by thoov** [comment]
@rwjblue done

**Comment by stefanpenner** [comment]
:+1:

**Comment by rwjblue** [comment]
Thank you!

**Pull request merged**
