### PR TITLE
[BUGFIX release] fix issue with unchaining ChainNodes

### PR DESCRIPTION
**Pull request by bekzod**
fix for https://github.com/emberjs/ember.js/pull/15845 #15836

### CODE REVIEW

**Comment by rwjblue** [comment]
Can you cherry pick the failing test commits here so that we can confirm they are passing?

**Comment by rwjblue** [comment]
Can you confirm that the regression this fixes is in 2.16? If so, can you prefix the fixing commit with `[BUGFIX release]` so we know to include it in the next patch release?

**Comment by bekzod** [comment]
done

**Comment by bekzod** [comment]
accidentally closed it :P

**Review by rwjblue — APPROVED** [review]

**Comment by rwjblue** [comment]
Thank you!

**Comment by krisselden** [comment]
This is poor root cause analysis, remove should never be called unbalanced, we still don't know the cause of the original regression this is just masking the symptom.

**Comment by krisselden** [comment]
we need to find the commit that caused the regression, this fix is just hiding the issue, we must have changed something around chains being overriden during extend or finish chains

**Comment by krisselden** [comment]
@bekzod can you git bisect to find the regressing commit? this fix is no good, it is just hiding the unbalanced watch/unwatch.  This is going to cause other more subtle bugs.

**Comment by bekzod** [comment]
@krisselden roger that

**Comment by bekzod** [comment]
found offending commit https://github.com/emberjs/ember.js/commit/0c72faaa4586da57283691ac1d8f4a3f1f88f081

**Comment by bekzod** [comment]
will checkout why it is happening later today

**Pull request merged**
