### PR TITLE
with-tests

### PR DESCRIPTION
**Pull request by chadhietala**
Adds glimmer2 with tests and also refactors the conditional tests to
share the basic truthy and falsy tests.

### CODE REVIEW

**Comment by rwjblue** [comment]
This looks good to me.

@chancancode - r?

**Comment by GavinJoyce** [comment]
FYI there are failing `with` tests on master:

https://travis-ci.org/emberjs/ember.js/jobs/107584377#L1845

image

**Comment by rwjblue** [comment]
Yes, I noticed this as well.  I am confused what changed from when the PR build passed Travis to when it was merged to cause this to fail...

**Comment by GavinJoyce** [comment]
I think something went wrong with the travis webhook integration. Notice how this PR doesn't have a check mark:

image

**Comment by rwjblue** [comment]
D'oh!  Thanks @GavinJoyce!

**Comment by rwjblue** [comment]
Reverting in https://github.com/emberjs/ember.js/pull/12921 for now.  (Sorry for the trouble on this @chadhietala)

**Comment by chadhietala** [comment]
#12907 Probably should be updated to be like `#if` and `#unless` in that list.

**Pull request merged**
