### PR TITLE
[DOC] Use destructuring in Ember.Helper docs

### PR DESCRIPTION
**Pull request by seanpdoyle**
https://babeljs.io/docs/learn-es2015/#destructuring

Move assignments from the body of the functions to the parameters list.

### CODE REVIEW

**Comment by rwjblue** [comment]
I personally agree and would write it this way, but I spoke with @mixonic about this when he submitted the initial docs and we decided that the way it was written struck a balance between using newer things (like concise methods and ES6 modules) while still being easy to understand for those newer to ES6 concepts.

In the end, the goal of our API documentation is to make it very clear to folks how to use a given API.  Using newer ES6 features (even when we all agree they are better) can definitely be a hindrance to that goal.

**Comment by rwjblue** [comment]
Thank you very much for taking the time to submit, but I think we should keep these as is for now.

**Comment by seanpdoyle** [comment]
@rwjblue I've turned :lemon:s into lemonade: https://robots.thoughtbot.com/destructuring-ember-parameters-in-ember-helpers

**Comment by rwjblue** [comment]
Awesome!

**Pull request closed without merging**
