### PR TITLE
Rename LinkView to LinkComponent and deprecate the former

### PR DESCRIPTION
**Pull request by cibernox**
Since Views are being deprecated and `Ember.LinkView` actually extends Ember.Component since early March.

`Ember.View` is still available but throws a deprecation warning when used.

### CODE REVIEW

**Comment by rwjblue** [comment]
Thank you for tackling, this is a great start!

I think we need to ensure that calling `Ember.LinkView.reopen` (which is mentioned in the guides and API docs) also triggers a deprecation.

**Comment by cibernox** [comment]
Added deprecation on reopen too (not sure if there is a more idiomatic way of doing that)

**Comment by mixonic** [comment]
@cibernox a followup that add a URL and entry in the deprecation guide would be great, but I'll do it this AM if you don't have time. We will be looking at this stuff all day anyway.

Thank you!

**Comment by mixonic** [comment]
@rwjblue This should go into `[BUGFIX beta]`. Sorry, will try to be more strict about this.

**Pull request merged**
