### PR TITLE
[BUGFIX beta] Fix positional parameters when used with component helper

### LINKED ISSUE #13158: Component positional params don't update when used with the component helper
I came across this when [porting component helper tests to Glimmer2](https://github.com/emberjs/ember.js/pull/13140).

Twiddle: https://ember-twiddle.com/8bd17b5f64fdf1f400d8

When this is fixed, please uncomment https://github.com/emberjs/ember.js/pull/13140/files#r56916691

### PR DESCRIPTION
**Pull request by Serabe**
Updates positional parameters when component is invoked with the component
helper.

Uncomments the test, as asked in #13158.

Fixes #13158 in `htmlbars`

### CODE REVIEW

**Comment by Serabe** [comment]
More comments on this:

1. The code is not clean, not clean at all, but `params` and `attrs` are hard to deal with in `htmlbars`.
2. Positional parameters are coming to Glimmer 2 as well (#13393). They will need no fix when they are finished.
3. Shall I open a new PR for porting this to LTS?

**Comment by rwjblue** [comment]
I do not think we backport this into lts-2-4 branch. My reasoning is basically that this doesn't seem like a regression (as far as I can tell it has never worked)....

**Comment by Serabe** [comment]
It worked in 2.2. [Twiddle](https://ember-twiddle.com/0e42ac30206a6fe661934b70a7353379?openFiles=twiddle.json%2C)

**Comment by rwjblue** [comment]
Thanks @Serabe!

**Pull request merged**
